Repository kodadot/nft-gallery, pull requests merged in 2021-05, with the labels that each got.

#340 283 issue warning for buy
  dashboard/src/components/rmrk/Gallery/AvailableActions.vue
  dashboard/src/icons.ts
Labels: bug, garage

#388 Fighting against technical debt
  dashboard/package.json
  dashboard/yarn.lock
Labels: garage

#386 Show art in original format
  dashboard/src/components/rmrk/Gallery/Appreciation.vue
  dashboard/src/components/rmrk/Gallery/GalleryItem.vue
  dashboard/src/components/rmrk/Gallery/Item/Facts.vue
  dashboard/src/components/rmrk/Gallery/Item/Name.vue
  dashboard/src/components/rmrk/Gallery/Item/Sharing.vue
  dashboard/src/components/rmrk/Pack/PackSaver.vue
  dashboard/src/icons.ts
  dashboard/src/typography.scss
Labels: enhancement
