Repository kodadot/nft-gallery, pull requests merged in 2021-03, with the labels that each got.

#127 Corner case that user changed symbol (Not propagated to NFT)
  dashboard/src/components/rmrk/Create/CreateToken.vue
Labels: bug

#128 Profile
  dashboard/package.json
  dashboard/src/assets/subscan.svg
  dashboard/src/components/rmrk/Gallery/CollectionItem.vue
  dashboard/src/components/rmrk/Gallery/Gallery.vue
  dashboard/src/components/rmrk/Gallery/GalleryCardList.vue
  dashboard/src/components/rmrk/Gallery/Item/Name.vue
  dashboard/src/components/rmrk/Gallery/Item/Sharing.vue
  dashboard/src/components/rmrk/Pack/PackItem.vue
  dashboard/src/components/rmrk/Profile/ProfileLink.vue
  dashboard/src/components/rmrk/service/RmrkService.ts
  dashboard/src/components/rmrk/service/scheme.ts
  dashboard/src/components/rmrk/utils.ts
  dashboard/src/components/shared/format/Identity.vue
  dashboard/src/main.ts
  dashboard/src/router/profile.ts
  dashboard/src/router/rmrk.ts
  dashboard/src/utils/mixins/inlineMixin.ts
  dashboard/src/views/Profile.vue
  dashboard/yarn.lock
Labels: enhancement

#136 Identity resolves a bit faster
  dashboard/src/components/shared/format/Identity.vue
  dashboard/src/vuex/IdentityModule.ts
Labels: garage

#177 change route from /u to /rmrk/u
  dashboard/src/router/profile.ts
Labels: garage

#200 model view
  dashboard/package.json
  dashboard/src/components/rmrk/Gallery/GalleryItem.vue
  dashboard/src/components/rmrk/Gallery/Item/Sharing.vue
  dashboard/src/components/rmrk/Gallery/ViewModel.vue
  dashboard/src/components/rmrk/Media/MediaResolver.vue
  dashboard/src/components/rmrk/Media/ModelMedia.vue
  dashboard/src/components/rmrk/types.ts
  dashboard/src/components/rmrk/utils.ts
  dashboard/src/main.ts
  dashboard/src/router/rmrk.ts
  dashboard/yarn.lock
Labels: observations

#203 Can show svg games (svg+xml)
  dashboard/src/components/rmrk/Gallery/GalleryItem.vue
  dashboard/src/components/rmrk/Media/IFrameMedia.vue
  dashboard/src/components/rmrk/Media/MediaResolver.vue
  dashboard/src/components/rmrk/types.ts
  dashboard/src/components/rmrk/utils.ts
  dashboard/tslint.json
Labels: enhancement

#175 Extend Money Component to show fiat value
  dashboard/src/coingecko.ts
  dashboard/src/components/rmrk/Gallery/GalleryItem.vue
  dashboard/src/components/shared/format/Money.vue
Labels: UX first

#222 201 same images are grouped
  dashboard/src/components/rmrk/Create/CreateCollection.vue
  dashboard/src/components/rmrk/Gallery/Gallery.vue
  dashboard/src/components/rmrk/Gallery/GalleryRare.vue
  dashboard/src/components/rmrk/Gallery/Search/query.ts
  dashboard/src/main.ts
Labels: UX first, enhancement

#235 added identity to landing page
  dashboard/src/components/landing/Landing.vue
Labels: UX first, garage

#250 navbar profile
  dashboard/package.json
  dashboard/src/components/Navbar.vue
  dashboard/src/components/rmrk/Create/CreateCollection.vue
  dashboard/src/components/rmrk/Create/CreateToken.vue
  dashboard/src/components/rmrk/Gallery/AvailableActions.vue
  dashboard/src/components/rmrk/Gallery/Gallery.vue
  dashboard/src/components/rmrk/Gallery/GalleryItem.vue
  dashboard/src/components/rmrk/Pack/PackSaver.vue
  dashboard/src/components/rmrk/Profile/NavbarProfileDropdown.vue
  dashboard/src/components/shared/AccountSelect.vue
  dashboard/src/components/shared/Auth.vue
  dashboard/src/components/shared/Avatar.vue
  dashboard/src/locales/en.json
  dashboard/src/vuex/IdentityModule.ts
  dashboard/vue.config.js
  dashboard/yarn.lock
Labels: UX first, enhancement
