Repository kodadot/nft-gallery, pull requests merged in 2022-11, with the labels that each got.

#4209 🔧 History component Amount token
  components/rmrk/Gallery/History.vue
Labels: ✅ - code-lgtm

#4212 feat: Redesign scroll up button
  components/shared/ScrollTopButton.vue
  styles/components/_scroll-to-top-button.scss
  styles/index.scss
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4223 #4219 footer overflow fix
  styles/layouts/_footer.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4248 #4247 hidden search dropdown
  styles/components/_carousel.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4243 #4241 Navbar scroll update
  components/Navbar.vue
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: 🤞 - changes-requested, paid

#4245 #4244 Dark mode explore leftovers
  components/landing/LandingPage.vue
  components/landing/SearchLanding.vue
  libs/ui/src/components/CardArticle/CardArticle.scss
  styles/components/_search.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
Labels: 🤞 - changes-requested

#4282 ✨ top collection skeleton
  components/landing/TopCollections.vue
Labels: ✅ - code-lgtm

#4293 #4284 Show trending collection in SearchSuggestions if *urlPrefix* either *rmrk* or *bsx*
  components/search/SearchBar.vue
Labels: ✅ - works-for-me

#4290 3273 preview of 3 d items in dropzone
  components/media/type/ModelMedia.vue
  components/rmrk/Create/DropUpload.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4292 🔧 profil wrong currency
  components/bsx/Offer/OffersUserTable.vue
  components/bsx/Offer/StatsOverview.vue
  components/rmrk/Profile/ProfileActivity.vue
Labels: ✅ - code-lgtm

#4272 #4271 adding change account button
  components/rmrk/Profile/NavbarProfileDropdown.vue
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4222 #4144 new wallet changes
  components/common/WalletModal.vue
  styles/themes/_dark.scss
  utils/config/wallets.ts
Labels: 🤞 - changes-requested

#4315 fix links hover color
  styles/themes/_light.scss
Labels: ✅ - code-lgtm

#4327 feat: support clv wallet
  assets/partners/logo-clover.png
  utils/config/wallets.ts
  utils/config/wallets/BaseDotsamaWallet.ts
Labels: ✅ - code-lgtm

#4307 Show user preview of to be minted piece while making mint
  components/media/type/ModelMedia.vue
  components/rmrk/Create/DropUpload.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4316 fix: remove empty search result from suggestions (history)
  components/search/SearchSuggestion.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4325 fix: remove black drop shadow on default state (dark mode)
  styles/components/_top-collections.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4326 Revert ":snake: Stuck Snek"
  components/bsx/Gallery/Item/GalleryItem.vue
  utils/config/permision.config.ts
Labels: 🐍 - basilisk

#4305 feat: add tabs component from oruga
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemActivity.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/useGalleryItem.ts
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  package.json
  pnpm-lock.yaml
  queries/subsquid/general/nftListWithSearch.graphql
  styles/components/_o-table.scss
  styles/components/_o-tabs.scss
  styles/index.scss
Labels: redesign

#4333 Fix search collection navbar
  components/search/Search.vue
Labels: ✅ - code-lgtm, paid

#4301 Fix gallery skeleton
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/rmrk/Gallery/Gallery.vue
Labels: ✅ - works-for-me

#4319 #4117 New hover card for user profile
  components/identity/module/IdentityPopover.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/utils/useIdentity.ts
  components/rmrk/Gallery/GalleryCard.vue
  locales/en.json
  styles/themes/_dark.scss
  tests/cypress/e2e/components/identity.cy.ts
Labels: ✅ - code-lgtm

#4343 🔧 navbar item dark mode hover state
  styles/themes/_dark.scss
Labels: ✅ - works-for-me

#4344 #4334 loader overflow issue
  components/shared/Loader.vue
Labels: paid

#4330 ✨ gallleryItem MISC
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemShareBtn.vue
  components/gallery/useGalleryItem.ts
  libs/ui/src/components/IdentityItem/IdentityItem.vue
  libs/ui/src/components/NeoButton/NeoButton.story.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/histoire.scss
  libs/ui/src/index.ts
  locales/en.json
  pages/snek/gallery/_id.vue
  plugins/icons.ts
  pnpm-lock.yaml
  store/history.ts
  styles/abstracts/_derived-variables.scss
  styles/abstracts/_variables.scss
  styles/components/_toast.scss
  styles/index.scss
Labels: ✅ - works-for-me

#4351 fix: remove placeholder text on focus
  components/search/SearchBar.vue
Labels: ✅ - works-for-me

#4346 fix: profile dropdown text color in light mode
  styles/themes/_light.scss
Labels: 🤞 - changes-requested, paid

#4353 #4337 hover card updates
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  tests/cypress/e2e/components/identity.cy.ts
Labels: 🤞 - changes-requested, paid

#4332 Top collection data volume and % change
  components/landing/TopCollections.vue
  components/landing/TopCollectionsItem.vue
  components/series/types.ts
  components/series/utils.ts
  queries/collectionsSales.graphql
  styles/components/_top-collections.scss
Labels: ✅ - code-lgtm, paid

#4369 fix landing page broken colors
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4297 teleport KSM token between Kusama and Basilisk
  components/landing/TopCollectionsItem.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/teleport/Teleport.vue
  locales/en.json
  package.json
  pages/teleport-bridge.vue
  pnpm-lock.yaml
  utils/teleport.ts
Labels: 🐍 - basilisk, paid

#4376 Follow up top collection data volume
  components/landing/TopCollections.vue
  components/landing/TopCollectionsItem.vue
  components/series/types.ts
  components/series/utils.ts
  libs/ui/src/components/NeoButton/NeoButton.vue
  styles/components/_top-collections.scss
Labels: ✅ - code-lgtm

#4382 Fix: Search reload explore
  components/search/Search.vue
Labels: ✅ - works-for-me

#3585 Add iqr/h-spread and box plot chart
  components/rmrk/Gallery/CollectionItem.vue
  components/shared/chart/BoxPlot/Canvas.vue
  components/shared/chart/BoxPlot/Container.vue
  components/shared/chart/BoxPlot/containerOptions.ts
  package.json
  pnpm-lock.yaml
  utils/chart.ts
Labels: ✅ - works-for-me

#4392 ✨ enter key icon in search bar
  components/search/SearchBar.vue
  static/k-search-enter.svg
  styles/components/_search.scss
Labels: ✅ - code-lgtm

#4408 fix: navbar logo replace
  assets/Koda_Beta.svg
  assets/Koda_Beta_dark.svg
  components/Navbar.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4409 ✨ dropUpload file size limit
  components/rmrk/Create/DropUpload.vue
  locales/en.json
  utils/constants.ts
Labels: ✅ - code-lgtm

#4398 fix :bug: correct colors for wallet buttons
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm

#4404 fix: Wallet selection darkmode
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm

#4375 chore: skip e2e snek gallery item and simple mint
  package.json
  pnpm-lock.yaml
  tests/cypress/e2e/basicE2E.cy.ts
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4413 Fix nft details in carousel
  components/carousel/utils/useCarousel.ts
  utils/carousel.ts
Labels: ✅ - code-lgtm

#4423 :fire: green glow begone!
  components/rmrk/Gallery/GalleryCard.vue
Labels: ✅ - code-lgtm
