Repository kodadot/nft-gallery, pull requests merged in 2022-01, with the labels that each got.

#1908 ⚒️ spotlight detail
  components/spotlight/SpotlightDetail.vue
Labels: 🧙‍♀️-bug-hunt

#1870 Added 'address sharing' and 'balance checking' to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: changes-requested-🤞, paid

#2063 #2051 Make toggle disabled in search component at collection detail i…
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/Search/SearchBarCollection.vue
  components/shared/form/BasicSwitch.vue
Labels: paid

#2057 #2031 Carefully remove unused components
  components/Error.vue
  components/FourZeroFour.vue
  components/rmrk/OnChainProperty.vue
  components/shared/OptionDropdown.vue
  components/shared/format/Percent.vue
  components/toolbox/ConvertAddress.vue
  components/toolbox/HashData.vue
  components/toolbox/SignMessage.vue
  components/toolbox/Toolbox.vue
  components/toolbox/VerifySignature.vue
Labels: paid

#2068 feat: trigger send from existing emojis
  components/rmrk/Gallery/Appreciation.vue
  components/rmrk/Gallery/EmotionList.vue
Labels: paid

#2084 fix: rework searchbar to be more space efficient 💻
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Pagination.vue
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid

#2107 #2050 esCarbonless spanish route not working in about section
  pages/esCarbonless.vue
Labels: paid

#2047 Update template-typescript-w-decorator.vue
  .vscode/vetur/snippets/template-typescript-w-decorator.vue
  .vscode/vetur/snippets/vue.json
Labels: paid

#2067 #2062 typos/grammar
  CONTRIBUTING.md
  README.md
Labels: changes-requested-🤞

#2091 #2059 Use only border-top on control buttons/actions
  components/rmrk/Gallery/Appreciation.vue
  components/rmrk/Gallery/CollectionPriceChart.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/PriceChart.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/shared/SwitchLocale.vue
  components/shared/history/HistoryBrowser.vue
  styles/global.scss
Labels: changes-requested-🤞, paid

#2080 #2053 Unify collection detail and collections view with $primary
  components/rmrk/Gallery/Search/SearchBarCollection.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
Labels: changes-requested-🤞, paid

#2046 #2037 removing unused packages
  package.json
  yarn.lock
Labels: changes-requested-🤞

#2121 fix: remove margin of container to solve fading issue
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid
