Repository kodadot/nft-gallery, pull requests merged in 2022-09, with the labels that each got.

#3661 Add Rococo Basilisk & Basilisk explorer
  components/rmrk/Profile/utils.ts
  components/shared/BlockExplorerLink.vue
  pages/transfer.vue
  utils/config/chain.config.ts
Labels: ✅ - code-lgtm

#3892 feat: Migrating Latest Sales + Newest List to /snek
  components/landing/Landing.vue
Labels: ✅ - code-lgtm

#3885 feat: add route to snek/assets
  components/Navbar.vue
  components/bsx/Asset/AssetList.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  locales/en.json
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3825 refactor: Curated List - Vue Composition API
  .eslintrc.js
  components/Navbar.vue
  components/bsx/Asset/AssetTable.vue
  components/bsx/Create/RoyaltyForm.vue
  components/landing/CuratedList.vue
  components/landing/LandingPage.vue
  components/rmrk/utils.ts
  components/shared/ChainSelect.vue
  components/shared/format/ChainMoney.vue
  components/unique/types.ts
  composables/useAuth.ts
  composables/useGraphql.ts
  pages/index.vue
  pages/snek/create.vue
  utils/config/permision.config.ts
Labels: ✅ - works-for-me

#3884 New GraphQL routes
  nuxt.config.js
  queries/config/.graphqlconfig
  tests/cypress/e2e/basicE2E.cy.ts
  tests/cypress/support/commands.ts
  utils/constants.ts
Labels: moonriver, moonbeam

#3893 feat: Migrating Offers related components to /snek
  components/Navbar.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/rmrk/Profile/ProfileDetail.vue
  pages/snek/offers.vue
  tests/cypress/support/commands.ts
Labels: 🤞 - changes-requested, paid

#3815 Update 🇵🇹 Portuguese translations
  locales/pt.json
Labels: ✅ - code-lgtm

#3871 refactor: Carousel components
  components/base/types.ts
  components/bsx/Gallery/Item/GalleryItem.vue
  components/carousel/CarouselCardList.vue
  components/carousel/CarouselIndex.vue
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/CarouselTypePopularCollection.vue
  components/carousel/CarouselTypeRelated.vue
  components/carousel/CarouselTypeVisited.vue
  components/carousel/GalleryItemCarousel.vue
  components/carousel/LatestSales.vue
  components/carousel/NewestList.vue
  components/carousel/PopularCollections.vue
  components/carousel/module-old/CarouselCardFooter.vue
  components/carousel/module-old/CarouselCardInfo.vue
  components/carousel/module-old/CarouselCardMedia.vue
  components/carousel/module-old/CarouselList.vue
  components/carousel/module/CarouselListNew.vue
  components/carousel/utils/useCarousel.ts
  components/landing/LandingPage.vue
  components/rmrk/Gallery/GalleryItem.vue
  composables/useAuth.ts
  queries/subsquid/general/collectionEntityById.graphql
  queries/subsquid/general/lastNftListByEvent.graphql
  queries/subsquid/general/nftEntitiesByIDs.graphql
  queries/subsquid/general/popularCollectionList.graphql
  utils/carousel.ts
  utils/types/types.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3913 fix: black placeholder image
  components/shared/view/BasicImage.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3906 fix/chain-token
  components/rmrk/Profile/NavbarProfileDropdown.vue
  utils/config/chain.config.ts
Labels: ✅ - code-lgtm, 🤞 - changes-requested

#3886 #3805 Fill up translations strings where we are missing them
  components/base/BaseCollectionForm.vue
  components/base/BaseTokenForm.vue
  components/common/RampCredit.vue
  components/common/WalletModal.vue
  components/landing/LandingPage.vue
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Create/CreativeMint.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Pagination.vue
  components/rmrk/Profile/IdentityForm.vue
  components/sales/SalesTable.vue
  components/search/SearchBar.vue
  components/series/SeriesTable.vue
  components/shared/Sharing.vue
  components/shared/history/Browser.vue
  components/spotlight/SpotlightTable.vue
  locales/en.json
  locales/fr.json
  locales/id.json
  locales/pt.json
  pages/teleport.vue
  pages/transfer.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3924 🔧 hotfix wallet connect
  components/common/WalletModal.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3904 feat: rename moonsama to moonriver
  components/movr/Gallery/Item/GalleryItem.vue
  components/movr/Gallery/Item/utils.ts
  components/rmrk/Profile/ProfileDetail.vue
  components/shared/ChainSelect.vue
  nuxt.config.js
  package.json
  pages/movr/collection/_id.vue
  pages/movr/create.vue
  pages/movr/explore.vue
  pages/movr/gallery/_id.vue
  pages/movr/index.vue
  pages/movr/u/_id.vue
  pnpm-lock.yaml
  queries/subsquid/general/nftListWithSearch.graphql
  utils/config/chain.config.ts
  utils/config/permision.config.ts
  utils/config/types.ts
  utils/constants.ts
  utils/prefix.ts
  utils/queryPathResolver.ts
Labels: ✅ - code-lgtm, moonriver

#3895 redesign: prepare landing page for new design
  components/TheFooter.vue
  components/TheFooterOld.vue
  components/landing/LandingPage.vue
  components/landing/LandingPageOld.vue
  composables/useExperiments.ts
  layouts/centered-half-layout.vue
  layouts/default.vue
  layouts/full-width-layout.vue
  pages/index.vue
  utils/mixins/experimentMixin.ts
Labels: paid

#3921 fix: offer request fail while non-logged
  components/bsx/Offer/MyOffer.vue
Labels: ✅ - code-lgtm, 🤞 - changes-requested

#3917 fix: invisible close btn in modal
  styles/components/_modal.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, paid

#3942 🔧 typo wallet connect
  components/common/WalletModal.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3940 🔧 collection stats hide burned nfts
  queries/subsquid/rmrk/collectionStatsById.graphql
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3889 redesign: Carousel component
  components/carousel/CarouselIndex.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
  components/carousel/module/CarouselListNew.vue
  components/carousel/module/CarouselMedia.vue
  components/landing/LandingPage.vue
  package.json
  pnpm-lock.yaml
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3964 hotfix: broken on mobile
  components/Navbar.vue
  components/search/Search.vue
Labels: paid

#3959 fix: incorrect color on Message
  styles/global.scss
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3982 New URL for Snek
  package.json
  pnpm-lock.yaml
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3977 fix: light mode leftovers
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3975 #3974 links from stats at /snek
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3970 feat(landing): search on landing page
  assets/fonts/WorkSans-VariableFont_wght.ttf
  components/Navbar.vue
  components/landing/LandingPage.vue
  components/landing/SearchLanding.vue
  components/search/SearchBar.vue
  locales/en.json
  static/landing-search-left-dark.svg
  static/landing-search-left.svg
  static/landing-search-right-dark.svg
  static/landing-search-right.svg
  static/search-k-keyboard.svg
  styles/abstracts/_variables.scss
  styles/components/_search.scss
  styles/fonts.scss
  styles/global.scss
  styles/index.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3985 ⚠️ Breaking: Support of the latest SubSquid
  .gitignore
  queries/collectionCuratedList.graphql
  queries/rmrk/subsquid/allCollectionSaleEvents.graphql
  queries/rmrk/subsquid/collectionsEvents.graphql
  queries/rmrk/subsquid/nftByIdMinimal.graphql
  queries/subsquid/bsx/allCollectionSaleEvents.graphql
  queries/subsquid/bsx/assetById.graphql
  queries/subsquid/bsx/assetListByIdList.graphql
  queries/subsquid/bsx/itemEvents.graphql
  queries/subsquid/bsx/offerListByCollectionId.graphql
  queries/subsquid/bsx/offerListByNftId.graphql
  queries/subsquid/general/collectionBurnableStats.graphql
  queries/subsquid/general/collectionById.graphql
  queries/subsquid/general/collectionEntityById.graphql
  queries/subsquid/general/eventListByNftId.graphql
  queries/subsquid/general/existingCollectionList.graphql
  queries/subsquid/general/nftById.graphql
  queries/subsquid/general/nftEntitiesByIDs.graphql
  queries/subsquid/general/nftIdListByCollection.graphql
  queries/subsquid/general/nftListedCountByCollection.graphql
  queries/subsquid/rmrk/collectionStatsById.graphql
  queries/subsquid/rmrk/nftById.graphql
Labels: 🐍 - basilisk, moonriver, moonbeam

#3994 fix: adjust query on series, spotlight, and hot nfts
  queries/rmrk/subsquid/hotNfts.graphql
  queries/rmrk/subsquid/seriesInsightList.graphql
  queries/rmrk/subsquid/spotlightList.graphql
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4014 fix: loader
  components/bsx/Offer/OffersUserTable.vue
Labels: paid

#4008 feat: Update minter for BSX so royalty can have 2 decimal places
  components/bsx/Create/CreateToken.vue
  components/bsx/Create/RoyaltyForm.vue
  components/rmrk/Create/CreativeMint.vue
  components/shared/form/BasicNumberInput.vue
  locales/en.json
  utils/royalty.ts
Labels: ✅ - code-lgtm, 🤞 - changes-requested, paid, ✅ - works-for-me

#3953 Update 🇷🇺Russian translation in KodaDot
  locales/ru.json
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4001 Update 🇪🇸 Spanish translation in KodaDot
  locales/es.json
Labels: translations

#4027 fix: image previews on moonriver
  components/rmrk/utils.ts
  components/shared/view/BasicImage.vue
  utils/cachingStrategy.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4031 fix: disable movr & glmr on production env
  components/shared/ChainSelect.vue
  utils/constants.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4037 chore: enable royalty to be zero
  components/bsx/Create/RoyaltyForm.vue
Labels: ✅ - code-lgtm

#4030 One non-fungible serpent
  components/Navbar.vue
  components/bsx/Asset/AssetList.vue
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  components/bsx/Offer/OfferTable.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/shared/ChainSelect.vue
  nuxt.config.js
  package.json
  pages/bsx/assets.vue
  pages/bsx/create.vue
  pages/snek/create.vue
  plugins/assets.ts
  pnpm-lock.yaml
  queries/subsquid/bsx/assetList.graphql
  store/assets.ts
  store/identity.ts
  store/index.ts
  utils/api/bsx/query.ts
  utils/constants.ts
Labels: 🐍 - basilisk

#4047 fix: Incorrect currency shown at /bsx
  components/rmrk/Profile/utils.ts
  utils/config/chain.config.ts
Labels: ✅ - code-lgtm

#4051 fix: snackbar index order 🔢
  components/rmrk/Gallery/Item/Navigation.vue
  components/shared/ScrollTopButton.vue
  components/shared/gallery/BaseGalleryItem.vue
  styles/components/_modal.scss
  styles/layouts/_main-navigation.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4026 fix: Newly minted nft have Carbonless properties by default (bsx)
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/AttributeInput.vue
  components/rmrk/Create/CustomAttributeInput.vue
  components/rmrk/Create/mintUtils.ts
  locales/en.json
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4011 feat: multi chain latestEvent query and add collection name
  components/base/types.ts
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/module/CarouselInfo.vue
  components/carousel/module/CarouselMedia.vue
  components/carousel/utils/useCarousel.ts
  composables/useGraphql.ts
  queries/subsquid/general/lastNftListByEvent.graphql
  utils/carousel.ts
  utils/types/types.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me
