Repository kodadot/nft-gallery, pull requests merged in 2022-06, with the labels that each got.

#3097 #2615 Adding nudge in wallet auth
  components/common/WalletModal.vue
  langDir/en.json
Labels: ✅ - approved, paid

#3093 fix: remove search query from url when empty
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchBarCollection.vue
Labels: ✅ - approved, paid

#3067 #842 Ability to sort by multiple metrics
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
  components/rmrk/Gallery/Search/exist.ts
  components/rmrk/Gallery/Search/types.ts
  langDir/en.json
  queries/nftListWithSearch.graphql
Labels: paid

#3107 fix: responsive design for Artist profile
  components/rmrk/Profile/ProfileDetail.vue
Labels: ✅ - approved

#3043 feat(1386): hot-dashboard for recently sold nfts
  components/Navbar.vue
  components/hot/HotTable.vue
  components/hot/types.ts
  components/series/utils.ts
  components/stats/StatsHeader.vue
  langDir/en.json
  pages/hot.vue
  queries/rmrk/subsquid/hotNfts.graphql
  utils/datetime.ts
Labels: ✅ - approved, paid

#3112 #3110 Adding missing translations in landing in en.json
  components/landing/Landing.vue
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/rmrk/Gallery/LatestSales.vue
  components/rmrk/Gallery/NewestList.vue
  components/rmrk/Gallery/PopularCollections.vue
  langDir/en.json
Labels: ✅ - approved

#3141 bugfix(bsx): fix metadata error
  components/bsx/Gallery/Item/GalleryItem.vue
Labels: paid

#3146 fix: IdentityPopover component show 0
  components/shared/IdentityPopover.vue
Labels: paid

#3104 #3103 Show passion feed in gallery only if it is greater than 10
  components/base/SubmitButton.vue
  components/bsx/Gallery/Item/utils.ts
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Item/ActionList.vue
  components/rmrk/Gallery/Item/Navigation.vue
  components/shared/gallery/CollectionNavigation.vue
  components/unique/Gallery/Item/Detail.vue
  utils/api/format.ts
  utils/gallery/actions.ts
  utils/prefix.ts
  utils/uniquery.ts
Labels: ✅ - approved

#3147 check and justify sort condition from url
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
  utils/constants.ts
Labels: paid

#3129 fix: chain agnostic on profile
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/utils.ts
Labels: 🐍 - basilisk, paid

#3164 3162 Adjust Basilisk to Basilisk (testnet)
  package.json
  pnpm-lock.yaml
Labels: paid

#3153 fix: import unimplemented query error on bsx
  components/shared/IdentityPopover.vue
  queries/subsquid/general/userStatsByAccount.graphql
  queries/userStatsByAccount.graphql
Labels: 🐍 - basilisk

#3130 fix: collection and profile on bsx
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
Labels: 🐍 - basilisk, paid

#3133 Push user to NFT tab after finishing minting collection
  components/bsx/Create/Create.vue
  components/bsx/Create/CreateCollection.vue
  components/rmrk/Create/Create.vue
  components/rmrk/Create/CreateCollection.vue
  components/unique/Create/Create.vue
  components/unique/Create/CreateCollection.vue
  pages/bsx/create.vue
  pages/rmrk/create.vue
  pages/statemine/create.vue
  pages/westend/create.vue
  pages/westmint/create.vue
  utils/mixins/createMixin.ts
Labels: 🐍 - basilisk

#3217 fix: fix tabs at profile detail
  queries/subsquid/general/firstNftByIssuer.graphql
  queries/subsquid/general/nftListByIssuer.graphql
  queries/subsquid/general/nftListCollected.graphql
  queries/subsquid/general/nftListSold.graphql
Labels: 🐍 - basilisk

#3209 fix: display nft without name in bsx
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Profile/Sales.vue
Labels: 🐍 - basilisk, 🤞 - changes-requested

#3062 fix: remove duplicate item from Newest List
  components/rmrk/Gallery/LatestSales.vue
  components/rmrk/Gallery/NewestList.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  queries/rmrk/subsquid/lastNftListByEvent.graphql
  utils/carousel.ts
  utils/types/types.ts
Labels: 🤞 - changes-requested, 🧊- rubick

#3241 Add item into history events of collection
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Profile/ProfileDetail.vue
Labels: paid

#3238 #3225 Fixing wrong numbers
  queries/subsquid/general/userStatsByAccount.graphql
  queries/userStatsByAccount.graphql
Labels: ✅ - approved, paid

#3101 feat(2223): passion feed for stats
  components/series/SeriesTable.vue
  components/spotlight/SpotlightTable.vue
  langDir/en.json
  queries/rmrk/subsquid/seriesInsightList.graphql
  queries/rmrk/subsquid/spotlightList.graphql
  utils/mixins/passionListMixin.ts
Labels: ✅ - approved, paid

#3175 Fixing IdentityPopover Last bought
  components/shared/IdentityPopover.vue
  queries/subsquid/general/buyEventByProfile.graphql
  queries/subsquid/general/userStatsByAccount.graphql
  queries/userStatsByAccount.graphql
Labels: ✅ - approved

#3257 🔧 stats by profile Id (bsx)
  components/rmrk/Profile/ProfileActivity.vue
  queries/profileStatsById.graphql
  queries/subsquid/general/profileStatsById.graphql
  utils/math.ts
Labels: 🐍 - basilisk, 🤞 - changes-requested

#3260 feat: show nft royalties on basilisk
  components/bsx/Gallery/Item/GalleryItem.vue
  components/rmrk/service/scheme.ts
  components/shared/format/Money.vue
  langDir/en.json
  queries/subsquid/general/nftById.graphql
  utils/royalty.ts
Labels: paid

#3227 #3192 Landing page chain checks
  pages/bsx/index.vue
  pages/index.vue
  utils/prefix.ts
Labels: paid

#3268 Audio NFT player
  utils/gallery/media.ts
Labels: paid

#3261 chore: link to tech stack article
  CONTRIBUTING.md
Labels: paid

#3270 fix unsupported file on bsx
  components/bsx/Gallery/Item/GalleryItem.vue
  utils/gallery/media.ts
Labels: 🐍 - basilisk, 🤞 - changes-requested

#3251 feat(3208): Stats of the whole Basilisk marketplace
  components/Navbar.vue
  components/bsx/Offer/OfferStats.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/StatsOverview.vue
  components/bsx/Offer/types.ts
  langDir/en.json
  pages/bsx/stats.vue
  pnpm-lock.yaml
  queries/subsquid/bsx/offerList.graphql
  queries/subsquid/bsx/statsForBsx.graphql
  utils/config/indexer.config.ts
  utils/countOf.ts
Labels: 🐍 - basilisk

#3267 feat: Show royalties in History component for bsx
  components/rmrk/Gallery/History.vue
  langDir/en.json
  utils/historyEvent.ts
Labels: 🐍 - basilisk, 🤞 - changes-requested

#3288 feat: better tooltip for royalty slider
  components/bsx/Create/RoyaltyForm.vue
  components/shared/form/BasicSlider.vue
  langDir/en.json
Labels: paid

#3275 #3202 Disable make offer button after offer was made
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  components/bsx/Offer/OfferList.vue
  components/rmrk/Gallery/Item/ActionList.vue
  components/rmrk/Gallery/LatestSales.vue
  langDir/en.json
  styles/global.scss
Labels: 🤞 - changes-requested

#3297 fix: Relative time link on BSX
  components/rmrk/Gallery/History.vue
  pnpm-lock.yaml
Labels: ✅ - approved

#3316 modify unclear text about royalty
  components/bsx/Create/RoyaltyForm.vue
  langDir/en.json
Labels: paid
