Repository kodadot/nft-gallery, pull requests merged in 2022-12, with the labels that each got.

#4395 Transform top collections nuxt3 way
  components/landing/TopCollections.vue
  components/landing/topCollections/TopCollections.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/landing/topCollections/utils/types.ts
  components/landing/topCollections/utils/useTopCollections.ts
  composables/useGraphql.ts
  locales/de.json
  locales/en.json
  queries/subsquid/general/collectionsSales.graphql
  queries/subsquid/general/topCollectionList.graphql
Labels: 🤞 - changes-requested, paid

#4432 update search bar visibility and disable scroll on burger menu
  components/Navbar.vue
  components/landing/SearchLanding.vue
Labels: ✅ - code-lgtm

#4448 #4441 Add close option into search navbar on mobile
  components/Navbar.vue
  locales/en.json
  styles/layouts/_main-navigation.scss
Labels: ✅ - code-lgtm

#4424 #4267 Search bar network changes
  components/landing/SearchLanding.vue
  components/navbar/NavbarExplore.vue
  components/search/Search.vue
  locales/en.json
  styles/abstracts/_variables.scss
  styles/components/_search.scss
  styles/themes/_dark.scss
Labels: 🤞 - changes-requested, paid

#4410 ✨ bsx series-insight
  assets/bsx-logo.png
  components/Navbar.vue
  components/landing/topCollections/TopCollections.vue
  components/series/SeriesTable.vue
  components/stats/StatsHeader.vue
  locales/en.json
  pages/sales.vue
  pages/series-insight.vue
  pages/spotlight.vue
  styles/global.scss
Labels: ✅ - code-lgtm, paid

#4355 redesign gallery chart component
  components/chart/PriceChart.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  locales/en.json
  styles/components/_o-tabs.scss
  styles/components/_price-chart.scss
  styles/index.scss
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, ✅ - visual-ok

#4449 Batch transfers
  components/shared/BalanceInput.vue
  pages/transfer.vue
Labels: paid

#4440 #4276 Landing page visual change
  components/TheFooter.vue
  components/carousel/CarouselIndex.vue
  components/carousel/CarouselTypeSpotlight.vue
  components/landing/LandingPage.vue
  components/landing/SearchLanding.vue
  static/blurred-landing-footer.svg
  static/landing-blurred-header-left.svg
  static/landing-blurred-header-right.svg
  static/landing-search-left-dark.svg
  static/landing-search-left.svg
  static/landing-search-right-dark.svg
  static/landing-search-right.svg
  static/landing-shape-header-left-dark.svg
  static/landing-shape-header-left-light.svg
  static/landing-shape-header-right-dark.svg
  static/landing-shape-header-right-light.svg
  styles/components/_search.scss
  styles/global.scss
  styles/layouts/_footer.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: 🤞 - changes-requested

#4462 fix: Text link hover state
  styles/components/_price-chart.scss
  styles/components/_search.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4461 fix: #4459 Inconsistent hover state on selected language
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
Labels: ✅ - visual-ok

#4463 fix: Landing page visual change footer part
  styles/global.scss
  styles/layouts/_footer.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - visual-ok

#4446 fix + ♻️ #4443 navbar hover + refactor
  components/Navbar.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/CreateDropdown.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/StatsDropdown.vue
  locales/en.json
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
  tests/cypress/support/commands.ts
Labels: 🤞 - changes-requested, ✅ - visual-ok

#4476 fix: #4302 add wallet name
  components/common/WalletModal.vue
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/identity/module/IdentityLink.vue
  components/identity/utils/useIdentity.ts
  components/navbar/ProfileDropdown.vue
  components/rmrk/Profile/ProfileAssetsList.vue
  components/rmrk/Profile/utils.ts
  locales/en.json
  store/fiat.ts
  store/wallet.ts
  styles/themes/_dark.scss
  utils/calculation.ts
  utils/coingecko.ts
Labels: 🤞 - changes-requested, paid

#4501 ⬆️ upgrade sub-api dependencies
  package.json
  pnpm-lock.yaml
  store/identity.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4493 🔧 fr translation
  locales/fr.json
Labels: ✅ - code-lgtm

#4484 fix: bring back galleryItem price chart data
  components/gallery/GalleryItemTabsPanel/GalleryItemChart.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4504 fix: Missing hover effect on explore hover dropdown links
  styles/themes/_light.scss
Labels: ✅ - code-lgtm

#4502 :bug: correct url for highest sales popover
  components/identity/module/IdentityPopoverFooter.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4508 :zap: fix identity reactivity
  components/identity/IdentityIndex.vue
  components/identity/utils/useIdentity.ts
Labels: ✅ - works-for-me

#4503 :bug: repeated search works
  components/search/Search.vue
Labels: ✅ - code-lgtm

#4489 :bug: remove capitalize from navbar history
  styles/components/_search.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4510 Bump ParaSpell version
  components/teleport/Teleport.vue
  package.json
  pnpm-lock.yaml
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4488 :bug: remove rest of Fira Code
  components/common/WalletModal.vue
  components/gallery/GalleryItem.vue
  components/identity/module/IdentityPopover.vue
  components/shared/Loader.vue
  static/placeholder.svg
  styles/abstracts/_initial-variables.scss
  styles/abstracts/_variables.scss
  styles/components/_button.scss
  styles/components/_search.scss
  styles/global.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
Labels: 🤞 - changes-requested, paid, fixed-payment

#4524 fix: content dissapears after few seconds in walletModal in mobile devices
  components/common/WalletModal.vue
Labels: ✅ - code-lgtm

#4517 fix : scroll bar when timeframe dropdown is open in price chart
  components/chart/PriceChart.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue
  styles/components/_price-chart.scss
Labels: ✅ - visual-ok

#4520 :bug: navbar non-mobile smaller screen
  components/Navbar.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/ProfileDropdown.vue
  styles/layouts/_main-navigation.scss
Labels: 🤞 - changes-requested, paid

#4530 :broom: update landing articles
  components/landing/FeaturedArticles.vue
Labels: ✅ - code-lgtm

#4506 redesign: [price-section] [desktop] [ui-only] buy, offer, list, transfer, change price, and not listed section
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  queries/subsquid/bsx/offerHighest.graphql
  styles/global.scss
  tests/cypress/e2e/basicE2E.cy.ts
  utils/format/time.ts
Labels: ✅ - code-lgtm

#4539 fix: missing user address in profile hover card
  components/identity/IdentityIndex.vue
Labels: paid, ✅ - works-for-me

#4519 Stretch search on mobile
  components/Navbar.vue
  components/search/SearchBar.vue
  components/search/SearchSuggestion.vue
  styles/components/_search.scss
  styles/layouts/_main-navigation.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#4518 Collection card redesign
  components/collection/CollectionCard.vue
  components/collection/CollectionDetail.vue
  components/collection/CollectionList.vue
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/rmrk/Gallery/CollectionDetail.vue
  locales/en.json
  styles/components/_collection-card.scss
  styles/global.scss
  styles/index.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4511 #4496 gallery card changes
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
  components/carousel/module/CarouselMedia.vue
  components/shared/gallery/Gallery.vue
  components/shared/gallery/NftCard.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.story.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/index.ts
  libs/ui/src/scss/variable.scss
  styles/components/_carousel.scss
Labels: paid, ✅ - works-for-me, ✅ - visual-ok

#4548 fix: SearchBar in Navbar vertical-align
  styles/layouts/_main-navigation.scss
Labels: ✅ - visual-ok

#4557 test: adjust e2e test for collection and gallery
  components/collection/CollectionDetail.vue
  components/collection/CollectionList.vue
  components/shared/gallery/Gallery.vue
  tests/cypress/support/commands.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me
