Repository kodadot/nft-gallery, pull requests merged in 2022-08, with the labels that each got.

#3636 Change the appearance when cancelling a transaction
  langDir/en.json
  utils/mixins/metaMixin.ts
Labels: ✅ - works-for-me

#3619 feat: Hide own offer afterwards I bought item
  components/bsx/Offer/OfferList.vue
  queries/subsquid/bsx/offerListByNftId.graphql
Labels: paid, ✅ - works-for-me

#3640 Replace Magick with Rubick for RMRK
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Profile/ProfileActivity.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/service/scheme.ts
  queries/fragments/event.graphql
  queries/rmrk/subsquid/nftByIdMinimal.graphql
  queries/subsquid/general/eventListByNftId.graphql
  queries/subsquid/rmrk/collectionForMint.graphql
  queries/subsquid/rmrk/nftById.graphql
  queries/subsquid/rmrk/usedCollectionSymbolsByAccount.graphql
  utils/mixins/infiniteScrollMixin.ts
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3650 fix: misleading number on stats page
  components/bsx/Offer/StatsOverview.vue
  langDir/en.json
Labels: ✅ - works-for-me

#3637 fix: set api connected on transfer page
  pages/transfer.vue
Labels: ✅ - works-for-me

#3641 feat: add tooltip for expiration on offer table
  components/bsx/Offer/OfferTable.vue
  utils/datetime.ts
  utils/format/time.ts
  utils/mixins/offerMixin.ts
Labels: paid, ✅ - works-for-me

#3627 #3333 Add explainer text in create nft
  components/base/BaseTokenForm.vue
  components/base/CollectionSelect.vue
  components/bsx/Create/CreateToken.vue
  langDir/en.json
  pages/bsx/create.vue
Labels: ✅ - works-for-me

#3617 RELIST + UNLIST Action Button
  components/bsx/Gallery/Item/ActionList.vue
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/GalleryItem.vue
  langDir/en.json
  utils/shoppingActions.ts
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3603 Add cross env and test windows build
  .eslintrc.js
  .gitattributes
  .github/workflows/build.yml
  package.json
  pnpm-lock.yaml
Labels: ✅ - works-for-me

#3673 Feat: Add arrows on image detail for Basilisk
  components/bsx/Gallery/Item/GalleryItem.vue
Labels: ✅ - works-for-me

#3451 #2911 cypress e2e
  components/Navbar.vue
  components/bsx/Gallery/Item/ActionList.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/CollectionDetail.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/GalleryCardList.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
  components/shared/IdentityPopover.vue
  components/shared/form/BasicSwitch.vue
  cypress.json
  package.json
  pages/e2e-login.vue
  pnpm-lock.yaml
  tests/cypress.config.ts
  tests/cypress/e2e/basicE2E.cy.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/e2e.ts
Labels: ✅ -code-LGTM

#3677 feat: hover popup for collection item
  components/rmrk/Gallery/CollectionDetail.vue
  queries/subsquid/general/collectionListWithSearch.graphql
Labels: ✅ - works-for-me

#3695 fix collection stats
  components/rmrk/Gallery/CollectionActivity.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/shared/format/Money.vue
  queries/subsquid/rmrk/collectionStatsById.graphql
Labels: subsquid, 🤞 - changes-requested, paid

#3663 feat: add vue-test-utils and unit test for BalanceInput.vue
  components/shared/BalanceInput.vue
  package.json
  pnpm-lock.yaml
  tests/api.spec.ts
  tests/unit-testing/components/shared/BalanceInput.test.ts
  utils/mixins/prefixMixin.ts
  vitest.config.js
Labels: ✅ -code-LGTM, paid, ✅ - works-for-me

#3676 #3627 Changing default value
  components/base/BaseTokenForm.vue
  components/base/CollectionSelect.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateToken.vue
  pages/rmrk/create.vue
Labels: 🤞 - changes-requested

#3691 fix: relist event, does not update directly on the page
  components/bsx/Gallery/Item/GalleryItem.vue
Labels: ✅ -code-LGTM, paid, ✅ - works-for-me

#3690 fix: bsx - not show collection name after fresh mint
  components/bsx/Gallery/Item/GalleryItem.vue
Labels: ✅ - works-for-me

#3546 feat: Handle when user hasn't have enough balance to mint
  components/base/BaseCollectionForm.vue
  components/base/BaseTokenForm.vue
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/DropUpload.vue
  components/shared/AccountBalance.vue
  components/shared/BalanceInput.vue
  components/shared/form/BasicInput.vue
  langDir/en.json
  utils/mixins/authMixin.ts
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3689 test: cypress github workflow
  .github/workflows/build.yml
  .gitignore
  package.json
  pnpm-lock.yaml
  tests/cypress/e2e/basicE2E.cy.ts
Labels: ✅ - works-for-me

#3698 fix: gallery sorting was broken on rmrk
  components/rmrk/Gallery/NewestList.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
  tests/cypress/support/commands.ts
  utils/constants.ts
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3693 feat: bsx landing page add lastest and newest list
  components/landing/Landing.vue
  components/rmrk/Gallery/LatestSales.vue
  langDir/en.json
  queries/rmrk/subsquid/lastNftListByEvent.graphql
Labels: 🤞 - changes-requested, paid, ✅ - works-for-me

#3651 fix: support chart on bsx collection
  components/bsx/Collection/ChartContainer.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/CollectionPriceChart.vue
  components/shared/chart/LineChart.vue
  components/shared/chart/chartMixin.ts
  components/shared/collection/PriceChart.vue
  queries/subsquid/bsx/allCollectionSaleEvents.graphql
Labels: ✅ - works-for-me

#3730 🌞 identitypopover, footer, card, box, carousel, wallet btn, chart axis fix
  components/base/CarouselCardList.vue
  components/rmrk/Gallery/PriceChart.vue
  styles/themes/light.scss
Labels: redesign-seeds

#3711 Unify minting process experience
  components/base/BaseCollectionForm.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/CreativeMint.vue
  components/rmrk/Create/SimpleMint.vue
  langDir/en.json
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3738 AvailableAction.vue - Unit Test
  components/rmrk/Gallery/AvailableActions.vue
  globals.d.ts
  package.json
  pnpm-lock.yaml
  tests/unit-testing/components/rmrk/Gallery/AvailableActions.test.ts
  utils/config/wallets/BaseDotsamaWallet.ts
  utils/config/wallets/CloverWallet.ts
  utils/config/wallets/LedgerWallet.ts
  utils/config/wallets/MathWallet.ts
  utils/config/wallets/NovaWallet.ts
  utils/config/wallets/PolkadotjsWallet.ts
  utils/config/wallets/SubWallet.ts
  utils/config/wallets/TalismanWallet.ts
  vitest.config.js
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3702 feat: use existing metadata when retry happen on minting
  components/bsx/Create/CreateToken.vue
  components/shared/Loader.vue
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3759 e2e: fix flaky test
  package.json
  pnpm-lock.yaml
  tests/cypress.config.ts
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
  tests/cypress/support/commands.ts
  tests/unit-testing/components/rmrk/Gallery/AvailableActions.test.ts
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3757 🎩 update new favicon
  nuxt.config.js
  static/android-chrome-192x192.png
  static/android-chrome-384x384.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/favicon.svg
  static/img/icons/favicon-32x32.png
  static/site.webmanifest
Labels: ✅ - works-for-me

#3744 fix: btn style on notifier
  components/bsx/Gallery/Item/GalleryItem.vue
  components/moonsama/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Pack/PackItem.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/shared/MessageNotify.vue
  components/shared/Sharing.vue
  components/shared/modals/ShowQRModal.vue
  components/unique/Collection/Item/CollectionItem.vue
  components/unique/Gallery/Item/GalleryItem.vue
  pages/statemine/u/_id.vue
  pages/westmint/u/_id.vue
  styles/global.scss
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3758 feat: show last buy price in `Newest list card`
  queries/rmrk/subsquid/lastNftListByEvent.graphql
  utils/carousel.ts
  utils/types/types.ts
Labels: 🤞 - changes-requested, paid

#3742 #3713 white text, bg changes
  styles/themes/light.scss
  styles/variables.scss
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3748 refactor: move identity and identitypopover to one folder
  components/Navbar.vue
  components/base/CarouselCardList.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/bsx/Offer/StatsOverview.vue
  components/landing/CuratedList.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/ProfileLink.vue
  components/rmrk/Profile/Sales.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  components/shared/Auth.vue
  components/shared/IdentityPopover.vue
  components/shared/identity/IdentityChain.vue
  components/shared/identity/IdentityIndex.vue
  components/shared/identity/IdentitySocial.vue
  components/shared/identity/popover/IdentityPopover.vue
  components/shared/identity/popover/IdentityPopoverFooter.vue
  components/shared/identity/popover/IdentityPopoverHeader.vue
  components/spotlight/SpotlightTable.vue
  pages/sales.vue
  pages/series-insight.vue
  pages/spotlight.vue
  pages/statemine/u/_id.vue
  pages/teleport.vue
  pages/transfer.vue
  pages/westmint/u/_id.vue
  utils/format/time.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3741 🔧 refactor nft storage in services
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/CreativeMint.vue
  components/rmrk/Create/SimpleMint.vue
  components/unique/Create/CreateCollection.vue
  components/unique/Create/CreateToken.vue
  services/nftStorage.ts
  store/pinning.ts
  utils/nftStorage.ts
  utils/safePin.ts
Labels: refactoring, ✅ - code-lgtm, ✅ - works-for-me

#3786 fix: 3d objects are not showing on landing
  queries/rmrk/subsquid/lastNftListByEvent.graphql
  utils/carousel.ts
  utils/types/types.ts
Labels: ✅ - code-lgtm, paid

#3785 e2e: Media Component
  .github/workflows/build.yml
  components/media/type/AudioMedia.vue
  components/media/type/ImageMedia.vue
  components/media/type/ModelMedia.vue
  components/media/type/VideoMedia.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/shared/gallery/BaseGalleryItem.vue
  components/shared/view/BasicImage.vue
  components/unique/Gallery/Item/Detail.vue
  tests/cypress/e2e/components/media.cy.ts
  tests/cypress/support/commands.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3795 🎩 update Properties design
  components/bsx/Gallery/Item/GalleryItem.vue
  components/moonsama/Gallery/Item/GalleryItem.vue
  components/shared/gallery/Properties.vue
  components/unique/Gallery/Item/GalleryItem.vue
  components/unique/Gallery/Item/Properties.vue
Labels: enhancement

#3770 bugfix: right link for transfer
  pages/teleport.vue
  pages/transfer.vue
  utils/explorerGuide.ts
  utils/mixins/chainMixin.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3800 🎩 display account Balance in NavbarProfileDropdown
  components/rmrk/Profile/NavbarProfileDropdown.vue
Labels: UX first, ✅ - code-lgtm

#3788 🧹 rename langDir folder to locales
  .github/workflows/diagram.yml
  locales/README.md
  locales/all_lang.json
  locales/assets/edit_and_commit.png
  locales/assets/fork_and_edit.png
  locales/bn.json
  locales/cn.json
  locales/cz.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/it.json
  locales/jp.json
  locales/ko.json
  locales/nl.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sk.json
  locales/tu.json
  locales/ua.json
  locales/ur.json
  locales/vt.json
  nuxt.config.js
  utils/config/i18n.ts
Labels: refactoring, ✅ - code-lgtm, 🧹 - clean-up

#3787 #3731 post fixes
  components/Navbar.vue
  styles/global.scss
  styles/themes/light.scss
  styles/variables.scss
Labels: ✅ - code-lgtm

#3768 feat: show placeholder variant based on colormode
  components/media/MediaResolver.vue
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/shared/gallery/BaseGalleryItem.vue
  components/shared/view/BasicImage.vue
  components/unique/Collection/Item/CollectionItem.vue
  static/placeholder-white.webp
  static/placeholder.webp
Labels: ✅ - code-lgtm, paid

#3809 fix(searchbar): Pagination buttons on explorer is off
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid

#3715 added new medium article writings list
  CONTRIBUTING.md
  README.md
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3799 fix: indexed-db for media component
  .github/workflows/build.yml
  components/bsx/Gallery/Item/GalleryItem.vue
  components/media/PreviewMediaResolver.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/rmrk/Gallery/Layout.vue
  tests/cypress.config.ts
  tests/cypress/e2e/components/media.cy.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3816 🔧 carousel large screen responsive
  components/base/CarouselCardList.vue
Labels: ✅ - code-lgtm

#3792 fix: Tags on RMRK NFTs
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/shared/gallery/Properties.vue
  components/unique/Create/CreateCollection.vue
  components/unique/Create/CreateToken.vue
Labels: ✅ - code-lgtm, 🤞 - changes-requested

#3831 fix/input-dark-mode
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3834 fix: flush indexed db on service-worker
  plugins/pwa.ts
Labels: ✅ - code-lgtm

#3833 fix: unknown content type
  components/rmrk/utils.ts
  utils/gallery/media.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3838 fix/hover black text
  components/rmrk/Gallery/Gallery.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3771 refactor: Identity - Vue Composition API
  components/Navbar.vue
  components/base/CarouselCardList.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/bsx/Offer/StatsOverview.vue
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/identity/module/IdentityPopover.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/module/IdentitySocial.vue
  components/identity/utils/useIdentity.ts
  components/identity/utils/useIdentityStats.ts
  components/landing/CuratedList.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/ProfileLink.vue
  components/rmrk/Profile/Sales.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  components/shared/Auth.vue
  components/shared/identity/IdentityChain.vue
  components/shared/identity/IdentityIndex.vue
  components/shared/identity/popover/IdentityPopover.vue
  components/spotlight/SpotlightTable.vue
  composables/useApi.ts
  composables/useGraphql.ts
  composables/usePrefix.ts
  pages/sales.vue
  pages/series-insight.vue
  pages/spotlight.vue
  pages/statemine/u/_id.vue
  pages/teleport.vue
  pages/transfer.vue
  pages/westmint/u/_id.vue
  plugins/consola.ts
  utils/mixins/prefixMixin.ts
  vue-shim.d.ts
Labels: ✅ - code-lgtm

#3802 e2e: Identity on hover
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/rmrk/Profile/ProfileDetail.vue
  package.json
  pnpm-lock.yaml
  tests/cypress/e2e/components/identity.cy.ts
  tests/cypress/support/commands.ts
  tsconfig.json
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3819 refactor: Carousel - Move from rmrk folder
  components/bsx/Gallery/Item/GalleryItem.vue
  components/carousel/CarouselCardList.vue
  components/carousel/GalleryItemCarousel.vue
  components/carousel/LatestSales.vue
  components/carousel/NewestList.vue
  components/carousel/PopularCollections.vue
  components/landing/Landing.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Gallery/Pagination.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3849 fix: patch vuex deprecation warning
  package.json
  patches/vuex@3.6.2.patch
  pnpm-lock.yaml
Labels: paid

#3840 feat/shadows-on-landing
  components/landing/Landing.vue
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, paid

#3692 #3463 Master offers component
  components/Navbar.vue
  components/bsx/Offer/MasterOfferTable.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OffersUserTable.vue
  locales/en.json
  pages/bsx/offers.vue
  queries/subsquid/bsx/acceptableOfferByCurrentOwner.graphql
  queries/subsquid/bsx/offerListUser.graphql
  tests/cypress/support/commands.ts
  utils/offerStatus.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3853 fix: Identity popover - copy to clipboard broken
  components/identity/module/IdentityPopoverHeader.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3861 fix: Text on hover in menu is not visible
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm

#3763 SearchBar Refactor & Redesign
  components/Navbar.vue
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/PaginatedCardList.vue
  components/rmrk/Gallery/Search/query.ts
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  components/rmrk/service/scheme.ts
  components/search/SearchBar.vue
  components/search/SearchBarCollection.vue
  components/search/SearchResultItem.vue
  components/search/SearchSortDropdown.vue
  components/search/TypeTagInput.vue
  components/search/exist.ts
  components/search/types.ts
  components/series/SeriesTable.vue
  components/spotlight/SpotlightTable.vue
  locales/en.json
  pages/transform.vue
  queries/subsquid/general/nftListWithSearch.graphql
  styles/global.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_light.scss
Labels: ✅ - works-for-me

#3878 fix: add hover color on navigation bar on light mode
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm

#3879 test: copy address in identity component
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/utils/useIdentityStats.ts
  tests/cypress/e2e/components/identity.cy.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#3870 fix: Close Emoji panel by clicking elsewhere
  components/rmrk/Gallery/Appreciation.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#3857 feat: btn fill up address
  components/bsx/Offer/MasterOfferTable.vue
  components/shared/AddressInput.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me
