Repository kodadot/nft-gallery, pull requests merged in 2022-02, with the labels that each got.

#2176 #2138 Show Tweet about recent purchase with creator Twitter
  components/rmrk/Gallery/AvailableActions.vue
Labels: paid

#2166 #2156 Remove KSM from Spotlight & Series insight
  components/series/SeriesTable.vue
  components/shared/format/Money.vue
  components/spotlight/SpotlightTable.vue
Labels: changes-requested-🤞

#2207 fix: block navigation if certain elements are being focused
  components/rmrk/Gallery/Item/Navigation.vue
Labels: paid

#2102 Initial e2e tests setup for https://github.com/kodadot/nft-gallery/issues/1503
  cypress.json
  package.json
  tests/cypress/fixtures/example.json
  tests/cypress/integration/e2e/search.spec.js
  tests/cypress/integration/e2e/smokeTests.spec.js
  tests/cypress/plugins/index.js
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tsconfig.json
  yarn.lock
Labels: changes-requested-🤞

#2172 ✨ latest sales with CarouselList
  components/base/CarouselCardList.vue
  components/landing/Landing.vue
  components/rmrk/Gallery/LatestSales.vue
  components/rmrk/Gallery/NewestList.vue
  langDir/en.json
  queries/unique/lastSoldNft.graphql
  queries/unique/newestListNft.graphql
Labels: enhancement

#2225 #2208 Show only first row from description at collection
  components/rmrk/Gallery/CollectionItem.vue
  components/shared/collapse/DescriptionWrapper.vue
Labels: paid

#2235 ✨ latest Sales timestamp & owner
  components/base/CarouselCardList.vue
  components/rmrk/Gallery/LatestSales.vue
  queries/unique/lastSoldNft.graphql
  utils/icons.ts
Labels: paid

#2234 #2218 Align navbar with recent style changes
  components/Navbar.vue
Labels: paid

#2245 feat: add new prelaoder graphic
  components/shared/Loader.vue
  static/preloader.svg
Labels: paid

#2253 #2025 search on mobile 1.1
  .github/diagram.svg
  components/rmrk/Gallery/Search/SearchBar.vue
  styles/global.scss
Labels: paid

#2097 Feat: Add Support for keyboard shortcuts
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Item/Navigation.vue
  components/rmrk/Gallery/Pagination.vue
  components/rmrk/Gallery/PriceChart.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchBarCollection.vue
  components/settings/KeyboardShortcuts.vue
  components/shared/collapse/DescriptionWrapper.vue
  components/spotlight/SpotlightTable.vue
  nuxt.config.js
  pages/settings.vue
  plugins/keyboardEvents.ts
  utils/mixins/keyboardEventsMixin.ts
Labels: changes-requested-🤞, paid

#2268 feat: reorder navbar elements
  components/Navbar.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  langDir/en.json
Labels: paid

#2306 fix: Invalid Promise-like handling.
  nuxt.config.js
  plugins/globalVariables.ts
  utils/WithKeyring.ts
  utils/directUpload.ts
  utils/extension.ts
  utils/mixins/queryMixin.ts
Labels: paid

#2303 #2256 Mobile-first experience
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/Gallery/Collections.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/GalleryCardList.vue
  components/rmrk/Gallery/Item/Navigation.vue
  components/shared/gallery/BaseGalleryItem.vue
  styles/global.scss
Labels: changes-requested-🤞, paid

#2325 fix: focus input element after keyevent
  components/rmrk/Gallery/AvailableActions.vue
  components/shared/AddressInput.vue
  components/shared/BalanceInput.vue
Labels: paid

#2304 fix: update profile links and user profile overflow
  components/rmrk/Gallery/Item/Sharing.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/ProfileLink.vue
  static/polkascan.png
Labels: paid

#2297 Show keyboard shortcuts board when user presses ? key.
  components/shared/modals/ModalWrapper.vue
  components/shared/modals/keyboardShortcutsModal.vue
  layouts/centered-half-layout.vue
  layouts/default.vue
  layouts/full-width-layout.vue
  plugins/keyboardEvents.ts
  styles/global.scss
Labels: changes-requested-🤞, paid

#2316 fix: set sorting to desc by default on spotlight and series
  components/series/SeriesTable.vue
  components/spotlight/SpotlightTable.vue
Labels: paid

#2307 #2110 - Add to search price range min - max
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/types.ts
  queries/nftListWithSearch.graphql
  queries/nftPriceRange.graphql
Labels: changes-requested-🤞

#2292 Show available balance at NFTs for BUY
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/shared/Auth.vue
  components/unique/Create/CreateCollection.vue
  langDir/en.json
  nuxt.config.js
  pages/teleport.vue
  pages/transfer.vue
  plugins/userBalance.ts
  store/identity.ts
Labels: changes-requested-🤞, paid

#2366 feat: sticky header in series and spotlight.
  components/series/SeriesTable.vue
  components/spotlight/SpotlightTable.vue
Labels: changes-requested-🤞

#2381 Payout leaderboard for KodaDot #1477 1/2
  LEADERBOARD.md
Labels: paid

#2387 feat: added readme link to storage article
  .eslintrc.js
  README.md
Labels: paid

#2403 feat(SearchBar): Show price range next to the filter
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid

#2410 feat: add hints on how to open shortcuts overview
  components/shared/Loader.vue
  components/shared/modals/ModalWrapper.vue
  components/shared/modals/keyboardShortcutsModal.vue
  langDir/en.json
Labels: paid

#2422 fix: b-carousel prop error and cls issue
  components/rmrk/Gallery/CuratedList.vue
Labels: paid

#2418 Price range v2 #2370
  components/landing/Landing.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  queries/nftListWithSearch.graphql
  queries/nftPriceRange.graphql
Labels: paid

#2457 #2341 - Navbar transformation during scrolling
  components/Navbar.vue
Labels: paid

#2407 #2378 Make navbar transparent aero effect
  components/Navbar.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/shared/ChainSelect.vue
  components/shared/SwitchLocale.vue
  components/shared/history/HistoryBrowser.vue
  styles/global.scss
  styles/variables.scss
Labels: paid

#2430 #2420 - fix searchbar on mobile
  components/Navbar.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid
