Repository kodadot/nft-gallery, pull requests merged in 2022-05, with the labels that each got.

#2914 [skip netlify] kodabot
  CONTRIBUTING.md
Labels: paid

#2940 fix: modal ui justify on mobile
  components/rmrk/Gallery/EmotionList.vue
  styles/global.scss
Labels: paid

#2924 feat: show animationUrl on carousel items
  components/base/CarouselCardList.vue
  components/base/types.ts
  components/rmrk/Media/MediaResolver.vue
  components/rmrk/Media/PreviewMediaResolver.vue
  queries/fragments/baseMeta.graphql
  utils/carousel.ts
Labels: paid

#2931 feat: page locate index
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/GalleryCardList.vue
  components/rmrk/Gallery/PaginatedCardList.vue
  components/rmrk/Profile/ProfileDetail.vue
  utils/mixins/infiniteScrollMixin.ts
Labels: paid

#2950 fix(collection stats): alignment
  components/rmrk/Gallery/CollectionActivity.vue
  langDir/en.json
Labels: paid

#2971 Replace rubick@004 queries to use rubick@006
  components/rmrk/Gallery/LatestSales.vue
  components/rmrk/Gallery/NewestList.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  nuxt.config.js
  utils/mixins/prefixMixin.ts
Labels: paid

#2978 Add on series price per buy
  components/series/SeriesTable.vue
  components/series/types.ts
  components/series/utils.ts
  langDir/en.json
Labels: paid

#2973 WIP: user profile with history events
  components/rmrk/Profile/ProfileDetail.vue
  queries/rmrk/subsquid/allEventsByProfil.graphql
Labels: 🤞 - changes-requested

#2991 feat: Addressable spotlight
  components/spotlight/SpotlightTable.vue
  langDir/en.json
Labels: paid

#2945 feat: gains for user
  components/rmrk/Gallery/Flipper.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/UserGainHistory.vue
  components/rmrk/Profile/ProfileDetail.vue
  langDir/en.json
  queries/fragments/event.graphql
  queries/rmrk/subsquid/allCollectionSaleEvents.graphql
  queries/rmrk/subsquid/allNftSaleEventsHistoryByAccountId.graphql
Labels: 🤞 - changes-requested, paid

#2993 fix: lint warnings
  components/rmrk/Gallery/Pagination.vue
  components/rmrk/Gallery/Search/SearchBarCollection.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/series/utils.ts
  components/shared/IdentityPopover.vue
  plugins/consola.ts
  tsconfig.json
Labels: paid

#2948 Extract shopping logic to utils
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/GalleryItem.vue
  pnpm-lock.yaml
  tests/shoppingActions.spec.ts
  utils/mixins/metaMixin.ts
  utils/shoppingActions.ts
Labels: ✅ - approved, paid

#2985 Filter on top of collection detail show only collected
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/Search/SearchBarCollection.vue
  components/rmrk/Gallery/Search/types.ts
  langDir/en.json
Labels: ✅ - approved, paid

#3014 fix: unlist event does not display emoji at history
  components/rmrk/Gallery/History.vue
Labels: paid

#3015 fix: Relocate first page query in searchbar
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid

#2975 refactor(2918): subsquid for ProfileDetail
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/PaginatedCardList.vue
  components/rmrk/Profile/ProfileDetail.vue
  pages/statemine/u/_id.vue
  pages/westmint/u/_id.vue
  queries/fragments/subsquidNft.graphql
  queries/subsquid/general/firstNftByIssuer.graphql
  queries/subsquid/general/nftListByIssuer.graphql
  queries/subsquid/general/nftListCollected.graphql
  queries/subsquid/general/nftListSold.graphql
Labels: ✅ - approved

#3033 Feat(1285) : Recent Sales for Creator
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  queries/rmrk/subsquid/recentSalesForCreator.graphql
Labels: paid

#3041 clean: remove unused code and reuse minimark
  components/accounts/utils.ts
  components/rmrk/Create/Admin/AdminPanel.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Flipper.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/service/Consolidator.ts
  components/rmrk/service/NftUtils.ts
  components/rmrk/service/scheme.ts
  components/rmrk/service/types.ts
  components/rmrk/types.ts
  components/rmrk/utils.ts
  components/unique/Create/CreateCollection.vue
  components/unique/Create/CreateToken.vue
  utils/ipfs.ts
  utils/proxy.ts
Labels: paid

#2995 Feat(#1238) : Stats profile activity
  components/rmrk/Profile/ProfileActivity.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/shared/format/StatsColumn.vue
  langDir/en.json
  queries/collectionById.graphql
  queries/rmrk/subsquid/nftEntitiesByIDs.graphql
  queries/rmrk/subsquid/profileStatsById.graphql
  utils/math.ts
Labels: 🤞 - changes-requested

#3025 refactor history component
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Gallery/History.vue
  langDir/en.json
  langDir/id.json
  langDir/pt.json
  pnpm-lock.yaml
  queries/rmrk/subsquid/allEventsByProfile.graphql
  queries/rmrk/subsquid/nftByIdMinimal.graphql
  utils/historyEvent.ts
Labels: 🤞 - changes-requested

#3065 Add difference from previous trade into history
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Gallery/History.vue
Labels: paid

#3078 chore: updated readme with public good writing
  README.md
Labels: paid

#3076 fix: Missing translation at loader
  utils/mixins/txMixin.ts
Labels: paid
