Repository kodadot/nft-gallery, pull requests merged in 2022-10, with the labels that each got.

#3869 🎩 Top Collections
  components/landing/LandingPage.vue
  components/landing/LandingPageOld.vue
  components/landing/ReTopCollections.vue
  components/landing/ReTopCollectionsItem.vue
  components/landing/TopCollections.vue
  components/landing/TopCollectionsItem.vue
  locales/en.json
  queries/rmrk/subsquid/topCollectionList.graphql
  styles/components/_top-collections.scss
  styles/global.scss
  styles/index.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: redesign-seeds, ✅ - works-for-me

#4060 chore: update subapi package without warnings 📦
  package.json
  pnpm-lock.yaml
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4066 💅 bsx chain in new landing
  components/carousel/module/CarouselInfo.vue
  components/carousel/utils/useCarousel.ts
  components/landing/LandingPage.vue
  components/landing/SearchLanding.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4064 💅 top collection responsive & new landing font
  components/landing/ReTopCollections.vue
  styles/abstracts/_fonts.scss
  styles/components/_carousel.scss
  styles/components/_top-collections.scss
  styles/global.scss
  styles/index.scss
Labels: ✅ - works-for-me

#4076 🔧 denyList for bsx
  components/rmrk/Collection/List/CollectionList.vue
  queries/subsquid/general/collectionListWithSearch.graphql
  utils/constants.ts
  utils/prefix.ts
Labels: paid

#4075 🔧 disable button on expired offer
  components/bsx/Offer/OfferTable.vue
  locales/en.json
Labels: ✅ - code-lgtm, paid

#4057 feat: issue_4022
  components/rmrk/Collection/List/CollectionList.vue
  components/rmrk/Gallery/Gallery.vue
  components/search/Search.vue
  components/search/SearchCollection.vue
  components/search/SearchSortDropdown.vue
  utils/constants.ts
  utils/mixins/prefixMixin.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4016 #3948 Footer redesign
  components/TheFooter.vue
  locales/en.json
  styles/abstracts/_variables.scss
  styles/components/_carousel.scss
  styles/layouts/_footer.scss
  styles/themes/_dark.scss
Labels: paid, redesign

#4093 fix: Remove infinity scroll on collection on the top
  components/rmrk/Gallery/CollectionItem.vue
Labels: ✅ - code-lgtm

#4104 fix: Hide testnet, movr & glmr on production
  components/landing/SearchLanding.vue
  components/shared/ChainSelect.vue
  package.json
  pnpm-lock.yaml
  utils/constants.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4097 feat: show only installed wallets
  utils/config/wallets.ts
Labels: paid

#4092 feat: add featured articles
  components/landing/FeaturedArticles.vue
  components/landing/LandingPage.vue
  locales/en.json
  styles/components/_article.scss
  styles/index.scss
Labels: ✅ - code-lgtm

#4095 fix: keep desc while loading
  components/rmrk/Gallery/CollectionItem.vue
Labels: ✅ - code-lgtm

#4110 fix: Transfer copy link & view transaction
  pages/transfer.vue
Labels: paid

#4131 #4116 Search shadow fix
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, paid

#4063 feat: navbar redesign
  assets/Koda_Beta.svg
  assets/Koda_Beta_dark.svg
  components/Navbar.vue
  components/common/ColorModeButton.vue
  components/navbar/NavbarExplore.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/shared/ChainSelect.vue
  components/shared/ConnectWalletButton.vue
  components/shared/SwitchLocale.vue
  layouts/default.vue
  locales/en.json
  styles/components/_button.scss
  styles/components/_search.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
  tests/cypress/support/commands.ts
Labels: paid

#4130 chore: update styleguide with info about composition api
  STYLE_GUIDE.md
Labels: ✅ - code-lgtm, paid

#4127 feat: :lipstick: release redesigned landing page
  components/Navbar.vue
  components/TheFooterOld.vue
  components/carousel/CarouselIndex.vue
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/module-old/CarouselCardFooter.vue
  components/carousel/module-old/CarouselCardInfo.vue
  components/carousel/module-old/CarouselCardMedia.vue
  components/carousel/module-old/CarouselList.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/utils/useCarousel.ts
  components/landing/LandingPage.vue
  components/landing/LandingPageOld.vue
  components/landing/ReTopCollections.vue
  components/landing/ReTopCollectionsItem.vue
  components/landing/TopCollections.vue
  components/landing/TopCollectionsItem.vue
  components/shared/KodadotSocialLinks.vue
  layouts/centered-half-layout.vue
  layouts/default.vue
  layouts/full-width-layout.vue
  pages/index.vue
  styles/components/_carousel.scss
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: blocked

#4134 fix: Redirect to incorrect place after click on collection on navbar
  components/navbar/NavbarExplore.vue
Labels: ✅ - code-lgtm

#4159 fix: Incorrect url of nft on More From This Collection
  utils/carousel.ts
Labels: paid

#4162 #4161 fixes with drawer, colors // connect wallet on mobile
  components/Navbar.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  components/shared/ConnectWalletButton.vue
  styles/abstracts/_variables.scss
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm

#4135 fix: incorrect currency displayed in profiledropdown
  components/carousel/module/CarouselInfo.vue
  components/rmrk/Gallery/CollectionDetail.vue
  components/rmrk/Gallery/Gallery.vue
  components/shared/CommonTokenMoney.vue
  utils/api/bsx/query.ts
  utils/config/chain.config.ts
  utils/mixins/prefixMixin.ts
Labels: paid

#4170 fix: More from this collection chain name
  components/carousel/module/CarouselInfo.vue
  utils/carousel.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4168 🔧 landing mobile version
  components/Navbar.vue
  components/landing/SearchLanding.vue
  styles/components/_search.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
Labels: mobile, ✅ - code-lgtm, css, ✅ - works-for-me

#4180 fix: load more
  components/search/SearchSuggestion.vue
Labels: ✅ - works-for-me

#4156 #4155 Card leftovers
  components/carousel/module/CarouselInfo.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4178 ✨ Enkrypt wallet support
  assets/partners/logo-enkrypt.png
  utils/config/wallets.ts
  utils/config/wallets/EnkryptWallet.ts
Labels: wallet, ✅ - code-lgtm, paid

#4182 fix: run kodadot with docker-compose up --build
  Dockerfile
  docker-compose.yml
Labels: ✅ - code-lgtm

#4188 fix: Neobrutalism landing page release UI
  components/Navbar.vue
  components/TheFooter.vue
  components/landing/SearchLanding.vue
  components/landing/TopCollectionsItem.vue
  styles/components/_search.scss
  styles/global.scss
  styles/layouts/_footer.scss
  styles/themes/_dark.scss
Labels: paid

#4099 ✨ snek collection stats
  components/rmrk/Gallery/CollectionItem.vue
Labels: paid

#4200 fix: Overlay of networks while searching on landing
  styles/components/_search.scss
Labels: paid

#4203 fix: make sure spotlight name not null
  queries/subsquid/general/collectionCuratedList.graphql
Labels: ✅ - code-lgtm
