Repository kodadot/nft-gallery, pull requests merged in 2022-07, with the labels that each got.

#3336 format price on bsx
  components/shared/format/Money.vue
Labels: ✅ - approved, paid

#3381 feat: calculate 14days expiration for `offer`
  components/bsx/Offer/OfferTable.vue
Labels: paid

#3391 Make sure if user has enough funds to make offer
  components/bsx/Gallery/Item/AvailableActions.vue
Labels: paid

#3382 Center table at BSX stats and handle longer item names
  components/bsx/Offer/OfferStats.vue
  components/bsx/Offer/OfferTable.vue
  pages/bsx/stats.vue
Labels: paid

#3394 fix: Pagination and infinity scrolling is broken on Basilisk & Moonsama
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/Gallery.vue
  queries/subsquid/general/collectionById.graphql
  queries/subsquid/general/nftListWithSearch.graphql
Labels: paid

#3414 fix: I can accept my own offer for nft Ive bought
  components/bsx/Offer/OfferTable.vue
Labels: paid

#3282 🔧 bsx seo preview & canonical links
  components/bsx/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Profile/ProfileDetail.vue
  nuxt.config.js
  package.json
  pages/bsx/collection/_id.vue
  pages/bsx/create.vue
  pages/bsx/detail/_id.vue
  pages/bsx/explore.vue
  pages/bsx/gallery/_id.vue
  pages/rmrk/collection/_id.vue
  pages/rmrk/explore.vue
  pages/rmrk/gallery/_id.vue
  pnpm-lock.yaml
  utils/format/balance.ts
Labels: ✅ - approved, paid

#3373 feat: Keep top border only on action buttons for on-chain actions
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  components/moonsama/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/AvailableActions.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/rmrk/Gallery/Item/ActionList.vue
  components/rmrk/Gallery/Item/Sharing.vue
  components/unique/Gallery/Item/AvailableActions.vue
  components/unique/Gallery/Item/GalleryItem.vue
  plugins/icons.ts
  styles/border.scss
  utils/account.ts
  utils/shoppingActions.ts
Labels: ✅ - approved

#3456 fix: Wrap long description on gallery item
  components/bsx/Gallery/Item/GalleryItem.vue
  components/moonsama/Gallery/Item/GalleryItem.vue
  components/unique/Gallery/Item/GalleryItem.vue
Labels: ✅ - works-for-me

#3452 feat: calculate 14days expiration for offer
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Offer/OfferTable.vue
  utils/format/time.ts
  utils/gallery/abstractCalls.ts
Labels: ✅ - works-for-me

#3442 🔧 bsx gallery sort & buy now
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
  components/rmrk/Gallery/Search/types.ts
  utils/constants.ts
Labels: ✅ - works-for-me

#3436 #3435 Removing warning errors on landing page reload
  components/rmrk/Gallery/LatestSales.vue
  components/rmrk/Gallery/NewestList.vue
Labels: ✅ - works-for-me

#3471 fix: request error from sort by condition
  components/rmrk/Gallery/CollectionItem.vue
Labels: ✅ - approved, paid, ✅ - works-for-me

#3439 #3438 Fixing search focus issue
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid, ✅ - works-for-me

#3483 fix: Duplicate of items in collection
  components/rmrk/Gallery/CollectionItem.vue
Labels: paid, ✅ - works-for-me

#3415 add to faq
  langDir/all_lang.json
  langDir/en.json
Labels: FAQ, 🤞 - changes-requested

#3495 🔧 collections cards hover
  components/rmrk/Collection/List/CollectionList.vue
Labels: ✅ - works-for-me

#3490 fix: incorrect number of NFTs in collection
  components/base/CollectionSelect.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateToken.vue
  components/unique/Create/CreateToken.vue
  queries/collectionForMint.graphql
  queries/subsquid/general/collectionForMint.graphql
  queries/unique/collectionForMint.graphql
Labels: ✅ - works-for-me

#3499 refactor: change `balance` to `amount`
  components/shared/BalanceInput.vue
Labels: paid, ✅ - works-for-me

#3453 feat: incoming offers page
  components/Navbar.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferList.vue
  components/bsx/Offer/OfferTable.vue
  components/rmrk/Profile/NavbarProfileDropdown.vue
  langDir/en.json
  pages/bsx/incomingOffers.vue
  queries/subsquid/bsx/acceptableOfferByCurrentOwner.graphql
  utils/mixins/offerMixin.ts
Labels: 🐍 - basilisk, ✅ - works-for-me

#3496 feat: history component for item
  components/bsx/Gallery/Item/GalleryItem.vue
  queries/subsquid/bsx/itemEvents.graphql
Labels: 🐍 - basilisk, paid, ✅ - works-for-me

#3474 feat: replace range slider with input fields
  components/rmrk/Gallery/Gallery.vue
  components/rmrk/Gallery/Search/SearchBar.vue
  components/shared/format/Money.vue
  components/shared/format/PriceRange.vue
  langDir/en.json
Labels: paid

#3506 fix: Wrong text after accepting incoming offer
  langDir/en.json
  utils/mixins/offerMixin.ts
Labels: ✅ - works-for-me

#3491 #3433 Search bar suggestions changes
  components/rmrk/Gallery/Search/SearchBar.vue
Labels: paid, ✅ - works-for-me

#3473 Show user balance at minting screen
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/shared/AccountBalance.vue
  pages/teleport.vue
Labels: 🐍 - basilisk, paid

#3524 fix: search gallery on bsx
  components/rmrk/Gallery/Gallery.vue
Labels: 🐍 - basilisk, paid, ✅ - works-for-me

#3526 #3508 Sorting by name collection fix
  components/bsx/Offer/OfferTable.vue
Labels: ✅ - approved, paid, ✅ - works-for-me

#3519 fix: sorting by price on offer table does not work correctly
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  utils/format/balance.ts
Labels: paid, ✅ - works-for-me

#3529 fix: BSX price input handling and input conversion
  components/bsx/Create/CreateToken.vue
  components/shared/BalanceInput.vue
Labels: ✅ - approved, paid, ✅ - works-for-me

#3525 fix: Sorting by price should always keep Buy Now on
  components/rmrk/Gallery/Search/SearchBar.vue
  components/rmrk/Gallery/Search/SearchBarCollection.vue
Labels: paid, ✅ - works-for-me

#3518 feat/3509-desc-table-bsx
  components/bsx/Offer/OfferTable.vue
  langDir/en.json
Labels: 🐍 - basilisk, ✅ - approved, paid, ✅ - works-for-me

#3536 disable prefer-symlinked-executables
  .npmrc
Labels: ✅ - approved

#3517 feat/3507-renaming-sorting-options
  components/rmrk/Gallery/Search/SearchBarCollection.vue
  components/rmrk/Gallery/Search/SearchSortDropdown.vue
  langDir/en.json
Labels: ✅ - works-for-me

#3477 #3203 add table to show currently standing offers for user
  components/bsx/Gallery/OffersUserTable.vue
  components/rmrk/Profile/ProfileDetail.vue
  queries/subsquid/bsx/offerListUser.graphql
Labels: 🐍 - basilisk, 🤞 - changes-requested, paid

#3538 fix: cant mint if I dont want to put NFT on sale
  components/bsx/Create/CreateToken.vue
Labels: paid

#3502 #3501 Pagination for global offers for Basilisk
  components/bsx/Offer/OfferTable.vue
Labels: 🐍 - basilisk, paid, ✅ - works-for-me

#3484 add collection offer
  components/bsx/Offer/CollectionOffers.vue
  components/bsx/Offer/OfferStats.vue
  components/bsx/Offer/OfferTable.vue
  components/rmrk/Gallery/CollectionItem.vue
  queries/subsquid/bsx/offerListByCollectionId.graphql
  utils/offerStatus.ts
Labels: 🐍 - basilisk, ✅ - approved, ✅ - works-for-me

#3537 fix: incorrect text on above offers table
  components/bsx/Offer/OfferStats.vue
  components/bsx/Offer/OfferTable.vue
Labels: ✅ - works-for-me

#3545 fix: default select on bsx and missing i18 on select option
  components/rmrk/Gallery/PaginatedCardList.vue
  langDir/en.json
Labels: ✅ - works-for-me

#3503 #3492 Small UI change
  components/bsx/Gallery/Item/GalleryItem.vue
Labels: ✅ - approved, ✅ - works-for-me

#3553 Add ability to sort by time in incoming offers
  components/bsx/Offer/MyOffer.vue
Labels: ✅ - approved, paid, ✅ - works-for-me

#3543 fix: some 3D nft in /collection/{id} could not display correctly
  components/rmrk/Gallery/GalleryCard.vue
Labels: ✅ - approved, paid, ✅ - works-for-me

#3552 fix: Sorting by price in offers made doesn't work properly
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/rmrk/Profile/ProfileDetail.vue
  utils/mixins/offerMixin.ts
Labels: paid, ✅ - works-for-me

#3562 feat: hidden `westend` `westmint` in production env
  components/shared/ChainSelect.vue
  nuxt.config.js
  utils/constants.ts
Labels: ✅ - approved, ✅ - works-for-me

#3566 fix: The asset instance ID has already been used for an asset
  components/bsx/Create/CreateToken.vue
Labels: paid, ✅ - works-for-me

#3551 bugfix: Tooltip not enough funds when have enough balance
  components/bsx/Gallery/Item/ActionList.vue
  components/bsx/Gallery/Item/AvailableActions.vue
  components/bsx/Gallery/Item/GalleryItem.vue
  langDir/en.json
  utils/shoppingActions.ts
Labels: paid

#3577 #3576 Fixed: Duplicate nfts in user profile created section
  components/rmrk/Gallery/PaginatedCardList.vue
Labels: ✅ - works-for-me

#3572 feat: global sorting in offer table
  components/bsx/Offer/OfferTable.vue
Labels: ✅ - works-for-me

#3590 fix: Expiration computing
  utils/api/general.ts
  utils/mixins/offerMixin.ts
Labels: ✅ - works-for-me

#3595 Balance Input
  components/bsx/Create/CreateToken.vue
  components/shared/BalanceInput.vue
  components/shared/form/BasicBalanceInput.vue
  components/shared/input/balance/NewBalanceInput.vue
  tests/balance.spec.ts
  utils/balance.ts
Labels: ✅ - approved-code, ✅ - works-for-me

#3581 fix: incorrect information on user offer at profile page
  components/bsx/Offer/OffersUserTable.vue
  components/rmrk/Profile/ProfileDetail.vue
Labels: paid, ✅ - works-for-me

#3578 refactor: add expiration date and filtering options to offers everywhere
  components/bsx/Offer/CollectionOffers.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  queries/subsquid/bsx/offerListUser.graphql
  utils/mixins/offerMixin.ts
Labels: paid, ✅ - works-for-me

#3573 fix: BalanceInput
  components/bsx/Gallery/Item/AvailableActions.vue
  components/shared/BalanceInput.vue
Labels: ✅ -code-LGTM, paid, ✅ - works-for-me

#3618 bugfix: hide pagination when item amount is small
  components/bsx/Offer/OfferTable.vue
  utils/mixins/offerMixin.ts
Labels: ✅ -code-LGTM, ✅ - works-for-me

#3614 fix: Can not see other columns at certain width
  components/bsx/Offer/OfferTable.vue
Labels: paid, ✅ - works-for-me

#3633 fix: balanceInput is broken
  components/bsx/Gallery/Item/AvailableActions.vue
  components/shared/BalanceInput.vue
Labels: ✅ - works-for-me

#3631 fix: remove bar from empty table
  components/bsx/Offer/OfferTable.vue
Labels: paid, ✅ - works-for-me
