Repository kodadot/nft-gallery, pull requests merged in 2023-11, with the labels that each got.

#7895 fix: Not possible to play with generative art drop page when not connected
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativePreview.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7862 fix: Current generative drops are not unlockable
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableItemInfo.vue
  components/collection/unlockable/UnlockableTag.vue
  components/collection/voteDrop/DropContainer.vue
  composables/useUnlockable.ts
  services/keywise.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7860 fix: real full screen for nft img #7846
  components/collection/activity/Activity.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemPreviewer.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#7886 fix: subscribe form missing on route navigation
  components/CustomSubstackEmbed.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7889 feat: remove hover action on touch device
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7868 Show image as fallback when video is loading or fails (video poster)
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  utils/gallery/media.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#7698 #7685 replace placeholders
  components/collection/CollectionHeader/CollectionBanner.vue
  composables/useTheme.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  public/Kdark.webp
  public/Klight.webp
  utils/constants.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7915 fix: Remove "beta" from Chain selection menu options + reorder
  libs/static/src/chains.ts
  libs/static/src/names.ts
  tests/e2e/createcollection.spec.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7916 fix: Mint phase time is off for generative drop
  components/collection/drop/Generative.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7918 beta update
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_assetshub.yml
  components/CustomSubstackEmbed.vue
  components/carousel/CarouselTypeLatestMints.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/Activity.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableItemInfo.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/UnlockableTag.vue
  components/collection/voteDrop/DropContainer.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemPreviewer.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/massmint/Massmint.vue
  components/shared/Markdown.vue
  components/shared/form/BasicSwitch.vue
  composables/useTheme.ts
  composables/useUnlockable.ts
  libs/static/src/chains.ts
  libs/static/src/names.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  locales/en.json
  package.json
  plugins/vueHtmlSecure.ts
  pnpm-lock.yaml
  public/Kdark.webp
  public/Klight.webp
  services/capture.ts
  services/keywise.ts
  tests/e2e/createcollection.spec.ts
  tests/e2e/footer.spec.ts
  utils/constants.ts
  utils/gallery/media.ts
Labels: large, waiting-for-review, beta

#7919 release update
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_assetshub.yml
  components/CustomSubstackEmbed.vue
  components/carousel/CarouselTypeLatestMints.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/Activity.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableItemInfo.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/UnlockableTag.vue
  components/collection/voteDrop/DropContainer.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemPreviewer.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/massmint/Massmint.vue
  components/shared/Markdown.vue
  components/shared/form/BasicSwitch.vue
  composables/useTheme.ts
  composables/useUnlockable.ts
  libs/static/src/chains.ts
  libs/static/src/names.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  locales/en.json
  package.json
  plugins/vueHtmlSecure.ts
  pnpm-lock.yaml
  public/Kdark.webp
  public/Klight.webp
  services/capture.ts
  services/keywise.ts
  tests/e2e/createcollection.spec.ts
  tests/e2e/footer.spec.ts
  utils/constants.ts
  utils/gallery/media.ts
Labels: release, large, waiting-for-review

#7914 Change minimal copies to 1 by default
  components/create/CreateNft.vue
Labels: small, waiting-for-review

#7907 Menu buttons
  components/shared/filters/MobileFilter.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7623 perf: Graphql CDN using Stellate
  components/TheFooter.vue
  libs/static/src/indexers.ts
  utils/constants.ts
  utils/websocket.ts
Labels: paid, small, waiting-for-review, Open to discussion

#7910 Go back to main menu after selecting chain
  components/Navbar.vue
  components/navbar/MobileExpandableSection.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/NavbarChainOptions.vue
  components/navbar/NavbarExploreOptions.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7639 feat: support non ipfs metadata url
  components/carousel/CarouselTypeRelated.vue
  components/gallery/GalleryItemDescription.vue
  utils/config/ipfs.ts
  utils/ipfs.ts
Labels: small, waiting-for-review

#7927 feat: Download template in massmint onboard
  components/massmint/OnBoarding.vue
  locales/en.json
  public/massmint/template.csv
  public/massmint/template.json
  public/massmint/template.txt
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7913 fix: vue component ref type
  components/base/BaseCollectionForm.vue
  components/base/BaseTokenForm.vue
  components/search/SearchBar.vue
  components/shared/form/BasicBalanceInput.vue
Labels: small, waiting-for-review

#7849 Enviroment var to expand test cases
  .env.example
  .github/workflows/playwright.yml
  nuxt.config.ts
  pages/e2e-login.vue
  tests/e2e/account.spec.ts
  tests/e2e/createcollection.spec.ts
Labels: ✅ - works-for-me, small

#7908 feat: assethub show empty collection and delete collection
  components/collection/CollectionGrid.vue
  components/collection/HeroButtons.vue
  components/profile/ProfileDetail.vue
  composables/transaction/transactionBurn.ts
  composables/transaction/types.ts
  composables/useTransaction.ts
  layouts/explore-layout.vue
  plugins/loader.ts
  queries/subsquid/general/collectionByIdMicro.graphql
  queries/subsquid/general/collectionListWithSearchProfile.graphql
  queries/subsquid/general/profileTabsCount.graphql
Labels: ✅ - works-for-me, medium, waiting-for-review

#7950 fix: Spacing between sections in gallery item
  assets/styles/abstracts/_variables.scss
  components/gallery/GalleryItem.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7949 fix: Profile not full width
  layouts/full-width-no-footer.vue
  pages/[prefix]/u/[id].vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7929 Test: Explore test refactor and small prefix test addition
  components/explore/ExploreTabs.vue
  tests/e2e/custom.ts
  tests/e2e/explore.spec.ts
  tests/e2e/prefix.spec.ts
Labels: ✅ - works-for-me, medium

#7933 fix: Status of Minting when collection is minted out
  components/drops/DropCard.vue
  components/drops/TimeTag.vue
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#7953 #7932 view collection button too close
  components/collection/unlockable/UnlockableCollectionInfo.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7943 fix: banner background position
  components/collection/CollectionHeader/CollectionBanner.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok, small, waiting-for-review

#7940 Mobile collection card
  components/collection/CollectionGrid.vue
  components/shared/DynamicGrid.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7954 Revert "Enviroment var to expand test cases"
  .env.example
  .github/workflows/playwright.yml
  nuxt.config.ts
  pages/e2e-login.vue
  tests/e2e/account.spec.ts
  tests/e2e/createcollection.spec.ts
Labels: small, waiting-for-review

#7967 fix: disable verbatimModuleSyntax
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/search/SearchSuggestion.vue
  components/shared/QRCode.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoSecondaryButton/NeoSecondaryButton.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  tsconfig.json
Labels: ✅ - code-lgtm, small, waiting-for-review

#7820 🔧 sentry plugin
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: medium, waiting-for-review

#7938 Test: Create NFT page
  components/bsx/Create/RoyaltyForm.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/create/CreateNftPreview.vue
  components/rmrk/Create/AttributeInput.vue
  components/rmrk/Create/CustomAttributeInput.vue
  tests/e2e/createnft.spec.ts
  tests/e2e/custom.ts
Labels: medium

#7979 fix: Errors on landing
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  queries/subsquid/general/latestEvents.graphql
  queries/subsquid/ksm/latestEvents.graphql
Labels: ✅ - works-for-me, small, waiting-for-review

#7961 fix: Select all on profile only works on Assethubs
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7946 feat: new teleport page
  components/teleport/NetworkDropdown.vue
  components/teleport/Teleport.vue
  layouts/teleport-layout.vue
  locales/en.json
  pages/[prefix]/teleport.vue
  utils/chain.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#7958 sync deposit with copies
  components/create/CreateNft.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#7960 🔧 burn collection all chains
  components/collection/HeroButtons.vue
  components/create/CreateNft.vue
  composables/transaction/transactionBurn.ts
  composables/transaction/types.ts
Labels: small, waiting-for-review

#7988 fix-create nft test
  tests/e2e/createnft.spec.ts
Labels: small, waiting-for-review

#7991 feat: Add to landing generative mints
  components/carousel/CarouselTypeGenerative.vue
  components/carousel/utils/useCarouselEvents.ts
  components/landing/LandingPage.vue
  locales/en.json
Labels: small, waiting-for-review

#7968 remove not enough balance disabled status
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7711 feat: Auto teleport V1
  assets/styles/abstracts/_animations.scss
  assets/styles/global.scss
  components/balance/MultipleBalances.vue
  components/buy/Buy.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportTooltip.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  components/shared/OnRampModal.vue
  components/shared/TransactionSteps/TransactionSteps.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/TransactionSteps/utils.ts
  components/teleport/Teleport.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleport.ts
  composables/autoTeleport/useAutoTeleportTransactionActions.ts
  composables/autoTeleport/useAutoTeleportTransition.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/autoTeleport/useAutoTeleportWatch.ts
  composables/transaction/mintCollection/transactionMintCollectionBasilisk.ts
  composables/transaction/mintCollection/transactionMintCollectionRmrk.ts
  composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
  composables/transaction/transactionMintCollection.ts
  composables/transaction/types.ts
  composables/useAmount.ts
  composables/useExplorer.ts
  composables/useMultipleBalance.ts
  composables/useTeleport.ts
  composables/useTransaction.ts
  locales/en.json
  public/accent-blur.svg
  public/auto-teleport-arrow-disabled.svg
  public/auto-teleport-arrow.svg
  stores/fiat.ts
  stores/preferences.ts
  utils/balance.ts
  utils/math.ts
  utils/teleport.ts
  utils/transactionExecutor.ts
Labels: 🤞 - changes-requested, paid, large, waiting-for-review

#7993 Expand event limit for generative on landing
  components/carousel/utils/useCarouselEvents.ts
Labels: small, waiting-for-review

#7985 Bump XCM SDK -> 3.0.5
  package.json
  pnpm-lock.yaml
Labels: ✅ - works-for-me, small

#7984 Teleport V2 followups
  components/teleport/NetworkDropdown.vue
  components/teleport/Teleport.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#7986 ✨ confirm delete collection modal
  components/collection/ConfirmDeleteCollectionModal.vue
  components/collection/HeroButtonDeleteCollection.vue
  locales/en.json
  tests/e2e/createnft.spec.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#8017 fix edge case
  components/collection/activity/utils.ts
Labels: small, waiting-for-review

#7987 remove padding from collectionprofile image
  components/collection/CollectionHeader/CollectionBanner.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8028 fix: Add bottom margin to the burger menu
  components/shared/filters/modules/AdvancedFilter.vue
Labels: small, waiting-for-review

#8040 🔧 uniq legacy burn
  utils/gallery/abstractCalls.ts
Labels: small, waiting-for-review

#8026 fix: Nested nfts does not appears in More & Visited
  components/carousel/utils/useCarousel.ts
  queries/fragments/nftResources.graphql
  queries/subsquid/ksm/nftEntitiesByIDs.graphql
Labels: ✅ - code-lgtm, small, waiting-for-review

#8035 query for resources on ksm collection activity
  composables/collectionActivity/useCollectionActivity.ts
  queries/subsquid/ksm/collectionActivityEvents.graphql
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8006 feat: migration UI - Review & Congrats page
  components/migrate/landing/content/Ready.vue
  components/migrate/steps/Review.vue
  composables/useMigrate.ts
  composables/useMultipleBalance.ts
  locales/en.json
  pages/migrate/congrats.vue
Labels: ✅ - works-for-me, large

#8025 feat: On teleport should be selected related pair of chain
  components/teleport/Teleport.vue
  utils/teleport.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8019 fix: ipfs utils bypass kodaimage
  utils/ipfs.ts
Labels: small

#7917 fix: Mobile burger movement and consistency
  assets/styles/abstracts/_variables.scss
  assets/styles/components/_connect-wallet.scss
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/common/shoppingCart/ShoppingCartModal.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#8031 Fallbacks for getting token prices
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  nuxt.config.ts
  pnpm-lock.yaml
  stores/fiat.ts
  utils/coingecko.ts
  utils/constants.ts
  utils/price.ts
  utils/support.ts
Labels: medium, waiting-for-review

#8053 🔧 lint code
  components/collection/voteDrop/DropContainer.vue
  components/create/CreateCollection.vue
  components/rmrk/service/scheme.ts
  composables/autoTeleport/useAutoTeleportTransition.ts
Labels: small, waiting-for-review

#8049 missing checkmark
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
Labels: ✅ - works-for-me, small

#8048 feat: Tooltip learn more auto teleport
  components/common/autoTeleport/AutoTeleportTooltip.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8016 mint NFT - show USD value
  components/create/CreateNft.vue
  composables/useUsdValue.ts
  stores/fiat.ts
  tests/e2e/createnft.spec.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8050 replace placeholders
  public/Kdark.webp
  public/Klight.webp
  utils/constants.ts
Labels: ✅ - visual-ok, small, waiting-for-review

#8036 feat: kodaprice
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  nuxt.config.ts
  stores/fiat.ts
  utils/coinprice.ts
  utils/constants.ts
  utils/price.ts
  utils/support.ts
Labels: paid, ✅ - works-for-me, medium, waiting-for-review

#8055 feat: Disable video controls on explore cards
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8072 🔧 carousel icon pack
  libs/ui/src/components/NeoCarousel/NeoCarousel.vue
Labels: ✅ - works-for-me

#8056 Footer improvements
  assets/styles/layouts/_footer.scss
  components/TheFooter.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#8075 fix: Unable to mint continuously on ahk
  composables/transaction/mintToken/transactionMintStatemine.ts
  tests/transactionMintStatemine.spec.ts
Labels: ✅ - works-for-me

#8059 fix: Refetch data after changing tab
  components/collection/CollectionHeader/CollectionBanner.vue
  layouts/explore-layout.vue
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/collection/[id]/index.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8064 use only 400 and 700 font-weight
  assets/styles/layouts/_main-navigation.scss
  assets/styles/pages/create.scss
  components/blog/BlogPost.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/migrate/landing/content/Index.vue
  components/migrate/landing/header/Faq.vue
  components/shared/view/InfoBox.vue
  nuxt.config.ts
Labels: ✅ - works-for-me

#8067 padding around images
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: ✅ - works-for-me, small

#8024 fix: BSX Assets page broken
  components/bsx/Asset/AssetList.vue
  components/bsx/Asset/AssetTable.vue
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoLoading/NeoLoading.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
Labels: ✅ - code-lgtm, 🤞 - changes-requested, ✅ - works-for-me, small, waiting-for-review

#8101 fix: Countdown gone in drop page
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/voteDrop/DropContainer.vue
Labels: ✅ - works-for-me

#8079 mobile / Nova Wallet -> full screen button in galleryItem
  assets/styles/global.scss
  components/gallery/GalleryItem.vue
Labels: ✅ - works-for-me

#8102 :snake: good bye Snek [Rococo]
  .vscode/settings.json
  components/carousel/utils/useCarouselEvents.ts
  components/common/ConnectWallet/WalletAsset.vue
  components/common/NotificationBox/useNotification.ts
  components/common/shoppingCart/utils.ts
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/landing/LandingPage.vue
  components/navbar/StatsDropdown.vue
  components/shared/BlockExplorerLink.vue
  composables/collectionActivity/helpers.ts
  composables/transaction/mintCollection/constructMeta.ts
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/transactionList.ts
  composables/transaction/transactionMintCollection.ts
  composables/transaction/transactionMintToken.ts
  composables/transaction/transactionSend.ts
  composables/useBalance.ts
  composables/useChain.ts
  composables/useExplorer.ts
  composables/useIsChain.ts
  composables/useMultipleBalance.ts
  composables/usePrefix.ts
  composables/useUsdValue.ts
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  pages/bsx/assets.vue
  pages/snek/assets.vue
  pages/snek/claim.vue
  pages/snek/incomingOffers.vue
  pages/snek/offers.vue
  pages/snek/stats.vue
  stores/fiat.ts
  stores/identity.ts
  utils/api/bsx/query.ts
  utils/chain.ts
  utils/config/chain.config.ts
  utils/config/permission.config.ts
  utils/constants.ts
  utils/gallery/abstractCalls.ts
  utils/prefix.ts
Labels: ✅ - works-for-me

#8119 💅 generative art in popular collection
  composables/popularCollections/constants.ts
Labels: ✅ - works-for-me

#8123 "to" below "from" on narrow device
  components/collection/activity/events/eventRow/EventRowTablet.vue
Labels: ✅ - works-for-me

#8118 fix: preheat wrong file
  utils/ipfs.ts
Labels: ✅ - works-for-me

#8116 fix: allow opengraph on details page
  public/robots.txt
Labels: ✅ - code-lgtm

#8110 fix: Loader text [stuck...] can be hidden once tx is signed
  components/shared/Loader.vue
Labels: ✅ - works-for-me

#8099 🔧 buy now stroke cart icon
  components/Navbar.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
  composables/useShoppingCartIcon.ts
Labels: ✅ - works-for-me, ✅ - visual-ok

#8105 fix: auto-add #{sn} to the name of nft
  composables/useNft.ts
  queries/subsquid/general/latestEvents.graphql
  queries/subsquid/ksm/latestEvents.graphql
  utils/carousel.ts
  utils/nft.ts
Labels: ✅ - works-for-me

#8125 Drops-max-card-width
  components/drops/DropCard.vue
  components/drops/Drops.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small

#8157 fix: pfp in collection detail
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#8128 toggle ramp instance variant
  composables/useRamp.ts
Labels: ✅ - code-lgtm, small

#8168 close transfer modal to reveal loading modal
  components/common/itemTransfer/ItemTransferModal.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8165 fix: Scrolling down on collection activity tab resets the page
  layouts/explore-layout.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8148 Fixed slider borders
  components/collection/unlockable/UnlockableSlider.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8156 avoid spamming `executeTransaction`
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/transaction/utils.ts
  composables/useTransaction.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8167 Update LICENSE
  LICENSE
Labels: small, waiting-for-review

#8144 fix: Auto teleport fails on buy step and no icons on dark mode welcome modal
  assets/styles/global.scss
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/shared/TransactionSteps/TransactionSteps.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  utils/support.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8174 🔧 round 2 card price
  components/shared/CommonTokenMoney.vue
  components/shared/format/Money.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7921 Search mobile
  assets/styles/components/_search.scss
  components/Navbar.vue
  components/search/SearchBar.vue
  public/search-mobile-navbar-dark.svg
  public/search-mobile-navbar.svg
Labels: ✅ - works-for-me, small, waiting-for-review

#8152 fix: Dynamic modal copy based on context
  components/common/autoTeleport/AutoTeleportActionButton.vue
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#8183 fix: build on cf-pages
  .github/workflows/build.yml
  pnpm-lock.yaml
Labels: large, waiting-for-review

#8185 Setup @nuxt/image
  components/carousel/module/CarouselMedia.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/gallery/GalleryItem.vue
  components/massmint/EditPanel.vue
  components/massmint/OverviewTable.vue
  components/profile/activityTab/HistoryRow.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
  libs/ui/src/components/TheImage/TheImage.vue
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  providers/cloudflare.ts
Labels: paid, ✅ - works-for-me, large, waiting-for-review

#8145 fix: Cart icon scalling in quick actions
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small

#8190 trim leading zeroes
  utils/nft.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8141 Integrated tailwindcss, refactored colors and rewrote NeoButton component
  assets/styles/components/_connect-wallet.scss
  libs/ui/histoire.config.ts
  libs/ui/package.json
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.story.vue
  libs/ui/src/histoire.scss
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#8199 keep items alive only while in collection path
  pages/[prefix]/collection/[id]/index.vue
Labels: small, waiting-for-review

#8195 Test: Collection test and small modifications
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/CollectionInfo.vue
  components/collection/HeroButtons.vue
  components/collection/activity/ActivityChart.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/explore/tab/TabOnCollection.vue
  components/shared/filters/SidebarFilter.vue
  components/shared/filters/modules/AdvancedFilter.vue
  components/shared/filters/modules/EventTypeFilter.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  tests/e2e/collection.spec.ts
  tests/e2e/createcollection.spec.ts
  tests/e2e/custom.ts
  tests/e2e/explore.spec.ts
  tests/e2e/footer.spec.ts
  tests/e2e/galleryitem.spec.ts
  tests/e2e/language.spec.ts
  tests/e2e/prefix.spec.ts
  tests/e2e/profile.spec.ts
  tests/e2e/redirect.spec.ts
  tests/e2e/search.spec.ts
Labels: medium, waiting-for-review

#8202 :facepalm: landing has hardcode generative art
  components/carousel/CarouselTypeGenerative.vue
Labels: small, waiting-for-review

#8208 :bug: cannot mint when capture fails
  components/collection/drop/Generative.vue
  locales/en.json
Labels: small, waiting-for-review

#8213 🔧 drops view collection button
  components/collection/unlockable/UnlockableCollectionInfo.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8216 fix: disabled drop
  components/drops/DropCard.vue
  components/drops/useDrops.ts
Labels: ✅ - code-lgtm, small

#8214 🔧 generate drop button
  components/collection/drop/GenerativePreview.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8182 fix: Navbar desktop and mobile
  assets/styles/abstracts/_variables.scss
  assets/styles/components/_connect-wallet.scss
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/Navbar.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/navbar/MobileExpandableSection.vue
  components/shared/filters/MobileFilter.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  public/Koda.svg
  public/Koda_dark.svg
Labels: ✅ - works-for-me, medium, waiting-for-review

#8188 fix: download image does not work
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  locales/en.json
Labels: ✅ - works-for-me, small

#8217 beta update
  assets/styles/abstracts/_variables.scss
  assets/styles/components/_connect-wallet.scss
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/Navbar.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/drops/DropCard.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/navbar/MobileExpandableSection.vue
  components/shared/filters/MobileFilter.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  locales/en.json
  public/Koda.svg
  public/Koda_dark.svg
Labels: beta

#8181 fix: Fix auto-teleport modal on mobile
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8230 Fix/scrolling-redirect
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/collection/[id]/index.vue
Labels: small, waiting-for-review

#8229 CardArticle to tailwindcss
  libs/ui/src/components/CardArticle/CardArticle.scss
  libs/ui/src/components/CardArticle/CardArticle.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
Labels: ✅ - code-lgtm, small, waiting-for-review

#8235 beta update
  assets/styles/global.scss
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/create/Confirm/ConfirmMintItem.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/Confirm/PriceItem.vue
  components/shared/format/Money.vue
  libs/ui/src/components/CardArticle/CardArticle.scss
  libs/ui/src/components/CardArticle/CardArticle.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/components/NeoModal/NeoModal.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/collection/[id]/index.vue
Labels: medium, waiting-for-review, beta

#8236 release update
  assets/styles/global.scss
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/create/Confirm/ConfirmMintItem.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/Confirm/PriceItem.vue
  components/shared/format/Money.vue
  libs/ui/src/components/CardArticle/CardArticle.scss
  libs/ui/src/components/CardArticle/CardArticle.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/components/NeoModal/NeoModal.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/collection/[id]/index.vue
Labels: release, medium

#8239 Fixed onerror in NeoAvatar
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8242 fix: chunk paraspell sdk
  components/collection/drop/TokenImportButton.vue
  nuxt.config.ts
Labels: small, waiting-for-review

#8256 fix: Text not aligned
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/shared/format/Money.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#8249 Fix: Wrong Chainsymbol showing in total spending on profile page #8248
  components/profile/ProfileActivitySummery.vue
  locales/en.json
Labels: small, waiting-for-review

#8255 fix: Modals width broken
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/create/Confirm/ConfirmMintItem.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#8259 fix: floor price dose not load on profile page
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  queries/subsquid/ahk/nftListWithSearch.graphql
  queries/subsquid/general/nftListWithSearch.graphql
  queries/subsquid/ksm/nftListWithSearch.graphql
  queries/subsquid/rmrk/nftListWithSearch.graphql
Labels: ✅ - works-for-me, ✅ - visual-ok, small

#8257 LatestSales---show-sale-price
  components/base/types.ts
  components/carousel/module/CarouselInfo.vue
  components/carousel/utils/useCarouselEvents.ts
  queries/subsquid/general/latestEvents.graphql
  queries/subsquid/ksm/latestEvents.graphql
Labels: ✅ - works-for-me, ✅ - visual-ok, small

#8252 fix: fallback nuxt image
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
Labels: small, waiting-for-review

#8267 🔧 libs/ui build error
  .github/CODEOWNERS
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
  libs/ui/src/components/TheImage/TheImage.vue
Labels: small, waiting-for-review

#8277 Tests/Remove old Cypress tests
  tests/cypress-deprecated/basicE2E.cy.ts
  tests/cypress-deprecated/commands.ts.old
  tests/cypress-deprecated/create-collection.cy.ts
  tests/cypress-deprecated/e2e-run-tests.js
  tests/cypress-deprecated/e2e.ts
  tests/cypress-deprecated/identity.cy.ts
  tests/cypress-deprecated/language.cy.ts
  tests/cypress-deprecated/media.cy.ts
  tests/cypress-deprecated/opengraph-collection.cy.ts
  tests/cypress-deprecated/opengraph-item.cy.ts
  tests/cypress-deprecated/prefix.cy.ts
  tests/cypress-deprecated/redirect.cy.ts
  tests/cypress-deprecated/rmrk-simple-mint.cy.ts
Labels: large, waiting-for-review

#8263 fix: Gap between banner and navbar
  assets/styles/layouts/_main-navigation.scss
  components/collection/collectionInfoLine.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8276 Fix/Collection and explore tests failing
  tests/e2e/collection.spec.ts
  tests/e2e/explore.spec.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium

#8253 Collection-activity-toggle-hide-outliers
  assets/styles/components/_price-chart.scss
  components/chart/PriceChart.vue
  components/collection/activity/ActivityChart.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/en.json
Labels: small, waiting-for-review

#8270 Collection-activity-toggle-smoothing
  components/chart/PriceChart.vue
  components/collection/activity/ActivityChart.vue
  locales/en.json
Labels: ✅ - code-lgtm, paid, small, waiting-for-review

#8124 feat: Loading modal for actions
  assets/styles/abstracts/_theme.scss
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/shared/modals/ModalBody.vue
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.scss
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue
  libs/ui/src/scss/_theme.scss
  locales/en.json
Labels: 🤞 - changes-requested, large, waiting-for-review

#8274 🔧 libs/ui MediaItem
  components/base/MediaItem.vue
  components/carousel/module/CarouselMedia.vue
  components/collection/drop/GenerativePreview.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/shared/DropUpload.vue
  libs/ui/src/components/MediaItem/MediaItem.story.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  libs/ui/src/index.ts
Labels: medium, waiting-for-review

#8284 (chore): deprecating old routes on waifu
  components/poap/claim/ClaimForm.vue
  pages/bsx/claim.vue
  services/waifu.ts
Labels: medium, waiting-for-review

#8292 🔧 reviewdog lint
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
Labels: small, waiting-for-review

#8275 Added trick to save iframe with good quality
  libs/ui/src/components/MediaItem/type/IFrameMedia.vue
Labels: ✅ - works-for-me, small

#8298 :wrench: new drop is snowflakes
  components/carousel/CarouselTypeGenerative.vue
  components/collection/unlockable/UnlockableLandingTag.vue
Labels: small, waiting-for-review

#8288 feat: Lazy Drops
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/voteDrop/DropContainer.vue
  components/drops/useDrops.ts
  params/types.ts
  queries/subsquid/general/firstNftOwnedByAccountAndCollectionId.graphql
  services/waifu.ts
Labels: ✅ - works-for-me, medium

#8306 chore: prevent reload on development mode
  nuxt.config.ts
Labels: small, waiting-for-review

#8290 fix: Chart tooltip is in background
  components/chart/PriceChart.vue
  components/shared/collection/PriceChart.vue
Labels: ✅ - works-for-me, small

#8289 fix: Search Hard to read (adjust colours)
  components/shared/gallery/NeoTag.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#8294 feat: Email signup modal for free drops
  assets/styles/abstracts/_animations.scss
  components/collection/drop/DropConfirmModal.vue
  components/collection/drop/Generative.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  locales/en.json
  services/waifu.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#8308 fix: Loading screen boring
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/voteDrop/DropContainer.vue
Labels: ✅ - works-for-me, small
