Repository kodadot/nft-gallery, pull requests merged in 2023-05, with the labels that each got.

#5821 fix: unit display on snek network
  plugins/assets.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#5802 test: fix identity display name
  composables/useApi.ts
  tests/cypress/e2e/components/identity.cy.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5847 fix: Price in Units
  tests/unit-testing/components/shared/BalanceInput.test.ts
  tests/unit-testing/components/shared/BasicBalanceInput.test.ts
  utils/mixins/prefixMixin.ts
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#5855 Update QA.md
  QA.md
Labels: docs, small, waiting-for-review

#5796 fix: hide owner dropdown on collection page
  components/collection/HeroButtons.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5733 #5726 card changes #5727 button space issue
  components/explore/ExploreOffer.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  styles/components/_collection-card.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#5774 tests: fix skipped e2e tests
  components/collection/HeroButtons.vue
  components/explore/ExploreSort.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/items/ItemsGrid/ItemsGrid.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  tests/cypress.config.ts
  tests/cypress/e2e/basicE2E.cy.ts
  tests/cypress/support/commands.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#5860 Reverting back to marckV2 for rmrk2
  libs/static/src/indexers.ts
Labels: small, waiting-for-review

#5848 Unlockable-content
  assets/unlockable-dark.svg
  assets/unlockable.svg
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/UnlockableTag.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/rmrk/service/scheme.ts
  composables/useUnlockable.ts
  composables/useUnlockableIcon.ts
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  locales/en.json
  services/keywise.ts
  utils/constants.ts
Labels: medium, waiting-for-review

#5871 waifu 8th iteration
  components/generative/GenerativeMintForm.vue
  components/generative/options.ts
  components/generative/promptBuilder.ts
  services/replicate.ts
  services/waifu.ts
  utils/constants.ts
Labels: small, waiting-for-review

#5842 fix: Offers tab on kusama bug
  libs/ui/src/components/DisablableTab/DisablableTab.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#5751 feat: carousel for resources on gallery detail
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemPreviewer.vue
  components/gallery/useGalleryItem.ts
  composables/useNft.ts
Labels: ✅ - code-lgtm, ✅ - visual-ok, medium, waiting-for-review

#5831 fix: modal style
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/shared/Sharing.vue
  components/shared/modals/ModalWrapper.vue
  libs/ui/src/components/NeoModal/NeoModal.vue
  styles/global.scss
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#5851 Search items on top of collections
  components/gallery/GalleryItem.vue
  components/items/ItemsGrid/utils/useSearchParams.ts
  components/rmrk/Gallery/History.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  components/search/Search.vue
  components/search/SearchBar.vue
  components/search/SearchCollection.vue
  components/search/TypeTagInput.vue
  components/search/utils/useCollectionSearch.ts
  components/series/SeriesTable.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/gallery/NeoTag.vue
  components/spotlight/SpotlightTable.vue
  locales/en.json
  pages/transform.vue
  styles/abstracts/_theme.scss
  styles/components/_search.scss
  styles/layouts/_main-navigation.scss
  utils/exist.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#5892 fix: Enable RMRK2 on production - kodadot.xyz
  libs/static/src/chains.ts
  utils/chain.ts
Labels: small, waiting-for-review

#5885 ➖ remove FAQ component
  components/common/FrequentlyAsked.vue
  locales/bn.json
  locales/cn.json
  locales/cz.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/it.json
  locales/jp.json
  locales/ko.json
  locales/nl.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sk.json
  locales/tu.json
  locales/ua.json
  locales/ur.json
  locales/vt.json
  pages/rmrk/faq.vue
  static/sitemap.xml
Labels: ✅ - code-lgtm, large, waiting-for-review

#5765 Massmint - Table + Edit Panel + Dialogs
  components/massmint/ChooseCollectionDropdown.vue
  components/massmint/EditPanel.vue
  components/massmint/Massmint.vue
  components/massmint/OverviewTable.vue
  components/massmint/modals/DeleteModal.vue
  components/massmint/modals/MintingModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/ReviewModal.vue
  components/massmint/modals/modals.scss
  components/massmint/types.ts
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadCompressedMedia/useZipValidator.ts
  components/massmint/useMassMint.ts
  layouts/noFooter.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoInput/NeoField.vue
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoInput/NeoInput.vue
  libs/ui/src/components/NeoModal/NeoModal.vue
  libs/ui/src/components/NeoSidebar/NeoSidebar.scss
  libs/ui/src/components/NeoSidebar/NeoSidebar.vue
  libs/ui/src/index.ts
  libs/ui/src/types.ts
  locales/en.json
  pages/_prefix/massmint/index.vue
  styles/abstracts/_theme.scss
  styles/global.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, large

#5823 🔧 ChainMoney composition api
  components/shared/format/ChainMoney.vue
Labels: small, waiting-for-review

#5844 #5772 nsfw changes in gallery
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  locales/en.json
Labels: small, waiting-for-review

#5895 ➖ remove b-progress component
  components/metadata/Metadata.vue
Labels: small, waiting-for-review

#5904 fix: Newest list/latest sales not showing rmrk2 NFTs
  components/carousel/utils/useCarousel.ts
Labels: small, waiting-for-review

#5911 fix: Spotlighted: rmrk2
  components/carousel/utils/useCarouselSpotlight.ts
Labels: small, waiting-for-review

#5875 fix: Chart dropdown menu all white buttons
  components/chart/PriceChart.vue
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#5914 :ambulance: default prefix is not your default prefix
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#5916 fix: Spotlighted: rmrk2 - add more
  components/carousel/utils/useCarouselSpotlight.ts
Labels: small, waiting-for-review

#5924 :bug: name could be null
  components/shared/filters/modules/usePopularCollections.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5864 chore: upgrade polkadot packages
  .browserslistrc
  components/gallery/GalleryItemDescription.vue
  nuxt.config.js
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#5927 :boom: take url by prefix
  libs/static/src/endpoints.ts
  utils/chain.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5925 fix: Add other RMRK2 Collections to sidebar
  components/shared/filters/modules/constants.ts
Labels: small, waiting-for-review

#5929 :tada: we got rid of the annoying polkadot messages
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#5931 Custom Link component for NeoNftCard
  components/items/ItemsGrid/ItemsGridImage.vue
  components/shared/gallery/NftCard.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#5928 fix: Notification Setting price now will.. not visible and ugly af
  styles/global.scss
Labels: small, waiting-for-review

#5858 #5852 Buefy icon to neo icon
  components/Navbar.vue
  components/TheFooter.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/IdentityForm.vue
  components/common/LoadPreviousPage.vue
  components/explore/FilterMenuButton.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/module/IdentitySocial.vue
  components/landing/EsCarbonless.vue
  components/landing/EsSustainability.vue
  components/navbar/MobileExpandableSection.vue
  components/rmrk/Create/DropUpload.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/Item/Facts.vue
  components/rmrk/Gallery/Layout.vue
  components/rmrk/Gallery/PriceChart.vue
  components/search/SearchSuggestion.vue
  components/series/SeriesTable.vue
  components/settings/KeyboardShortcuts.vue
  components/shared/DragDrop.vue
  components/shared/ScrollTopButton.vue
  components/shared/Sharing.vue
  components/shared/Tooltip.vue
  components/shared/collapse/CollapseCardWrapper.vue
  components/shared/collapse/CollapseWrapper.vue
  components/shared/collapse/DescriptionWrapper.vue
  components/shared/filters/MobileFilter.vue
  components/shared/filters/modules/EventTypeFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/PriceFilter.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/gallery/BaseGalleryItem.vue
  components/unique/Gallery/Item/Detail.vue
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  pages/carbonless.vue
  pages/sustainability.vue
  pages/teleport.vue
  pages/transfer.vue
  styles/layouts/_footer.scss
Labels: ✅ - code-lgtm, medium, waiting-for-review

#5883 #5853 neo modal
  components/gallery/GalleryItemPreviewer.vue
  libs/ui/src/components/NeoModal/NeoModal.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#5915 add skeleton for the item count
  components/collection/CollectionList.vue
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#5862 Tooltip improvements
  components/common/NotificationBox/NotificationItem.vue
  components/explore/ExploreOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/shared/filters/modules/PopularCollections.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: small, waiting-for-review

#5894 #5889 hiding stats
  components/Navbar.vue
  tests/cypress/support/commands.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5937 🔧 footer hello links
  components/TheFooter.vue
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/id.json
  locales/pt.json
  pages/contribute.vue
  pages/tutorials.vue
Labels: small, waiting-for-review

#5400 ✨ migrate Identity store to pinia
  components/Navbar.vue
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/Create/utils.ts
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/IdentityForm.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/identity/IdentityIndex.vue
  components/identity/utils/useIdentity.ts
  components/navbar/ChainSelectDropdown.vue
  components/navbar/MobileNavbarProfile.vue
  components/navbar/ProfileDropdown.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/AccountBalance.vue
  components/shared/Auth.vue
  components/shared/SimpleAccountBalance.vue
  composables/useAuth.ts
  pages/teleport.vue
  pages/transfer.vue
  store/identity.ts
  store/index.ts
  stores/identity.ts
  stores/lang.ts
  stores/wallet.ts
  utils/WithKeyring.ts
  utils/mixins/authMixin.ts
  utils/mixins/identityMixin.ts
Labels: ✅ - code-lgtm, 🤞 - changes-requested, ✅ - works-for-me, large, waiting-for-review

#5918 fix: redirect rmrk2 prefix to ksm
  middleware/redirects.ts
  tests/cypress/e2e/redirect.cy.ts
Labels: small, waiting-for-review

#5948 🔧 invalid props
  libs/ui/src/components/NeoModal/NeoModal.vue
Labels: small, waiting-for-review

#5946 refactor: add NeoDatepicker
  components/shared/form/BasicDatePicker.vue
  libs/ui/src/components/NeoDatepicker/NeoDatepicker.story.vue
  libs/ui/src/components/NeoDatepicker/NeoDatepicker.vue
  libs/ui/src/index.ts
Labels: small, waiting-for-review

#5935 🎉 STATEMINE v0
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/landing/LandingPage.vue
  components/stmn/Create/CreateCollection.vue
  composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
  composables/transaction/mintToken/transactionMintStatemine.ts
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/transactionList.ts
  composables/transaction/transactionSend.ts
  composables/useChain.ts
  libs/static/package.json
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  locales/en.json
  package.json
  pages/statemine/u/_id.vue
  pages/stmn/create/collection.vue
  pages/stmn/create/item.vue
  pnpm-lock.yaml
  pnpm-workspace.yaml
  script/substack.json
  store/assets.ts
  tests/prefix.spec.ts
  utils/api/bsx/query.ts
  utils/config/defineApolloConfig.ts
  utils/config/permision.config.ts
  utils/config/types.ts
  utils/gallery/abstractCalls.ts
  utils/prefix.ts
Labels: A-statemine, 🤞 - changes-requested, large, waiting-for-review

#5952 fix: Add Mushroom Topia to sidebar in explorer
  components/shared/filters/modules/constants.ts
Labels: ✅ - code-lgtm, small

#5958 fix: identity and remove persist in wallet store
  components/identity/utils/useIdentity.ts
  stores/wallet.ts
Labels: small, waiting-for-review

#5934 feat: upgrade nodejs to v18
  .github/actions/pnpm-install/action.yml
  .node-version
  Dockerfile
  FIRST_TIME.md
  netlify.toml
  package.json
  pnpm-lock.yaml
Labels: paid, small, waiting-for-review

#5891 fix: Withdraw or accept offer wont refresh table
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
Labels: small, waiting-for-review

#5973 🔧 reviewdog workflow
  .github/actions/pnpm-install/action.yml
  libs/static/.eslintrc
Labels: small, waiting-for-review

#5919 show tooltip only above overflowing text
  components/gallery/UnlockableTag.vue
  components/shared/filters/modules/PopularCollections.vue
  composables/useTextOverflow.ts
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5969 fix: Add prefix to the transfer
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_basilisk.yml
  .github/ISSUE_TEMPLATE/bug_minting.yml
  .github/ISSUE_TEMPLATE/bug_moonbeam.yml
  .github/ISSUE_TEMPLATE/bug_rmrk2.yml
  .github/ISSUE_TEMPLATE/bug_statemine.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  REWARDS.md
  components/navbar/ProfileDropdown.vue
  middleware/redirects.ts
  pages/_prefix/transfer.vue
  pages/teleport.vue
Labels: medium, waiting-for-review

#5953 fix: unable to make offer due to balance issue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
Labels: small, waiting-for-review

#5998 ➖ remove general settings
  components/metadata/Metadata.vue
  components/settings/General.vue
  components/settings/SettingChooser.vue
  components/settings/SettingChooserDevelopment.vue
  pages/settings.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6000 ➖ remove b-checkbox component
  components/rmrk/Gallery/Holder/Holder.vue
  components/settings/Interface.vue
  components/shared/filters/modules/EventTypeFilter.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/form/BasicCheckbox.vue
Labels: medium, waiting-for-review

#6006 🔧 ga integration
  nuxt.config.js
Labels: small, waiting-for-review

#5960 fix: Rewrite Singular to KodaDot in item description
  components/gallery/GalleryItemDescription.vue
  components/redirect/useRedirectModal.ts
  components/rmrk/Gallery/Item/Description.vue
  components/shared/Markdown.vue
  components/shared/collapse/DescriptionWrapper.vue
  utils/url.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium

#5965 fix: Full screen button missing
  libs/ui/src/components/MediaItem/MediaItem.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#5950 test: adjust mock login
  components/common/ConnectWallet/ConnectWalletModal.vue
  pages/e2e-login.vue
  store/assets.ts
  tests/cypress/e2e/create-collection.cy.ts
  tests/cypress/support/commands.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#6002 feat: Landing - Newest List & Latest sales
  components/carousel/utils/useCarousel.ts
Labels: small, waiting-for-review

#5964 fix: close sidebar on network change
  components/common/ConnectWallet/ConnectWalletModal.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#5872 add skeleton when query is loading
  components/collection/CollectionCard.vue
  components/collection/CollectionDetail.vue
  components/collection/CollectionList.vue
  components/collection/utils/constants.ts
  components/items/ItemsGrid/ItemsGrid.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  styles/components/_collection-card.scss
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#5970 fix: Dropdown selecting multiple options in non multi choice dropdown
  components/navbar/MobileLanguageOption.vue
  components/navbar/ProfileDropdown.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small

#6012 fix: Change order on Newest List and Sales
  components/carousel/utils/useCarousel.ts
Labels: small, waiting-for-review

#5917 feat: add NeoSteps
  components/bsx/Create/GenerativeMint.vue
  libs/ui/src/components/NeoCarousel/NeoCarousel.story.vue
  libs/ui/src/components/NeoSteps/NeoStepItem.vue
  libs/ui/src/components/NeoSteps/NeoSteps.scss
  libs/ui/src/components/NeoSteps/NeoSteps.story.vue
  libs/ui/src/components/NeoSteps/NeoSteps.vue
  libs/ui/src/index.ts
  libs/ui/src/scss/_theme.scss
  styles/global.scss
Labels: ✅ - works-for-me, medium, waiting-for-review

#6010 ✨ cookie policy page
  components/CookieBanner.vue
  pages/cookie-notice.vue
Labels: medium, waiting-for-review

#6001 🔧 withdrow active offer
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
Labels: small, waiting-for-review

#6014 fix: Hide collections with empty metadata
  queries/subsquid/general/collectionListWithSearch.graphql
Labels: small, waiting-for-review

#5999 ➖ remove getSetting
  components/common/RampCredit.vue
  components/shared/AccountSelect.vue
  composables/useApi.ts
  pages/_prefix/transfer.vue
  pages/rmrk/credit.vue
  utils/WithKeyring.ts
  utils/mixins/apiUrlMixin.ts
Labels: medium, waiting-for-review

#5945 refactor: add NeoSwitch
  components/rmrk/Create/ArweaveUploadSwitch.vue
  components/rmrk/Create/SimpleMint.vue
  components/series/SeriesTable.vue
  components/settings/Interface.vue
  components/shared/Support.vue
  components/shared/form/BasicSwitch.vue
  components/spotlight/SpotlightTable.vue
  libs/ui/src/components/NeoSwitch/NeoSwitch.story.vue
  libs/ui/src/components/NeoSwitch/NeoSwitch.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium

#5976 refactor: add NeoRadio and NeoRadioButton
  components/rmrk/Gallery/Layout.vue
  components/shared/input/selectable/RadioSelect.vue
  libs/ui/src/components/NeoRadio/NeoRadio.story.vue
  libs/ui/src/components/NeoRadio/NeoRadio.vue
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, medium

#6021 🩹 Temp fix for balance issue
  components/shared/AccountBalance.vue
  stores/identity.ts
Labels: small, waiting-for-review

#6035 fix: responsive ModalWrapper content
  libs/ui/src/components/NeoModal/NeoModal.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#5856 ➖ remove b-tooltip component
  components/bsx/Offer/OfferTable.vue
  components/common/IdentityForm.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/navbar/CreateDropdown.vue
  components/rmrk/Create/DropUpload.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/Layout.vue
  components/rmrk/Gallery/Pagination.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  components/sales/SalesTable.vue
  components/settings/Minting.vue
  components/shared/Tooltip.vue
  components/shared/form/BasicSwitch.vue
  components/spotlight/SpotlightTable.vue
  styles/layouts/_main-navigation.scss
Labels: ✅ - code-lgtm, large, waiting-for-review

#6033 fix: Simple Option that drives to a non-existent page when using mobile
  components/navbar/CreateDropdown.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6023 fix: skeleton card variant size
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: paid, ✅ - visual-ok, small, waiting-for-review

#5933 #5852 move neo loader
  components/shared/Loader.vue
  libs/ui/src/components/NeoLoading/NeoLoading.scss
  libs/ui/src/components/NeoLoading/NeoLoading.story.vue
  libs/ui/src/components/NeoLoading/NeoLoading.vue
  libs/ui/src/index.ts
  styles/global.scss
Labels: small, waiting-for-review

#6019 feat: multi chain balances
  components/balance/MultipleBalances.vue
  components/common/ConnectWallet/WalletAsset.vue
  locales/en.json
Labels: medium, waiting-for-review

#6044 #6043 dark skeleton
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok, small, waiting-for-review

#6046 Fix change network on mobile
  components/Navbar.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/CreateDropdown.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/MobileNavbarProfile.vue
  components/navbar/NavbarChainOptions.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/StatsDropdown.vue
  locales/en.json
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6005 #5967 dropdown visual changes
  components/navbar/ProfileDropdown.vue
  styles/layouts/_main-navigation.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok, small, waiting-for-review

#6058 🔥 burn only on active offers
  composables/transaction/transactionBurn.ts
  queries/subsquid/bsx/acceptableOfferListByNftId.graphql
Labels: ✅ - code-lgtm, small, waiting-for-review

#6069 :art: rounded radio button
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
  libs/ui/src/scss/variable.scss
Labels: small, waiting-for-review

#6071 :art: new cool submit button
  components/base/SubmitButton.vue
Labels: ✅ - code-lgtm, small

#6079 🔧 Hotfix SubmitButton.vue
  components/base/SubmitButton.vue
Labels: small, waiting-for-review

#6077 :technologist: label in NeoField is optional
  libs/ui/src/components/NeoInput/NeoField.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6082 ✨ GenerativeMint redesign
  components/base/SubmitButton.vue
  components/bsx/Create/GenerativeMint.vue
  components/generative/GenerativeMintForm.vue
  components/generative/promptBuilder.ts
  components/shared/input/selectable/RadioSelect.vue
  layouts/generative-mint-layout.vue
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
  libs/ui/src/components/NeoSteps/NeoSteps.scss
  pages/bsx/waifu.vue
  pages/snek/waifu.vue
Labels: ✅ - code-lgtm, medium

#6088 :tada: Polkadot for Specific things
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  libs/static/package.json
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  package.json
  pages/_prefix/transfer.vue
  pnpm-lock.yaml
  stores/fiat.ts
  utils/chain.ts
  utils/config/permision.config.ts
  utils/config/types.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, large

#6084 fix: set address on prefix
  middleware/prefix.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6076 fix: Errors in /collection/:id
  components/collection/CollectionCard.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - code-lgtm, small

#6057 fix: dropdown overlay legend
  components/chart/PriceChart.vue
  styles/components/_price-chart.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6081 ✨ create attribute button
  components/rmrk/Create/CustomAttributeInput.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6085 Fix/tooltip-blocking-events
  components/rmrk/Profile/ProfileDetail.vue
  libs/ui/src/components/DisablableTab/DisablableTab.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6086 ➖ remove vuex-persist dep
  nuxt.config.js
  package.json
  plugins/vuex-persist.ts
  pnpm-lock.yaml
Labels: medium, waiting-for-review

#6063 feat: Implement new collection search
  components/rmrk/service/scheme.ts
  components/search/SearchSuggestion.vue
  components/search/utils/collectionSearch.ts
  utils/constants.ts
Labels: paid, medium, waiting-for-review

#6098 fix: re-add dot in sidebar
  components/balance/MultipleBalances.vue
  stores/identity.ts
Labels: small, waiting-for-review

#6103 :memo: Update that we send rewards in DOT
  REWARDS.md
Labels: small, waiting-for-review, docs

#6104 fix: Wrap text when no collection and item is found in search
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.scss
Labels: ✅ - code-lgtm, small, waiting-for-review

#6101 :wrench: for any chain use system token if not specified
  utils/api/bsx/query.ts
Labels: small, waiting-for-review

#6095 🔧 simple mint hotfix
  components/rmrk/Create/Admin/AdminPanel.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/PasswordInput.vue
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#5824 MassMint - Upload description file
  components/massmint/EditPanel.vue
  components/massmint/Massmint.vue
  components/massmint/types.ts
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  components/massmint/uploadDescription/parsers/common.ts
  components/massmint/uploadDescription/parsers/parseCsv.ts
  components/massmint/uploadDescription/parsers/parseJson.ts
  components/massmint/uploadDescription/parsers/parseTxt.ts
  components/massmint/uploadDescription/useParseDescriptionFile.ts
  components/massmint/useMassMint.ts
  pages/_prefix/massmint/index.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, large

#5655 ✨ migrate assets store
  composables/usePrefix.ts
  nuxt.config.js
  plugins/assets.ts
  store/assets.ts
  store/index.ts
  stores/assets.ts
  utils/mixins/assetMixin.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6087 ➖ remove store index
  pages/_prefix/transfer.vue
  store/index.ts
Labels: small, waiting-for-review

#6102 :tada: Hello Statemint
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/transactionList.ts
  composables/transaction/transactionSend.ts
  libs/static/package.json
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  package.json
  pnpm-lock.yaml
  utils/chain.ts
  utils/config/permision.config.ts
  utils/config/types.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#6125 🎉 New production endpoint for SNEK
  libs/static/src/indexers.ts
  libs/static/src/types.ts
  utils/constants.ts
Labels: small, waiting-for-review

#6126 :wrench: correct name for waifu minter
  layouts/generative-mint-layout.vue
Labels: small, waiting-for-review

#6114 fix: Long collection name: unable to see it all without openning
  components/collection/CollectionDetail.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#5854 ➖ remove b-image component
  components/collection/CollectionCard.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/generative/CongratsView.vue
  components/series/SeriesTable.vue
  components/shared/view/BasicImage.vue
  components/shared/view/SelectableImage.vue
  components/unique/Collection/Item/CollectionItem.vue
  components/unique/Collection/Item/TransferCollectionModal.vue
  components/unique/Gallery/Item/DangerModal.vue
  components/unique/graphqlResponseTypes.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6128 :technologist: set that nft can be burned
  components/gallery/GalleryItem.vue
Labels: small, waiting-for-review

#5959 fix: gallery item image container is not square on tablet
  components/gallery/GalleryItem.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6110 🔧 asset page & NeoTable
  components/bsx/Asset/AssetTable.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  libs/ui/src/components/NeoTable/NeoTableColumn.vue
  libs/ui/src/index.ts
Labels: 🤞 - changes-requested, small, waiting-for-review

#6132 add back the sort option `sn_ASC`
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/pt.json
  locales/ru.json
  locales/ua.json
  utils/constants.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#6111 ➖ remove setUrlPrefix dispatch
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/explore/ExploreChain.vue
  components/landing/SearchLanding.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/NavbarChainOptions.vue
  components/navbar/NavbarExploreOptions.vue
  components/shared/filters/modules/PopularCollections.vue
  middleware/prefix.ts
Labels: small, waiting-for-review

#6112 feat: unify profile and assets (part 1)
  components/balance/MultipleBalances.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/shared/Avatar.vue
  composables/useSearchNfts.ts
  libs/ui/src/components/IdentityItem/IdentityItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  styles/global.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6115 fix: Optimize search to search collection
  components/search/SearchSuggestion.vue
Labels: paid, small, waiting-for-review

#5870 #5852 Neo Input and Neo Field
  components/accounts/AddressParser.vue
  components/base/BaseCollectionForm.vue
  components/base/BaseTokenForm.vue
  components/base/CollectionSelect.vue
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/Offer/DaySelect.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/IdentityForm.vue
  components/explore/ExploreGrid.vue
  components/poap/claim/ClaimForm.vue
  components/rmrk/Create/Admin/AdminPanel.vue
  components/rmrk/Create/ArweaveUploadSwitch.vue
  components/rmrk/Create/AttributeInput.vue
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/DropUpload.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/Layout.vue
  components/rmrk/Gallery/PaginatedCardList.vue
  components/search/Search.vue
  components/search/SearchCollection.vue
  components/search/SearchPriceRange.vue
  components/search/SearchSortDropdown.vue
  components/series/SeriesTable.vue
  components/settings/AddOption.vue
  components/settings/Interface.vue
  components/shared/AddressInput.vue
  components/shared/BalanceInput.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/DisabledInput.vue
  components/shared/ReadOnlyBalanceInput.vue
  components/shared/Sharing.vue
  components/shared/filters/modules/EventTypeFilter.vue
  components/shared/filters/modules/PriceFilter.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/form/AuthField.vue
  components/shared/form/BasicBalanceInput.vue
  components/shared/form/BasicInput.vue
  components/shared/form/BasicNumberInput.vue
  components/shared/form/BasicSlider.vue
  components/shared/form/BasicSwitch.vue
  components/shared/input/selectable/RadioSelect.vue
  components/spotlight/SpotlightTable.vue
  components/unique/Collection/Item/TransferCollectionModal.vue
  libs/ui/src/components/NeoInput/NeoField.vue
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoInput/NeoInput.story.vue
  libs/ui/src/components/NeoInput/NeoInput.vue
  libs/ui/src/scss/_theme.scss
  pages/_prefix/transfer.vue
  pages/teleport.vue
  styles/abstracts/_theme.scss
  tests/cypress/e2e/create-collection.cy.ts
  tests/cypress/support/commands.ts
  tests/unit-testing/components/shared/BalanceInput.test.ts
  tests/unit-testing/components/shared/BasicBalanceInput.test.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, large

#6135 ➖ unused pages
  components/landing/EsCarbonless.vue
  components/rmrk/Create/Admin/ActionSelector.vue
  components/rmrk/Create/Admin/AdminPanel.vue
  components/rmrk/Create/Admin/SendHandler.vue
  components/settings/KeyboardShortcuts.vue
  pages/about.vue
  pages/esCarbonless.vue
  pages/esSustainability.vue
  pages/partnership.vue
  pages/rmrk/admin.vue
  pages/transform.vue
  plugins/keyboardEvents.ts
  static/sitemap.xml
Labels: ✅ - code-lgtm, large, waiting-for-review
