Repository kodadot/nft-gallery, pull requests merged in 2023-08, with the labels that each got.

#6471 feat: General onboarding article for developers want to use KodaDot
  CONTRIBUTING.md
  README.md
  components/blog/BlogPost.vue
  content/blog/first-time.md
  locales/README.md
  pages/blog/index.vue
  styles/abstracts/_theme.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6503 [BlogPost] Dynamic NFTs: Revolutionizing Digital Ownership
  content/blog/revolutionizing-digital-ownership.md
  static/blog/revolutionizing-digital-ownership-1.png
  static/blog/revolutionizing-digital-ownership-2.png
  static/blog/revolutionizing-digital-ownership-3.png
  static/blog/revolutionizing-digital-ownership-4.png
Labels: ✅ - works-for-me, small, waiting-for-review, docs

#6507 fix: Add blog to footer
  components/TheFooter.vue
  locales/en.json
Labels: blocked, small, waiting-for-review

#6500 [Blogpost] The Rise of Onchain NFTs: Shaping the Future of Digital Collectibles
  components/blog/BlogPost.vue
  content/blog/shaping-the-future-of-digital-collectibles.md
  pages/blog/index.vue
  static/blog/shaping-the-future-of-digital-collectibles-1.png
Labels: 🤞 - changes-requested, paid, small, waiting-for-review

#6453 🔧 vue 3 composition create pages
  composables/useCreate.ts
  pages/bsx/create.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/snek/create.vue
  pages/stmn/create.vue
  utils/mixins/createMixin.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6448 #6417 tooltip update gallery
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  libs/static/src/chains.ts
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  locales/en.json
  styles/components/_gallery-item.scss
Labels: 🤞 - changes-requested, medium, waiting-for-review

#6514 beta update
  CONTRIBUTING.md
  README.md
  components/Navbar.vue
  components/TheFooter.vue
  components/blog/BlogPost.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/useGalleryItem.ts
  components/massmint/Massmint.vue
  components/navbar/NavbarExploreOptions.vue
  components/rmrk/Gallery/Pagination.vue
  components/shared/BlockExplorerLink.vue
  components/shared/CommonTokenMoney.vue
  components/shared/MessageNotify.vue
  components/shared/Sharing.vue
  components/shared/view/BasicImage.vue
  components/transfer/Transfer.vue
  composables/useCreate.ts
  composables/usePrefix.ts
  content/blog/first-time.md
  content/blog/revolutionizing-digital-ownership.md
  content/blog/shaping-the-future-of-digital-collectibles.md
  libs/static/src/chains.ts
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  locales/README.md
  locales/en.json
  pages/blog/index.vue
  pages/bsx/create.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/snek/create.vue
  pages/stmn/create.vue
  pnpm-lock.yaml
  static/blog/revolutionizing-digital-ownership-1.png
  static/blog/revolutionizing-digital-ownership-2.png
  static/blog/revolutionizing-digital-ownership-3.png
  static/blog/revolutionizing-digital-ownership-4.png
  static/blog/shaping-the-future-of-digital-collectibles-1.png
  styles/abstracts/_theme.scss
  styles/components/_connect-wallet.scss
  styles/components/_gallery-item.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
  tests/cypress/e2e/prefix.cy.ts
  utils/mixins/createMixin.ts
Labels: beta

#6515 release update
  CONTRIBUTING.md
  README.md
  components/Navbar.vue
  components/TheFooter.vue
  components/blog/BlogPost.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/useGalleryItem.ts
  components/massmint/Massmint.vue
  components/navbar/NavbarExploreOptions.vue
  components/rmrk/Gallery/Pagination.vue
  components/shared/BlockExplorerLink.vue
  components/shared/CommonTokenMoney.vue
  components/shared/MessageNotify.vue
  components/shared/Sharing.vue
  components/shared/view/BasicImage.vue
  components/transfer/Transfer.vue
  composables/useCreate.ts
  composables/usePrefix.ts
  content/blog/first-time.md
  content/blog/revolutionizing-digital-ownership.md
  content/blog/shaping-the-future-of-digital-collectibles.md
  libs/static/src/chains.ts
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  locales/README.md
  locales/en.json
  pages/blog/index.vue
  pages/bsx/create.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/snek/create.vue
  pages/stmn/create.vue
  pnpm-lock.yaml
  static/blog/revolutionizing-digital-ownership-1.png
  static/blog/revolutionizing-digital-ownership-2.png
  static/blog/revolutionizing-digital-ownership-3.png
  static/blog/revolutionizing-digital-ownership-4.png
  static/blog/shaping-the-future-of-digital-collectibles-1.png
  styles/abstracts/_theme.scss
  styles/components/_connect-wallet.scss
  styles/components/_gallery-item.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
  tests/cypress/e2e/prefix.cy.ts
  utils/mixins/createMixin.ts
Labels: release

#6517 release update
  .github/ISSUE_TEMPLATE/bug_assetshub.yml
  .github/push_release_production.sh
  CONTRIBUTING.md
  README.md
  components/Navbar.vue
  components/TheFooter.vue
  components/blog/BlogPost.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/useGalleryItem.ts
  components/massmint/Massmint.vue
  components/navbar/NavbarExploreOptions.vue
  components/rmrk/Gallery/Pagination.vue
  components/shared/BlockExplorerLink.vue
  components/shared/CommonTokenMoney.vue
  components/shared/MessageNotify.vue
  components/shared/Sharing.vue
  components/shared/view/BasicImage.vue
  components/transfer/Transfer.vue
  composables/useCreate.ts
  composables/usePrefix.ts
  content/blog/first-time.md
  content/blog/revolutionizing-digital-ownership.md
  content/blog/shaping-the-future-of-digital-collectibles.md
  libs/static/package.json
  libs/static/src/chains.ts
  libs/static/src/indexers.ts
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  locales/README.md
  locales/en.json
  pages/blog/index.vue
  pages/bsx/create.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/snek/create.vue
  pages/stmn/create.vue
  pnpm-lock.yaml
  static/blog/revolutionizing-digital-ownership-1.png
  static/blog/revolutionizing-digital-ownership-2.png
  static/blog/revolutionizing-digital-ownership-3.png
  static/blog/revolutionizing-digital-ownership-4.png
  static/blog/shaping-the-future-of-digital-collectibles-1.png
  styles/abstracts/_theme.scss
  styles/components/_connect-wallet.scss
  styles/components/_gallery-item.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
  tests/cypress/e2e/prefix.cy.ts
  utils/constants.ts
  utils/mixins/createMixin.ts
Labels: release

#6516 fix: Use new gen formats for blog assets
  content/blog/revolutionizing-digital-ownership.md
  content/blog/shaping-the-future-of-digital-collectibles.md
  content/blog/what-is-erc6551.md
  static/blog/revolutionizing-digital-ownership-1.png
  static/blog/revolutionizing-digital-ownership-1.webp
  static/blog/revolutionizing-digital-ownership-2.png
  static/blog/revolutionizing-digital-ownership-2.webp
  static/blog/revolutionizing-digital-ownership-3.png
  static/blog/revolutionizing-digital-ownership-3.webp
  static/blog/revolutionizing-digital-ownership-4.png
  static/blog/revolutionizing-digital-ownership-4.webp
  static/blog/shaping-the-future-of-digital-collectibles-1.png
  static/blog/shaping-the-future-of-digital-collectibles-1.webp
  static/blog/what-is-erc6551.webp
Labels: ✅ - works-for-me, small, waiting-for-review

#6519 Sitemap should include blog posts
  nuxt.config.js
Labels: ✅ - works-for-me, small, waiting-for-review

#6493 #6489 padding
  pages/index.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6523 build: temporary disable source-map
  nuxt.config.js
Labels: paid, small, waiting-for-review

#6531 Docker setup is not working
  Dockerfile
Labels: ✅ - code-lgtm, small, waiting-for-review

#6486 Transfer Redesign handover - (1) Desktop design
  assets/token/bsx.svg
  assets/token/dot.svg
  assets/token/ksm.svg
  components/shared/AddressInput.vue
  components/shared/TabItem.vue
  components/transfer/Transfer.vue
  components/transfer/TransferOld.vue
  composables/useIcon.ts
  locales/en.json
  pages/_prefix/transfer.vue
  utils/format/balance.ts
  utils/math.ts
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#6557 fix: Change URL slug of blogs Onchain nfts and Dynamic nfts
  content/blog/dynamic-nfts-revolutionizing-digital-ownership.md
  content/blog/the-rise-of-onchain-nfts-shaping-the-future-of-digital-collectibles.md
  content/blog/what-is-erc6551-token-bound-accounts.md
  pages/blog/index.vue
Labels: ✅ - works-for-me, small, waiting-for-review, docs

#6560 [Blogpost] How do unlockable content NFTs work on KodaDot ?
  content/blog/how-do-unlockable-content-nfts-work-on-kodadot.md
  static/blog/how-do-unlockable-content-nfts-work-on-kodadot-1.webp
  static/blog/how-do-unlockable-content-nfts-work-on-kodadot-2.webp
  static/blog/how-do-unlockable-content-nfts-work-on-kodadot-3.webp
  static/blog/how-do-unlockable-content-nfts-work-on-kodadot-4.webp
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6521 [ARTICLE] keyboard shortcuts
  README.md
Labels: small, waiting-for-review, docs

#6562 fix: [Blogpost] The Power of Polkadot's Asset Hub: Revolutionizing Asset Management
  content/blog/the-power-of-polkadot's-Asset-hub-Revolutionizing-asset-management.md
  pages/blog/index.vue
  static/blog/the-power-of-polkadot's-Asset-hub-Revolutionizing-asset-management.webp
Labels: paid, medium, waiting-for-review

#6577 [Blogpost] A Comprehensive Guide to Peer-to-Peer NFT Atomic Swaps
  content/blog/a-comprehensive-guide-to-peer-to-peer-nft-atomic-swaps.md
  static/blog/a-comprehensive-guide-to-peer-to-peer-nft-atomic-swaps-1.webp
Labels: ✅ - works-for-me, small, waiting-for-review

#6579 [Blogpost] Exploring the World of Generative NFT Art: A Dance of Randomness and Recursion
  content/blog/exploring-the-world-of-generative-nft-art-a-dance-of-randomness-and-recursion.md
  static/blog/exploring-the-world-of-generative-nft-art-a-dance-of-randomness-and-recursion-1.webp
Labels: small, waiting-for-review

#6580 fix: typo, grammar issues in documentation
  CONTRIBUTING.md
  REWARDS.md
Labels: ✅ - code-lgtm, small, waiting-for-review, docs

#6584 feat: [blogpost] A Comprehensive Guide on Virtual Land NFTs in the Metaverse
  content/blog/a-comprehensive-guide-on-virtual-land-nfts-in-the-metaverse.md
  static/blog/a-comprehensive-guide-on-virtual-land-nfts-in-the-metaverse.webp
Labels: small, waiting-for-review

#6569 fix: You can change the network field to any string you want
  composables/usePrefix.ts
  utils/chain.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6575 🔧 migrate oruga package to lib/ui
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/massmint/ChooseCollectionDropdown.vue
  components/massmint/Massmint.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  libs/ui/package.json
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/histoire.scss
  package.json
  pnpm-lock.yaml
  styles/index.scss
Labels: small, waiting-for-review

#6586 feat: [blogpost] Understanding Cross-Chain NFT Transfers and how to b…
  content/blog/understanding-cross-chain-nft-transfers-and-how-to-bridge-your-nft-to-another-blockchain.md
  static/blog/understanding-cross-chain-nft-transfers-and-how-to-bridge-your-nft-to-another-blockchain.webp
Labels: small, waiting-for-review

#6581 feat: [Blogpost] Layer-2 Scaling Solutions: Unleashing Full Potential…
  components/blog/BlogPost.vue
  content/blog/layer-2-scaling-solutions-unleashing-full-potential-of-nfts.md
  static/blog/layer-2-scaling-solutions-unleashing-full-potential-of-nfts.webp
Labels: small, waiting-for-review

#6582 🔧 select collection on create nft page
  components/base/BaseTokenForm.vue
  components/base/CollectionSelect.vue
Labels: small, waiting-for-review

#6568 File import not working in massmint
  composables/massmint/useZipValidator.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6570 After minting, user does not get redirect to NFT and Error when trying to massmint on RMRK2
  components/rmrk/Create/CreateToken.vue
  composables/transaction/mintToken/transactionMintRmrk.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6587 beta update
  CONTRIBUTING.md
  REWARDS.md
  components/base/BaseTokenForm.vue
  components/base/CollectionSelect.vue
  components/blog/BlogPost.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/massmint/ChooseCollectionDropdown.vue
  components/massmint/Massmint.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  components/rmrk/Create/CreateToken.vue
  composables/massmint/useZipValidator.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/usePrefix.ts
  content/blog/a-comprehensive-guide-on-virtual-land-nfts-in-the-metaverse.md
  content/blog/a-comprehensive-guide-to-peer-to-peer-nft-atomic-swaps.md
  content/blog/exploring-the-world-of-generative-nft-art-a-dance-of-randomness-and-recursion.md
  content/blog/layer-2-scaling-solutions-unleashing-full-potential-of-nfts.md
  content/blog/understanding-cross-chain-nft-transfers-and-how-to-bridge-your-nft-to-another-blockchain.md
  libs/ui/package.json
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/histoire.scss
  package.json
  pnpm-lock.yaml
  static/blog/a-comprehensive-guide-on-virtual-land-nfts-in-the-metaverse.webp
  static/blog/a-comprehensive-guide-to-peer-to-peer-nft-atomic-swaps-1.webp
  static/blog/exploring-the-world-of-generative-nft-art-a-dance-of-randomness-and-recursion-1.webp
  static/blog/layer-2-scaling-solutions-unleashing-full-potential-of-nfts.webp
  static/blog/understanding-cross-chain-nft-transfers-and-how-to-bridge-your-nft-to-another-blockchain.webp
  styles/index.scss
  utils/chain.ts
Labels: beta

#6588 release update
  CONTRIBUTING.md
  REWARDS.md
  components/base/BaseTokenForm.vue
  components/base/CollectionSelect.vue
  components/blog/BlogPost.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/massmint/ChooseCollectionDropdown.vue
  components/massmint/Massmint.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  components/rmrk/Create/CreateToken.vue
  composables/massmint/useZipValidator.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/usePrefix.ts
  content/blog/a-comprehensive-guide-on-virtual-land-nfts-in-the-metaverse.md
  content/blog/a-comprehensive-guide-to-peer-to-peer-nft-atomic-swaps.md
  content/blog/exploring-the-world-of-generative-nft-art-a-dance-of-randomness-and-recursion.md
  content/blog/layer-2-scaling-solutions-unleashing-full-potential-of-nfts.md
  content/blog/understanding-cross-chain-nft-transfers-and-how-to-bridge-your-nft-to-another-blockchain.md
  libs/ui/package.json
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/histoire.scss
  package.json
  pnpm-lock.yaml
  static/blog/a-comprehensive-guide-on-virtual-land-nfts-in-the-metaverse.webp
  static/blog/a-comprehensive-guide-to-peer-to-peer-nft-atomic-swaps-1.webp
  static/blog/exploring-the-world-of-generative-nft-art-a-dance-of-randomness-and-recursion-1.webp
  static/blog/layer-2-scaling-solutions-unleashing-full-potential-of-nfts.webp
  static/blog/understanding-cross-chain-nft-transfers-and-how-to-bridge-your-nft-to-another-blockchain.webp
  styles/index.scss
  utils/chain.ts
Labels: release

#6600 :heavy_minus_sign: indexer config
  utils/config/indexer.config.ts
Labels: small, waiting-for-review

#6602 :wrench: disable radium block as per polkadot-js/apps#9764
  libs/static/src/endpoints.ts
Labels: small, waiting-for-review

#6573 Update ParaSpell XCM SDK
  components/teleport/Teleport.vue
  package.json
  pnpm-lock.yaml
Labels: ✅ - code-lgtm, small, waiting-for-review

#6592 ➖ unused components
  components/bsx/Offer/CollectionOffers.vue
  components/bsx/input/OfferBalanceInput.vue
  components/rmrk/Create/ArweaveUploadSwitch.vue
  components/rmrk/Create/CreateToken.vue
  components/settings/Minting.vue
  components/shared/SimpleAccountBalance.vue
  stores/preferences.ts
Labels: medium, waiting-for-review

#6605 modals border-radius 0
  libs/ui/src/components/NeoModal/NeoModal.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6603 asset hubs rpcs
  libs/static/src/endpoints.ts
  libs/static/src/services.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6525 feat: blog subsection
  content/blog/dynamic-nfts-revolutionizing-digital-ownership.md
  content/blog/the-power-of-polkadot's-Asset-hub-Revolutionizing-asset-management.md
  libs/ui/src/components/CardArticle/CardArticle.scss
  pages/blog/index.vue
  static/blog-cover.png
  static/blog/the-power-of-polkadots-Asset-hub-Revolutionizing-asset-management.webp
Labels: ✅ - code-lgtm, ✅ - visual-ok, medium

#6616 🔧 spotlight vue3
  components/hot/HotTable.vue
  components/rmrk/Profile/ProfileLink.vue
  components/sales/SalesTable.vue
  components/shared/ScrollTopButton.vue
  components/spotlight/SpotlightDetail.vue
  components/spotlight/SpotlightTable.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  locales/en.json
  pages/hot.vue
  pages/sales.vue
  pages/spotlight.vue
  styles/components/_scroll-to-top-button.scss
Labels: large, waiting-for-review

#6620 [blogpost] KodaDots Drop Page explained
  components/blog/BlogPost.vue
  content/blog/kodadot's-drop-page-explained.md
  static/blog/kodadot's-drop-page-explained-2.webp
  static/blog/kodadot's-drop-page-explained-3.webp
  static/blog/kodadot's-drop-page-explained-4.webp
  static/blog/kodadot's-drop-page-explained-5.webp
  static/blog/kodadot's-drop-page-explained-6.webp
  static/blog/kodadot's-drop-page-explained-7.webp
  static/blog/kodadots-drop-page-explained-1.webp
Labels: small, waiting-for-review

#6611 fix: sentry hide source map
  nuxt.config.js
Labels: small, waiting-for-review

#6627 fix: replace image on blog
  static/blog/kodadot's-drop-page-explained-6.webp
Labels: small, waiting-for-review

#6628 🔧 bsx/snek stats composition api
  components/bsx/Offer/OfferStats.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/StatsOverview.vue
  components/bsx/Offer/types.ts
Labels: medium, waiting-for-review

#6631 Asset Hubs
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  components/carousel/utils/useCarousel.ts
  components/collection/drop/DropContainer.vue
  components/collection/drop/TokenImportButton.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/shoppingCart/utils.ts
  components/drops/Drops.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/useGalleryItem.ts
  components/landing/LandingPage.vue
  components/navbar/CreateDropdown.vue
  composables/collectionActivity/helpers.ts
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/transactionList.ts
  composables/transaction/transactionMintCollection.ts
  composables/transaction/transactionMintToken.ts
  composables/transaction/transactionSend.ts
  composables/useBalance.ts
  composables/useChain.ts
  composables/useIsChain.ts
  composables/useNft.ts
  content/blog/kodadot's-drop-page-explained.md
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  middleware/redirects.ts
  pages/ahk/create.vue
  pages/ahk/waifu.vue
  pages/ahp/create.vue
  pnpm-lock.yaml
  queries/subsquid/ahk/nftById.graphql
  stores/identity.ts
  tests/cypress/e2e/prefix.cy.ts
  tests/prefix.spec.ts
  utils/chain.ts
  utils/config/permision.config.ts
  utils/config/types.ts
  utils/constants.ts
  utils/gallery/abstractCalls.ts
  utils/prefix.ts
  utils/queryPathResolver.ts
  utils/teleport.ts
Labels: medium, waiting-for-review

#6643 fix(notification): scroll position resetting & minor code cleanup
  components/Navbar.vue
  components/navbar/NotificationBoxButton.vue
Labels: ✅ - code-lgtm, paid, small, waiting-for-review

#6633 🔧 bsx/snek offers composition api
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OffersUserTable.vue
  utils/mixins/offerMixin.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#6635 [blogpost] value driver
  content/blog/why-are-nfts-valuable-investment.md
  static/blog/why-are-nfts-valuable-investment-1.webp
Labels: ✅ - works-for-me, small, waiting-for-review

#6640 Delete cypress again
  .github/workflows/e2e.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  package.json
  pnpm-lock.yaml
  tests/cypress-deprecated/basicE2E.cy.ts
  tests/cypress-deprecated/commands.ts
  tests/cypress-deprecated/create-collection.cy.ts
  tests/cypress-deprecated/e2e-run-tests.js
  tests/cypress-deprecated/e2e.ts
  tests/cypress-deprecated/explore.cy.ts
  tests/cypress-deprecated/identity.cy.ts
  tests/cypress-deprecated/language.cy.ts
  tests/cypress-deprecated/media.cy.ts
  tests/cypress-deprecated/opengraph-collection.cy.ts
  tests/cypress-deprecated/opengraph-item.cy.ts
  tests/cypress-deprecated/prefix.cy.ts
  tests/cypress-deprecated/redirect.cy.ts
  tests/cypress-deprecated/rmrk-simple-mint.cy.ts
  tests/cypress.config.ts
  tsconfig.json
  vitest.config.js
Labels: ✅ - code-lgtm, medium

#6645 ➖ @kodadot1/vuex-options
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  tests/prefix.spec.ts
  utils/chain.ts
Labels: small, waiting-for-review

#6642 fix(cart): scroll position resetting & minor code cleanup
  components/Navbar.vue
  components/common/shoppingCart/ShoppingCartModalConfig.ts
  components/navbar/ShoppingCartButton.vue
Labels: paid, small, waiting-for-review

#6599 fix: adjust imageSrc on carousel component
  components/carousel/module/CarouselMedia.vue
  components/gallery/GalleryItemDescription.vue
  composables/useNft.ts
  locales/en.json
  package.json
  pnpm-lock.yaml
  styles/components/_carousel.scss
  utils/ipfs.ts
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#6653 🔧 sidebar closeBurgerMenu
  components/Navbar.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6657 doc(rewards): updated table with the correct rates based on the labels
  REWARDS.md
Labels: small, waiting-for-review, docs

#6662 ci: disable sentry on build
  nuxt.config.js
Labels: small, waiting-for-review

#6672 chore: remove sentry related packages
  nuxt.config.js
  package.json
  plugins/sentry.ts
  pnpm-lock.yaml
  tsconfig.json
  utils/notification.ts
Labels: large, waiting-for-review

#6670 🔧 vue3 composition
  components/bsx/Collection/ChartContainer.vue
  components/rmrk/Gallery/Flipper.vue
  components/rmrk/Gallery/Holding.vue
  components/rmrk/Profile/ProfileActivity.vue
  components/shared/chart/chartMixin.ts
  components/shared/modals/keyboardShortcutsModal.vue
  utils/mixins/apiUrlMixin.ts
  utils/mixins/assetMixin.ts
  utils/mixins/authMixin.ts
  utils/mixins/prefixMixin.ts
  utils/mixins/txMixin.ts
  utils/mixins/useApiMixin.ts
Labels: large, waiting-for-review

#6676 🔧 new snek release
  libs/static/src/indexers.ts
  utils/constants.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6679 :bookmark: static @ 0.0.3
  libs/static/package.json
Labels: small, waiting-for-review

#6671 build: add nuxt-optimisations
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: large, waiting-for-review

#6666 #6637 update press kit url
  components/TheFooter.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6674 feat: Buy now spinning wheel
  components/common/ConnectWallet/useConnectWallet.ts
  components/common/shoppingCart/ShoppingCartModal.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  composables/useDoAfterlogin.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  locales/en.json
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6673 fix: menu buttons resseting scroll position on mobile
  components/Navbar.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#6613 Changing network in navbar always redirects to Landing page
  components/Navbar.vue
  components/hot/HotTable.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/NavbarChainOptions.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  composables/useChainRedirect.ts
  composables/usePrefix.ts
  utils/config/permision.config.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#6651 docs: specified correct node version to avoid --openssl-legacy-provid…
  content/blog/first-time.md
Labels: small, waiting-for-review, docs

#6691 Update NeoButton.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
Labels: small, waiting-for-review

#6690 ci: exit on failed to parse
  package.json
  script/generate.mjs
Labels: small, waiting-for-review

#6639 docs(): documented fix for can't find .env
  .env.example
  content/blog/first-time.md
Labels: small, waiting-for-review, docs

#6682 fix: Followup Transfer Redesign
  app/router.scrollBehavior.js
  components/transfer/Transfer.vue
Labels: small, waiting-for-review

#6687 refactor(addressParser): to script setup composition api
  components/accounts/AddressParser.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6686 style(error): changed links style to not have the same as default text
  layouts/error.vue
Labels: small, waiting-for-review

#6704 fix: SearchBar component is called multiple times
  components/Navbar.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6707 build: reduce manifest size
  .github/workflows/build.yml
  components/Navbar.vue
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/drops/TimeTag.vue
  composables/useIcon.ts
  composables/useShoppingCartIcon.ts
  composables/useUnlockableIcon.ts
  pages/qrCode.vue
  static/Koda_Beta.svg
  static/Koda_Beta_dark.svg
  static/empty-cart.png
  static/fonts/WorkSans-VariableFont_wght.ttf
  static/partners/logo-clover.png
  static/partners/logo-enkrypt.png
  static/partners/logo-ledger.svg
  static/partners/logo-mathwallet.png
  static/partners/logo-nova.png
  static/partners/logo-polkadot-js.png
  static/partners/logo-subwallet.svg
  static/partners/logo-talisman.svg
  static/qrCode/discord.png
  static/qrCode/github.png
  static/qrCode/instagram.png
  static/qrCode/twitter.png
  static/shopping-cart-outline-sharp.svg
  static/shopping-cart-outline-sharp_dark.svg
  static/striked-out-cart-shopping.svg
  static/striked-out-cart-shopping_dark.svg
  static/token/bsx.svg
  static/token/dot.svg
  static/token/ksm.svg
  static/unlockable-banner.svg
  static/unlockable-dark.svg
  static/unlockable-introduce.svg
  static/unlockable-loader.svg
  static/unlockable-pulse.svg
  static/unlockable.svg
  styles/abstracts/_fonts.scss
  utils/config/wallets.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6703 🔧 vue3 composition api
  components/bsx/Offer/OfferTable.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Profile/Sales.vue
Labels: ✅ - works-for-me, large, waiting-for-review

#6710 fix: forbiding landing page on DOT
  components/landing/LandingPage.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6695 Transfer Redesign handover - Transaction confirm & Send Transaction
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  locales/en.json
Labels: ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#6712 fix: remove console error
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: small, waiting-for-review

#6715 :nail_care: Error into composition API
  components/shared/Error.vue
Labels: small, waiting-for-review

#6709 feat: use v-safe-href to sanitize url
  components/TheFooter.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/drops/DropCard.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/UnlockableTag.vue
  components/identity/IdentityItem.vue
  components/identity/module/IdentityLink.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/module/IdentitySocial.vue
  components/landing/FeaturedArticles.vue
  components/media/type/UnknownMedia.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/shared/BlockExplorerLink.vue
  components/shared/LinkResolver.vue
  components/shared/format/ExternalLink.vue
  components/teleport/Teleport.vue
  components/transfer/TransferOld.vue
  libs/ui/src/components/CardArticle/CardArticle.story.vue
  libs/ui/src/components/CardArticle/CardArticle.vue
  libs/ui/src/components/MediaItem/type/UnknownMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  nuxt.config.js
  package.json
  pages/blog/index.vue
  pages/qrCode.vue
  plugins/safeHref.ts
  pnpm-lock.yaml
Labels: ✅ - works-for-me, small, waiting-for-review

#6714 refactor: programmatic modal
  components/Navbar.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/TokenImportButton.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/useConnectWallet.ts
  components/common/NotificationBox/useNotificationBox.ts
  components/common/shoppingCart/ShoppingCartModal.vue
  components/common/shoppingCart/ShoppingCartModalConfig.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/ShoppingCartButton.vue
  components/redirect/useRedirectModal.ts
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/shared/ConnectWalletButton.vue
  libs/ui/src/components/NeoModalExtend/NeoModalExtend.vue
  libs/ui/src/components/NeoModalExtend/plugin.js
  libs/ui/src/index.ts
  nuxt.config.js
  plugins/oruga-modal.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, large, waiting-for-review

#6684 style(cart): NFT name allowed to overflow
  components/common/shoppingCart/ShoppingCartItemRow.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6728 fix: Collection pfp object fit
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
  styles/global.scss
Labels: small, waiting-for-review

#6729 fix: transfer amount
  components/landing/topCollections/TopCollectionsItem.vue
  components/transfer/Transfer.vue
  components/transfer/TransferOld.vue
  utils/calculation.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6717 🔧 Vue3 composition Money component
  components/shared/format/BasicMoney.vue
  components/shared/format/Money.vue
Labels: medium, waiting-for-review

#6724 🔧 PulseChart vue3
  components/shared/PulseChart.vue
Labels: medium, waiting-for-review

#6720 🔧 PriceChart vue3
  components/shared/collection/PriceChart.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#6723 🔧 GalleryCardList vue3
  components/rmrk/Gallery/GalleryCardList.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6693 Refactor/decorator2
  components/bsx/input/TokenBalanceInput.vue
  components/bsx/specific/MultiPaymentFeeButton.vue
  utils/mixins/assetMixin.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6737 🔧 upgrade nuxt-edge
  nuxt.config.js
  package.json
  patches/@nuxt__webpack-edge@2.16.0-27720022.54e852f.patch
  pnpm-lock.yaml
  script/substack.json
Labels: large, waiting-for-review

#6731 #6708 - how to use images in code
  .eslintrc.js
  STYLE_GUIDE.md
Labels: small, waiting-for-review

#6732 🔧 MyOffer & OffersUserTable
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OffersUserTable.vue
  composables/useChain.ts
Labels: A-basilisk, ✅ - works-for-me, small, waiting-for-review

#6688 fix(chain redirects): Follow up: Changing network in navbar always redirects to Landing page
  components/collection/HeroButtons.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/IdentityForm.vue
  components/drops/Drops.vue
  components/identity/IdentityIndex.vue
  components/identity/utils/useIdentity.ts
  components/navbar/ChainSelectDropdown.vue
  components/navbar/NavbarChainOptions.vue
  composables/useChainRedirect.ts
  composables/usePrefix.ts
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  pages/_prefix/massmint/index.vue
  pages/_prefix/massmint/onboarding.vue
  pages/sales.vue
  pages/series-insight.vue
  utils/config/permision.config.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#6700 #6636 cards update
  components/items/ItemsGrid/ItemsGridImage.vue
  libs/ui/src/scss/_theme.scss
  styles/abstracts/_theme.scss
Labels: 🤞 - changes-requested, ✅ - works-for-me, small, waiting-for-review

#6751 :wastebasket: remove on-finality RPC nodes
  libs/static/src/endpoints.ts
Labels: small, waiting-for-review

#6752 🔧 GalleryCard vue3
  components/rmrk/Gallery/GalleryCard.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#6748 chore: filter out polkadot from chain selector
  components/Navbar.vue
  components/shared/format/Money.vue
  utils/chain.ts
  utils/config/permision.config.ts
Labels: small, waiting-for-review

#6753 🔧 Loader vue3
  components/shared/Loader.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6761 🔧 Money prop
  components/bsx/format/TokenMoney.vue
  components/shared/format/BasicMoney.vue
  components/shared/format/Money.vue
Labels: small, waiting-for-review

#6760 🔧 canCancel Loader
  components/shared/Loader.vue
Labels: small, waiting-for-review

#6754 🔧 ReadOnlyBalance vue3
  components/shared/ReadOnlyBalanceInput.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6765 fix: Sidebar strip when active
  libs/ui/src/components/NeoModalExtend/plugin.js
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6755 fix: neo button hover color
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6772 refactor(BaseTokenForm): to compositionApi
  components/base/BaseTokenForm.vue
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6771 refactor(BaseCollectionForm): to compositionApi
  components/base/BaseCollectionForm.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6756 style: update table padding
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6675 fix: create drop card
  components/drops/CreateDropCard.vue
  components/drops/CreateDropGallery.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  static/drops/BlueShade.svg
  static/drops/PinkShade.svg
  static/drops/create_drop1.svg
  static/drops/create_drop2.svg
  static/drops/create_drop3.svg
  static/drops/create_drop4.svg
Labels: ✅ - code-lgtm, 🤞 - changes-requested, paid, ✅ - visual-ok, large, waiting-for-review

#6759 fix: console warn
  components/landing/FeaturedArticles.vue
  libs/ui/src/components/CardArticle/CardArticle.story.vue
  libs/ui/src/components/CardArticle/CardArticle.vue
Labels: small, waiting-for-review

#6758 fix: Check for balances for address more often
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  components/transfer/Transfer.vue
  components/transfer/TransferOld.vue
Labels: small, waiting-for-review

#6775 fix: token symbol on carousel
  components/carousel/module/CarouselInfo.vue
  components/common/shoppingCart/utils.ts
Labels: small, waiting-for-review

#6781 [blogpost] A Comprehensive Guide on How to Make Generative NFT Art
  content/blog/a-comprehensive-guide-on-how-to-make-generative-nft-art.md
  static/blog/a-comprehensive-guide-on-how-to-make-generative-nft-art.webp
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6786 💅 favicon
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/favicon.svg
Labels: small, waiting-for-review

#6790 🔧 DropUpload vue3
  components/shared/DropUpload.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#6803 fix: add alt tags to landing page images - lighthouse
  components/TheFooter.vue
  components/landing/SearchLanding.vue
  components/navbar/ShoppingCartButton.vue
  components/search/SearchBar.vue
Labels: paid, small, waiting-for-review

#6796 feat: Show royalty recipient in the Gallery Item
  components/gallery/GalleryItemDescription.vue
  queries/subsquid/ahk/nftById.graphql
  queries/subsquid/general/nftById.graphql
Labels: ✅ - visual-ok, small, waiting-for-review

#6768 fix: teleport tabs hover color
  components/teleport/TeleportTabs.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6804 refactor(SearchSortDropDown): to compositonApi
  components/search/SearchSortDropdown.vue
Labels: small, waiting-for-review

#6808 ref(redirectAfterChainChange): Refactor redirect function redirectAfterChainChange
  composables/useChainRedirect.ts
Labels: paid, medium, waiting-for-review

#6807 refactor: useEventListener
  components/Navbar.vue
  components/chart/PriceChart.vue
  components/redirect/useRedirectModal.ts
  components/shared/DropUpload.vue
  components/shared/ScrollTopButton.vue
  components/shared/chart/LineChart.vue
Labels: small, waiting-for-review

#6802 [blogpost] A Comprehensive Guide on How to Setup a Polkadot Wallet
  content/blog/a-comprehensive-guide-on-how-to-setup-a-polkadot-wallet.md
  static/blog/a-comprehensive-guide-on-how-to-setup-a-polkadot-wallet.webp
Labels: small, waiting-for-review

#6801 [blogpost] The Creator Economy: A Deep Dive into Fandom Shops and Brand Loyalty
  content/blog/the-creator-economy-a-deep-dive-into-fandom-shops-and-brand-loyalty.md
  static/blog/the-creator-economy-a-deep-dive-into-fandom-shops-and-brand-loyalty.webp
Labels: small, waiting-for-review

#6810 fix: adjust query in landing page
  components/carousel/utils/useCarousel.ts
  composables/useSearchNfts.ts
Labels: small

#6815 beta update
  .github/diagram.svg
  components/Navbar.vue
  components/TheFooter.vue
  components/bsx/Create/RoyaltyForm.vue
  components/carousel/utils/useCarousel.ts
  components/chart/PriceChart.vue
  components/gallery/GalleryItemDescription.vue
  components/landing/SearchLanding.vue
  components/navbar/ShoppingCartButton.vue
  components/redirect/useRedirectModal.ts
  components/search/SearchBar.vue
  components/search/SearchSortDropdown.vue
  components/shared/DropUpload.vue
  components/shared/ScrollTopButton.vue
  components/shared/chart/LineChart.vue
  components/teleport/TeleportTabs.vue
  composables/useChainRedirect.ts
  composables/useSearchNfts.ts
  content/blog/a-comprehensive-guide-on-how-to-setup-a-polkadot-wallet.md
  content/blog/the-creator-economy-a-deep-dive-into-fandom-shops-and-brand-loyalty.md
  queries/subsquid/ahk/nftById.graphql
  queries/subsquid/general/nftById.graphql
  script/generate.mjs
  static/blog/a-comprehensive-guide-on-how-to-setup-a-polkadot-wallet.webp
  static/blog/the-creator-economy-a-deep-dive-into-fandom-shops-and-brand-loyalty.webp
Labels: beta

#6816 release update
  .github/diagram.svg
  components/Navbar.vue
  components/TheFooter.vue
  components/bsx/Create/RoyaltyForm.vue
  components/carousel/utils/useCarousel.ts
  components/chart/PriceChart.vue
  components/gallery/GalleryItemDescription.vue
  components/landing/SearchLanding.vue
  components/navbar/ShoppingCartButton.vue
  components/redirect/useRedirectModal.ts
  components/search/SearchBar.vue
  components/search/SearchSortDropdown.vue
  components/shared/DropUpload.vue
  components/shared/ScrollTopButton.vue
  components/shared/chart/LineChart.vue
  components/teleport/TeleportTabs.vue
  composables/useChainRedirect.ts
  composables/useSearchNfts.ts
  content/blog/a-comprehensive-guide-on-how-to-setup-a-polkadot-wallet.md
  content/blog/the-creator-economy-a-deep-dive-into-fandom-shops-and-brand-loyalty.md
  queries/subsquid/ahk/nftById.graphql
  queries/subsquid/general/nftById.graphql
  script/generate.mjs
  static/blog/a-comprehensive-guide-on-how-to-setup-a-polkadot-wallet.webp
  static/blog/the-creator-economy-a-deep-dive-into-fandom-shops-and-brand-loyalty.webp
Labels: release

#6826 fix(useRedirectModal): Switch button items and activity at collection view opens new page and cart button on explorer too
  components/redirect/useRedirectModal.ts
  components/shared/Markdown.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#6824 fix: Display the newest article in hero
  content/blog/dynamic-nfts-revolutionizing-digital-ownership.md
  pages/blog/index.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#6795 fix: redirect modal style
  components/redirect/RedirectModal.vue
  components/redirect/useRedirectModal.ts
Labels: ✅ - visual-ok, small, waiting-for-review

#6764 feat: transfer redesign for mobile
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  components/transfer/TransferOld.vue
  libs/ui/src/components/NeoModal/NeoModal.vue
  pages/_prefix/transfer.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#6829 [blogpost] KodaDot Products: Exploring the New Horizon of NFTs
  content/blog/kodadot-products-exploring-the-new-horizon-of-nfts.md
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-1.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-2.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-3.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-4.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-5.webp
Labels: small, waiting-for-review

#6831 beta update
  components/redirect/RedirectModal.vue
  components/redirect/useRedirectModal.ts
  components/shared/Markdown.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  components/transfer/TransferOld.vue
  content/blog/dynamic-nfts-revolutionizing-digital-ownership.md
  content/blog/kodadot-products-exploring-the-new-horizon-of-nfts.md
  libs/ui/src/components/NeoModal/NeoModal.vue
  pages/_prefix/transfer.vue
  pages/blog/index.vue
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-1.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-2.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-3.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-4.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-5.webp
Labels: beta

#6832 release update
  components/redirect/RedirectModal.vue
  components/redirect/useRedirectModal.ts
  components/shared/Markdown.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  components/transfer/TransferOld.vue
  content/blog/dynamic-nfts-revolutionizing-digital-ownership.md
  content/blog/kodadot-products-exploring-the-new-horizon-of-nfts.md
  libs/ui/src/components/NeoModal/NeoModal.vue
  pages/_prefix/transfer.vue
  pages/blog/index.vue
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-1.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-2.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-3.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-4.webp
  static/blog/kodadot-products-exploring-the-new-horizon-of-nfts-5.webp
Labels: release

#6794 feat: highlight code
  components/blog/BlogPost.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#6830 refactor(BasicNumberInput): to composition api
  components/shared/form/BasicNumberInput.vue
Labels: small, waiting-for-review

#6843 fix: update accessibility issues - lighthouse #6838
  components/TheFooter.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselMedia.vue
  components/navbar/ProfileDropdown.vue
Labels: small, waiting-for-review

#6825 style: navbar menu on mobile
  styles/layouts/_main-navigation.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#6850 fix: Cant list items on AHK - for Uniques pallet
  composables/transaction/transactionList.ts
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#6854 fix: incorrect templateRef
  components/bsx/input/TokenBalanceInput.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6814 refactor(BasicSwitch): to composition api
  components/shared/form/BasicSwitch.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6770 Fix/permission
  components/Navbar.vue
  components/drops/Drops.vue
  composables/useChainRedirect.ts
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  pages/_prefix/massmint/index.vue
  pages/_prefix/massmint/onboarding.vue
  pages/sales.vue
  pages/series-insight.vue
  utils/config/permission.config.ts
  utils/config/types.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6745 Feat/profile v0 9
  components/collection/CollectionGrid.vue
  components/collection/CollectionGridWithBreadcrumbs.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/common/ChainDropdown.vue
  components/explore/DesktopControls.vue
  components/explore/MobileControls.vue
  components/items/Items.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/profile/FilterButton.vue
  components/profile/OrderByDropdown.vue
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileGrid.vue
  components/profile/ProfileLink.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/EmotionModal.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  components/shared/format/StatsColumn.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/en.json
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/u/_id.vue
  queries/subsquid/general/allEventsByProfile.graphql
  utils/historyEvent.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#6716 feat(transfer token switch): Implement token switching buttons on transfer redesign
  components/shared/TabItem.vue
  components/transfer/Transfer.vue
  components/transfer/TransferTokenTabs.vue
  composables/useToken.ts
  utils/objects.ts
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#6844 fix: update components to be more seo compatible - lighthouse
  components/TheFooter.vue
  components/landing/SearchLanding.vue
  components/navbar/ShoppingCartButton.vue
Labels: small, waiting-for-review

#6861 beta update
  ACTIVITY.md
  components/Navbar.vue
  components/TheFooter.vue
  components/blog/BlogPost.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/input/TokenBalanceInput.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselMedia.vue
  components/collection/CollectionGrid.vue
  components/collection/CollectionGridWithBreadcrumbs.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/common/ChainDropdown.vue
  components/drops/Drops.vue
  components/explore/DesktopControls.vue
  components/explore/MobileControls.vue
  components/items/Items.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/SearchLanding.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/ShoppingCartButton.vue
  components/profile/FilterButton.vue
  components/profile/OrderByDropdown.vue
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileGrid.vue
  components/profile/ProfileLink.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/EmotionModal.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  components/shared/BalanceInput.vue
  components/shared/TabItem.vue
  components/shared/form/BasicNumberInput.vue
  components/shared/form/BasicSwitch.vue
  components/shared/format/StatsColumn.vue
  components/transfer/Transfer.vue
  components/transfer/TransferTokenTabs.vue
  composables/transaction/transactionList.ts
  composables/useChainRedirect.ts
  composables/useToken.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/de.json
  locales/en.json
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  pages/_prefix/massmint/index.vue
  pages/_prefix/massmint/onboarding.vue
  pages/_prefix/u/_id.vue
  pages/sales.vue
  pages/series-insight.vue
  queries/subsquid/general/allEventsByProfile.graphql
  styles/layouts/_main-navigation.scss
  utils/config/permission.config.ts
  utils/config/types.ts
  utils/historyEvent.ts
  utils/objects.ts
Labels: beta

#6862 release update
  ACTIVITY.md
  components/Navbar.vue
  components/TheFooter.vue
  components/blog/BlogPost.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/input/TokenBalanceInput.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselMedia.vue
  components/collection/CollectionGrid.vue
  components/collection/CollectionGridWithBreadcrumbs.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/common/ChainDropdown.vue
  components/drops/Drops.vue
  components/explore/DesktopControls.vue
  components/explore/MobileControls.vue
  components/items/Items.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/SearchLanding.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/ShoppingCartButton.vue
  components/profile/FilterButton.vue
  components/profile/OrderByDropdown.vue
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileGrid.vue
  components/profile/ProfileLink.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/EmotionModal.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/Sales.vue
  components/shared/BalanceInput.vue
  components/shared/TabItem.vue
  components/shared/form/BasicNumberInput.vue
  components/shared/form/BasicSwitch.vue
  components/shared/format/StatsColumn.vue
  components/transfer/Transfer.vue
  components/transfer/TransferTokenTabs.vue
  composables/transaction/transactionList.ts
  composables/useChainRedirect.ts
  composables/useToken.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/de.json
  locales/en.json
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  pages/_prefix/massmint/index.vue
  pages/_prefix/massmint/onboarding.vue
  pages/_prefix/u/_id.vue
  pages/sales.vue
  pages/series-insight.vue
  queries/subsquid/general/allEventsByProfile.graphql
  styles/layouts/_main-navigation.scss
  utils/config/permission.config.ts
  utils/config/types.ts
  utils/historyEvent.ts
  utils/objects.ts
Labels: release

#6806 refactor(SearchBar): to compositionApi and refactored keyboard mixin
  components/search/SearchBar.vue
  composables/useKeyboardEvents.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#6863 feat: 3 nfts per collection on landing page
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/module/CarouselMedia.vue
  components/carousel/utils/useCarousel.ts
  components/carousel/utils/useCarouselEvents.ts
  queries/subsquid/general/latestEvents.graphql
  queries/subsquid/ksm/latestEvents.graphql
  utils/carousel.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#6859 ➖ unused PaginatedCardList
  components/rmrk/Gallery/PaginatedCardList.vue
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6870 [blogpost] Unravelling the Mystery: Where to Buy Polkadot
  content/blog/unravelling-the-mystery-where-to-buy-polkadot.md
  static/blog/unravelling-the-mystery-where-to-buy-polkadot.webp
Labels: ✅ - works-for-me, small, waiting-for-review

#6874 ➖ balanceInput test
  tests/unit-testing/components/shared/BalanceInput.test.ts
Labels: medium, waiting-for-review

#6876 remove: failing test
  tests/unit-testing/components/shared/BasicBalanceInput.test.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6841 refactor(SearchCollection): to compositionApi
  components/search/SearchCollection.vue
Labels: ✅ - code-lgtm, medium, waiting-for-review
