Repository kodadot/nft-gallery, pull requests merged in 2023-03, with the labels that each got.

#5135 feat: dynamic grid on new collection
  components/explore/ExploreGrid.vue
  components/explore/ExploreIndex.vue
  components/explore/ExploreTabs.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/shared/DynamicGrid.vue
  store/preferences.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5136 fix: Explore gallery cards have unequeal height
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#5141 fix: faq not working
  nuxt.config.js
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5137 feat: use dynamic grid on existing explorer
  components/collection/CollectionList.vue
  components/shared/DynamicGrid.vue
  components/shared/gallery/Gallery.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok

#5149 #5144 highlight clickable
  styles/abstracts/_theme.scss
  styles/components/_gallery-item.scss
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, ✅ - visual-ok

#5174 fix: properties and mediaUri on gallery detail
  components/gallery/GalleryItemDescription.vue
  components/gallery/useGalleryItem.ts
  components/rmrk/service/scheme.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5169 fix: Sorting in my profile not working properly
  components/rmrk/Gallery/PaginatedCardList.vue
Labels: ✅ - code-lgtm

#5159 🐛 holders/flippers redirect link
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
Labels: ✅ - visual-ok

#5160 fix: Search bar focus after hitting enter
  components/search/SearchBar.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5148 feat: fontawesome pro sharp regular by default
  components/collection/CollectionHeader/HeroButtons.vue
  components/explore/ExploreChain.vue
  components/explore/ExploreSort.vue
  components/explore/tab/TabItem.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  nuxt.config.js
  plugins/icons.ts
Labels: ✅ - works-for-me, ✅ - visual-ok

#5170 fix: Search tag when searching nothing
  components/shared/gallery/BreadcrumbsFilter.vue
Labels: ✅ - visual-ok

#5134 #5132 Gallery item detail description
  styles/components/_gallery-item.scss
Labels: paid, ✅ - works-for-me

#5189 ✨ migrate chain store to pinia
  components/accounts/utils.ts
  components/series/utils.ts
  components/spotlight/utils.ts
  plugins/polkadot.ts
  store/chain.ts
  stores/chain.ts
  utils/account.ts
  utils/support.ts
Labels: ✅ - code-lgtm

#5194 fix: Search from collection page broken
  components/search/SearchBar.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5187 fix: clear search url
  components/search/Search.vue
Labels: ✅ - works-for-me

#5192 feat: load rmrk2 images on item-explore
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/shared/gallery/Gallery.vue
  composables/useNft.ts
  libs/ui/.eslintrc.js
  package.json
  pages/_prefix/explore/items.vue
  pnpm-lock.yaml
  queries/subsquid/rmrk2/nftListWithSearch.graphql
  utils/queryPathResolver.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#5221 fix: pressed enter two times to search on landing page
  components/search/Search.vue
  components/search/SearchBar.vue
Labels: ✅ - works-for-me

#5215 🔧 mobile identity link color
  components/collection/CollectionInfo.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/identity/module/IdentityLink.vue
Labels: ✅ - works-for-me

#5089 [Feedback request] 🔧 container is-fluid
  components/Navbar.vue
  components/TheFooter.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/common/FrequentlyAsked.vue
  components/items/Items.vue
  components/landing/LandingPage.vue
  layouts/default.vue
  layouts/explore-layout.vue
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  pages/jobs.vue
  pages/rmrk/faq.vue
  styles/global.scss
Labels: redesign, visual change, ✅ - visual-ok

#5235 fix(ui): fix sidebar issue in safari
  libs/ui/src/components/NeoSidebar/NeoSidebar.scss
Labels: ✅ - works-for-me

#5236 #5232 slider overflow
  styles/components/_carousel.scss
Labels: ✅ - visual-ok

#5211 #5155 adding margin when scrolling to desktop only
  components/explore/SidebarFilter.vue
Labels: paid, ✅ - works-for-me

#5223 bug fix in explore sort
  components/explore/ExploreSort.vue
Labels: ✅ - works-for-me, ✅ - visual-ok

#5237 #5216 neo icon
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.story.vue
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/index.ts
  styles/components/_connect-wallet.scss
Labels: ✅ - visual-ok

#5229 ✨ sidebar filters-full border
  components/explore/FilterMenuButton.vue
  components/explore/MobileFilter.vue
  components/explore/SidebarFilter.vue
  components/explore/filters/PriceFilter.vue
  components/explore/filters/StatusFilter.vue
  pages/_prefix/collection/_id/index.vue
  pages/_prefix/explore/items.vue
  styles/abstracts/_variables.scss
  styles/global.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#5260 fix: Disable RMRK2 for kodadot.xyz
  utils/constants.ts
Labels: ✅ - code-lgtm

#5261 fix: Remove grid option from collections
  components/collection/CollectionList.vue
  components/explore/DesktopControls.vue
  components/shared/DynamicGrid.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5238 #5143 spacing issue explore
  components/explore/SidebarFilter.vue
  layouts/explore-layout.vue
Labels: ✅ - visual-ok

#5264 fix: Search dropdown redirect
  components/search/Search.vue
Labels: ✅ - visual-ok

#5263 #5230 collection popover area issue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok

#5269 feat(ui): add wallet connect auth tips
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  locales/de.json
  locales/en.json
  locales/es.json
  styles/components/_connect-wallet.scss
Labels: ✅ - visual-ok

#5217 Massmint onboarding
  components/massmint/Massmint.vue
  components/massmint/OnBoarding.vue
  components/navbar/CreateDropdown.vue
  composables/useLocalStorage.ts
  locales/en.json
  pages/_prefix/massmint/index.vue
  pages/_prefix/massmint/onboarding.vue
  plugins/icons.ts
  pnpm-lock.yaml
  stores/preferences.ts
  styles/components/_carousel-arrows.scss
  styles/components/_carousel.scss
Labels: ✅ - works-for-me

#5270 fix: Unable to fill footer form
  components/TheFooter.vue
  styles/layouts/_footer.scss
Labels: ✅ - works-for-me

#5224 #5209 activity tab
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  libs/ui/src/scss/_theme.scss
Labels: ✅ - works-for-me, ✅ - visual-ok

#5283 fix: subscribe input on footer
  styles/layouts/_footer.scss
Labels: ✅ - works-for-me, ✅ - visual-ok

#5242 Massmin choose collection
  components/explore/tab/TabOnCollection.vue
  components/explore/tab/TabOnExplore.vue
  components/massmint/Massmint.vue
  components/massmint/OnBoarding.vue
  components/massmint/useMassMint.ts
  components/shared/TabItem.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  locales/en.json
  utils/queryPathResolver.ts
Labels: ✅ - works-for-me, ✅ - visual-ok

#5287 fix: collection display on landing card
  styles/components/_carousel.scss
  utils/carousel.ts
Labels: paid, ✅ - visual-ok

#5273 fix(ui): different landing page visual
  components/TheFooter.vue
  components/landing/SearchLanding.vue
  static/blurred-landing-footer.png
  static/blurred-landing-footer.svg
  static/landing-blurred-header-left.png
  static/landing-blurred-header-left.svg
  static/landing-blurred-header-right.png
  static/landing-blurred-header-right.svg
Labels: ✅ - visual-ok

#5294 fix: Explorer items doesnot reappear when untick buy now
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - works-for-me

#5295 feat: Increase card number on landing
  components/carousel/CarouselIndex.vue
  components/carousel/module/CarouselAgnostic.vue
  components/landing/FeaturedArticles.vue
  script/substack.mjs
Labels: ✅ - visual-ok

#5276 Composable-transactionMint
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  composables/transaction/mintCollection/constructMeta.ts
  composables/transaction/mintCollection/transactionMintCollectionBasilisk.ts
  composables/transaction/mintCollection/transactionMintCollectionRmrk.ts
  composables/transaction/mintCollection/useNewCollectionId.ts
  composables/transaction/mintCollection/utils.ts
  composables/transaction/mintToken/constructMeta.ts
  composables/transaction/mintToken/transactionMintBasilisk.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/transaction/transactionMintCollection.ts
  composables/transaction/transactionMintToken.ts
  composables/transaction/types.ts
  composables/useTransaction.ts
  locales/en.json
  tests/mass.spec.ts
  utils/directUpload.ts
  utils/mintUtils.ts
  utils/notification.ts
Labels: paid, ✅ - works-for-me

#5309 fix: gallery item break point set to 930px
  components/gallery/GalleryItem.vue
Labels: ✅ - visual-ok

#5311 fix: My non-carbonless NFT is carbonless
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  components/settings/Minting.vue
Labels: ✅ - code-lgtm

#5279 feat: load rmrk2 image on gallery item
  components/base/types.ts
  components/carousel/module/CarouselMedia.vue
  components/carousel/utils/useCarousel.ts
  components/gallery/GalleryItem.vue
  components/gallery/useGalleryItem.ts
  components/rmrk/service/scheme.ts
  composables/transaction/mintToken/transactionMintBasilisk.ts
  composables/useNft.ts
  queries/subsquid/rmrk2/collectionEntityById.graphql
  queries/subsquid/rmrk2/nftById.graphql
  utils/queryPathResolver.ts
Labels: ✅ - works-for-me

#5315 fix: remove unused `box`class of `Error.vue`
  components/shared/Error.vue
Labels: ✅ - code-lgtm, paid

#5349 test: insufficient funds on create collection rmrk
  tests/cypress/e2e/create-collection.cy.ts
Labels: ✅ - works-for-me

#5320 feat: Social links collection detail
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/CollectionHeader/HeroButtons.vue
  components/collection/CollectionInfo.vue
  components/collection/HeroButtons.vue
  components/identity/utils/useIdentity.ts
Labels: ✅ - works-for-me, ✅ - visual-ok

#5340 fix: spacing collection detail
  layouts/explore-layout.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5337 fix: Stroke around pfp collection
  components/collection/CollectionHeader/CollectionBanner.vue
Labels: ✅ - works-for-me, ✅ - visual-ok

#5351 🔧 collection redesign description markdown
  components/collection/CollectionInfo.vue
Labels: ✅ - code-lgtm

#5347 #5346 empty search result
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - code-lgtm

#5339 chore: add locale sort/check script
  .gitignore
  locales/sk.json
  package.json
  script/checkLocale.mjs
Labels: ✅ - works-for-me

#5338 fix: Own filter collection
  components/items/ItemsGrid/useItemsGrid.ts
  components/items/ItemsGrid/utils/useSearchParams.ts
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5357 fix(ui): add theme text color for <strong>
  styles/global.scss
Labels: ✅ - code-lgtm

#5390 fix: remove cache for chain list
  components/landing/SearchLanding.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/CreateDropdown.vue
  components/navbar/NavbarExploreOptions.vue
  composables/useChain.ts
  middleware/prefix.ts
  package.json
  plugins/vuex-persist.ts
  pnpm-lock.yaml
  utils/chain.ts
Labels: ✅ - code-lgtm

#5386 fix: subscribe button styling
  styles/layouts/_footer.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5383 feat: Collection description long text wrap
  components/collection/CollectionInfo.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
Labels: ✅ - visual-ok

#5382 fix: No properties displayed
  components/gallery/GalleryItemDescription.vue
  composables/transaction/mintToken/constructMeta.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
Labels: ✅ - visual-ok

#5380 #5365 double border fix
  styles/components/_o-tabs.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5381 #5378 expired check
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
Labels: ✅ - code-lgtm

#5327 fix: activity tab did not refresh after buy
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  composables/useGraphql.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#5348 #5167 breadcrumbs for min and max price
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/modules/PriceFilter.vue
Labels: paid

#5412 fix: Hover bg on nav links
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  styles/global.scss
Labels: ✅ - visual-ok

#5300 #5178 Massmint upload picture
  components/massmint/Massmint.vue
  components/massmint/UploadPicture/UploadPicture.vue
  components/shared/upload/DropUpload.vue
  libs/ui/src/components/NeoCollapse/NeoCollapse.scss
  libs/ui/src/components/NeoCollapse/NeoCollapse.vue
  libs/ui/src/index.ts
  locales/en.json
Labels: ✅ - visual-ok
