Repository kodadot/nft-gallery, pull requests merged in 2023-12, with the labels that each got.

#8244 MediaItem to tailwindcss
  assets/styles/global.scss
  components/massmint/OverviewTable.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
  libs/ui/src/components/MediaItem/type/IFrameMedia.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/MediaItem/type/JsonMedia.vue
  libs/ui/src/components/MediaItem/type/ModelMedia.vue
  libs/ui/src/components/MediaItem/type/ObjectMedia.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
Labels: ✅ - code-lgtm, medium, waiting-for-review

#8361 🔧 switch to tailwind & fix histoire darkmode
  libs/ui/histoire.config.ts
  libs/ui/src/components/NeoSwitch/NeoSwitch.scss
  libs/ui/src/scss/tailwind.scss
Labels: small, waiting-for-review

#8341 Migrated NeoCheckbox to tailwindcss
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.scss
Labels: small, waiting-for-review

#8360 fix: incorrect bg color on hover state
  components/common/NotificationBox/NotificationItem.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small

#8343 Migrated NeoCollapsible to tailwindcss
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.scss
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.story.vue
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8374 feat: Show fees in listings modal
  assets/styles/global.scss
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/listingCart/ListingCartModal.vue
  components/shared/modals/ModalBody.vue
  composables/autoTeleport/useAutoTeleportTransition.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  locales/en.json
  utils/teleport.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8357 fix: Email signup modal button animation
  assets/styles/abstracts/_animations.scss
  components/collection/drop/DropConfirmModal.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small

#8388 Free drop signup modal iteration
  components/collection/drop/DropConfirmModal.vue
  components/collection/unlockable/UnlockableTag.vue
  components/gallery/UnlockableTag.vue
  components/landing/SignupBanner.vue
  composables/useIcon.ts
  composables/useNft.ts
  composables/useUnlockableIcon.ts
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#8304 fix: Modal loading styling
  assets/styles/abstracts/_theme.scss
  libs/ui/src/scss/_theme.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#8045 💅 customize collection
  components/collection/CustomizeModal.vue
  components/collection/HeroButtonCustomizeCollection.vue
  components/collection/HeroButtons.vue
  composables/transaction/transactionSetCollectionMaxSupply.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useTransaction.ts
  queries/subsquid/general/collectionByIdMinimal.graphql
Labels: ✅ - works-for-me, medium, waiting-for-review

#8397 Fixed NeoAvatar size bug
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8336 Migrated NeoAutocomplete to tailwindcss
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.scss
Labels: ✅ - code-lgtm, small, waiting-for-review

#8302 Massmint-multiupload
  composables/transaction/mintToken/constructDirectoryMeta.ts
  composables/transaction/mintToken/transactionMintStatemine.ts
  composables/transaction/mintToken/utils.ts
  services/nftStorage.ts
  tests/transactionMintStatemine.spec.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#8320 fix: Disabled claim till generate new
  components/collection/drop/GenerativePreview.vue
Labels: small

#8389 💅 collection max supply
  components/collection/CollectionInfo.vue
  components/collection/utils/types.ts
  components/collection/utils/useCollectionDetails.ts
  locales/en.json
  queries/subsquid/general/collectionStatsById.graphql
Labels: ✅ - works-for-me, small, waiting-for-review

#8401 🔧 NeoCheckbox story
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.story.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
Labels: small, waiting-for-review

#8355 Migrated NeoInput to tailwindcss
  libs/ui/src/components/NeoInput/NeoField.scss
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoInputitems/NeoInputitems.scss
Labels: ✅ - works-for-me, small

#8338 Migrated NeoAvatar to tailwindcss
  libs/ui/src/components/NeoAvatar/NeoAvatar.scss
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8350 Migrated NeoDropdown to tailwindcss
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8413 ⬆️ minimark package
  composables/transaction/transactionBurn.ts
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#8412 NeoLoading to tailwindcss and added icons to historie
  libs/ui/package.json
  libs/ui/src/components/NeoLoading/NeoLoading.scss
  libs/ui/src/components/NeoLoading/NeoLoading.story.vue
  libs/ui/src/components/NeoLoading/NeoLoading.vue
  libs/ui/src/histoire.setup.ts
  pnpm-lock.yaml
Labels: small, waiting-for-review

#8328 Remark---massmint-multi-upload
  composables/transaction/mintToken/transactionMintRmrk.ts
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#8426 Fix/Checkmark icon on generative drops
  components/collection/drop/Generative.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok, small

#8351 Migrated NeoIcon to tailwindcss
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/tailwind.config.js
Labels: ✅ - works-for-me, small

#8435 fix(carousel.ts): add optional chaining to nft.resources array access
  utils/carousel.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#8421 Links not visible in Description & Show more link
  assets/styles/components/_content-markdown.scss
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#8334 fix: When switching from transfer on polkadot, refresh network
  middleware/prefix.global.ts
  pages/[prefix]/explore/collectibles.vue
  pages/[prefix]/explore/items.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small

#8446 fix: Make claim button active when wallet is not connected
  components/collection/drop/Generative.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#8447 (Fix): Drop (name) + (max)
  components/collection/drop/Generative.vue
  components/collection/unlockable/utils.ts
  params/types.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8417 feat: gallery item page view counter
  components/gallery/GalleryItem.vue
  composables/usePageViews.ts
  libs/ui/tailwind.config.js
  plugins/icons.ts
  utils/constants.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#8440 feat: Claim drop modals and flow
  assets/styles/global.scss
  components/collection/drop/DropConfirmModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/modal/ClaimingDrop.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/EmailSignup.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/utils/useCountDown.ts
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  components/shared/SkeletonLoader.vue
  components/shared/modals/ModalBody.vue
  composables/useSocialShare.ts
  locales/en.json
  services/waifu.ts
Labels: 🤞 - changes-requested, large, waiting-for-review

#8460 🔧 add new live drop
  components/carousel/CarouselTypeGenerative.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  composables/popularCollections/constants.ts
Labels: small, waiting-for-review

#8434 Added gasless drop modal feature to require funds on account
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/unlockable/const.ts
  composables/useMultipleBalance.ts
  locales/en.json
  stores/identity.ts
Labels: medium, waiting-for-review

#8462 adding wallstreet to landing
  components/carousel/CarouselTypeGenerative.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  composables/popularCollections/constants.ts
Labels: small, waiting-for-review

#8477 :poop: make all drops free
  components/drops/DropCard.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8449 Fixed checkbox in chart settings
  components/chart/PriceChart.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8458 fix: Visual gap in drops new claim drop modal flow
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/drop/modal/ClaimingDrop.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/utils/useCountDown.ts
  components/collection/voteDrop/DropContainer.vue
  utils/dom.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#8478 :bug: isFreeDrop is accessed via computed
  components/drops/DropCard.vue
Labels: small, waiting-for-review

#8480 beta update
  components/base/MediaItem.vue
  components/chart/PriceChart.vue
  components/collection/HeroButtons.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/drop/modal/ClaimingDrop.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/utils/useCountDown.ts
  components/collection/voteDrop/DropContainer.vue
  components/drops/DropCard.vue
  components/gallery/GalleryItem.vue
  composables/useSocialShare.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/components/NeoModal/NeoModal.story.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  package.json
  plugins/vueSocialSharing.ts
  pnpm-lock.yaml
  utils/dom.ts
Labels: large, beta

#8481 release update
  components/base/MediaItem.vue
  components/chart/PriceChart.vue
  components/collection/HeroButtons.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/drop/modal/ClaimingDrop.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/utils/useCountDown.ts
  components/collection/voteDrop/DropContainer.vue
  components/drops/DropCard.vue
  components/gallery/GalleryItem.vue
  composables/useSocialShare.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/components/NeoModal/NeoModal.story.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  package.json
  plugins/vueSocialSharing.ts
  pnpm-lock.yaml
  utils/dom.ts
Labels: release, large

#8506 Fix/Playwright prefix test
  tests/e2e/prefix.spec.ts
Labels: small, waiting-for-review

#8493 Fix img height bug
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8529 feat: Drop brackets from usd price in item trading history
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#8484 🔧 show collection royalty
  components/collection/CollectionInfo.vue
  components/collection/utils/useCollectionDetails.ts
  queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql
Labels: ✅ - works-for-me, small, waiting-for-review

#8523 NeoTabs to tailwindcss
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
Labels: ✅ - code-lgtm, small, waiting-for-review

#8521 NeoTooltip to tailwindcss
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8505 fix: teleport with existential deposit
  components/teleport/Teleport.vue
  libs/static/src/chains.ts
  locales/en.json
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#8545 Remove footer on Drop page
  pages/[prefix]/drops/index.vue
Labels: small, waiting-for-review

#8517 NeoNotification to tailwindcss
  libs/ui/src/components/NeoNotification/NeoNotification.vue
Labels: small, waiting-for-review

#8518 NeoPagination to tailwindcss
  libs/ui/src/components/NeoPagination/NeoPagination.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8543 NeoRadio to tailwindcss
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
  libs/ui/tailwind.config.js
Labels: small, waiting-for-review

#8494 fix: view collection on drops should not open new window
  components/collection/unlockable/UnlockableCollectionInfo.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8546 Test/Fix Footer reddit link
  tests/e2e/footer.spec.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8509 NeoMessage to tailwindcss
  components/MessageNotify.vue
  libs/ui/src/components/NeoMessage/NeoMessage.scss
  libs/ui/src/components/NeoMessage/NeoMessage.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#8538 ref: Improve process adding new drop on landing
  components/carousel/CarouselTypeGenerative.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  composables/popularCollections/constants.ts
  utils/drop.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#8534 fix: NeoTable content dark mode
  libs/ui/src/components/NeoTable/NeoTable.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8520 NeoSlider to tailwindcss
  libs/ui/src/components/NeoSlider/NeoSlider.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8514 Small refactoring NeoModalExtend
  libs/ui/src/components/NeoModalExtend/NeoModalExtend.vue
Labels: small, waiting-for-review

#8555 Fixed mobile pagination
  components/profile/activityTab/History.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8533 fix: Small cards mobile layout
  components/items/ItemsGrid/ItemsGrid.vue
  components/shared/DynamicGrid.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8536 fix: drop modal bugs
  components/collection/drop/modal/DropConfirmModal.vue
  utils/dom.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#8567 Beta update
  components/MessageNotify.vue
  components/carousel/CarouselTypeGenerative.vue
  components/collection/CollectionInfo.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/ProfileDropdown.vue
  components/profile/activityTab/History.vue
  components/shared/DynamicGrid.vue
  components/teleport/Teleport.vue
  composables/popularCollections/constants.ts
  libs/static/src/chains.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoMessage/NeoMessage.scss
  libs/ui/src/components/NeoMessage/NeoMessage.vue
  libs/ui/src/components/NeoModalExtend/NeoModalExtend.vue
  libs/ui/src/components/NeoNotification/NeoNotification.vue
  libs/ui/src/components/NeoPagination/NeoPagination.vue
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
  libs/ui/src/components/NeoSlider/NeoSlider.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  locales/en.json
  pages/[prefix]/drops/index.vue
  plugins/i18n.ts
  queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql
  stores/preferences.ts
  tests/e2e/footer.spec.ts
  tests/e2e/prefix.spec.ts
  utils/config/i18n.ts
  utils/dom.ts
  utils/drop.ts
Labels: large, waiting-for-review

#8572 release update
  components/MessageNotify.vue
  components/carousel/CarouselTypeGenerative.vue
  components/collection/CollectionInfo.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/ProfileDropdown.vue
  components/profile/activityTab/History.vue
  components/shared/DynamicGrid.vue
  components/teleport/Teleport.vue
  composables/popularCollections/constants.ts
  libs/static/src/chains.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoMessage/NeoMessage.scss
  libs/ui/src/components/NeoMessage/NeoMessage.vue
  libs/ui/src/components/NeoModalExtend/NeoModalExtend.vue
  libs/ui/src/components/NeoNotification/NeoNotification.vue
  libs/ui/src/components/NeoPagination/NeoPagination.vue
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
  libs/ui/src/components/NeoSlider/NeoSlider.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  locales/en.json
  pages/[prefix]/drops/index.vue
  plugins/i18n.ts
  queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql
  stores/preferences.ts
  tests/e2e/footer.spec.ts
  tests/e2e/prefix.spec.ts
  utils/config/i18n.ts
  utils/dom.ts
  utils/drop.ts
Labels: large, waiting-for-review

#8516 NeoModalHead to tailwindcss
  components/common/shoppingCart/ShoppingCartModal.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  libs/ui/tailwind.config.js
  tests/e2e/collection.spec.ts
Labels: ✅ - works-for-me, small

#8540 NeoStickyModal to tailwindcss
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.scss
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8586 fix: modals broken on mobile screen size
  components/shared/modals/ModalBody.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#8581 Copilot tag removal
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_AND_DESIGN_PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_AND_QA_PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_PULL_REQUEST_TEMPLATE.md
  .github/push_release_beta.sh
  .github/push_release_old-prod.sh
  .github/push_release_production.sh
Labels: small, waiting-for-review

#8569 feat: holder of drop functionality
  components/collection/drop/HolderOfCollection.vue
  components/collection/drop/HolderOfGenerative.vue
  locales/en.json
  pages/[prefix]/drops/[id].vue
  params/types.ts
  queries/subsquid/general/holderOfCollectionById.graphql
  queries/subsquid/general/unlockableCollectionById.graphql
  services/waifu.ts
Labels: large, waiting-for-review

#8592 :wrench: chroma is the main drop
  utils/drop.ts
Labels: small

#8594 beta update
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_AND_DESIGN_PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_AND_QA_PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_PULL_REQUEST_TEMPLATE.md
  .github/push_release_beta.sh
  .github/push_release_old-prod.sh
  .github/push_release_production.sh
  components/collection/drop/HolderOfCollection.vue
  components/collection/drop/HolderOfGenerative.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/shared/modals/ModalBody.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.scss
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.vue
  libs/ui/tailwind.config.js
  locales/en.json
  pages/[prefix]/drops/[id].vue
  params/types.ts
  queries/subsquid/general/holderOfCollectionById.graphql
  queries/subsquid/general/unlockableCollectionById.graphql
  services/waifu.ts
  tests/e2e/collection.spec.ts
  utils/drop.ts
Labels: large, beta

#8595 release update
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_AND_DESIGN_PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_AND_QA_PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/QUICK_PULL_REQUEST_TEMPLATE.md
  .github/push_release_beta.sh
  .github/push_release_old-prod.sh
  .github/push_release_production.sh
  components/collection/drop/HolderOfCollection.vue
  components/collection/drop/HolderOfGenerative.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/shared/modals/ModalBody.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.scss
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.vue
  libs/ui/tailwind.config.js
  locales/en.json
  pages/[prefix]/drops/[id].vue
  params/types.ts
  queries/subsquid/general/holderOfCollectionById.graphql
  queries/subsquid/general/unlockableCollectionById.graphql
  services/waifu.ts
  tests/e2e/collection.spec.ts
  utils/drop.ts
Labels: release

#8596 beta update
  components/collection/drop/HolderOfGenerative.vue
Labels: small, beta

#8597 release update
  components/collection/drop/HolderOfGenerative.vue
Labels: release, small, waiting-for-review

#8598 Hotfix: minted generative
  components/collection/drop/HolderOfGenerative.vue
Labels: small, waiting-for-review

#8601 Prod releasing bugfixes for holder of
  components/collection/drop/HolderOfGenerative.vue
  locales/en.json
Labels: small, waiting-for-review

#8615 fix: On ahp
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  locales/en.json
Labels: small, waiting-for-review

#8565 override container max-width
  assets/styles/layouts/_main-navigation.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#8549 teleport warning followup
  assets/styles/global.scss
  components/teleport/EDWarningModal.vue
  components/teleport/FundsAtRiskWarning.vue
  components/teleport/Teleport.vue
  locales/en.json
  utils/teleport.ts
Labels: 🤞 - changes-requested, medium, waiting-for-review

#8452 ref: Loading modal slowness
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/Confirm/MintConfirmModal.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleport.ts
  composables/autoTeleport/useAutoTeleportTransition.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  utils/support.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#8522 fix: Profile: Every time you refresh - The token order changes
  components/balance/MultipleBalances.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8547 feat: Drops requiring funds to enable auto-teleport
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/unlockable/const.ts
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/utils.ts
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useAmount.ts
  composables/useMultipleBalance.ts
  locales/en.json
  stores/identity.ts
  utils/format/balance.ts
  utils/teleport.ts
Labels: 🤞 - changes-requested, large, waiting-for-review

#8589 💅 landing top collection asset hub
  components/landing/LandingPage.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/landing/topCollections/utils/useTopCollections.ts
  queries/subsquid/general/topCollections.graphql
Labels: 🤞 - changes-requested, small, waiting-for-review

#8531 ensure copy works on all devices
  plugins/clipboard.client.ts
  plugins/vueClipboard.ts
  utils/copyToClipboard.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#8414 feat: Collection filtering on top of profile
  assets/styles/global.scss
  components/explore/ActiveCount.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/profile/CollectionFilter.vue
  components/profile/ProfileDetail.vue
  composables/useChainRedirect.ts
  libs/ui/src/scss/tailwind.scss
  queries/fragments/collectionDetails.graphql
Labels: paid, ✅ - works-for-me, large, waiting-for-review

#8620 Revert "feat: Drops requiring funds to enable auto-teleport"
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/unlockable/const.ts
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/utils.ts
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useAmount.ts
  composables/useMultipleBalance.ts
  locales/en.json
  stores/identity.ts
  utils/format/balance.ts
  utils/teleport.ts
Labels: large, waiting-for-review

#8621 beta update
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/balance/MultipleBalances.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/explore/ActiveCount.vue
  components/explore/DesktopControls.vue
  components/explore/ExploreGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/LandingPage.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/landing/topCollections/utils/useTopCollections.ts
  components/profile/CollectionFilter.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileGrid.vue
  components/shared/DynamicGrid.vue
  components/shared/GridLayoutControls.vue
  components/teleport/EDWarningModal.vue
  components/teleport/FundsAtRiskWarning.vue
  components/teleport/Teleport.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleport.ts
  composables/autoTeleport/useAutoTeleportTransition.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useChainRedirect.ts
  libs/ui/src/scss/tailwind.scss
  locales/en.json
  plugins/clipboard.client.ts
  plugins/vueClipboard.ts
  queries/fragments/collectionDetails.graphql
  queries/subsquid/general/topCollections.graphql
  stores/preferences.ts
  utils/copyToClipboard.ts
  utils/support.ts
  utils/teleport.ts
Labels: large, waiting-for-review, beta

#8626 release update
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/balance/MultipleBalances.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/explore/ActiveCount.vue
  components/explore/DesktopControls.vue
  components/explore/ExploreGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/LandingPage.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/landing/topCollections/utils/useTopCollections.ts
  components/profile/CollectionFilter.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileGrid.vue
  components/shared/DynamicGrid.vue
  components/shared/GridLayoutControls.vue
  components/teleport/EDWarningModal.vue
  components/teleport/FundsAtRiskWarning.vue
  components/teleport/Teleport.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleport.ts
  composables/autoTeleport/useAutoTeleportTransition.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useChainRedirect.ts
  libs/ui/src/scss/tailwind.scss
  locales/en.json
  plugins/clipboard.client.ts
  plugins/vueClipboard.ts
  queries/fragments/collectionDetails.graphql
  queries/subsquid/general/topCollections.graphql
  stores/preferences.ts
  utils/copyToClipboard.ts
  utils/support.ts
  utils/teleport.ts
Labels: release

#8624 Stuck at claim of Chroma drop #8619
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/unlockable/const.ts
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/utils.ts
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useAmount.ts
  composables/useMultipleBalance.ts
  locales/en.json
  stores/identity.ts
  utils/format/balance.ts
  utils/teleport.ts
Labels: large, waiting-for-review

#8627 beta update
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/unlockable/const.ts
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/utils.ts
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useAmount.ts
  composables/useMultipleBalance.ts
  locales/en.json
  stores/identity.ts
  utils/format/balance.ts
  utils/teleport.ts
Labels: beta

#8628 release update
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/unlockable/const.ts
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/utils.ts
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useAmount.ts
  composables/useMultipleBalance.ts
  locales/en.json
  stores/identity.ts
  utils/format/balance.ts
  utils/teleport.ts
Labels: release

#8637 fix: Top collections mobile
  locales/en.json
Labels: small, waiting-for-review

#8640 fix: Shuffle landing strips
  components/landing/LandingPage.vue
Labels: small, waiting-for-review

#8583 get true last id from chain
  composables/transaction/mintToken/utils.ts
  tests/transactionMintStatemine.spec.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#8643 fix: Different number of items in drops page and drop iteself
  components/drops/DropCard.vue
Labels: small, waiting-for-review

#8585 Fix/collection-preview-animation-src
  components/rmrk/Gallery/GalleryCard.vue
Labels: 🤞 - changes-requested, small, waiting-for-review

#8653 toHuman -> toNumber
  tests/transactionMintStatemine.spec.ts
Labels: small, waiting-for-review

#8652 🔧 landing newestlist margin top
  components/landing/LandingPage.vue
Labels: small, waiting-for-review

#8588 💅 sort by volume DESC
  components/explore/ExploreSort.vue
  locales/en.json
Labels: 🤞 - changes-requested, small, waiting-for-review

#8651 🔧 drop responsive
  components/collection/drop/HolderOfGenerative.vue
Labels: small, waiting-for-review

#8524 NeoSteps to tailwindcss
  libs/ui/src/components/NeoSteps/NeoSteps.scss
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
Labels: ✅ - works-for-me, small, waiting-for-review

#8502 Migrated NeoSelect to tailwindcss
  libs/ui/src/components/NeoSelect/NeoSelect.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#8541 NeoSkeleton to tailwindcss
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.scss
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#8582 Fix/buy-nft-fail
  utils/support.ts
Labels: ✅ - works-for-me, small

#8658 💅 sort by highestSale DESC
  components/explore/ExploreSort.vue
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#8665 Replace is-capitalize with tailwindcss
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  components/base/MediaItem.vue
  components/carousel/module/CarouselInfo.vue
  components/collection/CollectionInfo.vue
  components/collection/drop/modal/ClaimingDrop.vue
  components/collection/drop/modal/EmailSignup.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/IdentityForm.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/identity/IdentityConfirmModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/create/CreateNftPreview.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/generative/GenerativeMintForm.vue
  components/landing/MobileHeroBanner.vue
  components/landing/SearchLanding.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/massmint/OnBoardingCard.vue
  components/migrate/steps/Review.vue
  components/navbar/NavbarExploreOptions.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
  components/shared/SkeletonLoader.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/filters/modules/PopularCollections.vue
  components/teleport/Teleport.vue
  components/transfer/TransferConfirmModal.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#8662 fix: button active hover state on collection filter
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: small, waiting-for-review

#8672 🔧 ahp landing collection spotlight
  components/carousel/utils/useCarouselSpotlight.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8661 fix: incorrect unique owners at hover card
  components/collection/utils/useCollectionDetails.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8674 Test/Change tutorial URL on footer test
  tests/e2e/footer.spec.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8655 🔧 navbar search square btn
  components/Navbar.vue
  components/collection/HeroButtons.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8667 fix: load-carousel-early
  components/carousel/CarouselIndex.vue
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/module/CarouselInfo.vue
  components/carousel/utils/useCarouselEvents.ts
  components/landing/LandingPage.vue
Labels: small, waiting-for-review

#8654 feat: Dynamic unlockable tag
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/utils/useUnlockableTag.ts
  components/drops/useDrops.ts
  locales/en.json
  utils/drop.ts
Labels: 🤞 - changes-requested, ✅ - works-for-me, medium, waiting-for-review

#8679 fix: remove search bar from landing
  assets/styles/components/_search.scss
  components/landing/SearchLanding.vue
Labels: small, waiting-for-review

#8680 perf: load carousel early for generative list
  components/carousel/CarouselTypeGenerative.vue
  components/carousel/utils/useCarouselEvents.ts
Labels: small, waiting-for-review

#8682 fix: Make default chain AHP
  libs/static/src/chains.ts
Labels: small, waiting-for-review

#8687 fix: search bar visibility
  components/Navbar.vue
Labels: small, waiting-for-review

#8689 feat: Hero section change
  assets/styles/components/_search.scss
  components/landing/HeroBanner.vue
  components/landing/LandingPage.vue
  components/landing/SearchLanding.vue
Labels: ✅ - visual-ok, medium, waiting-for-review

#8691 ➖ whitespace in carouselInfo
  components/carousel/module/CarouselInfo.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8551 change order of sections on mobile drop page
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintSection.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#8690 💅 refactor collection infos
  components/collection/CollectionInfo.vue
  components/collection/HeroButtons.vue
  components/collection/collectionInfoLine.vue
  components/shared/ModalIdentityItem.vue
  queries/subsquid/general/collectionByIdMinimal.graphql
  queries/subsquid/general/collectionByIdMinimalWithRoyalty.graphql
Labels: medium, waiting-for-review

#8636 fallback address for recieving royalties
  composables/transaction/transactionBuy.ts
  utils/balance.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8694 fix: Mobile collections filter needs more love
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
Labels: small, waiting-for-review

#8695 fix: email signup in footer
  assets/styles/layouts/_footer.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#8656 feat: HolderOf if someone used nft and then do resale
  components/drops/useDrops.ts
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemHolderOf.vue
  components/shared/view/InfoBox.vue
  locales/en.json
  utils/drop.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#8701 feat: add beehiiv posts
  components/landing/FeaturedArticles.vue
  libs/ui/src/components/CardArticle/CardArticle.vue
  package.json
  script/posts.json
  script/posts.mjs
  script/substack.json
  script/substack.mjs
Labels: large, waiting-for-review

#8668 feat: Free drops requires activated email
  components/collection/drop/Generative.vue
  components/collection/drop/modal/ConfirmEmail.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/EmailSignup.vue
  components/landing/LandingPage.vue
  components/landing/SignupBanner.vue
  locales/en.json
  public/email-subscription-dark.svg
  public/email-subscription.svg
  stores/preferences.ts
  utils/newsletter.ts
Labels: 🤞 - changes-requested, paid, large, waiting-for-review

#8714 :tada: new drop is christmas
  utils/drop.ts
Labels: small, waiting-for-review

#8706 do not alter blob urls
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: small, waiting-for-review

#8719 :zap: deprecate parity nodes on dot and ahp
  libs/static/src/endpoints.ts
Labels: small, waiting-for-review

#8720 fix: christmas city drop wrong popup
  components/drops/useDrops.ts
Labels: small, waiting-for-review

#8722 :zap: show christmas city on landing
  utils/drop.ts
Labels: small, waiting-for-review

#8737 Add Christimas City to Ahp Spotlight
  components/carousel/utils/useCarouselSpotlight.ts
Labels: ✅ - code-lgtm, small

#8732 Fix/Same-transfer,different-time
  components/collection/utils/timeAgo.ts
  utils/format/time.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8727 fix: Pill shape announcement refresh
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/utils/useUnlockableTag.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8728 fix: Item name drop
  components/carousel/CarouselTypeLatestMints.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8731 itemCount is owned nfts
  components/migrate/landing/content/Ready.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8738 ParaSpell XCM SDK v5->v11
  package.json
  pnpm-lock.yaml
Labels: ✅ - works-for-me, large, waiting-for-review

#8721 fix: redirect to correct prefix according to drop
  pages/[prefix]/drops/[id].vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8752 minimumLastIndexUsed => 0
  composables/transaction/mintToken/utils.ts
Labels: small, waiting-for-review

#8750 fix: Cards in gallery item
  assets/styles/components/_carousel.scss
  components/carousel/module/CarouselInfo.vue
Labels: small, waiting-for-review

#8772 Drop is genera
  utils/drop.ts
Labels: small, waiting-for-review

#8760 🔧 markdown paragraph spacing
  assets/styles/components/_content-markdown.scss
  components/shared/Markdown.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8757 🔧 collection stats listed no burned
  queries/subsquid/general/collectionStatsById.graphql
Labels: ✅ - works-for-me, small, waiting-for-review

#8749 add: Generate new cursor loading state
  components/collection/drop/GenerativePreview.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#8744 fix: Double information in the collection
  components/collection/CollectionInfo.vue
  locales/en.json
Labels: ✅ - works-for-me, small

#8779 :wastebasket: remove delay
  components/collection/drop/Generative.vue
Labels: small, waiting-for-review

#8766 add: [blogpost] Polkadot Generative Drops
  content/blog/polkadot-generative-drops-on-kodadot.md
  public/blog/polkadot-generative-drops-on-kodadot-1.webp
  public/blog/polkadot-generative-drops-on-kodadot-2.webp
  public/blog/polkadot-generative-drops-on-kodadot-3.webp
  public/blog/polkadot-generative-drops-on-kodadot-4.webp
  public/blog/polkadot-generative-drops-on-kodadot-5.webp
  public/blog/polkadot-generative-drops-on-kodadot-6.webp
Labels: ✅ - code-lgtm, 🤞 - changes-requested, small, A-blog

#8730 Landing-reconstruction
  components/landing/LandingPage.vue
  components/search/SearchBar.vue
  tests/e2e/basic.spec.ts
  tests/e2e/footer.spec.ts
  tests/e2e/search.spec.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8698 fix: Mobile activity tab
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8734 feat: Auto-teleport ED followup
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
Labels: ✅ - works-for-me, small
