Repository kodadot/nft-gallery, pull requests merged in 2023-07, with the labels that each got.

#6368 🔧 libs/ui package
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/gallery/GalleryItem.vue
  components/identity/IdentityItem.vue
  libs/ui/src/components/DisablableTab/DisablableTab.scss
  libs/ui/src/components/DisablableTab/DisablableTab.story.vue
  libs/ui/src/components/IdentityItem/IdentityItem.story.vue
  libs/ui/src/components/NeoInput/NeoInput.story.vue
  libs/ui/src/components/NeoModal/NeoModal.story.vue
  libs/ui/src/components/NeoRadio/NeoRadio.story.vue
  libs/ui/src/components/NeoSelect/NeoSelect.story.vue
  libs/ui/src/components/NeoSelect/NeoSelect.vue
  libs/ui/src/index.ts
  styles/abstracts/_variables.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6366 🔧 migrate b-pagination
  components/rmrk/Gallery/Pagination.vue
  libs/ui/src/components/NeoPagination/NeoPagination.vue
  libs/ui/src/index.ts
  styles/abstracts/_variables.scss
  styles/global.scss
Labels: ✅ - works-for-me, medium, waiting-for-review

#6377 🔧 new apollo clients
  utils/constants.ts
Labels: small, waiting-for-review

#6374 chore: bump paraspell
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#6376 🔧 Uncaught ReferenceError: G is not defined
  nuxt.config.js
Labels: small, waiting-for-review

#6378 🔧 getProcessMetadata (useNft)
  composables/useNft.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#6379 🔧 vue3 composition api pages
  pages/_prefix/collection/_id/activity.vue
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  pages/identity.vue
  pages/sustainability.vue
  tests/cypress/e2e/components/media.cy.ts
  utils/mixins/experimentMixin.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6381 🔧 stmn collection activity
  composables/collectionActivity/helpers.ts
Labels: small, waiting-for-review

#6384 🔧 History table To link
  components/rmrk/Gallery/History.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6370 fix: searchbar dropdown styling
  styles/components/_search.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6391 :wrench: pnpm lock @ 6.1
  pnpm-lock.yaml
Labels: small, waiting-for-review

#6231 refactor: neo tabs
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/search/SearchSuggestion.vue
  libs/ui/src/components/DisablableTab/DisablableTab.scss
  libs/ui/src/components/DisablableTab/DisablableTab.story.vue
  libs/ui/src/components/DisablableTab/DisablableTab.vue
  libs/ui/src/components/NeoTab/NeoTab.scss
  libs/ui/src/components/NeoTab/NeoTab.vue
  libs/ui/src/components/NeoTab/NeoTabItem.vue
  libs/ui/src/components/NeoTabs/NeoTabItem.vue
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/components/NeoTabs/NeoTabs.vue
  libs/ui/src/index.ts
  pages/bsx/create.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/settings.vue
  pages/snek/create.vue
  styles/components/_o-tabs.scss
  styles/components/_search.scss
  styles/global.scss
  styles/index.scss
  utils/mixins/createMixin.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#6393 6390 shanghai waifu
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/const.ts
  components/collection/unlockable/utils.ts
Labels: small, waiting-for-review

#6394 🔧 refact nuxt-property-decorator
  components/bsx/format/TokenMoney.vue
  components/rmrk/Gallery/Item/Name.vue
  components/rmrk/Gallery/Item/Price.vue
  components/search/SearchResultItem.vue
  components/shared/Auth.vue
  components/shared/BlockExplorerLink.vue
  components/shared/CommonTokenMoney.vue
  components/shared/Support.vue
  components/shared/gallery/Properties.vue
  components/shared/modals/ShowQRModal.vue
  components/shared/view/BasicPopup.vue
Labels: large, waiting-for-review

#6396 :art: most advanced code
  components/drops/DropCard.vue
  components/drops/useDrops.ts
Labels: small, waiting-for-review

#6363 fix: Drops pages could have dedicated og:image
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/utils.ts
  layouts/unlockable-mint-layout.vue
  plugins/seoMetaGenerator.ts
  tests/cypress/e2e/opengraph-collection.cy.ts
  tests/cypress/e2e/opengraph-item.cy.ts
  utils/seoImageGenerator.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6405 refactor: remove unused mixins
  utils/mixins/createdAtMixin.ts
  utils/mixins/extrinsicsMixin.ts
  utils/mixins/passionListMixin.ts
  utils/mixins/queryMixin.ts
  utils/mixins/singleSubscribeMixin.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6380 Fix/simple-mint
  components/accounts/utils.ts
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/service/NftUtils.ts
  components/rmrk/service/scheme.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6402 🔧 basicImage responsive to src props changes
  components/shared/view/BasicImage.vue
Labels: small

#6400 #6369 hover effect on dark mode
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/scss/_theme.scss
  styles/abstracts/_theme.scss
  styles/layouts/_main-navigation.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#6382 🔧 migrate b-navbar
  components/Navbar.vue
  components/navbar/CreateDropdown.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/NavbarExploreOptions.vue
Labels: ✅ - works-for-me, large, waiting-for-review

#6409 ✨ toku nft in spotlight
  components/carousel/utils/useCarouselSpotlight.ts
Labels: small, waiting-for-review

#6412 fix: Disabled BUY button on bsx
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6425 fix: Clicking on Activity while searching different collections shows…
  components/explore/tab/TabOnCollection.vue
Labels: small, waiting-for-review

#6263 #6223 double stroke issues
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/massmint/Massmint.vue
  libs/ui/src/components/NeoInput/NeoField.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6422 fix: make kodadot.xyz/drops working again
  middleware/redirects.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6401 #6387 alignment fix
  components/search/SearchSuggestion.vue
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.scss
  libs/ui/src/components/NeoTabs/NeoTabs.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6338 Neo select component
  components/base/CollectionSelect.vue
  components/bsx/Offer/MasterOfferTable.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/rmrk/Gallery/History.vue
  components/search/SearchSortDropdown.vue
  components/series/SeriesTable.vue
  components/settings/Interface.vue
  components/shared/BalanceInput.vue
  libs/ui/src/components/NeoSelect/NeoSelect.scss
  libs/ui/src/components/NeoSelect/NeoSelect.vue
  tests/unit-testing/components/shared/BalanceInput.test.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6407 🔧 overlapping modal
  components/Navbar.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ProfileDropdown.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6420 🔧 migrate oruga css to NeoLib
  components/gallery/GalleryItem.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  styles/components/_o-table.scss
  styles/components/_o-tooltip.scss
  styles/index.scss
Labels: ✅ - works-for-me, medium, waiting-for-review

#6414 🔧 migrate offers page to composition api
  components/bsx/Offer/MasterOfferTable.vue
  locales/en.json
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6435 beta update
  components/Navbar.vue
  components/accounts/utils.ts
  components/base/CollectionSelect.vue
  components/bsx/Offer/MasterOfferTable.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/carousel/utils/useCarouselSpotlight.ts
  components/explore/tab/TabOnCollection.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/massmint/Massmint.vue
  components/navbar/CreateDropdown.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/NavbarExploreOptions.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ProfileDropdown.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/service/NftUtils.ts
  components/rmrk/service/scheme.ts
  components/search/SearchSortDropdown.vue
  components/search/SearchSuggestion.vue
  components/series/SeriesTable.vue
  components/settings/Interface.vue
  components/shared/BalanceInput.vue
  components/shared/view/BasicImage.vue
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.scss
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoInput/NeoField.scss
  libs/ui/src/components/NeoSelect/NeoSelect.scss
  libs/ui/src/components/NeoSelect/NeoSelect.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  libs/ui/src/scss/_theme.scss
  locales/en.json
  middleware/redirects.ts
  stores/identity.ts
  styles/abstracts/_theme.scss
  styles/components/_o-table.scss
  styles/components/_o-tooltip.scss
  styles/index.scss
  styles/layouts/_main-navigation.scss
  tests/unit-testing/components/shared/BalanceInput.test.ts
  utils/mixins/createdAtMixin.ts
  utils/mixins/extrinsicsMixin.ts
  utils/mixins/passionListMixin.ts
  utils/mixins/queryMixin.ts
  utils/mixins/singleSubscribeMixin.ts
Labels: beta

#6436 release update
  components/Navbar.vue
  components/accounts/utils.ts
  components/base/CollectionSelect.vue
  components/bsx/Offer/MasterOfferTable.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/carousel/utils/useCarouselSpotlight.ts
  components/explore/tab/TabOnCollection.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/massmint/Massmint.vue
  components/navbar/CreateDropdown.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/NavbarExploreOptions.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ProfileDropdown.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/service/NftUtils.ts
  components/rmrk/service/scheme.ts
  components/search/SearchSortDropdown.vue
  components/search/SearchSuggestion.vue
  components/series/SeriesTable.vue
  components/settings/Interface.vue
  components/shared/BalanceInput.vue
  components/shared/view/BasicImage.vue
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.scss
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoInput/NeoField.scss
  libs/ui/src/components/NeoSelect/NeoSelect.scss
  libs/ui/src/components/NeoSelect/NeoSelect.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  libs/ui/src/scss/_theme.scss
  locales/en.json
  middleware/redirects.ts
  stores/identity.ts
  styles/abstracts/_theme.scss
  styles/components/_o-table.scss
  styles/components/_o-tooltip.scss
  styles/index.scss
  styles/layouts/_main-navigation.scss
  tests/unit-testing/components/shared/BalanceInput.test.ts
  utils/mixins/createdAtMixin.ts
  utils/mixins/extrinsicsMixin.ts
  utils/mixins/passionListMixin.ts
  utils/mixins/queryMixin.ts
  utils/mixins/singleSubscribeMixin.ts
Labels: release

#6438 fix: Statemine properties not showing
  composables/useNft.ts
  libs/static/src/indexers.ts
  queries/subsquid/stmn/nftById.graphql
  utils/constants.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6430 fix: Explore hover dropdown doing weird things
  components/Navbar.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/NavbarExploreOptions.vue
Labels: 🧪 - tested, small, waiting-for-review

#6443 ➖ unused utils
  script/substack.json
  tests/urlTransform.spec.ts
  utils/chainProperties.ts
  utils/format/string.ts
  utils/gpt.ts
  utils/groupBy.ts
  utils/history.ts
  utils/isFunction.ts
  utils/pinata.ts
  utils/pinning.ts
  utils/proxy.ts
  utils/rpc.ts
  utils/urlTransformer.ts
  utils/vueNotification.ts
Labels: refactoring, large, waiting-for-review

#6447 🔧 mobile activity table border none
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/shared/Sharing.vue
  composables/massmint/massMintHelpers.ts
  composables/massmint/useMassMint.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#6437 🔧 migrate Buefy buttons
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/rmrk/Create/AttributeInput.vue
  components/rmrk/Create/CustomAttributeInput.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/EmotionList.vue
  components/rmrk/Gallery/EmotionModal.vue
  components/search/Search.vue
  components/search/SearchPriceRange.vue
  components/search/SearchSortDropdown.vue
  components/shared/collection/PriceChart.vue
  components/spotlight/SpotlightTable.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6451 Reduce-using-nuxt-proprty-decorator/Teleport-page
  pages/spotlight.vue
  pages/teleport.vue
Labels: ✅ - code-lgtm, large, waiting-for-review

#6450 Reduce-using-nuxt-property-decorator
  components/series/SeriesTable.vue
  pages/error.vue
  pages/hot.vue
  pages/sales.vue
  pages/series-insight.vue
Labels: ✅ - code-lgtm, large, waiting-for-review

#6452 Remove-nuxt-property-decorator-#2
  pages/_prefix/massmint/index.vue
  pages/_prefix/massmint/onboarding.vue
  pages/bsx/assets.vue
  pages/bsx/claim.vue
  pages/bsx/incomingOffers.vue
  pages/bsx/offers.vue
  pages/bsx/stats.vue
  pages/bsx/waifu.vue
  pages/rmrk/mint.vue
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6446 fix: Teleport bridge is showing incorrect balances
  components/teleport/Teleport.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6457 Nuxt-propert-decorator/more-pages
  pages/index.vue
  pages/snek/assets.vue
  pages/snek/claim.vue
  pages/snek/incomingOffers.vue
  pages/snek/offers.vue
  pages/snek/stats.vue
  pages/stmn/waifu.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6458 migrate/remove inlineMixin and rmrkVersionMixin
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/LinkResolver.vue
  utils/mixins/inlineMixin.ts
  utils/mixins/rmrkVersionMixin.ts
Labels: small, waiting-for-review

#6454 fix: collectionId in path of url
  components/items/ItemsGrid/utils/useSearchParams.ts
  components/search/SearchBar.vue
  components/search/utils/useCollectionSearch.ts
  composables/useListInfiniteScroll.ts
  stores/search.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6461 feat: KodaDot blog
  components/blog/BlogPost.vue
  content/blog/what-is-erc6551.md
  nuxt.config.js
  package.json
  pages/blog/_slug.vue
  pages/blog/index.vue
  pages/first-time.vue
  pnpm-lock.yaml
  styles/abstracts/_theme.scss
Labels: 🤞 - changes-requested, large, waiting-for-review

#6456 Nuxt-property-decorator/Transfer
  components/shared/Auth.vue
  components/transfer/Transfer.vue
  composables/useChain.ts
  pages/_prefix/transfer.vue
Labels: ✅ - works-for-me, large, waiting-for-review

#6479 Set Stick v3
  libs/static/package.json
Labels: small, waiting-for-review

#6482 release update
  .github/ISSUE_TEMPLATE/bug_assetshub.yml
  .github/push_release_production.sh
  libs/static/package.json
  libs/static/src/indexers.ts
  utils/constants.ts
Labels: release

#6459 🔥 remove tabs from massmint
  components/massmint/Massmint.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6485 resource.meta null check
  components/gallery/useGalleryItem.ts
Labels: paid, small, waiting-for-review

#6492 #6491
  styles/layouts/_footer.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6449 🔧 migrate b-button part 2
  components/Navbar.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/shared/MessageNotify.vue
  components/shared/Sharing.vue
  components/transfer/Transfer.vue
  pnpm-lock.yaml
  styles/components/_connect-wallet.scss
  styles/layouts/_main-navigation.scss
Labels: ✅ - works-for-me, large, waiting-for-review

#6497 fix: Drop page announcement on landing
  components/collection/unlockable/UnlockableLandingTag.vue
  locales/en.json
  styles/abstracts/_theme.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6505 🔧 blog page refacto
  pages/blog/index.vue
Labels: ✅ - works-for-me, small, waiting-for-review
