Repository kodadot/nft-gallery, pull requests merged in 2023-06, with the labels that each got.

#6142 ➖ currentUrlPrefix
  composables/usePrefix.ts
  middleware/redirects.ts
  pages/_prefix/massmint/onboarding.vue
  tests/unit-testing/components/shared/BalanceInput.test.ts
  tests/unit-testing/components/shared/BasicBalanceInput.test.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#6137 Init unlockable items page
  assets/unlockable-banner.svg
  assets/unlockable-introduce.svg
  components/collection/unlockable/CollectionBanner.vue
  components/collection/unlockable/CollectionInfo.vue
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/HeroButtons.vue
  components/collection/unlockable/ImageSlider.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableSchedule.vue
  components/collection/unlockable/UnlockableTag.vue
  components/collection/unlockable/const.ts
  components/collection/unlockable/utils.ts
  layouts/unlockable-mint-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/types.ts
  pages/_prefix/unlockable.vue
  queries/subsquid/general/collectionMintedBetween.graphql
  queries/subsquid/general/unlockableCollectionById.graphql
  services/waifu.ts
Labels: large, waiting-for-review

#6161 fix: revert snek endpoint and fix workspaces config
  libs/static/package.json
  libs/static/src/indexers.ts
  netlify.toml
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tests/cypress/support/commands.ts
  utils/constants.ts
Labels: large, waiting-for-review

#6165 quick and dirty mobile
  components/collection/unlockable/CollectionBanner.vue
  components/collection/unlockable/CollectionInfo.vue
  components/collection/unlockable/ImageSlider.vue
  components/collection/unlockable/UnlockableContainer.vue
Labels: paid, small, waiting-for-review

#6175 fix: Unlockable change text in How unlockable item works
  components/collection/unlockable/UnlockableContainer.vue
Labels: small, waiting-for-review

#6173 Five min is not five min
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/const.ts
  components/collection/unlockable/utils.ts
  queries/subsquid/general/nftOwnedCountByCollectionId.graphql
Labels: small, waiting-for-review

#6155 #5852 remove buefy tag
  components/shared/BreadcrumbsFilter.vue
  components/shared/gallery/NeoTag.vue
  components/shared/modals/keyboardShortcutsModal.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#6180 🔧 ExploreGrid NeoField mb-0
  components/explore/ExploreGrid.vue
  pnpm-lock.yaml
  static/sitemap.xml
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#6184 fix: component files resolving to the same name
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  layouts/unlockable-mint-layout.vue
Labels: small, waiting-for-review

#6013 fix: offer button issue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6145 Enable identity form on Polkadot
  components/common/IdentityForm.vue
  components/navbar/ProfileDropdown.vue
  components/shared/form/BasicInput.vue
Labels: ✅ - code-lgtm, paid, small

#6191 fix: Remove sitemap from static
  .gitignore
  static/sitemap.xml
Labels: paid, small, waiting-for-review

#6160 🔧 NeoField & NeoInput
  components/sales/SalesTable.vue
  components/shared/form/BasicInput.vue
  libs/ui/src/components/NeoInput/NeoField.scss
  libs/ui/src/components/NeoInput/NeoField.vue
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoInput/NeoInput.vue
  pnpm-lock.yaml
  styles/global.scss
Labels: ✅ - works-for-me, medium, waiting-for-review

#6187 🔧 profile page buttons
  README.md
  components/rmrk/Profile/ProfileDetail.vue
  components/rmrk/Profile/ProfileLink.vue
  components/shared/modals/ModalWrapper.vue
  components/transfer/DonationButton.vue
  static/dotscanner.svg
Labels: ✅ - works-for-me, medium, waiting-for-review

#6192 Better Unlockable Waifu
  components/collection/unlockable/UnlockableContainer.vue
  components/shared/MessageNotify.vue
  locales/en.json
  queries/subsquid/general/firstNftOwnedByAccountAndCollectionId.graphql
  services/waifu.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#6169 #6147 refactor footer
  components/TheFooter.vue
  locales/en.json
  pages/jobs.vue
  styles/layouts/_footer.scss
Labels: 🤞 - changes-requested, ✅ - visual-ok, medium, waiting-for-review

#6139 fix landing page chain selector buttons
  components/landing/SearchLanding.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6131 feat: menu on sidebar (part 2)
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/common/ConnectWallet/WalletAssetSetIdentity.vue
  components/identity/utils/useIdentity.ts
  components/navbar/ProfileDropdown.vue
  composables/useExperiments.ts
  composables/usePrefix.ts
  composables/useSearchNfts.ts
  stores/identity.ts
  stores/lang.ts
  styles/components/_connect-wallet.scss
  styles/global.scss
  utils/mixins/experimentMixin.ts
Labels: ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#6197 refactor: proper extends rootClasses
  components/rmrk/Profile/ProfileDetail.vue
  libs/ui/src/components/NeoInput/NeoField.vue
  libs/ui/src/components/NeoInput/NeoInput.vue
Labels: small, waiting-for-review

#6170 🔧 NeoIcon defaultIcon pack sharp
  libs/ui/src/components/NeoIcon/NeoIcon.vue
Labels: small, waiting-for-review

#6212 🔧 notification icon regular
  components/navbar/NotificationBoxButton.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6215 ➖ polkascan & fix subscan profile link
  components/rmrk/Profile/ProfileDetail.vue
  static/polkascan.png
Labels: small, waiting-for-review

#6214 #6208 overflow fix
  components/navbar/ChainSelectDropdown.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok, small, waiting-for-review

#6144 ➖ b-table component
  components/bsx/Asset/AssetTable.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/hot/HotTable.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Profile/Sales.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  components/shared/modals/keyboardShortcutsModal.vue
  components/spotlight/SpotlightTable.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#6195 #5852 b-numberinput to neoinput number
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/form/BasicNumberInput.vue
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#6053 Cache graphql in useGalleryItem
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemPreviewer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/gallery/useGalleryItem.ts
  composables/useGraphql.ts
  pnpm-lock.yaml
Labels: ✅ - works-for-me, small

#6174 fix: bring back schedule
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableSchedule.vue
Labels: small, waiting-for-review

#6203 feat: isChain composable
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  composables/useIsChain.ts
  composables/usePrefix.ts
Labels: small, waiting-for-review

#6217 🔧 explore filterMenuButton size and pack
  components/explore/FilterMenuButton.vue
  libs/ui/src/components/NeoIcon/NeoIcon.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6219 🔧 slider input number padding
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6234 🔧 NeoInput default IconPack
  libs/ui/src/components/NeoInput/NeoInput.vue
Labels: small, waiting-for-review

#6177 feat: release redesign sidebar menu
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/navbar/MobileNavbarProfile.vue
  components/navbar/ProfileDropdown.vue
  components/rmrk/Profile/ProfileAssetsList.vue
  composables/usePrefix.ts
  stores/identity.ts
  stores/lang.ts
  tests/cypress/e2e/language.cy.ts
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#6183 🔧 NeoInputitems
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Gallery/Item/Facts.vue
  components/shared/ArweaveLink.vue
  libs/ui/src/components/NeoInputitems/NeoInputitems.scss
  libs/ui/src/components/NeoInputitems/NeoInputitems.vue
  libs/ui/src/index.ts
Labels: medium, waiting-for-review

#6211 feat: unlockable drop landing page
  components/Navbar.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/landing/SearchLanding.vue
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  locales/en.json
Labels: 🤞 - changes-requested, small, waiting-for-review

#6230 fix: rearrange smart portfolio view
  components/balance/MultipleBalances.vue
  locales/en.json
  stores/identity.ts
Labels: ✅ - visual-ok, small, waiting-for-review

#6232 🔧 sort by Sequence
  components/explore/ExploreSort.vue
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#6239 fix: weird skeleton loading
  components/collection/CollectionCard.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#6152 ⚡ add statemine to teleport bridge
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/teleport/Teleport.vue
  components/teleport/TeleportTabs.vue
  libs/static/src/chains.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/types.ts
  pages/_prefix/teleport.vue
  utils/teleport.ts
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#6244 🔧 error layout
  layouts/error.vue
Labels: small, waiting-for-review

#6250 test: adjust check tags
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
Labels: small, waiting-for-review

#6265 ci: fix wretry version
  .github/workflows/e2e.yml
Labels: small, waiting-for-review

#6243 🔧 owner calculation
  composables/collectionActivity/helpers.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6218 🔧 NeoButton icon pack
  components/base/SubmitButton.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6282 feat: put "Learn" link into navbar
  components/Navbar.vue
Labels: small, waiting-for-review

#6295 fix: Change heading text on landing page
  components/landing/SearchLanding.vue
  locales/en.json
  styles/components/_search.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#6286 feat: update robots.txt
  static/robots.txt
Labels: ✅ - code-lgtm, paid, small, waiting-for-review, docs

#6245 ➖ vuex
  FIRST_TIME.md
  STYLE_GUIDE.md
  components/metadata/Metadata.vue
  package.json
  pages/_prefix/transfer.vue
  patches/vuex@3.6.2.patch
  pnpm-lock.yaml
  store/setting.ts
Labels: 🤞 - changes-requested, medium, waiting-for-review

#6297 🔧 workflow e2e
  .github/workflows/e2e.yml
Labels: small, waiting-for-review

#6287 #6262 sidebar consistency
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  styles/components/_connect-wallet.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6298 🔧 error layout
  layouts/error.vue
Labels: small, waiting-for-review

#6271 fix: Create drop down overflowing
  components/navbar/CreateDropdown.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  styles/layouts/_main-navigation.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6260 fix: Clicking on profile should close sidebar
  components/common/ConnectWallet/ConnectWalletModal.vue
  libs/ui/src/components/IdentityItem/IdentityItem.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#6274 🔧 top collection buttons
  styles/components/_top-collections.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#6156 Fix/minting-with-listing--rmrk2
  components/base/BaseTokenForm.vue
  components/base/types.ts
  components/gallery/GalleryItemDescription.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/service/scheme.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/transaction/types.ts
  locales/en.json
  package.json
  pnpm-lock.yaml
Labels: ✅ - works-for-me, large, waiting-for-review

#6303 release update
  .github/workflows/e2e.yml
  FIRST_TIME.md
  STYLE_GUIDE.md
  components/Navbar.vue
  components/base/BaseTokenForm.vue
  components/base/SubmitButton.vue
  components/base/types.ts
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/landing/SearchLanding.vue
  components/metadata/Metadata.vue
  components/navbar/CreateDropdown.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/service/scheme.ts
  components/shared/filters/modules/PopularCollections.vue
  components/teleport/Teleport.vue
  components/teleport/TeleportTabs.vue
  composables/collectionActivity/helpers.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/transaction/types.ts
  layouts/error.vue
  libs/static/src/chains.ts
  libs/ui/src/components/IdentityItem/IdentityItem.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoRadio/NeoRadio.story.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  libs/ui/src/types.ts
  locales/en.json
  package.json
  pages/_prefix/teleport.vue
  pages/_prefix/transfer.vue
  patches/vuex@3.6.2.patch
  pnpm-lock.yaml
  static/robots.txt
  store/setting.ts
  styles/components/_connect-wallet.scss
  styles/components/_search.scss
  styles/components/_top-collections.scss
  styles/layouts/_main-navigation.scss
  tests/cypress/e2e/rmrk-simple-mint.cy.ts
  utils/teleport.ts
Labels: release, large, waiting-for-review

#6249 refactor: neo collapse
  components/collection/activity/ActivityChart.vue
  components/massmint/OverviewTable.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/PriceChart.vue
  components/rmrk/Profile/Sales.vue
  components/search/Search.vue
  components/settings/KeyboardShortcuts.vue
  components/shared/collapse/CollapseCardWrapper.vue
  components/shared/collapse/CollapseWrapper.vue
  components/shared/filters/modules/EventTypeFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/PriceFilter.vue
  components/shared/filters/modules/StatusFilter.vue
  libs/ui/src/components/NeoCollapse/NeoCollapse.vue
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.scss
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#6296 fix: drop page counter styling
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/const.ts
  libs/ui/src/scss/_theme.scss
  styles/global.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6299 style: update gallery item previewer
  components/gallery/GalleryItemPreviewer.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small

#6256 feat: Follow up for success drop notification
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/utils/useCountDown.ts
  locales/en.json
Labels: ✅ - visual-ok, small, waiting-for-review

#6320 fix: text and icon missing
  libs/ui/src/scss/_theme.scss
Labels: small, waiting-for-review

#6328 ➖ unused components
  components/bsx/Offer/DaySelect.vue
  components/bsx/Offer/OfferList.vue
  components/bsx/specific/DestroyCollection.vue
  components/landing/EsSustainability.vue
  components/layouts/Placeholder.vue
  components/rmrk/Gallery/CollectionActivity.vue
  components/settings/AddOption.vue
Labels: ✅ - code-lgtm, large, waiting-for-review

#6323 feat: Drop image examples and carousel
  components/collection/unlockable/ImageSlider.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/const.ts
  locales/en.json
  styles/components/_carousel-arrows.scss
  styles/global.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6321 fix: Video thumbnail in activity preview
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#6324 chore: introduce no-follow links
  components/Navbar.vue
  components/TheFooter.vue
  components/carousel/module/CarouselMedia.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/UnlockableTag.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/module/IdentitySocial.vue
  components/landing/FeaturedArticles.vue
  components/media/type/UnknownMedia.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/shared/BlockExplorerLink.vue
  components/shared/Error.vue
  components/shared/LinkResolver.vue
  components/shared/format/ExternalLink.vue
  components/teleport/Teleport.vue
  layouts/error.vue
  libs/ui/src/components/CardArticle/CardArticle.vue
  libs/ui/src/components/MediaItem/type/UnknownMedia.vue
  pages/_prefix/transfer.vue
Labels: ✅ - code-lgtm, small

#6138 Activity-chart-outliers
  components/collection/activity/ActivityChart.vue
  components/collection/activity/utils.ts
  utils/math.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#6229 #6224 empty holders text
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  locales/en.json
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#6333 fix: Robots.txt is invalid
  nuxt.config.js
  static/robots.txt
  utils/constants.ts
Labels: small, waiting-for-review, docs

#6339 fix: UI - Settings - Minting - Arweave UI information popup
  components/rmrk/Create/ArweaveUploadSwitch.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#6337 :truck: unlockable to free-drop
  components/Navbar.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableLoader.vue
  pages/_prefix/drops/free-drop.vue
Labels: ✅ - code-lgtm, small

#6300 feat: drops page
  assets/unlockable-pulse.svg
  components/Navbar.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/drops/DropCard.vue
  components/drops/Drops.vue
  components/drops/TimeTag.vue
  components/drops/useDrops.ts
  libs/ui/src/components/NeoIcon/NeoIcon.scss
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  locales/en.json
  pages/_prefix/drops/index.vue
  styles/global.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#6264 #6254 hover issue
  libs/ui/src/components/NeoInputitems/NeoInputitems.scss
  styles/components/_search.scss
Labels: ✅ - code-lgtm, 🤞 - changes-requested, small, waiting-for-review

#6342 1-dot-waifu
  components/collection/drop/DropContainer.vue
  components/collection/drop/TokenImportButton.vue
  components/collection/drop/const.ts
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/const.ts
  components/collection/unlockable/utils.ts
  components/drops/DropCard.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  composables/useToast.ts
  layouts/unlockable-mint-layout.vue
  pages/_prefix/drops/dot-drop.vue
  queries/subsquid/general/collectionByIdMicro.graphql
  queries/subsquid/general/dropCollectionById.graphql
  queries/subsquid/general/nftIdListByCollection.graphql
  services/waifu.ts
Labels: large, waiting-for-review

#6352 :ambulance: ParaKek
  components/collection/drop/DropContainer.vue
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#6340 🔧 migrate b-slider to NeoSlider
  components/bsx/Create/RoyaltyForm.vue
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/form/BasicSlider.vue
  libs/ui/src/components/NeoSlider/NeoSlider.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#6354 ➖ unused packages
  components/rmrk/Gallery/Appreciation.vue
  components/rmrk/Gallery/Item/Navigation.vue
  components/shared/chart/BoxPlot/Canvas.vue
  components/shared/chart/BoxPlot/Container.vue
  components/shared/chart/BoxPlot/containerOptions.ts
  components/shared/wrapper/NoCollection.vue
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#6357 beta update
  components/bsx/Create/RoyaltyForm.vue
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/drops/DropCard.vue
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Appreciation.vue
  components/rmrk/Gallery/Item/Navigation.vue
  components/shared/chart/BoxPlot/Canvas.vue
  components/shared/chart/BoxPlot/Container.vue
  components/shared/chart/BoxPlot/containerOptions.ts
  components/shared/form/BasicSlider.vue
  components/shared/wrapper/NoCollection.vue
  libs/ui/src/components/NeoSlider/NeoSlider.vue
  libs/ui/src/index.ts
  package.json
  pnpm-lock.yaml
Labels: beta

#6358 release update
  components/bsx/Create/RoyaltyForm.vue
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/drops/DropCard.vue
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Appreciation.vue
  components/rmrk/Gallery/Item/Navigation.vue
  components/shared/chart/BoxPlot/Canvas.vue
  components/shared/chart/BoxPlot/Container.vue
  components/shared/chart/BoxPlot/containerOptions.ts
  components/shared/form/BasicSlider.vue
  components/shared/wrapper/NoCollection.vue
  libs/ui/src/components/NeoSlider/NeoSlider.vue
  libs/ui/src/index.ts
  package.json
  pnpm-lock.yaml
Labels: release

#6362 ➖ unused components
  components/generative/GenerativeMintForm.vue
  components/shared/form/RadioSelect.vue
  components/shared/input/balance/NewBalanceInput.vue
  components/unique/Collection/Item/CollectionItem.vue
  components/unique/Collection/Item/TransferCollectionModal.vue
  components/unique/Gallery/Item/AvailableActions.vue
  components/unique/Gallery/Item/DangerModal.vue
  components/unique/Gallery/Item/Detail.vue
Labels: ✅ - works-for-me, large, waiting-for-review
