Repository kodadot/nft-gallery, pull requests merged in 2023-09, with the labels that each got.

#7083 [nuxt3] checkpoint neo modal
  components/Navbar.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/TokenImportButton.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/common/ConnectWallet/WalletAssetSetIdentity.vue
  components/common/ConnectWallet/useConnectWallet.ts
  components/common/NotificationBox/useNotificationBox.ts
  components/common/shoppingCart/ShoppingCartModalConfig.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/ShoppingCartButton.vue
  components/redirect/useRedirectModal.ts
  components/rmrk/Gallery/EmotionList.vue
  components/shared/ConnectWalletButton.vue
  composables/useProgrammatic.ts
  libs/ui/src/components/NeoModalExtend/plugin.js
  libs/ui/src/components/NeoModalExtend/plugin.ts
Labels: medium, waiting-for-review

#7085 [Nuxt3]
  components/collection/CollectionGrid.vue
  components/explore/tab/TabOnCollection.vue
  components/explore/tab/TabOnExplore.vue
  components/gallery/GalleryItem.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/navbar/ExploreDropdown.vue
  components/shared/TabItem.vue
  layouts/default.vue
Labels: small, waiting-for-review

#7091 enable classic mint on ahk
  components/navbar/CreateDropdown.vue
Labels: small, waiting-for-review

#7082 🔧 fix ksm minting
  composables/transaction/mintToken/transactionMintRmrk.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7021 Profile followups
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventTag.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/profile/activityTab/HistoryRow.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/ResponsiveTable.vue
  queries/rmrk/subsquid/allEventsByProfile.graphql
  queries/subsquid/general/allEventsByProfile.graphql
  utils/historyEvent.ts
Labels: ✅ - code-lgtm, 🤞 - changes-requested, paid, ✅ - visual-ok, large, waiting-for-review

#7093 release update
  components/Navbar.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventTag.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/ChainDropdown.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/common/shoppingCart/ShoppingCartModalConfig.ts
  components/items/ItemsGrid/useItemsGrid.ts
  components/navbar/CreateDropdown.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/profile/activityTab/HistoryRow.vue
  components/rmrk/Create/SimpleMint.vue
  components/search/SearchSuggestion.vue
  components/shared/ConnectWalletButton.vue
  components/shared/PulseChart.vue
  components/shared/ResponsiveTable.vue
  components/shared/TransactionLoader.vue
  components/transfer/Transfer.vue
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/useChainRedirect.ts
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/NeoModalExtend/plugin.js
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  libs/ui/src/index.ts
  locales/en.json
  package.json
  queries/rmrk/subsquid/allEventsByProfile.graphql
  queries/subsquid/general/allEventsByProfile.graphql
  styles/components/_connect-wallet.scss
  styles/global.scss
  tests/transactionMintStatemine.spec.ts
  utils/historyEvent.ts
Labels: release

#7096 [Nuxt3]
  components/bsx/Asset/AssetList.vue
  components/collection/CollectionGrid.vue
  components/collection/CollectionGridWithBreadcrumbs.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventTag.vue
  components/items/Items.vue
  components/navbar/CreateDropdown.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/profile/activityTab/HistoryRow.vue
  components/shared/ResponsiveTable.vue
  composables/transaction/mintToken/transactionMintRmrk.ts
  pages/bsx/assets.vue
  pages/snek/assets.vue
  queries/rmrk/subsquid/allEventsByProfile.graphql
  queries/subsquid/general/allEventsByProfile.graphql
  utils/historyEvent.ts
Labels: large, waiting-for-review

#7104 🔧 more gql fixes
  components/bsx/Create/CreateToken.vue
  components/bsx/Offer/MasterOfferTable.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferStats.vue
  components/bsx/Offer/StatsOverview.vue
  components/profile/ProfileActivitySummery.vue
  components/rmrk/Gallery/Holding.vue
  components/series/SeriesTable.vue
  components/spotlight/SpotlightDetail.vue
Labels: medium, waiting-for-review

#7102 fix: force parsing metadata body with json
  utils/ipfs.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7079 :tada: unify the metadata
  libs/hyperdata/.editorconfig
  libs/hyperdata/.eslintignore
  libs/hyperdata/.eslintrc
  libs/hyperdata/.gitignore
  libs/hyperdata/.prettierrc
  libs/hyperdata/LICENSE
  libs/hyperdata/README.md
  libs/hyperdata/justfile
  libs/hyperdata/package.json
  libs/hyperdata/src/constatnts.ts
  libs/hyperdata/src/index.ts
  libs/hyperdata/src/normalize.ts
  libs/hyperdata/src/types.ts
  libs/hyperdata/src/utils.ts
  libs/hyperdata/tests/content.test.ts
  libs/hyperdata/tests/examples/fxhash.json
  libs/hyperdata/tests/generative.test.ts
  libs/hyperdata/tests/index.test.ts
  libs/hyperdata/tsconfig.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#7030 Refactor rmrk/CreateToken
  components/rmrk/Create/CreateToken.vue
Labels: 🤞 - changes-requested, paid, large, waiting-for-review

#7100 style: update search suggestion
  components/search/SearchSuggestion.vue
  styles/components/_search.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7117 Golfing away mixins
  components/rmrk/Gallery/GalleryCardList.vue
  package.json
  pnpm-lock.yaml
  utils/constants.ts
  utils/mixins/apiUrlMixin.ts
  utils/mixins/authMixin.ts
  utils/mixins/chainMixin.ts
  utils/mixins/infiniteScrollMixin.ts
  utils/mixins/keyboardEventsMixin.ts
  utils/mixins/metaMixin.ts
  utils/mixins/prefixMixin.ts
  utils/mixins/subscribeMixin.ts
  utils/mixins/txMixin.ts
  utils/mixins/useApiMixin.ts
Labels: large, waiting-for-review

#7111 fix: `page` not get reset after filter changes
  components/profile/activityTab/History.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7088 refactor: unify user identity fetching
  components/collection/HeroButtons.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/IdentityForm.vue
  components/identity/IdentityIndex.vue
  components/identity/utils/useIdentity.ts
  composables/useGraphql.ts
  composables/useIdentity.ts
  queries/subsquid/general/identityById.graphql
  stores/identity.ts
  utils/account.ts
  utils/constants.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#7120 [Nuxt3]
  ACTIVITY.md
  assets/styles/components/_search.scss
  components/collection/HeroButtons.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/IdentityForm.vue
  components/identity/IdentityIndex.vue
  components/identity/utils/useIdentity.ts
  components/profile/activityTab/History.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Gallery/GalleryCardList.vue
  components/search/SearchSuggestion.vue
  composables/useGraphql.ts
  composables/useIdentity.ts
  libs/static/package.json
  package.json
  pnpm-lock.yaml
  queries/subsquid/general/identityById.graphql
  stores/identity.ts
  utils/account.ts
  utils/constants.ts
  utils/ipfs.ts
  utils/mixins/apiUrlMixin.ts
  utils/mixins/authMixin.ts
  utils/mixins/infiniteScrollMixin.ts
  utils/mixins/keyboardEventsMixin.ts
  utils/mixins/metaMixin.ts
  utils/mixins/prefixMixin.ts
  utils/mixins/txMixin.ts
  utils/mixins/useApiMixin.ts
Labels: large, waiting-for-review

#7124 [Nuxt3]
  components/bsx/Collection/ChartContainer.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/Offer/OfferTable.vue
  components/collection/CollectionGrid.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/utils/useCollectionDetails.ts
  components/drops/DropCard.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/gallery/useGalleryItem.ts
  components/identity/IdentityItem.vue
  components/identity/utils/useIdentityStats.ts
  components/items/ItemsGrid/useItemsGrid.ts
  components/navbar/ProfileDropdown.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/Pagination.vue
  components/shared/modals/keyboardShortcutsModal.vue
  components/spotlight/SpotlightTable.vue
  composables/useGraphql.ts
  nuxt.config.js
  pages/settings.vue
Labels: medium, waiting-for-review

#7125 :memo: remove property decorator
  STYLE_GUIDE.md
Labels: small, waiting-for-review, docs

#6974 refactor: unify create collection
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateCollectionPage.vue
  components/create/CreateCollection.vue
  components/shared/DropUpload.vue
  components/stmn/Create/CreateCollection.vue
  composables/useApi.ts
  composables/useDeposit.ts
  composables/useTransaction.ts
  layouts/background-layout.vue
  locales/en.json
  nuxt.config.js
  package.json
  pages/_prefix/create/collection.vue
  pages/ahk/create.vue
  pages/ahp/create.vue
  pages/bsx/create.vue
  pages/create/collection.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/snek/create.vue
  playwright.config.ts
  plugins/vueHtmlSecure.ts
  pnpm-lock.yaml
  static/token/kusama_asset_hub.svg
  static/token/polkadot_asset_hub.svg
  styles/base/_typography.scss
  tests/e2e/basic.spec.ts
  utils/api/bsx/query.ts
  utils/chain.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#7058 fix: hover tooltip keep open when hovered over
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7140 🔧 CollectionInfos details
  components/carousel/utils/useCarouselSpotlight.ts
  components/collection/CollectionInfo.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/utils/types.ts
  components/collection/utils/useCollectionDetails.ts
  components/hot/HotTable.vue
  components/massmint/OnBoarding.vue
  composables/useGraphql.ts
Labels: small, waiting-for-review

#7138 feat: Add popular collections on AHK to sidebar on explore
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/constants.ts
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7099 feat: Transfer Page does not verify correct adrress format
  components/create/CreateCollection.vue
  components/shared/AddressChecker.vue
  components/shared/AddressInput.vue
  components/shared/view/InfoBox.vue
  components/transfer/Transfer.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/scss/_theme.scss
  libs/ui/src/types.ts
  locales/en.json
  nuxt.config.js
  package.json
  plugins/vueHtmlSecure.ts
  pnpm-lock.yaml
  styles/abstracts/_theme.scss
Labels: ✅ - works-for-me, large, waiting-for-review

#7152 feat: Recent NFT mints in drop page
  components/carousel/CarouselTypeLatestMints.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/utils/useCarouselEvents.ts
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableContainer.vue
  locales/en.json
  queries/subsquid/general/latestEvents.graphql
  queries/subsquid/ksm/latestEvents.graphql
Labels: ✅ - works-for-me, medium, waiting-for-review

#7112 feat: terms of use page
  app/router.scrollBehavior.js
  pages/terms-of-use.vue
  styles/layouts/_footer.scss
Labels: ✅ - works-for-me, large, waiting-for-review

#7098 feat: add privacy policy page
  pages/privacy-policy.vue
Labels: ✅ - works-for-me, large, waiting-for-review

#7156 🔧 bad id calculation
  components/stmn/Create/CreateToken.vue
  composables/transaction/mintToken/transactionMintStatemine.ts
  tests/transactionMintStatemine.spec.ts
Labels: ✅ - works-for-me, small, waiting-for-review, R-expected-for-the-next-release

#7110 fix: sorted update will cause list to flicker
  components/collection/CollectionGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7159 feat: Transak
  .env.example
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  composables/useExperiments.ts
  composables/useTransak.ts
  locales/en.json
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  styles/global.scss
Labels: large, waiting-for-review, R-expected-for-the-next-release

#7108 fix: gallery item event chart not working
  components/gallery/GalleryItemTabsPanel/GalleryItemChart.vue
  components/profile/activityTab/History.vue
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7142 fix: Collection Gallery Image low quality
  components/collection/CollectionHeader/CollectionBanner.vue
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7143 fix: GalleryItem Activity table filter interaction
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7081 fix: close notification modal after clicking a notification
  components/Navbar.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
  components/navbar/types.ts
  components/shared/ConnectWalletButton.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7147 fix: targetAddresses might be empty
  components/transfer/Transfer.vue
Labels: small, waiting-for-review

#7118 docs: updated style_guide
  STYLE_GUIDE.md
Labels: small, waiting-for-review, docs

#7150 fix: sortBy shouldn't be empty string
  components/collection/CollectionGrid.vue
Labels: 🤞 - changes-requested, ✅ - works-for-me, small, waiting-for-review

#7061 ✨ transfer loading modal on mobile
  components/shared/TransactionLoader.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7177 [Nuxt3]
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/profile/ProfileActivitySummery.vue
  components/search/Search.vue
  components/search/SearchBar.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/SidebarFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/PriceFilter.vue
  composables/useTextOverflow.ts
Labels: small, waiting-for-review

#7076 feat: mass listing
  components/common/listingCart/ListingCartItem.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/ListingCartPriceInput.vue
  components/common/shoppingCart/utils.ts
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/rmrk/service/scheme.ts
  locales/en.json
  pages/_prefix/u/_id.vue
  queries/subsquid/general/nftListWithSearch.graphql
  queries/subsquid/rmrk/nftListWithSearch.graphql
  stores/listingCart.ts
  stores/preferences.ts
  styles/global.scss
Labels: large, waiting-for-review

#7188 [Nuxt3]
  assets/styles/global.scss
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/common/listingCart/ListingCartItem.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/ListingCartPriceInput.vue
  components/common/shoppingCart/utils.ts
  components/identity/module/IdentityChain.vue
  components/identity/module/IdentityPopover.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/rmrk/service/scheme.ts
  components/shared/view/BasicPopup.vue
  locales/en.json
  pages/[prefix]/u/[id].vue
  queries/subsquid/general/nftListWithSearch.graphql
  queries/subsquid/rmrk/nftListWithSearch.graphql
  stores/listingCart.ts
  stores/preferences.ts
Labels: large, waiting-for-review

#7171 remove required prop console warnings
  components/shared/TabItem.vue
Labels: small, waiting-for-review

#7200 feat: Replace free drop with new one
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/unlockable/const.ts
  components/collection/unlockable/utils.ts
  components/drops/Drops.vue
Labels: small, waiting-for-review

#7181 🔧 DropUpload accept files
  components/shared/DropUpload.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7183 Drop down to choose which fiat on-ramp
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/shared/OnRampModal.vue
  composables/useTransak.ts
  locales/en.json
  static/onramp-providers/paybis-logo-dark.svg
  static/onramp-providers/paybis-logo.svg
  static/onramp-providers/ramp-logo-dark.svg
  static/onramp-providers/ramp-logo.svg
  static/onramp-providers/transak-logo-dark.svg
  static/onramp-providers/transak-logo.svg
  styles/global.scss
Labels: ✅ - code-lgtm, 🤞 - changes-requested, paid, medium, waiting-for-review

#7199 fix: 3D NFT Thumbnail Preview - mimeType
  libs/ui/src/components/MediaItem/MediaItem.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#7080 feat: more accessible icons
  components/collection/unlockable/UnlockableLoader.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/transfer/TransferConfirmModal.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.scss
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#7163 fix: sort button semi-hidden on mobile
  components/profile/OrderByDropdown.vue
  components/profile/ProfileDetail.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7173 🔧 carousel indicator background
  libs/ui/src/components/NeoCarousel/NeoCarousel.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7170 fix: close modal after clicking settings btn
  components/common/ConnectWallet/WalletAssetMenu.vue
  libs/ui/src/components/NeoModalExtend/plugin.js
Labels: ✅ - works-for-me, small, waiting-for-review

#7209 Conversion: Old cypress tests and data-cy attribute
  CONTRIBUTING.md
  components/Navbar.vue
  components/balance/MultipleBalances.vue
  components/carousel/CarouselTypeLatestSales.vue
  components/collection/CollectionGrid.vue
  components/collection/HeroButtons.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/drops/Drops.vue
  components/explore/ExploreSort.vue
  components/explore/ExploreTabs.vue
  components/explore/FilterMenuButton.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/generative/ContactForm.vue
  components/identity/module/IdentityPopover.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/media/type/AudioMedia.vue
  components/media/type/ImageMedia.vue
  components/media/type/ModelMedia.vue
  components/media/type/VideoMedia.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/CreateDropdown.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/NavbarExploreOptions.vue
  components/navbar/StatsDropdown.vue
  components/profile/OrderByDropdown.vue
  components/profile/ProfileDetail.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/GalleryCardList.vue
  components/rmrk/Gallery/Layout.vue
  components/search/SearchPriceRange.vue
  components/search/SearchSortDropdown.vue
  components/shared/CommonTokenMoney.vue
  components/shared/filters/modules/PriceFilter.vue
  components/shared/form/BasicSwitch.vue
  components/teleport/TeleportTabs.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/MediaItem/type/ModelMedia.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  pages/e2e-login.vue
  tests/e2e/language.spec.ts
  tests/e2e/prefix.spec.ts
  tests/e2e/redirect.spec.ts
Labels: large, waiting-for-review

#7198 revert: refactor for-loop with forEach
  utils/chart.ts
Labels: small, waiting-for-review

#7212 :wrench: speck v3
  package.json
  pnpm-lock.yaml
  utils/constants.ts
Labels: small, waiting-for-review

#7218 fix - broken explorer link in transfer
  components/shared/TransactionLoader.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#7237 Nuxt3
  components/profile/activityTab/Activity.vue
  components/shared/TransactionLoader.vue
  utils/queryPathResolver.ts
Labels: small, waiting-for-review

#7233 refactor: nuxt3 vuesocialshare update
  nuxt.config.js
  package.json
  plugins/vueSocialSharing.ts
  pnpm-lock.yaml
Labels: small, waiting-for-review

#7229 refactor: nuxt3 vueclipboard plugin
  nuxt.config.js
  package.json
  plugins/vueClipboard.ts
  pnpm-lock.yaml
Labels: small, waiting-for-review

#7204 Feat/massmint-onboarding-description
  components/blog/BlogPost.vue
  components/massmint/OnBoarding.vue
  components/massmint/OnBoardingCard.vue
  components/massmint/descriptionTabs.ts
  locales/en.json
  styles/components/_content-markdown.scss
  styles/global.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#7221 fix: Make preview picture bigger
  components/media/type/ImageMedia.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7226 fix: Some NFT's floor price feature on mass-listing cart does not work
  components/collection/utils/useCollectionDetails.ts
  components/common/listingCart/ListingCartModal.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7244 beta update
  components/blog/BlogPost.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/listingCart/ListingCartModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/massmint/OnBoarding.vue
  components/massmint/OnBoardingCard.vue
  components/massmint/descriptionTabs.ts
  components/media/type/ImageMedia.vue
  components/shared/TransactionLoader.vue
  locales/en.json
  static/cart/empty-cart-dark.png
  static/cart/empty-cart.png
  styles/components/_content-markdown.scss
  styles/global.scss
  styles/layouts/_footer.scss
Labels: beta

#7245 release update
  components/blog/BlogPost.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/listingCart/ListingCartModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/massmint/OnBoarding.vue
  components/massmint/OnBoardingCard.vue
  components/massmint/descriptionTabs.ts
  components/media/type/ImageMedia.vue
  components/shared/TransactionLoader.vue
  locales/en.json
  static/cart/empty-cart-dark.png
  static/cart/empty-cart.png
  styles/components/_content-markdown.scss
  styles/global.scss
  styles/layouts/_footer.scss
Labels: release, large

#7246 [Nuxt3]
  assets/styles/components/_content-markdown.scss
  assets/styles/global.scss
  assets/styles/layouts/_footer.scss
  components/base/BaseTokenForm.vue
  components/blog/BlogPost.vue
  components/bsx/Create/CreateToken.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/listingCart/ListingCartModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/massmint/OnBoarding.vue
  components/massmint/OnBoardingCard.vue
  components/massmint/descriptionTabs.ts
  components/media/type/ImageMedia.vue
  components/navbar/ShoppingCartButton.vue
  locales/en.json
  pnpm-lock.yaml
  public/cart/empty-cart-dark.png
  public/cart/empty-cart.png
  public/drop/unlockable-pulse.svg
  public/drop/vote-drop-avatar.webp
  public/drop/vote-drop-banner.webp
  public/onramp-providers/paybis-logo-dark.svg
  public/onramp-providers/paybis-logo.svg
  public/onramp-providers/ramp-logo-dark.svg
  public/onramp-providers/ramp-logo.svg
  public/onramp-providers/transak-logo-dark.svg
  public/onramp-providers/transak-logo.svg
Labels: A-nuxt, A-vue3, large, waiting-for-review

#7103 feat(Profile activity): Responsive visual changes
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/Pagination.vue
  components/shared/ResponsiveTable.vue
  composables/useResponsive.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7247 refactor: notification on nuxt3
  components/landing/LandingPage.vue
  composables/useProgrammatic.ts
  composables/useToast.ts
  libs/ui/src/components/NeoNotification/NeoNotificationNotice.vue
  libs/ui/src/components/NeoNotification/plugin.js
  libs/ui/src/components/NeoNotification/plugin.ts
  nuxt.config.js
  plugins/oruga-modal.ts
  plugins/oruga-notification.ts
Labels: medium, waiting-for-review

#7250 {Nuxt3}
  components/Navbar.vue
  components/carousel/CarouselTypeRelated.vue
  components/carousel/utils/useCarousel.ts
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/explore/ExploreGrid.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/landing/LandingPage.vue
  components/landing/SearchLanding.vue
  components/navbar/StatsDropdown.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/Pagination.vue
  components/shared/ResponsiveTable.vue
  components/teleport/TeleportTabs.vue
  components/transfer/DonationButton.vue
  composables/useResponsive.ts
Labels: waiting-for-review

#7251 refactor: [nuxt3] - fa icons
  components/Navbar.vue
  components/TheFooter.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/voteDrop/DropContainer.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/IdentityForm.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/explore/ExploreGrid.vue
  components/explore/FilterMenuButton.vue
  components/massmint/OnBoarding.vue
  components/navbar/MobileExpandableSection.vue
  components/rmrk/Gallery/EmotionList.vue
  components/settings/Minting.vue
  components/shared/DragDrop.vue
  components/shared/OnRampModal.vue
  components/shared/TransactionLoader.vue
  components/shared/modals/ModalWrapper.vue
  components/shared/view/InfoBox.vue
  components/transfer/DonationButton.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/components/NeoInput/NeoInput.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  libs/ui/src/components/NeoNotification/plugin.ts
  nuxt.config.js
  package.json
  plugins/icons.ts
  pnpm-lock.yaml
Labels: large, waiting-for-review

#7256 (Nuxt3)
  components/bsx/Offer/MyOffer.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/profile/ProfileActivitySummery.vue
  components/rmrk/Gallery/UserGainHistory.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  components/spotlight/SpotlightTable.vue
  composables/massmint/useMassMint.ts
  utils/config/useApollo.ts
  vue-shim.d.ts
Labels: medium, waiting-for-review

#7260 [Nuxt3] 🔧 language dropdown
  components/TheFooter.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/ProfileDropdown.vue
  components/profile/ProfileLink.vue
  components/shared/ResponsiveTable.vue
  composables/collectionActivity/useCollectionActivity.ts
  layouts/default.vue
  stores/lang.ts
  utils/config/i18n.ts
Labels: small, waiting-for-review

#7195 chore: add vitest coverage
  package.json
  pnpm-lock.yaml
  vitest.config.js
Labels: ✅ - works-for-me, small, waiting-for-review

#7261 fix: Make it possible to preview 3D NFTS prior to minting
  components/shared/DropUpload.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7258 fix: Searchbar Nft Search not working
  components/items/ItemsGrid/ItemsGrid.vue
  queries/subsquid/general/nftListWithSearch.graphql
Labels: ✅ - works-for-me, small, waiting-for-review

#7235 Fix/-massmint-not-working
  components/rmrk/Create/SimpleMint.vue
  composables/massmint/massMintHelpers.ts
  composables/massmint/useMassMint.ts
  composables/transaction/mintToken/constructMeta.ts
  services/nftStorage.ts
  utils/exponentialBackoff.ts
  utils/queueProcessor.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7265 🔧 NeoModal QRCode
  components/collection/HeroButtons.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  components/massmint/modals/DeleteModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/ReviewModal.vue
  components/profile/ProfileDetail.vue
  components/shared/OnRampModal.vue
  components/shared/QRCode.vue
  components/shared/modals/ModalWrapper.vue
  libs/ui/src/components/NeoModal/NeoModal.story.vue
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#7266 :wrench: configured waifu minter for BBW
  components/generative/promptBuilder.ts
Labels: small, waiting-for-review

#7273 ~ Nuxt3 ~
  components/CustomSubstackEmbed.vue
  components/TheFooter.vue
  components/generative/promptBuilder.ts
  components/items/ItemsGrid/ItemsGrid.vue
  components/landing/LandingPage.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/AddressInput.vue
  components/shared/Auth.vue
  components/shared/DropUpload.vue
  components/transfer/Transfer.vue
  components/transfer/TransferTokenTabs.vue
  composables/massmint/massMintHelpers.ts
  composables/massmint/useMassMint.ts
  composables/transaction/mintToken/constructMeta.ts
  composables/useIdentity.ts
  locales/en.json
  package.json
  pnpm-lock.yaml
  queries/subsquid/general/nftListWithSearch.graphql
  services/nftStorage.ts
  utils/exponentialBackoff.ts
  utils/queueProcessor.ts
  vitest.config.js
Labels: large, waiting-for-review

#7274 🔧 landing carousel
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/utils/useCarouselEvents.ts
  components/landing/LandingPage.vue
Labels: medium, waiting-for-review

#7281 - Nuxt3 -
  components/bsx/Asset/AssetList.vue
  components/bsx/Collection/ChartContainer.vue
  components/bsx/Offer/StatsOverview.vue
  components/bsx/format/TokenMoney.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/landing/LandingPage.vue
  components/landing/topCollections/utils/useTopCollections.ts
  components/shared/CommonTokenMoney.vue
  components/spotlight/SpotlightDetail.vue
  composables/useChain.ts
Labels: medium, waiting-for-review

#7284 Update ParaSpell XCM SDK
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#7290 Nuxt3
  assets/styles/components/_search.scss
  components/search/Search.vue
  components/search/SearchBar.vue
  components/search/SearchSuggestion.vue
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.vue
  package.json
  pnpm-lock.yaml
  utils/cachingStrategy.ts
Labels: medium, waiting-for-review

#7295 ~ Nuxt3 ~
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/gallery/GalleryItemPreviewer.vue
  components/massmint/modals/MintingModal.vue
  components/transfer/TransferConfirmModal.vue
  libs/static/package.json
  libs/ui/package.json
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  utils/config/pwa.ts
Labels: large, waiting-for-review

#7306 refactor: migration of nuxt route middleware
  components/carousel/utils/useCarouselSpotlight.ts
  composables/useGraphql.ts
  middleware/prefix.global.ts
  middleware/redirects.global.ts
Labels: small, waiting-for-review

#7308 🔧 useGraphql client
  components/carousel/CarouselTypeLatestMints.vue
  components/carousel/utils/useCarousel.ts
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/utils/useCollectionDetails.ts
  components/collection/voteDrop/DropContainer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/identity/utils/useIdentityStats.ts
  components/profile/activityTab/Activity.vue
  composables/collectionActivity/useCollectionActivity.ts
  composables/drop/useCheckReferenDumVote.ts
  composables/useIdentity.ts
Labels: small, waiting-for-review

#7297 Refactor seoMetaGenerator
  pages/carbonless.vue
  pages/cookie-notice.vue
  pages/e2e-login.vue
  pages/hot.vue
  pages/privacy-policy.vue
  pages/qrCode.vue
  pages/sales.vue
  pages/series-insight.vue
Labels: medium, waiting-for-review

#7309 Nuxt3
  composables/useGraphql.ts
  composables/useIdentity.ts
Labels: small, waiting-for-review

#7307 :wrench: lisbon waifu
  components/generative/promptBuilder.ts
Labels: small, waiting-for-review

#7311 🔧 Carousel landing & grphql default client
  components/carousel/utils/useCarousel.ts
  components/collection/utils/useCollectionDetails.ts
  components/gallery/useGalleryItem.ts
  components/landing/LandingPage.vue
  composables/useGraphql.ts
Labels: small, waiting-for-review

#7312 Nuxt3 final gql
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  pages/rmrk/mint.vue
  tests/cypress-deprecated/rmrk-simple-mint.cy.ts
Labels: large, waiting-for-review

#7305 Test: Gallery Item Interaction
  components/chart/PriceChart.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  playwright.config.ts
  tests/e2e/galleryitem.spec.ts
Labels: medium, waiting-for-review

#7230 feat: Change price and solo listing modal
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/multipleItemsCart/ListingCartMultipleItemsCart.vue
  components/common/listingCart/shared/ListingCartFloorPrice.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  locales/en.json
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#7286 fix: Change QR code colour
  components/collection/HeroButtons.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  components/profile/ProfileDetail.vue
  components/shared/modals/ShowQRModal.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7288 fix: Transfer does not respect token amount
  components/transfer/Transfer.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7283 fix: Mobile explorer items side scroll
  components/explore/ExploreSort.vue
  components/explore/MobileControls.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7280 fix: mimetype text/html should be image
  utils/gallery/media.ts
Labels: small, waiting-for-review

#7254 chore: adjust css deep selector
  .eslintrc.js
  components/Navbar.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  components/gallery/GalleryItemPreviewer.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/massmint/EditPanel.vue
  components/massmint/OnBoarding.vue
  components/profile/ProfileDetail.vue
  components/search/SearchResultItem.vue
  components/shared/AddressChecker.vue
  components/shared/DragDrop.vue
  components/shared/TransactionLoader.vue
  components/shared/filters/modules/PopularCollections.vue
  package.json
  pnpm-lock.yaml
  tests/floorPrice.spec.ts
  tests/shoppingActions.spec.ts
  utils/extension.ts
Labels: large, waiting-for-review

#7263 fix: Teleport Bridge: Rename Statemine to AssetHub Kusama
  components/teleport/Teleport.vue
  utils/chain.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7239 feat: Single item transfer
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/shared/AddressChecker.vue
  components/shared/AddressInput.vue
  components/shared/ModalIdentityItem.vue
  locales/en.json
Labels: ✅ - works-for-me, large, waiting-for-review

#7304 ⬆️ sub-api package
  components/transfer/Transfer.vue
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#7268 style: massmint onboard update
  components/massmint/OnBoarding.vue
  components/massmint/OnBoardingCard.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.scss
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.vue
  locales/en.json
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#7269 Feat/stack-cards
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  composables/useNft.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/types.ts
  queries/subsquid/ahk/nftListWithSearch.graphql
Labels: ✅ - works-for-me, ✅ - visual-ok, large

#7301 Refactor explore.spec.ts
  components/shared/filters/SidebarFilter.vue
  playwright.config.ts
  tests/cypress-deprecated/explore.cy.ts
  tests/e2e/explore.spec.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7289 style: mass listing selector popup
  components/common/listingCart/ListingCartMini.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  locales/en.json
  styles/global.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7278 feat: Teleport DOT between Statemint and Polkadot
  components/teleport/Teleport.vue
  composables/useChain.ts
  locales/en.json
  utils/teleport.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7331 fix: Scroll inside mass list modal
  components/common/listingCart/ListingCartModal.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#7327 style: update wallet connect modal
  components/common/ConnectWallet/ConnectWalletModal.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  styles/components/_connect-wallet.scss
Labels: small, waiting-for-review

#7344 beta update
  .github/diagram.svg
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/ListingCartModal.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/massmint/OnBoarding.vue
  components/massmint/OnBoardingCard.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  components/shared/AddressChecker.vue
  components/shared/AddressInput.vue
  components/shared/ModalIdentityItem.vue
  components/shared/filters/SidebarFilter.vue
  components/teleport/Teleport.vue
  components/transfer/Transfer.vue
  composables/useChain.ts
  composables/useNft.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.scss
  libs/ui/src/components/NeoCollapsible/NeoCollapsible.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/types.ts
  locales/en.json
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  queries/subsquid/ahk/nftListWithSearch.graphql
  styles/components/_connect-wallet.scss
  styles/global.scss
  tests/cypress-deprecated/explore.cy.ts
  tests/e2e/explore.spec.ts
  utils/teleport.ts
Labels: beta

#7330 fix: Display normal ksm unit
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7334 💄 empty shopping cart svgs
  components/common/shoppingCart/ShoppingCartModal.vue
  static/cart/empty-cart-dark.png
  static/cart/empty-cart-dark.svg
  static/cart/empty-cart.png
  static/cart/empty-cart.svg
Labels: ✅ - works-for-me, medium, waiting-for-review

#7347 fix: Listing price: I set the price 1 DOT it listed item for 100 DOTs
  components/common/listingCart/ListingCartModal.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7354 🔧 k-grey background
  components/common/listingCart/ListingCartMini.vue
  styles/global.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#7302 chore: fa sharp regular as default icon
  components/Navbar.vue
  components/TheFooter.vue
  components/base/SubmitButton.vue
  components/blog/BlogPost.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/voteDrop/DropContainer.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/IdentityForm.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/drops/TimeTag.vue
  components/explore/FilterMenuButton.vue
  components/massmint/OnBoarding.vue
  components/navbar/MobileExpandableSection.vue
  components/navbar/NotificationBoxButton.vue
  components/rmrk/Gallery/EmotionList.vue
  components/search/SearchBar.vue
  components/settings/Minting.vue
  components/shared/DragDrop.vue
  components/shared/DropUpload.vue
  components/shared/OnRampModal.vue
  components/shared/TransactionLoader.vue
  components/shared/modals/ModalWrapper.vue
  components/shared/view/InfoBox.vue
  components/transfer/DonationButton.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  libs/ui/src/components/NeoAutocomplete/NeoAutocomplete.story.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/components/NeoInput/NeoInput.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  package.json
  plugins/icons.ts
  pnpm-lock.yaml
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#7364 #7350 buy now button fix
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7372 feat: Add ToS checkbox to add funds modal
  components/shared/OnRampModal.vue
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#7368 🌍 typos in english translations
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#7257 chore: remove unused vars
  .eslintrc.js
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/unlockable/UnlockableSchedule.vue
  components/generative/GenerativeMintForm.vue
  components/generative/ImageSelectGrid.vue
  components/generative/promptBuilder.ts
  components/massmint/Massmint.vue
  components/poap/claim/ClaimForm.vue
  components/profile/ProfileActivitySummery.vue
  components/shared/ResponsiveTable.vue
  components/transfer/Transfer.vue
  composables/transaction/mintCollection/constructMeta.ts
  services/waifu.ts
  tests/cypress-deprecated/commands.ts.old
  utils/gallery/abstractCalls.ts
  utils/safePin.ts
  utils/shoppingActions.ts
  vue-i18n.d.ts
Labels: medium, waiting-for-review

#7376 Nuxt3
  .eslintrc.js
  components/bsx/Offer/MasterOfferTable.vue
  components/bsx/Offer/MyOffer.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/unlockable/UnlockableSchedule.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  components/create/CreateCollection.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/generative/GenerativeMintForm.vue
  components/generative/ImageSelectGrid.vue
  components/generative/promptBuilder.ts
  components/landing/LandingPage.vue
  components/massmint/Massmint.vue
  components/poap/claim/ClaimForm.vue
  components/profile/ProfileActivitySummery.vue
  components/profile/activityTab/HistoryRow.vue
  components/search/SearchBar.vue
  components/search/SearchSuggestion.vue
  components/shared/AddressChecker.vue
  components/shared/DropUpload.vue
  components/teleport/Teleport.vue
  components/transfer/Transfer.vue
  composables/transaction/mintCollection/constructMeta.ts
  composables/useTheme.ts
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue
  locales/en.json
  pages/[prefix]/teleport.vue
  pages/bsx/incomingOffers.vue
  services/waifu.ts
  stores/identity.ts
  tests/cypress-deprecated/commands.ts.old
  utils/chain.ts
  utils/config/chain.config.ts
  utils/config/permission.config.ts
  utils/constants.ts
  utils/gallery/abstractCalls.ts
  utils/safePin.ts
  utils/shoppingActions.ts
  vue-i18n.d.ts
Labels: large, waiting-for-review

#7349 fix: Cart confirm modal has enabled scroll
  components/common/shoppingCart/ShoppingCartModal.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7357 fix: Transfer URI link w/ usd amount after address
  components/transfer/Transfer.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7333 🔧 make listing cart state responsive to profile page filters
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/profile/ProfileDetail.vue
  stores/listingCart.ts
Labels: ✅ - works-for-me, small

#7332 🔧 clear listing store when minicart is unmounted
  components/common/listingCart/ListingCartMini.vue
  stores/listingCart.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7208 refactor: unify create page
  components/bsx/Create/RoyaltyForm.vue
  components/create/CreateCollection.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/create/CreateNftPreview.vue
  components/navbar/CreateDropdown.vue
  components/rmrk/Create/CustomAttributeInput.vue
  components/rmrk/Create/SimpleMint.vue
  components/shared/collapse/CollapseWrapper.vue
  components/shared/form/BasicNumberInput.vue
  composables/useDeposit.ts
  composables/useGraphql.ts
  layouts/background-layout.vue
  locales/en.json
  pages/_prefix/create/index.vue
  pages/_prefix/create/nft.vue
  pages/ahk/create.vue
  pages/ahp/create.vue
  pages/bsx/create.vue
  pages/create/nft.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/rmrk/mint.vue
  pages/snek/create.vue
  queries/subsquid/general/collectionByAccount.graphql
  queries/subsquid/general/nftByBlockNumber.graphql
  styles/abstracts/_theme.scss
  styles/pages/create.scss
  tests/e2e/basic.spec.ts
  utils/constants.ts
  utils/fetch.ts
  utils/ipfs.ts
  utils/notification.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#7384 Nuxt3
  assets/styles/abstracts/_theme.scss
  assets/styles/pages/create.scss
  components/bsx/Create/RoyaltyForm.vue
  components/create/CreateCollection.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/create/CreateNftPreview.vue
  components/gallery/GalleryItem.vue
  components/landing/LandingPage.vue
  components/navbar/CreateDropdown.vue
  components/rmrk/Create/CustomAttributeInput.vue
  components/search/SearchSuggestion.vue
  components/shared/collapse/CollapseWrapper.vue
  components/shared/form/BasicNumberInput.vue
  composables/useDeposit.ts
  layouts/background-layout.vue
  locales/en.json
  pages/[prefix]/create/index.vue
  pages/[prefix]/create/nft.vue
  pages/ahk/create.vue
  pages/ahp/create.vue
  pages/bsx/create.vue
  pages/create/nft.vue
  pages/index.vue
  pages/ksm/create.vue
  pages/rmrk/create.vue
  pages/snek/create.vue
  queries/subsquid/general/collectionByAccount.graphql
  queries/subsquid/general/nftByBlockNumber.graphql
  tests/e2e/basic.spec.ts
  utils/constants.ts
  utils/fetch.ts
  utils/ipfs.ts
  utils/notification.ts
Labels: large, waiting-for-review

#7367 Enable listing cart on explore items and collection pages
  components/items/ItemsGrid/ItemsGrid.vue
  composables/useListingCartConfig.ts
  layouts/explore-layout.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7365 #7337 round price
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
Labels: paid, ✅ - works-for-me, small, waiting-for-review

#7388 fix: incorrect token symbol in search suggestion
  components/rmrk/service/scheme.ts
  components/search/SearchSuggestion.vue
  components/shared/format/Money.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7275 feat: Better Visual integration for music files
  components/carousel/module/CarouselMedia.vue
  components/gallery/GalleryItem.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  composables/useNft.ts
  composables/usePlayerEventBus.ts
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
  libs/ui/src/components/NeoAudioPlayer/NeoAudioPlayer.vue
  libs/ui/src/components/NeoAudioPlayer/ProgressBar/ProgressBar.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/index.ts
  libs/ui/src/types.ts
  queries/subsquid/ksm/nftListWithSearch.graphql
  static/sound.svg
  utils/gallery/media.ts
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review

#7361 feat: clear identity
  components/common/IdentityForm.vue
  composables/useIdentity.ts
  locales/en.json
  styles/global.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#7386 Not connected wallet collection selection
  components/common/ChooseCollectionDropdown.vue
  components/create/CreateCollection.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/massmint/Massmint.vue
  composables/massmint/useMassMint.ts
  composables/transaction/types.ts
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/en.json
  tests/e2e/createcollection.spec.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7404 Nuxt3
  assets/styles/global.scss
  components/carousel/module/CarouselMedia.vue
  components/common/ChooseCollectionDropdown.vue
  components/common/IdentityForm.vue
  components/create/CreateCollection.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/massmint/Massmint.vue
  components/rmrk/service/scheme.ts
  components/search/SearchSuggestion.vue
  components/shared/format/Money.vue
  composables/massmint/useMassMint.ts
  composables/transaction/types.ts
  composables/useIdentity.ts
  composables/useListingCartConfig.ts
  composables/useNft.ts
  composables/usePlayerEventBus.ts
  layouts/explore-layout.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
  libs/ui/src/components/NeoAudioPlayer/NeoAudioPlayer.vue
  libs/ui/src/components/NeoAudioPlayer/ProgressBar/ProgressBar.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/index.ts
  libs/ui/src/types.ts
  locales/en.json
  public/sound.svg
  queries/subsquid/ksm/nftListWithSearch.graphql
  tests/e2e/createcollection.spec.ts
  utils/gallery/media.ts
Labels: large, waiting-for-review

#7390 fix: download
  utils/download.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7410 fix: blank page on localhost landing
  components/search/Search.vue
  components/search/SearchSuggestion.vue
Labels: small, waiting-for-review

#7411 fix: [nuxt3] consola as a plugin
  nuxt.config.js
  plugins/consola.ts
  vue-shim.d.ts
Labels: small, waiting-for-review

#7412 fix: [nuxt3] show content early on landing page
  components/landing/LandingPage.vue
Labels: small, waiting-for-review

#7409 fix: Rename Transfer Page Chain names
  components/transfer/Transfer.vue
Labels: small, waiting-for-review

#7408 fix: Wrong validation of polkadot address at transfer?
  components/shared/AddressChecker.vue
  locales/en.json
  utils/account.ts
Labels: small, waiting-for-review

#7413 fix: [nuxt3] qrcode and drop pages
  components/carousel/CarouselTypeLatestMints.vue
  components/collection/drop/DropContainer.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableLoader.vue
  nuxt.config.js
Labels: small, waiting-for-review

#7416 🔧 nuxt-link tag
  components/navbar/CreateDropdown.vue
  components/shared/AddressChecker.vue
  components/shared/LinkResolver.vue
  components/transfer/Transfer.vue
  locales/en.json
  utils/account.ts
Labels: small, waiting-for-review

#7420 fix:load-loop
  composables/useListInfiniteScroll.ts
Labels: small, waiting-for-review

#7421 🔧 invalid orderBy in `useSearchNfts`
  composables/useSearchNfts.ts
Labels: small, waiting-for-review

#7423 :wrench: speck prod
  utils/constants.ts
Labels: small, waiting-for-review

#7424 🔧 i18n text
  components/collection/HeroButtons.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/profile/ProfileDetail.vue
  components/transfer/Transfer.vue
Labels: small

#7422 fix: [nuxt-3] Transfer page Issues
  components/common/itemTransfer/ItemTransferModal.vue
  components/shared/AddressInput.vue
  components/transfer/Transfer.vue
Labels: small, waiting-for-review

#7392 Test: Transfer Page
  components/search/Search.vue
  components/shared/AddressChecker.vue
  components/transfer/Transfer.vue
  tests/e2e/basic.spec.ts
  tests/e2e/custom.ts
  tests/e2e/fixtures.ts
  tests/e2e/galleryitem.spec.ts
  tests/e2e/transfer.spec.ts
Labels: medium, waiting-for-review

#7426 🔧 drop page
  components/collection/drop/DropContainer.vue
  components/collection/voteDrop/DropContainer.vue
Labels: small, waiting-for-review

#7425 🚑 Speck in the prod
  utils/constants.ts
Labels: small, waiting-for-review

#7294 feat: Redesign Identity dialog
  assets/styles/global.scss
  components/common/IdentityForm.vue
  components/common/identity/IdentityConfirmModal.vue
  components/shared/PillTabs.vue
  components/shared/TransactionLoader.vue
  components/shared/format/Money.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  components/transfer/TransferTokenTabs.vue
  composables/useChain.ts
  composables/useIdentity.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoSteps/NeoSteps.vue
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.scss
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.vue
  libs/ui/src/index.ts
  libs/ui/src/types.ts
  locales/en.json
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, large, waiting-for-review
