Repository kodadot/nft-gallery, pull requests merged in 2023-10, with the labels that each got.

#7448 fix: search results floor & unit continuously loading
  components/search/SearchSuggestion.vue
Labels: small, waiting-for-review

#7455 🔧 collections sort by reactive
  components/collection/CollectionGrid.vue
  components/search/types.ts
Labels: small

#7456 🔧 gallery item collection detail popover
  components/collection/utils/useCollectionDetails.ts
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
Labels: small

#7454 fix: search NFT tab empty on preview
  components/search/SearchSuggestion.vue
  utils/cachingStrategy.ts
Labels: ✅ - code-lgtm, small

#7450 fix: create onchain identity on {0}
  components/common/IdentityForm.vue
  locales/en.json
Labels: ✅ - code-lgtm, small

#7463 toast: download error
  locales/en.json
  utils/download.ts
Labels: small, waiting-for-review

#7451 add: add top collection to sidebar on polkadothub
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/constants.ts
Labels: ✅ - code-lgtm, small

#7434 Fix--collection-activity-chart
  components/collection/activity/ActivityChart.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/utils.ts
Labels: small, waiting-for-review

#7439 style: mass list input border color
  components/common/listingCart/shared/ListingCartPriceInput.vue
  utils/constants.ts
Labels: small, waiting-for-review

#7468 fix: Remove Paybis from fiat-on ramp modal
  components/shared/OnRampModal.vue
Labels: small, waiting-for-review

#7467 fix: Put Tos and PP into footer
  components/TheFooter.vue
  locales/en.json
Labels: small, waiting-for-review

#7470 release update
  components/TheFooter.vue
  components/collection/activity/ActivityChart.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/utils.ts
  locales/en.json
Labels: release

#7476 fix: missing icon on NeoButtons
  libs/ui/src/components/NeoButton/NeoButton.vue
Labels: small, waiting-for-review

#7460 🔧 Unclickable profile dropdown (When not connected)
  components/navbar/ProfileDropdown.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7478 #7475 small portfolio btn
  components/common/ConnectWallet/WalletAssetPortfolio.vue
Labels: small, waiting-for-review

#7457 feat: going rounded - tag changes
  components/shared/gallery/NeoTag.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7486 typo fix : nftToShoppingCardItem => nftToShoppingCartItem
  components/common/shoppingCart/utils.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
Labels: small, waiting-for-review

#7485 fix: listing cart
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/ListingCartModal.vue
  stores/listingCart.ts
Labels: small, waiting-for-review

#7489 ⏩ stop fetching collection stats for every single item
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/rmrk/service/scheme.ts
  queries/subsquid/general/nftListWithSearch.graphql
  queries/subsquid/ksm/nftListWithSearch.graphql
  queries/subsquid/rmrk/nftListWithSearch.graphql
Labels: small, waiting-for-review

#7452 fix: page scroll over 3d models
  components/carousel/module/CarouselMedia.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ModelMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  nuxt.config.js
Labels: ✅ - works-for-me, small, waiting-for-review

#7435 fix: masslisting pending
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/multipleItemsCart/ListingCartMultipleItemsCart.vue
  components/common/listingCart/shared/ListingCartFloorPrice.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/hot/HotTable.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  components/shared/Loader.vue
  components/spotlight/SpotlightTable.vue
  nuxt.config.js
  stores/listingCart.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, medium, waiting-for-review

#7474 fix: double stroke on tabs
  components/profile/ProfileDetail.vue
  components/shared/TabItem.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7490 🔧 Identity Popover
  components/identity/module/IdentityPopover.vue
  components/identity/utils/useIdentityStats.ts
Labels: small, waiting-for-review

#7491 🔧 collection explore list
  components/collection/CollectionGrid.vue
Labels: small, waiting-for-review

#7493 feat: improve profile tabs item count load time
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileDetail.vue
  queries/profileStatsById.graphql
  queries/profileTabsCount.graphql
  queries/subsquid/general/profileStatsById.graphql
  queries/subsquid/general/profileTabsCount.graphql
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#7498 fix: create collection asset hub
  components/shared/DropUpload.vue
  components/shared/form/BasicSwitch.vue
  composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
  composables/transaction/mintCollection/useNewCollectionId.ts
Labels: small, waiting-for-review

#7479 fix: [nuxt-3] Gallery Item List and Transfer NFT issues
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartMultipleItemsCart.vue
  components/common/listingCart/shared/ListingCartFloorPrice.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/shared/AddressInput.vue
  components/shared/view/InfoBox.vue
  stores/listingCart.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium

#7501 fix: useGraphql
  components/carousel/utils/useCarousel.ts
  components/carousel/utils/useCarouselSpotlight.ts
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/CollectionInfo.vue
  components/collection/drop/DropContainer.vue
  components/collection/utils/useCollectionDetails.ts
  components/collection/voteDrop/DropContainer.vue
  components/create/CreateNft.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/profile/activityTab/Activity.vue
  components/rmrk/Gallery/GalleryCard.vue
  composables/useGraphql.ts
  composables/useIdentity.ts
  layouts/explore-layout.vue
Labels: medium, waiting-for-review

#7496 Revert "fix: mimetype text/html should be image"
  utils/gallery/media.ts
Labels: small, waiting-for-review

#7488 refactor: avoid glitch on switch network
  components/Navbar.vue
  pages/[prefix]/index.vue
Labels: small, waiting-for-review

#7502 fix: create nft
  components/create/CreateNft.vue
  components/shared/form/BasicNumberInput.vue
Labels: small, waiting-for-review

#7487 feat: Adding currency to transfer input
  components/transfer/Transfer.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7509 fix: gallery detail details tab
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/useGalleryItem.ts
  composables/useGraphql.ts
  plugins/safeHref.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#7513 🔧 galleryItem price
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
Labels: small, waiting-for-review

#7514 🔧 Identity stats
  components/collection/CollectionGrid.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/identity/utils/useIdentityStats.ts
  components/search/SearchSuggestion.vue
  nuxt.config.js
Labels: small, waiting-for-review

#7482 revert back to unstacked nft cards
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  composables/useNft.ts
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  queries/subsquid/ahk/nftListWithSearch.graphql
Labels: ✅ - works-for-me, medium, waiting-for-review

#7516 fix: carousel arrow
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/utils/useCarousel.ts
Labels: small, waiting-for-review

#7518 🔧 deposit row spacing
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
Labels: small

#7521 🔧 Holders activity tab
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  composables/collectionActivity/useCollectionActivity.ts
Labels: small, waiting-for-review

#6727 fix(ramp sdk): waiting for ramp network production keys
  .env.example
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/shared/OnRampModal.vue
  composables/useRamp.ts
  nuxt.config.js
  package.json
  pnpm-lock.yaml
Labels: blocked, 🤞 - changes-requested, medium, waiting-for-review

#7526 Merge main branch to nuxt
  .env.example
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/shared/OnRampModal.vue
  composables/useNft.ts
  composables/useRamp.ts
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  queries/subsquid/ahk/nftListWithSearch.graphql
  utils/gallery/media.ts
Labels: large, waiting-for-review

#7527 fix: resolve merge conflict
  components/items/ItemsGrid/useItemsGrid.ts
Labels: small, waiting-for-review

#7531 fix: offer tab on gallery item not showing offers
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#7532 fix: search on collection page
  components/search/Search.vue
  components/search/SearchBar.vue
  components/search/SearchSuggestion.vue
  components/search/utils/useCollectionSearch.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#7528 NeoDropdown issue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: small, waiting-for-review

#7536 🔧 nuxt generate seo
  nuxt.config.js
Labels: small, waiting-for-review

#7544 fix: snek/incomingoffers page is blank
  pages/snek/incomingOffers.vue
Labels: small, waiting-for-review

#7546 🔧 useSeoMeta
  components/settings/Metadata.vue
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/create/collection.vue
  pages/[prefix]/create/index.vue
  pages/[prefix]/create/nft.vue
  pages/[prefix]/drops/vote-drop.vue
  pages/[prefix]/explore/collectibles.vue
  pages/[prefix]/explore/items.vue
  pages/[prefix]/massmint/index.vue
  pages/[prefix]/massmint/onboarding.vue
  pages/[prefix]/transfer.vue
  pages/[prefix]/u/[id].vue
  pages/bsx/assets.vue
  pages/bsx/offers.vue
  pages/bsx/stats.vue
  pages/bsx/waifu.vue
  pages/create/collection.vue
  pages/create/nft.vue
  pages/settings.vue
  pages/snek/assets.vue
  pages/snek/claim.vue
  pages/snek/offers.vue
  pages/snek/stats.vue
  pages/spotlight.vue
  pages/terms-of-use.vue
Labels: large, waiting-for-review

#7549 🧹 refact page setup & remove auto imported component
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/collection/[id]/index.vue
  pages/[prefix]/detail/[id].vue
  pages/[prefix]/drops/dot-drop.vue
  pages/[prefix]/drops/free-drop.vue
  pages/[prefix]/drops/index.vue
  pages/[prefix]/gallery/[id].vue
  pages/[prefix]/index.vue
  pages/[prefix]/massmint/onboarding.vue
  pages/ahk/waifu.vue
  pages/identity.vue
  pages/index.vue
  pages/series-insight.vue
Labels: small, waiting-for-review

#7551 🔧 highest offer
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
Labels: small, waiting-for-review

#7534 fix: radio button on waifu
  components/shared/form/BasicInput.vue
  components/shared/form/RadioSelect.vue
  libs/ui/src/components/NeoRadio/NeoRadioButton.vue
Labels: small, waiting-for-review

#7524 fix: Unable to show html media
  components/media/type/IFrameMedia.vue
  libs/ui/src/components/MediaItem/type/IFrameMedia.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#7558 🔧 drops watcheffect
  components/drops/useDrops.ts
Labels: small, waiting-for-review

#7539 fix: recurring payment button on transfer not providing correct link
  components/transfer/Transfer.vue
  plugins/vueClipboard.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7555 fix: minting Settings not persistent after page refresh or navigating around the page
  components/settings/Minting.vue
  components/shared/Support.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7573 🔧 isDarkMode
  composables/useTheme.ts
Labels: small, waiting-for-review

#7574 🔧 pagination default icon pack
  libs/ui/src/components/NeoPagination/NeoPagination.vue
Labels: small, waiting-for-review

#7545 fix: offer showing as expired on incoming offers page
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7565 Netlify Deploy Button for Kodadot-app #1397
  CONTRIBUTING.md
Labels: small, waiting-for-review, docs

#7575 🔧 GalleryItem SEO
  components/gallery/GalleryItem.vue
Labels: small, waiting-for-review

#7569 feat: v4 koda logos
  components/Navbar.vue
  public/Koda_Beta.svg
  public/Koda_Beta_dark.svg
Labels: ✅ - visual-ok, small, waiting-for-review

#7577 Show html media in gallery list as static image
  assets/styles/global.scss
  components/media/MediaResolver.vue
  components/media/PreviewMediaResolver.vue
  components/media/type/AudioMedia.vue
  components/media/type/IFrameMedia.vue
  components/media/type/ImageMedia.vue
  components/media/type/JsonMedia.vue
  components/media/type/ModelMedia.vue
  components/media/type/ObjectMedia.vue
  components/media/type/UnknownMedia.vue
  components/media/type/VideoMedia.vue
  components/shared/DropUpload.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
Labels: paid, large, waiting-for-review

#7517 fix: Sometimes Audio resources are shown as images
  components/gallery/useGalleryItem.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7530 fix: dot-drop transaction data not correct
  components/collection/drop/DropContainer.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#7512 fix: Congratulations popup after buying an NFT is not availiable anymore?
  components/MessageNotify.vue
  components/buy/Buy.vue
  components/gallery/GalleryItem.vue
  components/shared/modals/ModalWrapper.vue
  composables/transaction/types.ts
  composables/useTransaction.ts
  libs/ui/src/components/NeoNotification/NeoNotification.vue
  locales/en.json
  utils/notification.ts
Labels: ✅ - works-for-me, medium, waiting-for-review

#7554 fix: changing the "Insert Address" causes an error in the target parameter
  components/bsx/Offer/MasterOfferTable.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7543 feat: Mass list add again feature
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/multipleItemsCart/ListingCartMultipleItemsCart.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  stores/listingCart.ts
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7579 fix: Chain redirect not working as expected for simple nft and collection creation
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  composables/useChainRedirect.ts
Labels: small, waiting-for-review

#7576 fix: After uploading file, UI will not let you go to the second step
  components/massmint/modals/DeleteModal.vue
  components/massmint/modals/MintingModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/ReviewModal.vue
  components/shared/DragDrop.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#7581 fix: collection search no result
  components/search/SearchSuggestion.vue
Labels: small, waiting-for-review

#7584 🐕 good boy
  libs/ui/src/components/NeoAudioPlayer/NeoAudioPlayer.vue
  libs/ui/src/components/NeoAudioPlayer/NeoWaveform.vue
Labels: small, waiting-for-review

#7585 🔧 deepscan transition
  components/common/listingCart/ListingCartMini.vue
  components/shared/DragDrop.vue
  components/shared/DropUpload.vue
  components/shared/view/BasicImage.vue
Labels: small, waiting-for-review

#7592 🔧 navbar search alignment
  assets/styles/layouts/_main-navigation.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#7567 Tests: Adding remaining tests to main branch
  components/explore/ExploreSort.vue
  components/shared/filters/modules/StatusFilter.vue
  playwright.config.ts
  tests/e2e/explore.spec.ts
  tests/e2e/footer.spec.ts
  tests/e2e/transfer.spec.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#7598 fix: Cycling trough examples not working properly on drops
  components/collection/unlockable/ImageSlider.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#7603 fix: Showing wrong number of items in collection
  queries/subsquid/general/collectionListWithSearch.graphql
Labels: ✅ - code-lgtm, small

#7606 feat: Small recent tag when connecting wallet
  assets/styles/global.scss
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/gallery/NeoTag.vue
  locales/en.json
  stores/wallet.ts
  utils/datetime.ts
Labels: medium, waiting-for-review

#7617 🔧 Identity NuxtLink
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/identity/IdentityItem.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7618 fix: dark mode style issue
  composables/useTheme.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7570 Programatic drops
  components/Navbar.vue
  components/collection/drop/DropContainer.vue
  components/collection/drop/TokenImportButton.vue
  components/collection/drop/const.ts
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/const.ts
  components/collection/voteDrop/DropContainer.vue
  components/collection/voteDrop/const.ts
  components/drops/DropCard.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/drop/useCheckReferenDumVote.ts
  content/blog/kodadot's-drop-page-explained.md
  layouts/unlockable-mint-layout.vue
  locales/en.json
  middleware/redirects.global.ts
  pages/[prefix]/drops/[id].vue
  pages/[prefix]/drops/dot-drop.vue
  pages/[prefix]/drops/free-drop.vue
  pages/[prefix]/drops/vote-drop.vue
  params/types.ts
  queries/referendumVoteByAccount.graphql
  services/waifu.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, large, waiting-for-review

#7601 fix: User is able to trigger a NFT creation transaction without selecting a collection
  components/common/ChooseCollectionDropdown.vue
  components/create/CreateNft.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#7627 🔧 NeoTooltip color
  assets/styles/components/_gallery-item.scss
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoTabs/NeoTabs.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7635 fix: reactive network fee on create nft
  components/create/Confirm/MintConfirmModal.vue
  composables/useDeposit.ts
Labels: small, waiting-for-review

#7620 fix: Some images not loading properly on Kusama
  utils/gallery/media.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7633 fix: Cards are missing collection
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7653 Owner-composable
  components/collection/HeroButtons.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/gallery/UnlockableTag.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  composables/useAuth.ts
  utils/account.ts
Labels: small, waiting-for-review

#7636 🔧 transfer assetHub
  composables/transaction/transactionSend.ts
Labels: small, waiting-for-review

#7666 fix: Wrong USD denomination on gallery item
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  utils/format/balance.ts
Labels: small, waiting-for-review

#7661 fix: Navbar mobile
  assets/styles/layouts/_main-navigation.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7659 fix: gap on infinite scroll
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  composables/useListInfiniteScroll.ts
  composables/useNft.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7658 fix: collection name card truncation
  components/carousel/module/CarouselInfo.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7619 #7507 full screen button
  components/gallery/GalleryItemPreviewer.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7547 feat: add append to body option to NeoModal
  components/common/listingCart/ListingCartModal.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/components/NeoModal/NeoModal.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#7657 fix: Hover card styling and popup area
  assets/styles/global.scss
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/identity/module/IdentityPopoverFooter.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7634 fix: More friendly errors for drops page
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/voteDrop/DropContainer.vue
  composables/drop/useCheckReferenDumVote.ts
  locales/en.json
  queries/referendumVoteByAccount.graphql
Labels: ✅ - works-for-me, small, waiting-for-review

#7648 fix: User profile tabs infinite scroll not working as expected
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7621 fix: Scroll to end when wallet disconnect
  libs/ui/src/components/NeoModalExtend/plugin.ts
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7669 fix: Explorer audio NFTs stopped playing on hover
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7646 refactor: seo title & description asset hub
  layouts/explore-layout.vue
  locales/en.json
  pages/[prefix]/explore/collectibles.vue
  pages/[prefix]/explore/items.vue
  utils/seo.ts
Labels: 🤞 - changes-requested, paid, small, waiting-for-review

#7690 🔧 seo blog pages
  nuxt.config.js
Labels: ✅ - code-lgtm, medium, waiting-for-review

#7656 feat: UI migrate - home page
  assets/styles/global.scss
  components/migrate/MigrateIndex.vue
  components/migrate/MigrateIndex/MigrateContent.vue
  components/migrate/MigrateIndex/MigrateHeader.vue
  components/migrate/MigrateIndex/MigrateHeaderFaq.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/scss/_theme.scss
  locales/en.json
  pages/migrate/index.vue
  plugins/vueHtmlSecure.ts
  public/migrate/arrow.svg
  public/migrate/state-ready.svg
  public/migrate/state-waiting.svg
  public/migrate/title-arrow.svg
Labels: 🤞 - changes-requested, ✅ - visual-ok, large, waiting-for-review

#7691 fix: Seems popular collections are gone
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/usePopularCollections.ts
  composables/popularCollections/constants.ts
  composables/popularCollections/usePopularCollections.ts
Labels: 🤞 - changes-requested, medium, waiting-for-review

#7687 fix: Zero balance on transfer when address has DOTs
  components/transfer/Transfer.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7660 fix: Visual things in modals
  assets/styles/global.scss
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/identity/IdentityItem.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7667 #7664 jumping issue fix
  assets/styles/layouts/_main-navigation.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#7694 fix: Rounding in Tranfer (change decimals)
  components/transfer/Transfer.vue
  utils/format/balance.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#7697 🐛 broken explorer link
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoNftCard/types.ts
Labels: small, waiting-for-review

#7700 enable filtering by collections
  components/items/ItemsGrid/useItemsGrid.ts
  queries/subsquid/general/tokenListWithSearch.graphql
Labels: small, waiting-for-review

#7712 beta update
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/identity/IdentityItem.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/migrate/MigrateIndex.vue
  components/migrate/MigrateIndex/MigrateContent.vue
  components/migrate/MigrateIndex/MigrateHeader.vue
  components/migrate/MigrateIndex/MigrateHeaderFaq.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/usePopularCollections.ts
  components/transfer/Transfer.vue
  composables/popularCollections/constants.ts
  composables/popularCollections/usePopularCollections.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoNftCard/types.ts
  libs/ui/src/scss/_theme.scss
  locales/en.json
  nuxt.config.js
  pages/migrate/index.vue
  plugins/vueHtmlSecure.ts
  pnpm-lock.yaml
  public/migrate/arrow.svg
  public/migrate/state-ready.svg
  public/migrate/state-waiting.svg
  public/migrate/title-arrow.svg
  queries/subsquid/general/tokenListWithSearch.graphql
  utils/format/balance.ts
Labels: large, waiting-for-review, beta

#7713 release update
  assets/styles/global.scss
  assets/styles/layouts/_main-navigation.scss
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/identity/IdentityItem.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/migrate/MigrateIndex.vue
  components/migrate/MigrateIndex/MigrateContent.vue
  components/migrate/MigrateIndex/MigrateHeader.vue
  components/migrate/MigrateIndex/MigrateHeaderFaq.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/usePopularCollections.ts
  components/transfer/Transfer.vue
  composables/popularCollections/constants.ts
  composables/popularCollections/usePopularCollections.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoNftCard/types.ts
  libs/ui/src/scss/_theme.scss
  locales/en.json
  nuxt.config.js
  pages/migrate/index.vue
  plugins/vueHtmlSecure.ts
  pnpm-lock.yaml
  public/migrate/arrow.svg
  public/migrate/state-ready.svg
  public/migrate/state-waiting.svg
  public/migrate/title-arrow.svg
  queries/subsquid/general/tokenListWithSearch.graphql
  utils/format/balance.ts
Labels: release

#7701 🔧 libs/ui errors & warning
  libs/ui/package.json
  libs/ui/src/components/MediaItem/MediaItem.story.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/AudioMedia.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  libs/ui/src/components/NeoAudioPlayer/NeoAudioPlayer.vue
  libs/ui/src/components/NeoAudioPlayer/NeoWaveform.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.story.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.story.vue
  libs/ui/src/components/NeoModal/NeoModal.vue
  libs/ui/src/components/NeoModalHead/NeoModalHead.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NFTMediaInfoStacked.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  libs/ui/src/components/NeoSteps/NeoSteps.vue
  libs/ui/src/components/NeoStickyModal/NeoStickyModal.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#7720 fix: make sidebar icons size medium
  components/common/ConnectWallet/WalletAssetMenu.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok, small

#7721 Tests: More tests and some tweaks
  components/CookieBanner.vue
  components/Navbar.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/identity/module/IdentityPopover.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
  components/profile/activityTab/History.vue
  tests/e2e/basic.spec.ts
  tests/e2e/custom.ts
  tests/e2e/footer.spec.ts
  tests/e2e/language.spec.ts
  tests/e2e/prefix.spec.ts
  tests/e2e/profile.spec.ts
  tests/e2e/settings.spec.ts
  tests/e2e/sidebar.spec.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#7714 fix: Alignment of cards in explorer
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
Labels: ✅ - works-for-me, small, waiting-for-review

#7704 fix: vuetippy hover card updates
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/identity/module/IdentityPopover.vue
  components/shared/view/BasicPopup.vue
  plugins/vueTippy.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7728 fix: Remove collection from smallest grid size card
  libs/ui/src/components/NeoNftCard/NFTMediaInfo.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#7710 enable search on token entities
  components/items/ItemsGrid/useItemsGrid.ts
  queries/subsquid/general/tokenListWithSearch.graphql
Labels: small, waiting-for-review

#7622 feat: Email Signup banner
  components/landing/LandingPage.vue
  components/landing/SignupBanner.vue
  locales/en.json
  public/signup-voucher-blur.svg
  public/signup-voucher-dark.svg
  public/signup-voucher.svg
  stores/preferences.ts
  utils/constants.ts
  utils/newsletter.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review

#7749 ⬆️ nuxt version
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review, A-maintenance

#7723 🔧 round 2 collection card number
  components/collection/CollectionDetail.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7699 #7389 dropdown remove
  components/create/CreateLanding.vue
  components/navbar/CreateDropdown.vue
  locales/en.json
  public/waifu-dark.svg
  public/waifu.svg
Labels: ✅ - works-for-me, large, waiting-for-review

#7747 fix: reduce video payload
  components/carousel/CarouselTypeRelated.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
  utils/gallery/media.ts
Labels: small, waiting-for-review

#7755 Revert "⬆️ nuxt version"
  package.json
  pnpm-lock.yaml
Labels: large

#7756 Revert "⬆️ nuxt version" - pushing to production
  package.json
  pnpm-lock.yaml
Labels: release

#7757 Revert "⬆️ nuxt version" - pushing to beta
  package.json
  pnpm-lock.yaml
Labels: beta

#7758 ⬆️ nuxt version
  nuxt.config.ts
Labels: small, waiting-for-review

#7764 pnpm update nuxt
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#7772 fix: cart action button
  components/common/listingCart/ListingCartModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/landing/SignupBanner.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: small, waiting-for-review

#7763 fix: sort is not always an array
  composables/useChainRedirect.ts
Labels: small, waiting-for-review

#7765 Update ParaSpell XCM SDK to -> v3.0.1
  components/teleport/Teleport.vue
  package.json
  pnpm-lock.yaml
  utils/teleport.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#7702 🔧 libs/ui CI build on push
  .github/workflows/build.libs-ui.yml
  libs/ui/__mocks__/model-viewer.js
  libs/ui/histoire.config.ts
  libs/ui/package.json
  libs/ui/src/components/MediaItem/type/ModelMedia.vue
  nuxt.config.ts
  pnpm-lock.yaml
Labels: large, waiting-for-review

#7797 🔧 default carbonless false
  stores/preferences.ts
Labels: small, waiting-for-review

#7800 🔧 create nft min price 0.01
  components/create/CreateNft.vue
Labels: small, waiting-for-review

#7803 fix:Remove discord, substack and add beehiiv, linkedin in footer
  components/TheFooter.vue
Labels: small, waiting-for-review

#7806 Nuxt-speedkit try two
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#7785 fix: stalled request on chrome
  utils/gallery/media.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#7796 🔧 dropcard skeleton
  components/drops/DropCard.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#7767 fix: fullscreen button not working for videos
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemPreviewer.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7804 Test: Footer link change and flakiness
  tests/e2e/footer.spec.ts
Labels: small, waiting-for-review

#7815 🐛 lastIndexUsed
  composables/massmint/useMassMint.ts
Labels: small, waiting-for-review

#7748 #7746 toggle changes
  libs/ui/src/components/NeoSwitch/NeoSwitch.scss
  libs/ui/src/scss/_theme.scss
Labels: paid, ✅ - works-for-me, small

#7813 fix: Change polkadothub (beta) on cards to ahp
  components/carousel/module/CarouselInfo.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#7783 #7762 tags
  components/landing/SignupBanner.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me, small, waiting-for-review

#7782 #7760 hide advanced
  components/shared/filters/MobileFilter.vue
  components/shared/filters/SidebarFilter.vue
Labels: paid, ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7812 fix: Holders at collection view doesnot have data
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#7732 feat: ui only for migrate (review, signing, congrats)
  assets/styles/global.scss
  components/migrate/MigrateIndex/MigrateContent.vue
  components/migrate/MigrateIndex/MigrateHeader.vue
  components/migrate/MigrateModal.vue
  components/migrate/MigrateReviewSign.vue
  components/migrate/MigrateReviewSign/MigrateReview.vue
  components/migrate/MigrateReviewSign/MigrateSign.vue
  components/migrate/migrate.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
  pages/migrate/congrats.vue
  pages/migrate/index.vue
  pages/migrate/review.vue
  pages/migrate/sign.vue
  public/migrate/congrats-dark.svg
  public/migrate/congrats.svg
Labels: ✅ - works-for-me, large, waiting-for-review

#7771 🔧 nft create form
  components/bsx/Create/RoyaltyForm.vue
  components/create/CreateNft.vue
  components/rmrk/Create/CustomAttributeInput.vue
  composables/useIsChain.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#7768 feat: hidden sidebar text on mobile
  components/common/ConnectWallet/WalletAssetMenu.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#7827 fix: Clearing identity: Change message
  components/common/IdentityForm.vue
  locales/en.json
Labels: ✅ - works-for-me, small, waiting-for-review

#7830 fix: wrong typeface on create page
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
Labels: ✅ - code-lgtm, small, waiting-for-review
