Repository kodadot/nft-gallery, pull requests merged in 2023-04, with the labels that each got.

#5413 #4918 cookie banner
  components/CookieBanner.vue
  locales/en.json
  styles/components/_toast.scss
  styles/global.scss
Labels: ✅ - visual-ok

#5475 feat: sort holders by the most owned NFTs in activity
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
Labels: ✅ - visual-ok

#5449 feat: sorting by price on collection items page
  components/explore/ExploreSort.vue
Labels: ✅ - visual-ok

#5492 ✨ explore items scrollTopButton
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - works-for-me, ✅ - visual-ok

#5473 fix: collection on mobile is broken
  components/collection/CollectionInfo.vue
Labels: paid, ✅ - works-for-me, ✅ - visual-ok

#5503 #5499 Playing with stepsize on chart
  components/chart/PriceChart.vue
Labels: ✅ - visual-ok

#5429 fix: Infinity scroll is slow
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  composables/useListInfiniteScroll.ts
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - works-for-me

#5463 🔧 in activity chart - fix case where not enough data for binning
  components/collection/activity/events/Events.vue
  components/collection/activity/utils.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5518 fix: collection description/info not refresh after search
  components/collection/CollectionInfo.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5529 fix: collection activity event row
  components/collection/activity/events/eventRow/EventRowTablet.vue
Labels: ✅ - visual-ok

#5533 fix: Time travel in charts
  components/chart/PriceChart.vue
Labels: small, waiting-for-review

#5534 fix: Stats: HOT - grammar mistake
  locales/en.json
Labels: small, waiting-for-review

#5519 fix: Wrong currency in collection detail
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#5514 feat: better markdown support
  CONTRIBUTING.md
  components/collection/CollectionInfo.vue
  components/gallery/GalleryItemDescription.vue
  components/massmint/OnBoarding.vue
  components/shared/Markdown.vue
  components/shared/collapse/DescriptionWrapper.vue
  components/unique/Collection/Item/CollectionItem.vue
  pages/contribute.vue
  pages/first-time.vue
  styles/components/_content-markdown.scss
  styles/index.scss
  utils/highlight.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium

#5484 refactor: rename rmrk2 to ksm
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  middleware/prefix.ts
  utils/chain.ts
  utils/config/chain.config.ts
Labels: small

#5472 #5450 adding explore options
  components/navbar/NavbarExploreOptions.vue
  styles/layouts/_main-navigation.scss
  utils/chain.ts
  utils/constants.ts
Labels: 🤞 - changes-requested, paid, ✅ - visual-ok, small

#5438 #5435 add rmrk label
  components/carousel/module/CarouselInfo.vue
  libs/static/src/names.ts
  libs/static/src/types.ts
Labels: paid, small, waiting-for-review

#5541 :ambulance: do not kill burn on unknown offer
  composables/transaction/transactionBurn.ts
Labels: small, waiting-for-review

#5561 #5435 rmrk label
  libs/static/src/names.ts
Labels: 🤞 - changes-requested, small, waiting-for-review

#5442 feat: notification box
  components/Navbar.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/NotificationBox/NotificationItem.vue
  components/common/NotificationBox/types.ts
  components/common/NotificationBox/useNotification.ts
  components/common/NotificationBox/useNotificationBox.ts
  components/navbar/NotificationBoxButton.vue
  locales/en.json
  queries/subsquid/general/collectionByAccount.graphql
  queries/subsquid/general/notificationsByAccount.graphql
  styles/abstracts/_variables.scss
  styles/global.scss
  utils/format/time.ts
Labels: paid, large, waiting-for-review

#5546 feat: float filter button on mobile collection activity page
  components/collection/activity/FilterFloatButton.vue
  components/explore/ExploreTabs.vue
  components/explore/FilterMenuButton.vue
  components/explore/MobileControls.vue
  components/shared/BreadcrumbsFilter.vue
  composables/useActiveRouterFilters.ts
Labels: ✅ - visual-ok, medium, waiting-for-review

#5563 #4452 neo modal
  components/collection/HeroButtons.vue
  libs/ui/src/components/NeoModal/NeoModa.story.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/components/NeoModal/NeoModal.vue
  libs/ui/src/index.ts
Labels: paid, small, waiting-for-review

#5589 fix: Switch chain to rmrk2 on rmrk2.kodadot.xyz
  middleware/prefix.ts
Labels: small, waiting-for-review

#5591 fix: Add whitelist for rmrk2.kodadot.xyz
  components/common/ConnectWallet/ConnectWalletModal.vue
  utils/config/whitelist.ts
Labels: small, waiting-for-review

#5564 feat: make only 2 filters active by default
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5570 #5560 update footer links
  components/TheFooter.vue
  locales/en.json
Labels: ✅ - visual-ok, small, waiting-for-review

#5571 #5539 button up fix
  components/shared/ScrollTopButton.vue
  styles/components/_scroll-to-top-button.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#5558 fix: Copy link should be on the item page
  components/collection/HeroButtons.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5557 fix: Menu on mobile broken
  components/Navbar.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5559 fix: Line in the middle after opening wallet dialog
  components/common/ConnectWallet/useConnectWallet.ts
  components/gallery/GalleryItemPreviewer.vue
Labels: paid, ✅ - visual-ok, small, waiting-for-review

#5569 #5548 empty state
  components/collection/activity/events/Events.vue
  locales/en.json
Labels: small, waiting-for-review

#5602 5535 final prefix
  components/carousel/utils/useCarousel.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/gallery/useGalleryItem.ts
  components/identity/module/IdentityLink.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/LandingPage.vue
  components/massmint/useMassMint.ts
  components/navbar/NavbarExploreOptions.vue
  components/navbar/ProfileDropdown.vue
  components/navbar/StatsDropdown.vue
  composables/collectionActivity/helpers.ts
  composables/transaction/mintCollection/constructMeta.ts
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/transactionList.ts
  composables/transaction/transactionMintCollection.ts
  composables/transaction/transactionMintToken.ts
  composables/transaction/transactionSend.ts
  composables/useChain.ts
  composables/useNft.ts
  libs/static/src/chains.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
  middleware/prefix.ts
  package.json
  pages/rmrk2/index.vue
  pages/series-insight.vue
  pnpm-lock.yaml
  queries/subsquid/ksm/collectionEntityById.graphql
  queries/subsquid/ksm/nftById.graphql
  queries/subsquid/ksm/nftListWithSearch.graphql
  utils/api/bsx/query.ts
  utils/config/chain.config.ts
  utils/config/defineApolloConfig.ts
  utils/config/types.ts
  utils/prefix.ts
  utils/queryPathResolver.ts
Labels: ✅ - code-lgtm, large, waiting-for-review

#5613 fix: get images on explorer collectibles for ksm
  components/collection/CollectionCard.vue
  components/rmrk/service/scheme.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#5594 fix: set prefix to localStorage
  components/navbar/ChainSelectDropdown.vue
  components/navbar/NavbarExploreOptions.vue
  composables/usePrefix.ts
  libs/static/src/chains.ts
  middleware/prefix.ts
  pages/_prefix/explore/index.vue
  plugins/vuex-persist.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#5609 🔥 remove creative minting
  components/navbar/CreateDropdown.vue
  components/rmrk/Create/CreativeMint.vue
  pages/rmrk/creative.vue
  tests/cypress/support/commands.ts
Labels: large, waiting-for-review

#5608 ⚡️ Activity: lazy load owner insights
  components/collection/activity/OwnerInsights.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
Labels: ✅ - works-for-me, medium, waiting-for-review

#5610 🔧 identityForm inputs length
  components/common/IdentityForm.vue
Labels: small, waiting-for-review

#5607 🐛 flippers all showing same
  composables/collectionActivity/helpers.ts
Labels: paid, small, waiting-for-review

#5604 fix: Remove appending ?page=1
  components/explore/ExploreChain.vue
  components/explore/ExploreSort.vue
  components/search/Search.vue
  components/search/SearchSuggestion.vue
  composables/useListInfiniteScroll.ts
  composables/useReplaceUrl.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#5601 fix: no margin bottom on collection items
  components/items/ItemsGrid/ItemsGrid.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok, small, waiting-for-review

#5598 fix: redirection when listed=true
  components/search/Search.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#5620 fix: Show rmrk2 on landing - beta.kodadot.xyz
  components/carousel/utils/useCarousel.ts
Labels: small, waiting-for-review

#5621 feat: larger height of gallery tab item container on mobile
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5631 ⚠️⚠️⚠️⚠️ UPGRADED MINIMARK TO LATEST VERSION ⚠️⚠️⚠️⚠️
  components/accounts/utils.ts
  components/bsx/Asset/AssetTable.vue
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/bsx/Offer/OfferTable.vue
  components/bsx/Offer/OffersUserTable.vue
  components/collection/activity/Activity.vue
  components/collection/activity/ActivityChart.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/common.ts
  components/common/NotificationBox/useNotification.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/generative/promptBuilder.ts
  components/rmrk/Create/Admin/AdminPanel.vue
  components/rmrk/Create/AttributeTagInput.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/SimpleMint.vue
  components/rmrk/Gallery/Appreciation.vue
  components/rmrk/Gallery/Flipper.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/service/NftUtils.ts
  components/rmrk/service/scheme.ts
  components/rmrk/service/types.ts
  components/rmrk/types.ts
  components/rmrk/utils.ts
  components/shared/gallery/Properties.vue
  composables/collectionActivity/helpers.ts
  composables/collectionActivity/types.ts
  composables/transaction/mintCollection/constructMeta.ts
  composables/transaction/mintCollection/transactionMintCollectionRmrk.ts
  composables/transaction/mintToken/constructMeta.ts
  composables/transaction/mintToken/transactionMintRmrk.ts
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/transactionList.ts
  composables/transaction/transactionSend.ts
  composables/transaction/types.ts
  composables/useRmrkVersion.ts
  composables/useTransaction.ts
  nuxt.config.js
  package.json
  pages/transfer.vue
  pnpm-lock.yaml
  services/nftStorage.ts
  store/assets.ts
  utils/cachingStrategy.ts
  utils/format/balance.ts
  utils/historyEvent.ts
  utils/mintUtils.ts
  utils/proxy.ts
  utils/shoppingActions.ts
Labels: large, waiting-for-review

#5648 fix: empty `to` in SEND event
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
Labels: small, waiting-for-review

#5640 empty flippers tip
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  locales/en.json
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#5651 fix: carousel landing page beta
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/utils/useCarousel.ts
  utils/chain.ts
  utils/constants.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5653 fix: Overflow content on tag input while minting nft
  styles/global.scss
Labels: small, waiting-for-review

#5649 feat: removing the extra padding above the first event on mobile
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5632 fix: Transfer doing weird thing
  composables/usePrefix.ts
Labels: small, waiting-for-review

#5641 🚸 keep real flippers only
  composables/collectionActivity/helpers.ts
Labels: small, waiting-for-review

#5668 🔧 gtag plugin
  components/CookieBanner.vue
  package.json
  plugins/vue-gtag.client.ts
  pnpm-lock.yaml
Labels: large, waiting-for-review

#5642 ✨ update sorting options
  components/explore/ExploreSort.vue
  locales/en.json
  locales/fr.json
  utils/constants.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5562 #5531 toggle issue fix
  components/navbar/ProfileDropdown.vue
  components/shared/ConnectWalletButton.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#5661 🔧 windows workflow
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  README.md
  libs/ui/src/components/NeoModal/NeoModal.story.vue
Labels: small, waiting-for-review

#5630 hotfix: enable minting on rmrk2
  components/navbar/CreateDropdown.vue
  components/rmrk/Create/CreateCollection.vue
  composables/transaction/mintToken/transactionMintRmrk.ts
  package.json
  pages/ksm/create.vue
  pnpm-lock.yaml
  utils/config/permision.config.ts
  utils/mixins/rmrkVersionMixin.ts
Labels: blocked, small, waiting-for-review

#5643 Extend-bulma-spacing-helpers
  components/bsx/Create/CreateCollectionPage.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/Activity.vue
  components/collection/activity/events/Events.vue
  components/common/FrequentlyAsked.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/NotificationBox/NotificationItem.vue
  components/gallery/GalleryItem.vue
  components/landing/LandingPage.vue
  components/massmint/Massmint.vue
  components/massmint/OnBoarding.vue
  components/rmrk/Create/Create.vue
  components/shared/chart/BoxPlot/Container.vue
  components/shared/upload/DropUpload.vue
  layouts/default.vue
  layouts/explore-layout.vue
  pages/_prefix/massmint/onboarding.vue
  pages/qrCode.vue
  pages/tutorials.vue
  styles/abstracts/_variables.scss
Labels: ✅ - code-lgtm, medium, waiting-for-review

#5685 Sorting KSM chains
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#5691 feat: Show rmrk version in item description
  components/gallery/GalleryItemDescription.vue
  locales/en.json
Labels: small, waiting-for-review

#5675 fix: tab alignment
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#5674 fix: not showing royalties in gallery detail
  queries/subsquid/ksm/nftById.graphql
Labels: ✅ - code-lgtm, ✅ - visual-ok, small, waiting-for-review

#5695 fix: default title seo.
  nuxt.config.js
Labels: small, waiting-for-review

#5693 fix: opening sidebar resets scroll position
  components/common/ConnectWallet/useConnectWallet.ts
  components/common/NotificationBox/useNotificationBox.ts
  styles/components/_modal.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#5708 :arrow_up: update @polkadot & @kodadot packages
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#5711 Cards change
  libs/ui/src/components/CardArticle/CardArticle.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/scss/_theme.scss
  styles/abstracts/_theme.scss
  styles/components/_carousel.scss
  styles/components/_collection-card.scss
  styles/components/_top-collections.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok, small, waiting-for-review

#5718 Royalty paying for RMRK2
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/rmrk/service/scheme.ts
  composables/transaction/transactionBuy.ts
  composables/transaction/types.ts
  queries/subsquid/ksm/nftById.graphql
  utils/support.ts
Labels: ✅ - code-lgtm, small, waiting-for-review

#5703 Properties and Royalties for KSM
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/CustomAttributeInput.vue
  components/shared/collapse/CollapseWrapper.vue
  composables/transaction/mintToken/transactionMintRmrk.ts
  pnpm-lock.yaml
  utils/mixins/rmrkVersionMixin.ts
Labels: ✅ - code-lgtm, medium, waiting-for-review

#5644 🔧 MediaItem placeholder prop
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  components/common/NotificationBox/NotificationItem.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemPreviewer.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/media/MediaResolver.vue
  components/shared/gallery/NftCard.vue
  components/shared/view/BasicImage.vue
  composables/useTheme.ts
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - code-lgtm, small, waiting-for-review

#5654 feat: popular collections
  components/items/ItemsGrid/useItemsGrid.ts
  components/items/ItemsGrid/utils/useSearchParams.ts
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/MobileFilter.vue
  components/shared/filters/SidebarFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/constants.ts
  components/shared/filters/modules/usePopularCollections.ts
  composables/useActiveRouterFilters.ts
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
  libs/ui/src/components/NeoSidebar/NeoSidebar.scss
  queries/subsquid/general/collectionByIds.graphql
  stores/exploreFilters.ts
  utils/queryParams.ts
Labels: ✅ - code-lgtm, ✅ - visual-ok, large, waiting-for-review

#5723 feat: display collection profile in search result
  components/search/SearchResultItem.vue
  components/search/SearchSuggestion.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#5724 fix: remove background pointer events
  styles/components/_search.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#5720 fix: External link modal
  components/redirect/useRedirectModal.ts
Labels: ✅ - works-for-me, ✅ - visual-ok, small, waiting-for-review

#5741 fix: balance issue
  nuxt.config.js
  plugins/userBalance.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#5719 feat: update links in footer
  components/TheFooter.vue
Labels: small, waiting-for-review

#5701 Feature/massmint upload media zip
  components/massmint/ChooseCollectionDropdown.vue
  components/massmint/Massmint.vue
  components/massmint/OverviewTable.vue
  components/massmint/UploadPicture/UploadPicture.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadCompressedMedia/useZipValidator.ts
  components/massmint/uploadDescription/UploadDescription.vue
  components/shared/DragDrop.vue
  components/shared/upload/DropUpload.vue
  libs/ui/src/components/NeoCollapse/NeoCollapse.scss
  libs/ui/src/components/NeoCollapse/NeoCollapse.vue
  locales/en.json
  package.json
  pnpm-lock.yaml
  styles/global.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok, large, waiting-for-review

#5742 fix: Loading preview for NFTs in search doesnt work
  components/search/SearchSuggestion.vue
Labels: paid, small, waiting-for-review

#5758 fix: rmrk2.kodadot.xyz redirect url
  composables/usePrefix.ts
  middleware/prefix.ts
Labels: paid, small, waiting-for-review

#5768 fix: No tooltip displayed on buy button
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
Labels: ✅ - visual-ok, small, waiting-for-review

#5710 #5697 Clickable nft in holders/flipper tab
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#5760 fix: Sometimes items doesnt load in collections activity
  components/collection/activity/events/eventRow/EventRowAvatar.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
Labels: small, waiting-for-review

#5761 fix: Searchbar see all arrow on NFT tab
  components/search/SearchSuggestion.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#5752 fix: don't display modal when download
  components/gallery/GalleryItemDescription.vue
  components/shared/collapse/DescriptionWrapper.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#5767 fix: setting persist storage
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  nuxt.config.js
  package.json
  plugins/piniaPersistedState.ts
  pnpm-lock.yaml
  stores/preferences.ts
Labels: ✅ - visual-ok, small, waiting-for-review

#5748 fix(ui): gallery item action display tablet & mobile width
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
Labels: small, waiting-for-review

#5783 🔧 hide nsfw collection
  utils/constants.ts
Labels: small, waiting-for-review

#5793 beta update
  components/explore/ExploreChain.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/constants.ts
  components/shared/filters/modules/usePopularCollections.ts
  locales/en.json
Labels: beta

#5735 feat: Add parent tab to GalleryItemDescription
  components/gallery/GalleryItemDescription.vue
  components/gallery/useGalleryItem.ts
  components/rmrk/service/scheme.ts
  locales/en.json
  queries/subsquid/ksm/nftById.graphql
  queries/subsquid/rmrk/nftById.graphql
  styles/components/_gallery-item.scss
Labels: ✅ - code-lgtm, small, waiting-for-review

#5798 fix: Minting visual bugs
  styles/global.scss
Labels: small, waiting-for-review

#5778 #5757 search empty text
  components/search/SearchSuggestion.vue
  locales/en.json
Labels: ✅ - code-lgtm, small, waiting-for-review

#5809 :bug: parent not present on rmrk
  queries/subsquid/rmrk/nftById.graphql
Labels: small, waiting-for-review

#5815 Update CODEOWNERS
  .github/CODEOWNERS
Labels: small, waiting-for-review

#5818 ➖ remove unused dependency
  package.json
  pnpm-lock.yaml
  utils/cachingStrategy.ts
Labels: ✅ - code-lgtm, large, waiting-for-review

#5801 fix: Activity event improvements
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/EventRowAvatar.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.scss
  libs/ui/src/components/NeoAvatar/NeoAvatar.story.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, ✅ - visual-ok, medium, waiting-for-review

#5822 refactor: NeoSkeleton component
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/hot/HotTable.vue
  components/landing/topCollections/TopCollections.vue
  components/rmrk/Gallery/Item/Name.vue
  components/sales/SalesTable.vue
  components/search/SearchResultItem.vue
  components/series/SeriesTable.vue
  components/shared/gallery/LabeledText.vue
  components/shared/view/BasicImage.vue
  components/spotlight/SpotlightTable.vue
  components/unique/Gallery/Item/Detail.vue
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.scss
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.story.vue
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium, waiting-for-review
