Repository kodadot/nft-gallery, pull requests merged in 2023-01, with the labels that each got.

#4563 :bug: fix urlPrefix on SeriesTable
  components/series/SeriesTable.vue
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4568 :bug: increase tooltip trigger area
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/scss/variable.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4573 #4570 all landing color to black
  components/TheFooter.vue
  styles/abstracts/_derived-variables.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: paid, ✅ - visual-ok

#4571 :bug: search history alignment + clickable area
  components/search/SearchSuggestion.vue
  styles/components/_search.scss
Labels: ✅ - visual-ok

#4578 #4569 hover state of connect button
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
Labels: paid, ✅ - visual-ok

#4561 :bug: fix chain name alignment
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - visual-ok

#4559 Fix disabled scrolling on mobile
  components/Navbar.vue
Labels: ✅ - code-lgtm

#4538 :wrench: bsx gift unlist
  components/bsx/Gallery/Item/AvailableActions.vue
Labels: ✅ - code-lgtm

#4540 :wrench: bsx withdraw offer as owner
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferList.vue
  components/bsx/Offer/OfferTable.vue
  utils/mixins/offerMixin.ts
Labels: ✅ - code-lgtm

#4572 #4566 Hover effect on links in navbar
  components/common/ColorModeButton.vue
  styles/layouts/_main-navigation.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm

#4549 fix: hover transition effect on cards
  libs/ui/src/components/CardArticle/CardArticle.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/scss/animation.scss
  libs/ui/src/scss/variable.scss
  styles/abstracts/_animations.scss
  styles/components/_carousel.scss
  styles/components/_collection-card.scss
  styles/components/_top-collections.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4576 #4252 Redesign congrats message after mint
  components/bsx/Gallery/Item/GalleryItem.vue
  components/movr/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/shared/MessageNotify.vue
  components/shared/Sharing.vue
  components/unique/Gallery/Item/GalleryItem.vue
  locales/en.json
  static/congrats-message-header.svg
Labels: 🤞 - changes-requested, paid

#4582 #4581 gallery btn changes
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/shared/Avatar.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  styles/global.scss
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: 🤞 - changes-requested

#4575 💄 gallery item prelaunch feedback + darkmode
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  libs/ui/src/components/IdentityItem/IdentityItem.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  styles/themes/_dark.scss
  styles/themes/_light.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4590 🐛 hover effect on wallet disconnect
  components/Navbar.vue
  components/navbar/MobileNavbarProfile.vue
  components/navbar/ProfileDropdown.vue
  components/shared/ConnectWalletButton.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/index.ts
  libs/ui/src/types.ts
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm

#4621 :sparkles: active state to `NeoDropdown`
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
Labels: ✅ - code-lgtm

#4546 ✨ burn collection with items
  components/bsx/specific/DestroyCollection.vue
  queries/subsquid/general/collectionBurnableStats.graphql
Labels: 🐍 - basilisk, ✅ - code-lgtm

#4629 fix: images on search components
  components/search/SearchSuggestion.vue
  tests/cache.spec.ts
  tests/ipfsUtils.spec.ts
  utils/cachingStrategy.ts
  utils/config/ipfs.ts
Labels: paid

#4624 🐛 responsivity by width (not touch)
  components/Navbar.vue
  components/navbar/ExploreDropdown.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#4634 :bug: landing layout shapes
  components/landing/SearchLanding.vue
  styles/components/_search.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4650 🔧 GalleryItem redesign MessageNotify
  components/bsx/Gallery/Item/GalleryItem.vue
  components/gallery/GalleryItem.vue
  components/movr/Gallery/Item/GalleryItem.vue
  components/rmrk/Gallery/GalleryItem.vue
  components/shared/MessageNotify.vue
  components/unique/Gallery/Item/GalleryItem.vue
  locales/en.json
Labels: paid

#4639 #4631 remove shadow
  styles/components/_collection-card.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#4610 ✨ rubick 008 release
  queries/config/.graphqlconfig
  utils/constants.ts
Labels: ✅ - code-lgtm, 🤞 - changes-requested

#4633 feat: Use subscription to track changes in Gallery Item
  components/gallery/useGalleryItem.ts
  composables/useGraphql.ts
  composables/useSubscriptionGraphql.ts
  nuxt.config.js
  package.json
  pnpm-lock.yaml
  utils/constants.ts
  utils/websocket.ts
Labels: paid

#4673 🔧 full width minting button
  components/base/BaseCollectionForm.vue
  components/bsx/Create/CreateCollection.vue
  components/bsx/Create/CreateToken.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Create/CreateToken.vue
  components/rmrk/Create/CreativeMint.vue
  components/rmrk/Create/SimpleMint.vue
  components/unique/Create/CreateCollection.vue
  components/unique/Create/CreateToken.vue
Labels: enhancement

#4653 fix: fetch image on explore collection
  components/collection/CollectionCard.vue
  components/collection/CollectionList.vue
  utils/cachingStrategy.ts
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4655 🔧 rmrk classic mint no price
  components/rmrk/Create/CreateToken.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4636 ✨ collection time frame select + refactor
  components/landing/topCollections/TopCollections.vue
  components/series/types.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/de.json
  locales/en.json
  styles/components/_top-collections.scss
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#4558 feat: integrate buy button
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/gallery/useGalleryItem.ts
  composables/useRmrkVersion.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoTooltip/NeoTooltip.scss
  libs/ui/src/components/NeoTooltip/NeoTooltip.vue
  locales/en.json
Labels: paid, ✅ - works-for-me

#4554 feat: integrate offer button
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/useGalleryItemAction.ts
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemShareBtn.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  composables/transaction/transactionList.ts
  composables/transaction/transactionOffer.ts
  composables/transaction/transactionSend.ts
  composables/transaction/types.ts
  composables/useApi.ts
  composables/useToast.ts
  composables/useTransaction.ts
  locales/en.json
  utils/api/bsx/query.ts
Labels: 🐍 - basilisk, blocked, ✅ - code-lgtm, ✅ - works-for-me

#4577 #4555 explore route changes
  components/carousel/CarouselTypeNewestList.vue
  components/collection/CollectionList.vue
  components/landing/SearchLanding.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/NavbarExploreOptions.vue
  components/rmrk/ExploreLayout/ExploreLayout.vue
  components/search/SearchBar.vue
  components/search/SearchSuggestion.vue
  components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
  components/shared/gallery/Gallery.vue
  layouts/error.vue
  layouts/explore-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoTab/NeoTab.scss
  libs/ui/src/components/NeoTab/NeoTab.vue
  libs/ui/src/components/NeoTab/NeoTabItem.vue
  libs/ui/src/index.ts
  locales/en.json
  middleware/redirects.ts
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/index.vue
  pages/_prefix/explore/items.vue
  pages/bsx/explore.vue
  pages/glmr/explore.vue
  pages/rmrk/explore.vue
  pages/snek/explore.vue
  pages/westend/explore.vue
  pages/westmint/explore.vue
  static/checkmark.svg
  styles/components/_o-tabs.scss
  styles/global.scss
  styles/themes/_dark.scss
  tests/cypress/e2e/basicE2E.cy.ts
Labels: 🤞 - changes-requested, paid, ✅ - visual-ok

#4691 ci: skip custom sentry on windows
  nuxt.config.js
Labels: paid

#4682 feat: meta attributes for redesigned gallery item
  components/gallery/GalleryItem.vue
Labels: ✅ - code-lgtm, paid

#4694 fix: reactive identity
  components/identity/IdentityIndex.vue
  components/identity/utils/useIdentity.ts
Labels: ✅ - code-lgtm

#4695 fix: Explorer Pagination and View update
  components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
  styles/global.scss
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm

#4711 fix: Popup on links in cards
  components/identity/module/IdentityPopover.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok

#4698 :white_check_mark: update e2e tests (new explore)
  .github/workflows/e2e.yml
  components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  tests/cypress.config.ts
  tests/cypress/e2e-run-tests.js
  tests/cypress/e2e/basicE2E.cy.ts
  tests/cypress/e2e/explore.cy.ts
  tests/cypress/support/commands.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4717 🔧 IdentityItem spacing issue
  components/gallery/GalleryItem.vue
  libs/ui/src/components/IdentityItem/IdentityItem.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4712 fix: Button states when not connected on gallery item
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4699 :bug: navbar on big touch devices
  components/Navbar.vue
  components/navbar/CreateDropdown.vue
  components/navbar/StatsDropdown.vue
Labels: paid, ✅ - works-for-me

#4729 fix: use workbox-window package
  components/CookieBanner.vue
  nuxt.config.js
  package.json
  plugins/pwa.ts
  plugins/vueGtag.ts
  pnpm-lock.yaml
Labels: paid

#4700 ✨ redesigned gallery item as default
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  composables/useChain.ts
  locales/en.json
  pages/_prefix/gallery/_id.vue
  pages/bsx/gallery/_id.vue
  pages/glmr/gallery/_id.vue
  pages/movr/gallery/_id.vue
  pages/rmrk/gallery/_id.vue
  pages/snek/gallery/_id.vue
Labels: 🤞 - changes-requested

#4718 fix: explore button on mobile
  components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
  layouts/explore-layout.vue
  styles/abstracts/_derived-variables.scss
  styles/global.scss
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4649 🐛 show real image ratio in gallery redesign
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: ✅ - code-lgtm

#4737 fix: Change description of SEO Cards
  nuxt.config.js
  package.json
  plugins/seoMetaGenerator.ts
Labels: paid

#4697 feat: Gallery Item Mobile Action Buttons
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  package.json
  static/timer.svg
  styles/themes/_dark.scss
Labels: ✅ - code-lgtm, paid

#4743 fix: Wrap markdown in description
  components/gallery/GalleryItemDescription.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4758 feat: Mobile Gallery Item: Full width on buy & Make Offer
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
Labels: paid

#4706 #4478 spacing issue fix
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
Labels: paid, ✅ - visual-ok

#4767 #4761 color identity mobile
  components/identity/module/IdentityLink.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4778 fix: disable buy button
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
Labels: ✅ - works-for-me, ✅ - visual-ok

#4774 fix: cors when download an image
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemMoreActionBtn.vue
  nuxt.config.js
  package.json
  utils/config/ipfs.ts
  utils/ipfs.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4783 fix: Missing collection link
  components/gallery/GalleryItem.vue
Labels: paid

#4766 #4763 gallery fixes
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
Labels: ✅ - visual-ok

#4799 🐛 chain on carousel nft cards
  components/carousel/module/CarouselInfo.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4724 Activity tab formatting and scroll
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  locales/en.json
  styles/components/_o-table.scss
  styles/components/_o-tabs.scss
Labels: ✅ - visual-ok

#4714 #4339 collection popover
  components/carousel/module/CarouselInfo.vue
  components/collection/utils/useCollectionDetails.ts
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/gallery/GalleryItem.vue
  components/identity/utils/useIdentity.ts
  components/unique/Gallery/Item/Detail.vue
  locales/en.json
  pnpm-lock.yaml
  queries/subsquid/general/collectionBuyEventStatsById.graphql
  queries/subsquid/general/collectionStatsById.graphql
  queries/subsquid/general/nftListSoldByCollection.graphql
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4771 🔥 burn item
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  composables/transaction/transactionBurn.ts
  composables/transaction/transactionOffer.ts
  composables/transaction/types.ts
  composables/useTransaction.ts
  locales/en.json
Labels: ✅ - code-lgtm

#4813 🔧 top-collections skeleton responsive
  components/landing/topCollections/TopCollections.vue
Labels: ✅ - code-lgtm

#4824 🐛 list button for unlisted owned items
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  styles/themes/_dark.scss
Labels: paid, ✅ - works-for-me

#4836 fix: patch hmr on nuxt bridge
  package.json
  patches/@nuxt__webpack-edge@2.16.0-27720022.54e852f.patch
  pnpm-lock.yaml
Labels: paid, ✅ - works-for-me

#4779 Refactoring small components to vue3
  components/TheFooter.vue
  components/bsx/Asset/AssetTable.vue
  components/bsx/Create/Create.vue
  components/bsx/Create/CreateCollectionPage.vue
  pages/bsx/create.vue
  pages/glmr/create.vue
  pages/movr/create.vue
  pages/snek/create.vue
Labels: ✅ - code-lgtm

#4823 ✨ delist button (unlist)
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  composables/transaction/transactionList.ts
  locales/en.json
Labels: ✅ - code-lgtm, paid, ✅ - works-for-me

#4828 feat: Wallet connect dialog init
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/ConnectWallet/useConnectWallet.ts
  components/common/WalletModal.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/shared/ConnectWalletButton.vue
  composables/useChain.ts
  locales/en.json
  styles/abstracts/_theme.scss
  styles/components/_connect-wallet.scss
  styles/index.scss
  styles/themes/_dark.scss
Labels: ✅ - works-for-me, ✅ - visual-ok

#4852 chore: Add the newest article on KodaDot landing page
  components/landing/FeaturedArticles.vue
Labels: paid

#4839 fix: long email address on create Identity
  components/common/IdentityForm.vue
  components/rmrk/Profile/IdentityForm.vue
  components/shared/form/BasicInput.vue
  pages/identity.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4811 🔥 withdraw on burn item
  composables/transaction/transactionBurn.ts
Labels: 🐍 - basilisk, ✅ - code-lgtm

#4834 ✨ Insufficient Funds in Offer Making
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#4860 feat: Redesign: asset page in wallet dialog
  components/Navbar.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/identity/module/IdentityLink.vue
  components/identity/utils/useIdentity.ts
  components/navbar/ProfileDropdown.vue
  components/rmrk/Profile/ProfileAssetsList.vue
  libs/ui/src/types.ts
  locales/en.json
  styles/components/_connect-wallet.scss
Labels: ✅ - works-for-me

#4846 feat: sort options on explore
  components/collection/CollectionList.vue
  components/explore/ExploreIndex.vue
  components/explore/ExploreSort.vue
  components/explore/ExploreTabItem.vue
  components/search/Search.vue
  components/shared/exploreTabsFilterSort/ExploreTabsFilterSort.vue
  components/shared/gallery/Gallery.vue
  layouts/explore-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdownItem.vue
  locales/en.json
  queries/subsquid/general/collectionListWithSearch.graphql
  styles/abstracts/_theme.scss
  tests/cypress/e2e/explore.cy.ts
  utils/constants.ts
Labels: ✅ - visual-ok
