Repository kodadot/nft-gallery, pull requests merged in 2023-02, with the labels that each got.

#4880 fix: wrong route path
  components/search/SearchBar.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4881 #4867 remove footer from explore
  layouts/explore-layout.vue
Labels: ✅ - code-lgtm

#4902 feat: bring existing query to chain and sort
  components/explore/ExploreChain.vue
  components/explore/ExploreSort.vue
Labels: ✅ - code-lgtm

#4901 feat: Name of the wallet account
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  locales/en.json
Labels: ✅ - visual-ok

#4826 ✨ SidebarFilter
  components/collection/CollectionList.vue
  components/common/EmptyResult.vue
  components/explore/ExploreIndex.vue
  components/explore/ExploreSort.vue
  components/explore/ExploreTabItem.vue
  components/explore/SidebarFilter.vue
  components/shared/gallery/BreadcrumbsFilter.vue
  components/shared/gallery/Gallery.vue
  layouts/explore-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoSidebar/NeoSidebar.scss
  libs/ui/src/components/NeoSidebar/NeoSidebar.story.vue
  libs/ui/src/components/NeoSidebar/NeoSidebar.vue
  libs/ui/src/index.ts
  locales/en.json
  pages/_prefix/explore/collectibles.vue
  pages/_prefix/explore/items.vue
  plugins/icons.ts
  store/preferences.ts
  styles/global.scss
Labels: ✅ - visual-ok

#4892 fix displayed rmrk to kusama
  components/navbar/ChainSelectDropdown.vue
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#4920 fix: NFT cards explore + landing
  components/media/type/VideoMedia.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
  styles/components/_carousel.scss
Labels: paid, ✅ - visual-ok

#4929 fix: icons in wallet dialog redesign
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  styles/components/_connect-wallet.scss
Labels: ✅ - visual-ok

#4939 ✨ swag shop link in footer
  components/TheFooter.vue
  plugins/icons.ts
Labels: ✅ - code-lgtm

#4947 refactor: remove idb-keyval
  components/Navbar.vue
  components/bsx/Create/CreateToken.vue
  components/media/PreviewMediaResolver.vue
  package.json
  pnpm-lock.yaml
  utils/cachingStrategy.ts
  utils/idbStore.ts
Labels: ✅ - works-for-me

#4935 fix: NFT broken card
  components/gallery/GalleryItem.vue
  components/shared/gallery/Gallery.vue
  libs/ui/src/components/MediaItem/MediaItem.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok

#4951 fix: check serviceWorker in navigator
  plugins/pwa.ts
Labels: ✅ - code-lgtm

#4940 fix: explorer input leftovers
  components/explore/SidebarFilter.vue
  locales/en.json
  static/arrow-right.svg
Labels: paid, ✅ - works-for-me, ✅ - visual-ok

#4921 fix: content style issue in light mode
  styles/base/_typography.scss
  styles/components/_content-markdown.scss
  styles/themes/_light.scss
  utils/highlight.ts
Labels: paid, ✅ - works-for-me, ✅ - visual-ok

#4946 feat: add prefetch to all pages using infinite scroll
  components/collection/CollectionList.vue
  components/rmrk/Gallery/CollectionItem.vue
  components/rmrk/Gallery/PaginatedCardList.vue
  components/rmrk/Profile/ProfileDetail.vue
  components/shared/gallery/Gallery.vue
  utils/mixins/infiniteScrollMixin.ts
Labels: ✅ - works-for-me

#4938 feat(Teleport): show ksm balance on Kusama
  components/teleport/Teleport.vue
  components/teleport/TeleportTabs.vue
  locales/en.json
  store/identity.ts
  utils/balance.ts
Labels: ✅ - visual-ok

#4980 feat: hide tooltip on scroll
  plugins/vueTippy.ts
Labels: paid, ✅ - visual-ok

#4968 fix: 4955 gallery item price chart
  components/chart/PriceChart.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  composables/useChain.ts
Labels: paid

#4960 fix: 4950 price fltr on active k-blue
  components/explore/SidebarFilter.vue
Labels: ✅ - visual-ok

#4973 fix: readd checkValidity()
  components/shared/form/BasicInput.vue
  tests/cypress/e2e/create-collection.cy.ts
Labels: paid

#4977 fix: Wrong redirect to a profile
  libs/ui/src/components/IdentityItem/IdentityItem.vue
Labels: paid, ✅ - visual-ok

#4987 🔧 galleryItem congrats message errors
  components/gallery/GalleryItem.vue
  components/shared/MessageNotify.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me

#4967 fix: 4956 move by 3 slides
  components/carousel/CarouselIndex.vue
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/CarouselTypePopularCollection.vue
  components/carousel/CarouselTypeRelated.vue
  components/carousel/CarouselTypeVisited.vue
  components/carousel/module/CarouselAgnostic.vue
Labels: ✅ - works-for-me

#4961 ✨ quick & not dirty explore grid layout size
  components/explore/ExploreGrid.vue
  components/explore/ExploreIndex.vue
Labels: ✅ - code-lgtm

#4989 🔧 nuxt-link prefix
  components/Navbar.vue
  components/bsx/Offer/MyOffer.vue
  components/bsx/Offer/OfferTable.vue
  components/carousel/utils/useCarousel.ts
  components/generative/CongratsView.vue
  components/landing/CuratedList.vue
  components/rmrk/Gallery/History.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Profile/Sales.vue
  components/spotlight/SpotlightTable.vue
Labels: p2

#4974 fix: 4958 add hover card stroke
  components/identity/module/IdentityPopoverFooter.vue
Labels: ✅ - visual-ok

#4994 fix: explore tabs & btn responsive (mobile/tablet)
  components/explore/ExploreIndex.vue
  components/explore/ExploreTabItem.vue
  layouts/explore-layout.vue
Labels: ✅ - works-for-me

#5012 fix: 5006 update grants to referral program (+ some prettier)
  components/TheFooter.vue
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/pt.json
  locales/ru.json
  locales/ua.json
Labels: ✅ - code-lgtm, ✅ - works-for-me

#5011 fix: 5004 footer gradient and stroke
  styles/global.scss
Labels: ✅ - visual-ok

#5021 feat: Replace old gallery cards on profile
  components/rmrk/Gallery/PaginatedCardList.vue
  components/shared/Avatar.vue
  components/shared/gallery/GalleryItemCardList.vue
  components/shared/gallery/NftCard.vue
  queries/fragments/subsquidNft.graphql
  queries/subsquid/general/collectionById.graphql
  queries/subsquid/general/nftListByIssuer.graphql
  utils/carousel.ts
Labels: ✅ - visual-ok

#5010 fix: 5005+5007 carousel 3 steps post fixes
  components/carousel/CarouselIndex.vue
  components/carousel/CarouselTypeLatestSales.vue
  components/carousel/CarouselTypeNewestList.vue
  components/carousel/CarouselTypePopularCollection.vue
  components/carousel/CarouselTypeRelated.vue
  components/carousel/CarouselTypeSpotlight.vue
  components/carousel/CarouselTypeVisited.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/utils/useCarousel.ts
  queries/subsquid/general/collectionEntityById.graphql
Labels: ✅ - visual-ok

#5048 fix: Gradient overflow
  libs/ui/src/components/NeoNftCard/NeoNftCard.scss
  styles/components/_carousel.scss
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5013 fix: 5003 nft card without name
  components/carousel/module/CarouselInfo.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/rmrk/Gallery/GalleryCard.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: ✅ - visual-ok

#5036 fix: card style in light mode
  styles/components/_card.scss
Labels: ✅ - works-for-me

#5049 fix: Separator height
  components/gallery/GalleryItem.vue
  layouts/explore-layout.vue
  styles/components/_connect-wallet.scss
  styles/global.scss
Labels: ✅ - visual-ok

#5055 fix: Keyboard shortcut K on landing should trigger active input
  components/search/SearchBar.vue
Labels: ✅ - works-for-me

#5079 fix: 5061 highest offer gallery item
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5062 fix: 5047 network capitalized
  components/landing/topCollections/TopCollectionsItem.vue
Labels: ✅ - code-lgtm

#5064 fix: 5050 search bar styling
  styles/components/_search.scss
Labels: ✅ - visual-ok

#5059 fix: Dark/light mode hover effect
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  styles/abstracts/_theme.scss
  styles/components/_search.scss
  styles/layouts/_footer.scss
  styles/layouts/_main-navigation.scss
Labels: ✅ - visual-ok

#5102 fix: 5099 sort by button variant
  components/explore/ExploreSort.vue
Labels: ✅ - code-lgtm

#5101 Hero buttons
  components/collection/HeroButtons.vue
  components/collection/utils/useCollectionDetails.ts
  layouts/explore-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  locales/en.json
  queries/subsquid/general/collectionByIdMinimal.graphql
Labels: ✅ - code-lgtm, ✅ - visual-ok

#5092 fix: 5087 carousel card layout
  components/carousel/module/CarouselInfo.vue
Labels: ✅ - code-lgtm

#5114 fix: Not showing collection on cards
  styles/components/_carousel.scss
  utils/carousel.ts
Labels: paid

#5088 #5044 checkbox neo
  components/explore/filters/StatusFilter.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.scss
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.story.vue
  libs/ui/src/components/NeoCheckbox/NeoCheckbox.vue
  libs/ui/src/index.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok

#5065 fix: 5060 min offer 0.01
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  locales/en.json
  utils/constants.ts
Labels: ✅ - code-lgtm, paid, ✅ - visual-ok

#5113 Hover collection card on explore page
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  libs/ui/src/components/NeoNftCard/NeoNftCard.vue
Labels: paid, ✅ - visual-ok

#5105 Redesign breadcrumbs
  components/explore/MobileFilter.vue
  components/explore/SidebarFilter.vue
  components/search/Search.vue
  components/shared/gallery/BreadcrumbsFilter.vue
  components/shared/gallery/NeoTag.vue
  layouts/explore-layout.vue
  locales/en.json
Labels: ✅ - code-lgtm, ✅ - works-for-me, ✅ - visual-ok

#5100 refactor: Unify usage of dark/ light mode
  components/Navbar.vue
  components/TheFooter.vue
  components/chart/PriceChart.vue
  components/common/ColorModeButton.vue
  components/landing/SearchLanding.vue
  components/media/MediaResolver.vue
  components/shared/view/BasicImage.vue
  composables/useTheme.ts
Labels: paid

#5107 🔧 Breadcrumb owned translation
  components/explore/ExploreSort.vue
  components/shared/gallery/BreadcrumbsFilter.vue
Labels: ✅ - code-lgtm

#5039 feat: item list on new collection page
  components/explore/ExploreIndex.vue
  components/explore/ExploreTabItem.vue
  components/items/Items.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  pages/_prefix/collection/_id.vue
  pages/_prefix/explore/items.vue
  pages/_prefix/u/_id.vue
  pnpm-lock.yaml
  queries/subsquid/general/nftListWithSearch.graphql
Labels: ✅ - code-lgtm

#5118 #5115 icons fix
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemButton/GalleryItemShareBtn.vue
  styles/components/_gallery-item.scss
Labels: paid, ✅ - visual-ok

#5052 #4437 cancel accept offer
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  composables/transaction/transactionOfferAccept.ts
  composables/transaction/transactionOfferWithdraw.ts
  composables/transaction/types.ts
  composables/useTransaction.ts
  libs/ui/src/components/NeoSecondaryButton/NeoSecondaryButton.scss
  libs/ui/src/components/NeoSecondaryButton/NeoSecondaryButton.vue
  libs/ui/src/index.ts
  libs/ui/src/scss/_theme.scss
  styles/abstracts/_theme.scss
  utils/shoppingActions.ts
Labels: paid

#5127 Collection breadcrumbs
  components/items/ItemsGrid/ItemsGrid.vue
  components/shared/gallery/BreadcrumbsFilter.vue
  locales/en.json
  script/substack.json
Labels: ✅ - works-for-me
