Repository kodadot/nft-gallery, pull requests merged in 2024-02, with the labels that each got.

#9206 fix: Teleport - checking funds visual bug
  components/common/autoTeleport/AutoTeleportModal.vue
Labels: S-works-for-me-✅, small

#9027 feat: Holder of drop page iteration
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/HolderOfCollection.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintSection/HolderOfCollectionMintRequirements.vue
  components/collection/drop/MintSection/MintRequirementItem.vue
  components/collection/drop/MintSection/MintSection.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/types.ts
  components/drops/useDrops.ts
  components/gallery/GalleryItemHolderOf.vue
  components/navbar/NavbarExploreOptions.vue
  components/teleport/Teleport.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/drop/useGenerativeDropDetails.ts
  composables/useMultipleBalance.ts
  composables/useTeleport.ts
  locales/en.json
  pages/[prefix]/drops/[id].vue
  params/types.ts
Labels: S-works-for-me-✅, large, waiting-for-review

#9244 🔧 nft-card border color
  assets/styles/components/_nft-card.scss
Labels: S-works-for-me-✅, waiting-for-review

#9241 🔧 OnRampModal theme colors
  components/balance/MultipleBalances.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/shared/OnRampModal.vue
Labels: S-works-for-me-✅, waiting-for-review

#9223 feat: Adding to share button text twitter handle of generative artists
  components/common/ShareDropdown.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  composables/useSocialShare.ts
  locales/en.json
  utils/parse.ts
Labels: S-works-for-me-✅, waiting-for-review

#9257 fx: Collection filter dropdown checkbox
  components/profile/CollectionFilter.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9167 Remove hover from mobile link
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/gallery/GalleryItem.vue
Labels: S-works-for-me-✅, small

#9227 fix: Properties Section titles no longer showing
  components/gallery/GalleryItemDescription.vue
Labels: S-works-for-me-✅, waiting-for-review

#9259 fix: Modal action button not taking up the entire space
  components/common/autoTeleport/AutoTeleportActionButton.vue
Labels: S-works-for-me-✅, waiting-for-review

#9232 fix: Teleport page issues
  components/teleport/Teleport.vue
Labels: S-works-for-me-✅

#9243 🔧 refactor massmint modals
  components/massmint/modals/DeleteModal.vue
  components/massmint/modals/MintingModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/MobileDisclaimerModal.vue
  components/massmint/modals/ReviewModal.vue
  components/massmint/modals/modals.scss
Labels: waiting-for-review

#9256 fix: Profile Sidebar keeps opened after navbar select
  components/Navbar.vue
  components/navbar/CreateDropdown.vue
  components/navbar/ExploreDropdown.vue
  components/navbar/MobileLanguageOption.vue
  components/navbar/NavbarChainOptions.vue
  components/navbar/NavbarExploreOptions.vue
  components/search/Search.vue
  locales/en.json
  middleware/modal.global.ts
  tests/e2e/sidebar.spec.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9284 style: Remove width from globals.scss
  assets/styles/global.scss
  components/Navbar.vue
  components/TheFooter.vue
  components/collection/CollectionInfo.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
  components/rmrk/Gallery/Holder/Holder.vue
Labels: S-code-lgtm-✅

#9252 fix: Drop page card hover and default state
  components/drops/DropCard.vue
Labels: S-changes-requested-🤞, waiting-for-review

#9226 feat: use fxart endpoint for drop
  components/collection/drop/PaidGenerative.vue
  components/drops/useDrops.ts
  composables/drop/useGenerativeDropDetails.ts
  composables/drop/useGenerativeDropMint.ts
  pages/[prefix]/drops/[id].vue
  params/types.ts
  services/fxart.ts
  services/waifu.ts
Labels: S-resolve-merge-conflicts-🤝

#9289 fix: Transfer: Copy Payme link not working
  components/transfer/Transfer.vue
Labels: S-works-for-me-✅

#9293 fix drop banner container padding
  components/collection/unlockable/UnlockableCollectionBanner.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅, waiting-for-review

#9269 fix: No search icon on devices from 1024 -> mobile
  components/Navbar.vue
  tests/e2e/basic.spec.ts
  tests/e2e/search.spec.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9237 Hide minted by in mobile cards in drop page
  components/carousel/CarouselTypeLatestMints.vue
Labels: S-works-for-me-✅

#9292 fix: collection icon
  components/collection/CollectionHeader/CollectionBanner.vue
Labels: S-code-lgtm-✅, paid, S-works-for-me-✅

#9283 style: refactor label size from globals.scss
  assets/styles/global.scss
  components/settings/Interface.vue
  components/settings/Minting.vue
  components/shared/collection/PriceChart.vue
  components/shared/gallery/Label.vue
  components/shared/gallery/LabeledText.vue
Labels: S-works-for-me-✅

#9208 feat: Buy Success modal
  components/buy/Buy.vue
  components/buy/SuccessfulBuyModal.vue
  components/collection/drop/TokenImportButton.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/common/IdentityForm.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/common/shoppingCart/types.ts
  components/common/shoppingCart/utils.ts
  components/common/successfulModal/ActionButtons.vue
  components/common/successfulModal/ShareSocialsSection.vue
  components/common/successfulModal/SingleItemMedia.vue
  components/common/successfulModal/SuccessfulModal.vue
  components/common/successfulModal/SuccessfulModalBody.vue
  components/common/successfulModal/TransactionSection.vue
  components/rmrk/service/scheme.ts
  composables/transaction/types.ts
  composables/useListingCartModal.ts
  composables/useMetaTransaction.ts
  composables/useTeleport.ts
  composables/useTransaction.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
  stores/listingCart.ts
  utils/transactionExecutor.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅, large

#9301 fix: Status of the newest drop - Change
  components/drops/DropCard.vue
  components/drops/TimeTag.vue
  locales/en.json
Labels: S-works-for-me-✅

#9306 fix: Mobile search focus on icon press
  components/search/Search.vue
  components/search/SearchBar.vue
Labels: paid, S-works-for-me-✅

#9305 use default theme class (light / dark)
  assets/styles/abstracts/_theme.scss
  assets/styles/global.scss
  components/drops/CreateDropCard.vue
  components/explore/ExploreSort.vue
  components/profile/OrderByDropdown.vue
  components/teleport/Teleport.vue
  components/teleport/TeleportTabs.vue
  libs/ui/histoire.config.ts
  libs/ui/src/components/NeoSelect/NeoSelect.scss
  libs/ui/src/scss/_theme.scss
  libs/ui/src/scss/tailwind.scss
  libs/ui/src/scss/variable.scss
  nuxt.config.ts
  tailwind.config.ts
Labels: S-works-for-me-✅

#9317 release update
  components/collection/drop/PaidGenerative.vue
Labels: release

#9332 fix: Single/mass buy success modal followup
  components/buy/SuccessfulBuyModal.vue
  components/common/successfulModal/SingleItemMedia.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅

#9342 beta update
  CONTRIBUTING.md
  assets/styles/components/_nft-card.scss
  components/buy/SuccessfulBuyModal.vue
  components/collection/drop/MintButton.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/common/successfulModal/SingleItemMedia.vue
  components/drops/useDrops.ts
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/NftMediaInfoStacked.vue
  content/blog/first-time.md
  utils/mintUtils.ts
Labels: beta

#9343 release update
  CONTRIBUTING.md
  assets/styles/components/_nft-card.scss
  components/buy/SuccessfulBuyModal.vue
  components/collection/drop/MintButton.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/common/successfulModal/SingleItemMedia.vue
  components/drops/useDrops.ts
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/NftMediaInfoStacked.vue
  content/blog/first-time.md
  utils/mintUtils.ts
Labels: release

#9307 style: Remove unused styles/classes from global.scss
  assets/styles/global.scss
  components/profile/CollectionFilter.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/filters/modules/PopularCollections.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9366 feat: more accurate estimate of waiting time
  components/shared/SigningModal/SigningModal.vue
  composables/useTransactionEstimatedTime.ts
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅

#9333 create collection success modal
  components/create/CreateCollection.vue
  components/create/modals/CollectionSuccessModal.vue
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅, waiting-for-review

#9373 fix: Landing mobile option to zoom out
  components/drops/DropCardSkeleton.vue
  components/landing/HeroBanner.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅, waiting-for-review

#9368 fix: Search by #number in collections not working
  components/items/ItemsGrid/utils/useSearchParams.ts
  tests/e2e/collection.spec.ts
Labels: S-works-for-me-✅

#9376 fix: Swap collection and blockchain fields in minting
  components/create/CreateNft.vue
Labels: S-works-for-me-✅

#9378 fix: Dividers in modals
  assets/styles/components/_connect-wallet.scss
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/Confirm/PriceItem.vue
  components/shared/ModalIdentityItem.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅

#9389 fix: HolderOf does not work on drops
  components/collection/drop/HolderOfGenerative.vue
Labels: S-works-for-me-✅

#9336 feat: Top collections - landing page v3
  assets/styles/components/_top-collections.scss
  assets/styles/index.scss
  components/landing/topCollections/TopCollections.vue
  components/landing/topCollections/TopCollectionsCard.vue
  components/landing/topCollections/TopCollectionsGrid.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/shared/DynamicGrid.vue
  composables/useCollectionVolume.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅

#9379 fix(buy modal): price change subscription
  components/buy/Buy.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9383 feat: Paid Mint modal, skeleton title to "Uploading data to IPFS"
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/shared/modals/ModalBody.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9356 fix: Collection incomplete text
  components/collection/CollectionInfo.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/utils/description.ts
  utils/parse.ts
Labels: S-works-for-me-✅

#9358 fix: Extremely lucky breakpoint
  components/carousel/CarouselTypeDrops.vue
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
Labels: S-works-for-me-✅

#9359 fix: Minting live in drop page not pulsing
  components/collection/drop/DropContainer.vue
  components/collection/drop/MintSection/MintSection.vue
  components/collection/drop/Phase.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/voteDrop/DropContainer.vue
  components/drops/TimeTag.vue
  libs/ui/tailwind.config.js
  public/drop/unlockable-pulse.svg
  public/unlockable-pulse.svg
Labels: S-works-for-me-✅

#9395 perf: featured drops
  components/carousel/CarouselTypeDrops.vue
  components/drops/DropCard.vue
  components/drops/useDrops.ts
  components/landing/HeroBanner.vue
  services/fxart.ts
Labels: S-code-lgtm-✅, paid

#9391 #9382 Holder of styling
  components/collection/drop/requirement/PrivateMintRequirements.vue
Labels: S-works-for-me-✅

#9392 #9319 hover card fix
  components/drops/DropCard.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅, S-resolve-merge-conflicts-🤝

#9397 fix: remaining nfts
  components/collection/drop/HolderOfGenerative.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItemHolderOf.vue
  composables/drop/useGenerativeDropMint.ts
  services/fxart.ts
  utils/drop.ts
Labels: S-works-for-me-✅

#9414 fix: Ensure that Drop API is called only when tx is successful
  components/collection/drop/HolderOfGenerative.vue
  components/shared/SigningModal/SigningModal.vue
Labels: paid

#9425 fix: Warning that nft was used for claim
  utils/drop.ts
Labels: S-works-for-me-✅

#9435 beta update
  components/collection/drop/HolderOfGenerative.vue
  components/common/successfulModal/SingleItemMedia.vue
  components/shared/SigningModal/SigningModal.vue
  queries/subsquid/general/holderOfCollectionById.graphql
  utils/drop.ts
Labels: beta

#9436 release update
  components/collection/drop/HolderOfGenerative.vue
  components/common/successfulModal/SingleItemMedia.vue
  components/shared/SigningModal/SigningModal.vue
  queries/subsquid/general/holderOfCollectionById.graphql
  utils/drop.ts
Labels: release

#9437 feat: Drop landing v2
  assets/styles/global.scss
  components/Navbar.vue
  components/drops/CreateCalendarEventModal.vue
  components/drops/CreateDropCard.vue
  components/drops/Drops.vue
  components/landing/HeroBanner.vue
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅

#9405 [Blogpost]: Kusama Asset Hub
  content/blog/a-brief-tour-of-kusama-asset-hub.md
  public/blog/a-brief-tour-of-kusama-asset-hub.webp
Labels: S-changes-requested-🤞

#9394 :sparkles: Code checker gen art
  components/codeChecker/CodeChecker.vue
  components/codeChecker/FileUploader.vue
  components/codeChecker/PreviewCard.vue
  components/codeChecker/SandboxIFrame.vue
  components/codeChecker/codechecker.config.js
  components/codeChecker/testItem.vue
  components/codeChecker/types.ts
  components/codeChecker/utils.ts
  components/codeChecker/validate.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
  pages/code-checker/index.vue
  public/sandbox.html
  utils/download.ts
Labels: S-works-for-me-✅

#9459 feat: Collection notification - drops minting is live
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/CollectionRelatedDropNotification.vue
  components/drops/useDrops.ts
  locales/en.json
Labels: paid, S-works-for-me-✅, S-visual-ok-✅

#9449 fix: Profile: Activity: Not showing NFT numbers
  components/gallery/GalleryItem.vue
  components/profile/activityTab/HistoryRow.vue
  components/shared/nftCard/NftMediaInfo.vue
  composables/collectionActivity/useCollectionActivity.ts
  composables/useNft.ts
  queries/rmrk/subsquid/allEventsByProfile.graphql
  queries/subsquid/general/allEventsByProfile.graphql
  queries/subsquid/general/collectionActivityEvents.graphql
  queries/subsquid/ksm/collectionActivityEvents.graphql
  queries/subsquid/rmrk/allEventsByProfile.graphql
  utils/carousel.ts
  utils/nft.ts
Labels: S-works-for-me-✅

#9463 fix: Copy transaction and link at success modal at drop page mint
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
Labels: S-works-for-me-✅

#9490 #9473 dynamic carousel for drops
  components/carousel/CarouselTypeDrops.vue
  components/drops/DropCard.vue
Labels: S-works-for-me-✅

#9483 feat: Drop page party kit action status
  components/collection/drop/CursorParty.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/common/party/CursorParty.vue
  components/common/party/Cusor.vue
  composables/drop/useGenerativeDropMint.ts
  composables/party/types.ts
  composables/party/useCursorDropEvents.ts
  composables/party/useCursorParty.ts
  composables/party/useParty.ts
  locales/en.json
  utils/format/balance.ts
Labels: S-works-for-me-✅

#9498 fix: Generating kept hanging
  components/collection/drop/GenerativePreview.vue
  utils/ss58Format.ts
Labels: paid, S-works-for-me-✅

#9492 feat: Requirements and minimum hold for drops
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/types.ts
Labels: paid, S-works-for-me-✅

#9501 fix: Missing locale when listing
  locales/en.json
Labels: paid, S-works-for-me-✅

#9500 feat: Party kit showing funds for user that are not connected
  components/collection/drop/CursorParty.vue
  components/common/party/CursorParty.vue
  components/common/party/Cusor.vue
  composables/party/useCursorParty.ts
  composables/party/useParty.ts
Labels: paid, S-works-for-me-✅

#9513 feat: notice for drop page
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/Phase.vue
Labels: paid, S-works-for-me-✅, waiting-for-review

#9517 fix: Video thumbnail not showing on profile activity
  components/collection/activity/events/eventRow/EventTag.vue
  components/profile/activityTab/HistoryRow.vue
  queries/subsquid/general/allEventsByProfile.graphql
  queries/subsquid/rmrk/allEventsByProfile.graphql
Labels: S-works-for-me-✅

#9537 fix/paid-generative-sometimes errors
  components/collection/drop/PaidGenerative.vue
Labels: S-works-for-me-✅

#9520 feat: Unfold collapsed cards on profile page
  components/items/ItemsGrid/useItemsGrid.ts
Labels: S-works-for-me-✅, S-visual-ok-✅, waiting-for-review

#9540 fix/bug when navigating back to collection page
  middleware/resetPageParam.global.ts
Labels: S-works-for-me-✅

#9453 fix: When I mint and want mint again, mint button doesnot work
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/shared/SigningModal/SigningModal.vue
Labels: S-works-for-me-✅

#9529 fix: Remove requirements if requirement is only price
  components/collection/drop/Phase.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9548 fix: Explore algorithm copy
  components/collection/CollectionRelatedDropNotification.vue
  locales/en.json
Labels: S-visual-ok-✅

#9536 feat: Recent generative nft mints in drop page
  assets/styles/components/_nft-card.scss
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/profile/OrderByDropdown.vue
  components/shared/nftCard/NftCard.vue
  components/shared/nftCard/NftCardSkeleton.vue
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/types.ts
  layouts/unlockable-mint-layout.vue
  locales/en.json
  queries/subsquid/ahk/nftListWithSearch.graphql
  queries/subsquid/general/nftListWithSearch.graphql
Labels: S-works-for-me-✅, S-visual-ok-✅

#9545 fix: Article card default state
  libs/ui/src/components/CardArticle/CardArticle.vue
Labels: S-visual-ok-✅

#9534 refactor: little bit cleanup drops component
  components/collection/drop/DropContainer.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/MintSection/MintSection.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/collection/unlockable/UnlockableContainer.vue
  components/collection/voteDrop/DropContainer.vue
  components/collection/voteDrop/const.ts
  components/drops/useDrops.ts
  composables/drop/useGenerativeDropMint.ts
  pages/[prefix]/drops/[id].vue
  services/fxart.ts
Labels: paid, S-works-for-me-✅, S-resolve-merge-conflicts-🤝

#9532 :tada: Read Only Immutable zkEVM
  libs/static/src/chains.ts
  libs/static/src/endpoints.ts
  libs/static/src/indexers.ts
  libs/static/src/names.ts
  libs/static/src/services.ts
  libs/static/src/types.ts
Labels: S-works-for-me-✅

#9567 Fix-NAN-in-collection-info
  components/collection/CollectionInfo.vue
Labels: S-works-for-me-✅

#9541 fix: Drop card banner = collection banner Leadlight
  components/drops/DropCard.vue
  components/drops/useDrops.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#9521 feat: drops geolocation
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/Phase.vue
  params/types.ts
Labels: paid, S-works-for-me-✅

#9560 fix: Enable Kusama to ahk bridge
  components/teleport/Teleport.vue
Labels: S-works-for-me-✅

#9564 Fix/free-generative-mint
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/utils.ts
  services/fxart.ts
Labels: S-works-for-me-✅

#9561 fix: Full screen not working for some items
  components/gallery/GalleryItem.vue
Labels: S-works-for-me-✅

#9571 fix: List for sale button appearing on Latest NFT mints on drop page
  components/collection/drop/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
Labels: S-works-for-me-✅

#9573 Disable RMRK1/2 Minting
  components/common/ChooseCollectionDropdown.vue
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  locales/en.json
  tests/e2e/createcollection.spec.ts
  tests/e2e/createnft.spec.ts
Labels: S-visual-ok-✅

#9302 fix: retry on cancel - migration page
  components/collection/CollectionHeader/CollectionBanner.vue
  components/migrate/steps/SignLoader1.vue
  components/migrate/steps/SignLoader2.vue
  components/migrate/steps/SignLoader3.vue
  composables/useMetaTransaction.ts
  composables/useMigrate.ts
  composables/useTransactionStatus.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, waiting-for-review

#9594 fix: location check for drop
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
Labels: S-works-for-me-✅

#9584 farcaster icon light mode
  components/TheFooter.vue
  public/icons/farcaster.svg
Labels: S-works-for-me-✅, S-visual-ok-✅

#9542 Drop phases followup
  components/collection/drop/CollectedBy.vue
  components/collection/drop/CollectedByAvatar.vue
  components/collection/drop/CreatedBy.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/Phase.vue
  components/drops/TimeTag.vue
  components/drops/useDrops.ts
  components/drops/utils.ts
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅, waiting-for-review

#9591 Update ParaSpell to -> v4.1.1
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅

#9597 fix: generate variants on fails base64 image
  components/collection/drop/GenerativePreview.vue
Labels: S-works-for-me-✅

#9586 quick fix: ensure drop loading state can be cleared
  components/collection/drop/GenerativePreview.vue
Labels: S-works-for-me-✅
