Repository kodadot/nft-gallery, pull requests merged in 2024-10, with the labels that each got.

#11039 fix: Collection page query over-fetching
  components/collection/CollectionHeader.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/CollectionInfo.vue
  components/collection/CollectionRelatedDropNotification.vue
  components/collection/activity/Activity.vue
  components/collection/activity/ActivityChart.vue
  components/collection/activity/events/Events.vue
  components/collection/utils/useCollectionDetails.ts
  composables/collectionActivity/useCollectionActivity.ts
  composables/useAsyncGraphql.ts
  composables/useCollectionDrop.ts
  layouts/explore-layout.vue
  locales/en.json
Labels: S-code-lgtm-✅, S-works-for-me-✅

#11073 fix: Create NFT - adjust font
  assets/styles/pages/create.scss
  components/create/CreateNft.vue
Labels: S-visual-ok-✅

#10934 fix: get token metadata from onchain
  components/base/types.ts
  components/carousel/module/CarouselMedia.vue
  components/collection/drop/ItemsGrid.vue
  components/common/CartItemDetails.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/common/shoppingCart/utils.ts
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/gallery/GalleryItemToolBar.vue
  components/gallery/useGalleryItem.ts
  components/items/Items.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/HistoryRow.vue
  components/profile/activityTab/OfferRow.vue
  components/rmrk/service/scheme.ts
  components/rmrk/types.ts
  components/rmrk/utils.ts
  components/series/types.ts
  components/series/utils.ts
  components/shared/nftCard/NftCard.vue
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/types.ts
  composables/collectionActivity/useCollectionActivity.ts
  composables/useNft.ts
  pages/[prefix]/detail/[id].vue
  pages/[prefix]/gallery/[id].vue
  services/imageWorker.ts
  services/oda.ts
  stores/nft.ts
  tests/e2e/collection.spec.ts
  tests/e2e/search.spec.ts
  tests/floorPrice.spec.ts
  utils/carousel.ts
  utils/ipfs.ts
  utils/math.ts
  utils/nft.ts
Labels: S-code-lgtm-✅

#11031 🔧 evm profile lowercase address
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileDetail.vue
  queries/subsquid/general/profileTabsCount.query.ts
  utils/address.ts
Labels: hacktoberfest-accepted

#11092 🔧 more from this collection & visited item
  components/carousel/CarouselTypeRelated.vue
  components/carousel/CarouselTypeVisited.vue
  components/gallery/GalleryItem.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅

#11088 fix: waiting times for mint
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useMultipleBalance.ts
Labels: S-code-lgtm-✅

#11093 (feat/beta): 25% of October 2024 Banana 🍌
  components/carousel/CarouselTypeRelated.vue
  components/carousel/CarouselTypeVisited.vue
  components/collection/CollectionCard.vue
  components/collection/CollectionDetail.vue
  components/collection/CollectionGrid.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/ActivityChart.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  components/collection/utils/types.ts
  components/collection/utils/useCollectionDetails.ts
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/shoppingCart/types.ts
  components/common/shoppingCart/utils.ts
  components/create/CreateNft.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemHolderOf.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemChart.vue
  components/gallery/UnlockableTag.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/utils/useIdentity.ts
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/items/ItemsGrid/useNftActions.ts
  components/landing/topCollections/utils/types.ts
  components/offer/OfferOverviewModal.vue
  components/offer/types.ts
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/service/NftUtils.ts
  components/search/SearchSuggestion.vue
  components/search/types.ts
  components/series/SeriesTable.vue
  components/series/utils.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/collectionActivity/types.ts
  composables/massmint/massMintHelpers.ts
  composables/useMultipleBalance.ts
  composables/useNft.ts
  composables/useUnlockable.ts
  stores/listingCart.ts
  stores/nft.ts
  tests/math.spec.ts
  types/index.ts
  utils/ipfs.ts
  utils/math.ts
  utils/mintUtils.ts
  utils/sorting.ts
Labels: beta

#11095 (feat/prod): 25% of October 2024 Banana 🍌
  components/carousel/CarouselTypeRelated.vue
  components/carousel/CarouselTypeVisited.vue
  components/collection/CollectionCard.vue
  components/collection/CollectionDetail.vue
  components/collection/CollectionGrid.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/ActivityChart.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  components/collection/utils/types.ts
  components/collection/utils/useCollectionDetails.ts
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/shoppingCart/types.ts
  components/common/shoppingCart/utils.ts
  components/create/CreateNft.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/GalleryItemHolderOf.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemChart.vue
  components/gallery/UnlockableTag.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/utils/useIdentity.ts
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/items/ItemsGrid/useNftActions.ts
  components/landing/topCollections/utils/types.ts
  components/offer/OfferOverviewModal.vue
  components/offer/types.ts
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/service/NftUtils.ts
  components/search/SearchSuggestion.vue
  components/search/types.ts
  components/series/SeriesTable.vue
  components/series/utils.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/collectionActivity/types.ts
  composables/massmint/massMintHelpers.ts
  composables/useMultipleBalance.ts
  composables/useNft.ts
  composables/useUnlockable.ts
  stores/listingCart.ts
  stores/nft.ts
  tests/math.spec.ts
  types/index.ts
  utils/ipfs.ts
  utils/math.ts
  utils/mintUtils.ts
  utils/sorting.ts
Labels: release

#11068 Trim trailing zeroes
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/offer/MakingOfferSingleItem.vue
  composables/useAmount.ts
Labels: S-code-lgtm-✅

#11118 (prod): 48% of October 2024 Cherry 🍒
  .github/diagram.svg
  components/common/ChooseCollectionDropdown.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/create/CreateNft.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemToolBar.vue
  components/massmint/types.ts
  components/offer/MakingOfferSingleItem.vue
  composables/massmint/massMintHelpers.ts
  composables/massmint/parsers/common.ts
  composables/massmint/parsers/parseJson.ts
  composables/massmint/useMassMint.ts
  composables/transaction/evm/useMetaTransaction.ts
  composables/useAmount.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  stores/wallet.ts
Labels: release

#11101 fix: Make offers on EVM
  components/common/ConnectWallet/ConnectEvm.vue
  components/common/ConnectWallet/ConnectSubstrate.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  utils/config/chain.config.ts
Labels: S-code-lgtm-✅

#11125 fix: Avatar image does not fit
  components/base/MediaItem.vue
  components/profile/ProfileDetail.vue
  components/shared/ProfileAvatar.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: S-works-for-me-✅

#11119 feat: code checker more validation
  components/codeChecker/CodeChecker.vue
  components/codeChecker/codechecker.config.js
  components/codeChecker/utils.ts
  components/codeChecker/validate.ts
Labels: S-works-for-me-✅

#11168 fix: Error encountered message: when clicked on mint
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  composables/drop/massmint/useDropMassMint.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#11157 perf: Improve `collectionForMint` query
  components/common/ChooseCollectionDropdown.vue
  composables/massmint/useMassMint.ts
  composables/useSubscriptionGraphql.ts
  queries/subsquid/general/collectionForMint.graphql
Labels: S-code-lgtm-✅
