Repository kodadot/nft-gallery, pull requests merged in 2024-01, with the labels that each got.

#8741 Fix/transfer
  components/transfer/Transfer.vue
  composables/useExistentialDeposit.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, large, waiting-for-review

#8778 fix: uppercase on network indicators
  assets/styles/components/_carousel.scss
  assets/styles/components/_nft-card.scss
  assets/styles/global.scss
  components/carousel/CarouselTypeLatestMints.vue
  components/carousel/module/CarouselInfo.vue
  components/collection/drop/modal/ConfirmEmail.vue
  components/collection/drop/modal/EmailSignup.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportTooltip.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/create/Confirm/ConfirmMintItem.vue
  components/create/Confirm/PriceItem.vue
  components/migrate/steps/Review.vue
  components/search/SearchSuggestion.vue
  components/shared/SkeletonLoader.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/nftCard/NftMediaInfo.vue
Labels: refactoring, ✅ - code-lgtm, ✅ - works-for-me, small, waiting-for-review

#8791 fix/hacking drop time
  components/collection/drop/Generative.vue
  components/drops/useDrops.ts
  utils/drop.ts
Labels: small, waiting-for-review

#8796 fix: Search by number not working
  components/items/ItemsGrid/useItemsGrid.ts
  components/items/ItemsGrid/utils/useSearchParams.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8783 fix: Audio NFT Sales thumbnail on popover not loading
  components/rmrk/Gallery/GalleryCard.vue
Labels: ✅ - code-lgtm, ✅ - works-for-me, small

#8806 🔧 link holder collection id
  components/collection/drop/HolderOfCollection.vue
Labels: small, waiting-for-review

#8808 fix: Buy now filter empty state
  components/profile/ProfileDetail.vue
Labels: ✅ - visual-ok, small, waiting-for-review

#8809 trigger 'buy-now' filter when sorting by price
  components/items/ItemsGrid/useItemsGrid.ts
Labels: ✅ - visual-ok, small, waiting-for-review

#8758 ref: Refactor Generative.vue
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintSection.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/drops/useDrops.ts
  composables/drop/useGenerativeDropDetails.ts
  composables/drop/useGenerativeDropMint.ts
  composables/drop/useGenerativeDropNewsletter.ts
  composables/useAmount.ts
  composables/useGraphql.ts
  locales/en.json
  utils/newsletter.ts
Labels: large, waiting-for-review, 🤝-resolve-merge-conflicts

#8807 ⬆️ nuxt 3.9 & vue 3.4
  middleware/redirects.global.ts
  package.json
  pages/[prefix]/index.vue
  pnpm-lock.yaml
Labels: 🤞 - changes-requested, large, waiting-for-review

#8821 fix: Auto teleport tooltip
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportPopover.vue
  components/common/autoTeleport/AutoTeleportTooltip.vue
Labels: ✅ - works-for-me, ✅ - visual-ok, medium, waiting-for-review

#8823 fix: Auto teleport active
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
Labels: ✅ - visual-ok, small, waiting-for-review

#8818 fix: Share link in success message
  components/MessageNotify.vue
  components/buy/Buy.vue
  components/common/ShareDropdown.vue
  composables/transaction/types.ts
  composables/useTransaction.ts
  utils/notification.ts
Labels: ✅ - works-for-me, small, waiting-for-review

#8437 feat: enable burns on migration
  components/base/MediaItem.vue
  components/migrate/landing/header/Faq.vue
  components/migrate/steps/Review.vue
  components/migrate/steps/SignLoader3.vue
  composables/useMigrate.ts
  nuxt.config.ts
  utils/ipfs.ts
Labels: ✅ - code-lgtm, 🤞 - changes-requested, medium, waiting-for-review, 🤝-resolve-merge-conflicts

#8829 set oruga to 7
  libs/ui/package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#8825 ➖ unused dependencies
  middleware/redirects.global.ts
  package.json
  pnpm-lock.yaml
Labels: large, waiting-for-review

#8817 feat: Add network filter to top collection
  components/common/ChainDropdown.vue
  components/landing/topCollections/TopCollections.vue
  components/landing/topCollections/utils/useTopCollections.ts
Labels: ✅ - code-lgtm, ✅ - works-for-me, medium

#8842 feat: Implement paid drop
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/MintSection.vue
  components/collection/drop/PaidGenerative.vue
  components/drops/DropCard.vue
  components/drops/useDrops.ts
  composables/drop/useGenerativeDropDetails.ts
  pages/[prefix]/drops/[id].vue
  params/types.ts
  services/waifu.ts
Labels: ✅ - works-for-me, large, waiting-for-review

#8838 feat: Claim congrats message improvements
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/SuccessfulDrop.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
Labels: 🤞 - changes-requested, visual change, ✅ - visual-ok, small, waiting-for-review

#8729 fix: videos in collection are not loading
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
Labels: ✅ - code-lgtm, 🤞 - changes-requested, small, waiting-for-review

#8848 feat: Paid drop improvements
  .vscode/settings.json
  assets/styles/abstracts/_theme.scss
  assets/styles/global.scss
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/newsletter/ConfirmEmail.vue
  components/collection/drop/modal/newsletter/EmailSignup.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/drop/modal/shared/WaitingDrop.vue
  components/collection/drop/modal/utils.ts
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/utils.ts
  components/common/confirmPurchaseModal/ConfirmNftPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleportTransactionActions.ts
  composables/drop/useGenerativeDropMint.ts
  composables/useAmount.ts
  locales/en.json
Labels: ✅ - works-for-me, large, waiting-for-review

#8810 feat: defaultSuggestion on search
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/CollectionInfo.vue
  components/collection/HeroButtons.vue
  components/collection/drop/HolderOfCollection.vue
  components/collection/utils/useCollectionDetails.ts
  components/landing/topCollections/utils/useTopCollections.ts
  components/search/SearchBar.vue
  components/search/SearchSuggestion.vue
  components/search/types.ts
  composables/popularCollections/usePopularCollections.ts
  queries/subsquid/general/topCollections.graphql
  utils/collection.ts
Labels: 🤞 - changes-requested, medium, waiting-for-review, 🤝-resolve-merge-conflicts

#8851 fix: neo button text conflicts
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: small, waiting-for-review

#8853 fix: Drop mobile visualization
  components/collection/drop/MintSection.vue
Labels: small, waiting-for-review

#8859 :wrench: prefer cloudflare service
  composables/drop/useGenerativeDropMint.ts
Labels: small, waiting-for-review

#8860 beta update
  composables/drop/useGenerativeDropMint.ts
Labels: beta

#8861 release update
  composables/drop/useGenerativeDropMint.ts
Labels: release

#8873 🔧 undefined consola
  composables/useTransaction.ts
Labels: small, waiting-for-review

#8871 🔧 NeoSkeleton color
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.scss
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8869 🔧 mint drop modal
  components/collection/drop/modal/paid/MintOverview.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8870 🔧 massmint modal price
  components/massmint/EditPanel.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8874 fix: minting drop for the second time
  components/drops/useDrops.ts
Labels: small, waiting-for-review

#8875 fix: List NFT floor price button doesn't work
  components/collection/utils/useCollectionDetails.ts
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  queries/subsquid/general/nftById.graphql
Labels: small, waiting-for-review

#8876 🔧 search suggestion ranking link
  components/search/SearchSuggestion.vue
  libs/ui/src/components/NeoTable/NeoTable.vue
Labels: ✅ - works-for-me, small, waiting-for-review

#8171 feat: unify metadata on gallery detail page
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/useGalleryItem.ts
  components/rmrk/service/scheme.ts
  composables/useNft.ts
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  services/imageWorker.ts
Labels: medium, waiting-for-review

#8898 clean: post cleanup after Basilisk
  components/collection/utils/types.ts
  components/collection/utils/useCollectionDetails.ts
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/shared/CommonTokenMoney.vue
  composables/useChainRedirect.ts
  composables/useTransaction.ts
  locales/de.json
  locales/en.json
  locales/es.json
  locales/pt.json
  locales/ru.json
  locales/ua.json
  queries/subsquid/general/collectionStatsByIdWithOffers.graphql
  utils/offerStatus.ts
Labels: medium, waiting-for-review

#8896 🔧 drop ended
  components/drops/DropCard.vue
Labels: refactoring, ✅ - works-for-me, small, waiting-for-review

#8893 🔧 input number price listing modal
  components/common/listingCart/shared/ListingCartPriceInput.vue
Labels: refactoring, ✅ - works-for-me, small, waiting-for-review

#8888 🔧 hotfix top collection loading
  components/search/SearchSuggestion.vue
Labels: small, waiting-for-review

#8885 🔧 price acitvity dropdown
  components/chart/PriceChart.vue
Labels: small, waiting-for-review

#8877 🔧 create collection for mint
  queries/subsquid/general/collectionForMint.graphql
  queries/subsquid/rmrk/collectionForMint.graphql
Labels: ✅ - works-for-me, small, waiting-for-review, A-migration

#8914 feat: Implement on-site image capturing for drops
  composables/drop/useGenerativeDropMint.ts
Labels: S-works-for-me-✅, small, waiting-for-review

#8903 fix: One decimal in top collections should be enough
  components/landing/topCollections/TopCollectionsItem.vue
  components/shared/format/Money.vue
  utils/format/balance.ts
Labels: S-works-for-me-✅, small, waiting-for-review

#8900 fix: Disable button when minted out even when not connected with wallet
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
Labels: S-works-for-me-✅, small

#8912 fix: Remove offers since we donot have them anymore
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
Labels: S-works-for-me-✅, small, waiting-for-review

#8907 feat: Show traders with identities in collection
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/collection/activity/utils.ts
  components/common/IdentityForm.vue
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/SidebarFilter.vue
  components/shared/filters/modules/IdentityVerficationFilter.vue
  composables/useIdentity.ts
  locales/en.json
  queries/subsquid/general/identities.graphql
  stores/activityFilters.ts
Labels: S-works-for-me-✅, S-visual-ok-✅, medium, waiting-for-review

#8916 fix: Offer.status in burger menu collection
  components/shared/filters/modules/StatusFilter.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅, small, waiting-for-review

#8918 fix: Massmint price on ahp being multiplied
  components/massmint/OverviewTable.vue
Labels: S-code-lgtm-✅, paid, S-works-for-me-✅, small, waiting-for-review

#8897 🔧 display Kodadot fee on buy
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  locales/en.json
Labels: S-changes-requested-🤞, small, waiting-for-review

#8932 Revert "fix: One decimal in top collections should be enough"
  components/landing/topCollections/TopCollectionsItem.vue
  components/shared/format/Money.vue
  utils/format/balance.ts
Labels: small, waiting-for-review

#8919 fix: Supply has been set but shows unlimited on collection page
  composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, small, waiting-for-review

#8935 fix: Empty collection should be visible only for the owner
  components/collection/CollectionGrid.vue
  components/profile/ProfileDetail.vue
Labels: small, waiting-for-review

#8937 Revert "Revert "fix: One decimal in top collections should be enough""
  components/landing/topCollections/TopCollectionsItem.vue
  components/shared/format/Money.vue
  utils/format/balance.ts
Labels: S-works-for-me-✅, small, waiting-for-review

#8939 :wrench: the usual
  utils/drop.ts
Labels: small, waiting-for-review

#8948 :wrench: drop date
  utils/drop.ts
Labels: small, waiting-for-review

#8922 fix: hard limit carousel
  components/carousel/CarouselTypeGenerative.vue
  components/carousel/module/CarouselInfo.vue
  components/carousel/utils/useCarouselEvents.ts
Labels: S-works-for-me-✅, medium, waiting-for-review

#8944 feat: Paid drop followups
  assets/styles/abstracts/_theme.scss
  assets/styles/global.scss
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/common/autoTeleport/AutoTeleportPopover.vue
  components/drops/useDrops.ts
  composables/useAmount.ts
  composables/useChain.ts
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  locales/en.json
Labels: S-works-for-me-✅, medium, waiting-for-review

#8951 feat: If wallet empty = bigger button for Add Funds
  components/balance/MultipleBalances.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetPortfolio.vue
  locales/en.json
Labels: paid, S-works-for-me-✅, small, waiting-for-review

#8917 feat: Check listing prices of nfts when loading confirm modal
  components/buy/Buy.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  composables/useSubscriptionGraphql.ts
  locales/en.json
Labels: paid, S-works-for-me-✅, medium

#8962 feat: "See listings" in drop page
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/MintSection.vue
Labels: small, waiting-for-review

#8688 fix: sanitize ipfs url
  package.json
  pnpm-lock.yaml
  tests/utils/ipfs.test.ts
  utils/ipfs.ts
Labels: S-code-lgtm-✅, medium, waiting-for-review, S-resolve-merge-conflicts-🤝

#8969 feat: setup Microsoft Clarity
  nuxt.config.ts
Labels: small, waiting-for-review

#8975 style: whitespace-nowrap
  assets/styles/global.scss
  components/chart/PriceChart.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/collectionInfoLine.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/ImageSlider.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/create/Confirm/ConfirmMintItem.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/navbar/NavbarExploreOptions.vue
  components/transfer/Transfer.vue
Labels: small

#8964 feat: migrate button on collection page
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  locales/en.json
Labels: S-code-lgtm-✅, S-changes-requested-🤞, S-visual-ok-✅, small, waiting-for-review

#8966 style: signing on migration page
  assets/styles/global.scss
  components/migrate/steps/Sign.vue
  components/migrate/steps/SignLoader.vue
  components/migrate/steps/SignLoader1.vue
  components/migrate/steps/SignLoader2.vue
  components/migrate/steps/SignLoader3.vue
  composables/useMigrate.ts
Labels: S-works-for-me-✅, small, waiting-for-review

#8963 fix: Unnecessary zeros
  components/collection/drop/PaidGenerative.vue
  components/drops/useDrops.ts
  components/shared/format/Money.vue
  composables/useAmount.ts
  utils/format/balance.ts
Labels: S-works-for-me-✅, S-visual-ok-✅, small, waiting-for-review

#8976 fix: Skeleton for drops
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
Labels: S-visual-ok-✅, medium, waiting-for-review

#8990 fix: Swap newsletter subscription with generative strip
  components/landing/LandingPage.vue
Labels: S-works-for-me-✅, small, waiting-for-review

#8991 fix: Collection hover card
  assets/styles/components/_nft-card.scss
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/identity/module/IdentityPopoverFooter.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: S-works-for-me-✅, S-visual-ok-✅, small, waiting-for-review

#8992 fix: Whole card clickable
  assets/styles/components/_carousel.scss
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
  components/carousel/module/CarouselMedia.vue
Labels: S-works-for-me-✅, S-visual-ok-✅, small, waiting-for-review

#9001 refactor: remove background-color on global.scss
  assets/styles/global.scss
  components/base/MediaItem.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/unlockable/CountdownTimer.vue
  components/collection/unlockable/ImageSlider.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/autoTeleport/AutoTeleportPopover.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/create/Confirm/PriceItem.vue
  components/create/CreateNftPreview.vue
  components/massmint/EditPanel.vue
  components/migrate/steps/Index.vue
  components/profile/CollectionFilter.vue
  components/shared/filters/MobileFilter.vue
Labels: medium, waiting-for-review

#9018 🔧 text-align to tailwind
  assets/styles/abstracts/_animations.scss
  assets/styles/components/_tippy.scss
  assets/styles/global.scss
  assets/styles/pages/create.scss
  components/Error.vue
  components/balance/MultipleBalances.vue
  components/base/MediaItem.vue
  components/collection/CollectionDetail.vue
  components/collection/CollectionInfo.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/MintSection.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/EmptyResult.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/autoTeleport/AutoTeleportPopover.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/create/CreateLanding.vue
  components/create/CreateNftPreview.vue
  components/drops/TimeTag.vue
  components/explore/ActiveCount.vue
  components/explore/ExploreSort.vue
  components/gallery/GalleryItemAction/GalleryItemActionSection.vue
  components/hot/HotTable.vue
  components/landing/HeroBanner.vue
  components/landing/topCollections/TopCollections.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/massmint/uploadDescription/UploadDescription.vue
  components/migrate/landing/content/Index.vue
  components/navbar/ChainSelectDropdown.vue
  components/profile/OrderByDropdown.vue
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileEmptyResult.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/sales/SalesTable.vue
  components/search/SearchSuggestion.vue
  components/series/SeriesTable.vue
  components/shared/DragDrop.vue
  components/shared/DropUpload.vue
  components/shared/Loader.vue
  components/shared/ResponsiveTable.vue
  components/shared/TransactionLoader.vue
  components/shared/format/StatsColumn.vue
  components/shared/modals/ModalWrapper.vue
  components/shared/modals/keyboardShortcutsModal.vue
  components/spotlight/SpotlightTable.vue
  components/teleport/FundsAtRiskWarning.vue
  layouts/error.vue
  layouts/generative-mint-layout.vue
  libs/ui/src/components/NeoCarousel/NeoCarousel.story.vue
  pages/blog/index.vue
  pages/migrate/congrats.vue
  pages/qrCode.vue
Labels: medium, waiting-for-review

#9019 🔧 pointer-events to tailwind
  assets/styles/components/_search.scss
  assets/styles/components/_toast.scss
  assets/styles/global.scss
  assets/styles/pages/create.scss
  components/collection/activity/FilterFloatButton.vue
  components/explore/FilterMenuButton.vue
  components/shared/modals/ModalBody.vue
  components/shared/view/SelectableImage.vue
Labels: medium, waiting-for-review

#9025 Updating to the new drop
  utils/drop.ts
Labels: small, waiting-for-review

#8998 refactor: remove border on global.scss
  assets/styles/global.scss
  components/Navbar.vue
  components/base/MediaItem.vue
  components/blog/BlogPost.vue
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/activity/OwnerInsights.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableSchedule.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/identity/IdentityConfirmModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/create/Confirm/PriceItem.vue
  components/create/CreateNftPreview.vue
  components/drops/CreateDropCard.vue
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/massmint/EditPanel.vue
  components/massmint/OverviewTable.vue
  components/massmint/modals/DeleteModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/ReviewModal.vue
  components/profile/CollectionFilter.vue
  components/profile/ProfileDetail.vue
  components/redirect/RedirectModal.vue
  components/rmrk/Gallery/EmotionList.vue
  components/shared/Loader.vue
  components/shared/OnRampModal.vue
  components/shared/TransactionLoader.vue
  components/shared/filters/MobileFilter.vue
  components/shared/filters/modules/EventTypeFilter.vue
  components/shared/filters/modules/IdentityVerficationFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/PriceFilter.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/modals/ModalBody.vue
  components/shared/nftCard/NftMediaInfoStacked.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  libs/ui/src/components/CardArticle/CardArticle.vue
  pages/blog/index.vue
Labels: large, waiting-for-review

#9022 🔧 border-radius to tailwind
  assets/styles/components/_card.scss
  assets/styles/components/_collection-card.scss
  assets/styles/components/_connect-wallet.scss
  assets/styles/components/_gallery-item.scss
  assets/styles/components/_keyboard-shortcut.scss
  assets/styles/components/_scroll-to-top-button.scss
  assets/styles/components/_search.scss
  assets/styles/global.scss
  assets/styles/layouts/_footer.scss
  assets/styles/layouts/_main-navigation.scss
  components/MessageNotify.vue
  components/base/MediaItem.vue
  components/blog/BlogPost.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/unlockable/ImageSlider.vue
  components/collection/unlockable/UnlockableSlider.vue
  components/collection/unlockable/UnlockableTag.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/NotificationBox/NotificationItem.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/CreateLanding.vue
  components/drops/TimeTag.vue
  components/explore/ActiveCount.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/gallery/UnlockableTag.vue
  components/massmint/OnBoarding.vue
  components/migrate/landing/header/Faq.vue
  components/profile/CollectionFilter.vue
  components/rmrk/Gallery/EmotionModal.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/shared/Avatar.vue
  components/shared/ModalIdentityItem.vue
  components/shared/TransactionLoader.vue
  components/shared/gallery/NeoTag.vue
  components/shared/view/BasicImage.vue
  libs/ui/src/components/NeoSecondaryButton/NeoSecondaryButton.scss
  libs/ui/src/components/NeoSecondaryButton/NeoSecondaryButton.vue
  pages/blog/index.vue
Labels: large, waiting-for-review

#9021 🔧 cursor-pointer to tailwind
  assets/styles/components/_carousel-arrows.scss
  assets/styles/components/_carousel.scss
  assets/styles/components/_collection-card.scss
  assets/styles/components/_gallery-item.scss
  assets/styles/components/_search.scss
  assets/styles/global.scss
  assets/styles/layouts/_footer.scss
  assets/styles/layouts/_main-navigation.scss
  components/Navbar.vue
  components/collection/activity/OwnerInsights.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/create/Confirm/PriceItem.vue
  components/create/CreateLanding.vue
  components/drops/CreateDropCard.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/massmint/OverviewTable.vue
  components/migrate/MigrateModal.vue
  components/migrate/landing/header/Faq.vue
  components/migrate/steps/Review.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/OnRampModal.vue
  components/shared/audioPlayer/AudioPlayer.vue
  components/shared/chart/LineChart.vue
  components/shared/gallery/NeoTag.vue
  components/shared/view/SelectableImage.vue
  components/teleport/Teleport.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
Labels: medium, waiting-for-review

#8994 fix: Cursor non pointer migrate overview
  components/migrate/steps/Review.vue
Labels: S-works-for-me-✅, S-visual-ok-✅, small, waiting-for-review

#9017 🔧 z-index to tailwind
  assets/styles/abstracts/_animations.scss
  assets/styles/components/_collection-card.scss
  assets/styles/components/_modal.scss
  assets/styles/components/_nft-card.scss
  assets/styles/components/_search.scss
  assets/styles/components/_toast.scss
  assets/styles/global.scss
  assets/styles/layouts/_footer.scss
  assets/styles/layouts/_main-navigation.scss
  components/CookieBanner.vue
  components/carousel/module/CarouselMedia.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/unlockable/ImageSlider.vue
  components/common/NotificationBox/NotificationBoxModal.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartMini.vue
  components/create/Confirm/MintConfirmModal.vue
  components/drops/CreateDropGallery.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemActionSlides.vue
  components/hot/HotTable.vue
  components/landing/SignupBanner.vue
  components/redirect/RedirectModal.vue
  components/redirect/useRedirectModal.ts
  components/rmrk/Gallery/GalleryCard.vue
  components/sales/SalesTable.vue
  components/series/SeriesTable.vue
  components/shared/SkeletonLoader.vue
  components/shared/filters/MobileFilter.vue
  pages/blog/index.vue
Labels: large, waiting-for-review

#9031 :bug: forgot to update the drop date
  utils/drop.ts
Labels: small, waiting-for-review

#8993 feat: On hover show absolute date of onchain event
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  components/common/TimeAgo.vue
  components/profile/activityTab/History.vue
  components/rmrk/Gallery/Flipper.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/Holder/helper.ts
  components/sales/SalesTable.vue
  utils/datetime.ts
  utils/historyEvent.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, small, waiting-for-review

#9030 chore: remove collection offer button
  components/explore/DesktopControls.vue
  components/explore/ExploreOffer.vue
  components/explore/MobileControls.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#8995 Migrate to vue chart js
  components/chart/PriceChart.vue
  package.json
  pnpm-lock.yaml
  utils/chart.ts
Labels: S-code-lgtm-✅, large, waiting-for-review

#9034 🔧 undefined bg colors
  components/collection/activity/events/eventRow/common.ts
  components/common/NotificationBox/useNotification.ts
  components/transfer/Transfer.vue
  composables/massmint/useMassMint.ts
Labels: small, waiting-for-review

#8968 fix: Better fullscreen mode for generative art
  components/gallery/GalleryItem.vue
Labels: small, waiting-for-review, S-resolve-merge-conflicts-🤝

#8965 fix: Transfer: batch payment link not working properly
  components/shared/AddressChecker.vue
  components/transfer/Transfer.vue
  tests/e2e/transfer.spec.ts
Labels: S-works-for-me-✅, medium, waiting-for-review

#9028 refactor: remove-color-global-scss
  assets/styles/global.scss
  components/chart/PriceChart.vue
  components/collection/ConfirmDeleteCollectionModal.vue
  components/collection/CustomizeModal.vue
  components/collection/activity/ownerInsightsTabs/FlipperTab.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Flipper.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  components/collection/drop/modal/newsletter/ConfirmEmail.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/create/Confirm/ConfirmMintItem.vue
  components/massmint/OverviewTable.vue
  components/massmint/modals/MintingModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/ReviewModal.vue
  components/migrate/steps/Index.vue
  components/migrate/steps/Review.vue
  components/migrate/steps/SignLoader1.vue
  components/navbar/NavbarExploreOptions.vue
  components/shared/DragDrop.vue
  components/shared/PillTabs.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/teleport/FundsAtRiskWarning.vue
  components/teleport/Teleport.vue
  composables/useMigrate.ts
  layouts/error.vue
  locales/en.json
Labels: S-code-lgtm-✅, medium, S-resolve-merge-conflicts-🤝

#9065 fix: View collection button bigger
  components/collection/unlockable/UnlockableCollectionInfo.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/types.ts
Labels: S-visual-ok-✅, small, waiting-for-review

#9078 fix: Mobile top collections missing USD
  components/landing/topCollections/TopCollectionsItem.vue
Labels: small, waiting-for-review

#9080 fix: stroke in profile collection filter and mobile tabs
  components/profile/CollectionFilter.vue
  components/profile/ProfileDetail.vue
Labels: S-visual-ok-✅, small, waiting-for-review

#9100 feat: Bigger collection filter in profile
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
Labels: small, waiting-for-review

#9077 fix: Remove offer from collection activity filter
  components/shared/filters/modules/EventTypeFilter.vue
Labels: paid, small, waiting-for-review

#9061 fix: Can we fix this blog post
  components/blog/BlogPost.vue
  content/blog/kodadots-drop-page-explained.md
  content/blog/the-power-of-polkadots-Asset-hub-Revolutionizing-asset-management.md
  content/blog/upcoming-nft-events-the-ultimate-guide-to-2023s-most-anticipated-gatherings.md
Labels: small, waiting-for-review, docs

#9079 fix: Explore on other networks profile button
  components/profile/ProfileEmptyResult.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/types.ts
Labels: S-visual-ok-✅, small, waiting-for-review

#9076 :bug: unable to retrieve keypair is basically when someone clears localstorage
  utils/transactionExecutor.ts
Labels: small, waiting-for-review

#9098 fix: top collection mobile chain dropdown
  components/common/ChainDropdown.vue
  components/landing/topCollections/TopCollections.vue
Labels: small, waiting-for-review

#9057 fix: Missing rest of sales/lists on collection while using filter
  components/collection/activity/events/Events.vue
Labels: small, waiting-for-review

#9081 fix: Weird hover in connect wallet
  assets/styles/components/_connect-wallet.scss
Labels: S-visual-ok-✅, small, waiting-for-review

#9086 fix: Transfer transaction loader modal broken
  components/shared/TransactionLoader.vue
  components/transfer/Transfer.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9084 fix: Price chart on resize error
  components/chart/PriceChart.vue
Labels: small, waiting-for-review

#9041 🔧 typography helpers to tailwind
  components/collection/CollectionInfo.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
  components/shared/TransactionLoader.vue
  components/shared/form/BasicNumberInput.vue
  components/shared/gallery/Properties.vue
  components/transfer/TransferConfirmModal.vue
  pages/cookie-notice.vue
  pages/privacy-policy.vue
Labels: small, waiting-for-review, S-resolve-merge-conflicts-🤝

#9099 fix: link color override
  assets/styles/global.scss
Labels: S-changes-requested-🤞, small, waiting-for-review

#9106 fix: lock file
  .github/workflows/build.yml
  pnpm-lock.yaml
Labels: large, waiting-for-review

#9108 build: remove unused packages
  .npmrc
  libs/ui/package.json
  package.json
  pnpm-lock.yaml
  script/generate.mjs
  utils/types/emoji-unicode.d.ts
Labels: S-code-lgtm-✅, paid, large, waiting-for-review

#9110 fix/deny washed
  components/landing/topCollections/utils/useTopCollections.ts
  queries/subsquid/general/topCollections.graphql
  utils/constants.ts
Labels: small, waiting-for-review

#9088 Translated a new language - hi.json
  locales/hi.json
Labels: S-changes-requested-🤞, paid, large, waiting-for-review

#9115 feat: Profile sidebar improvements
  components/balance/MultipleBalances.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletAssetSetIdentity.vue
  components/identity/IdentityItem.vue
  locales/en.json
Labels: S-code-lgtm-✅, medium, waiting-for-review

#9118 🇮🇳 hindi translation
  locales/hi.json
  utils/config/i18n.ts
Labels: S-code-lgtm-✅, small, waiting-for-review

#9117 fix: Collection profile mobile filter missing styles
  components/shared/filters/MobileFilter.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9114 feat: Transfer nfts show fees
  components/common/itemTransfer/ItemTransferModal.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9111 fix: Item activity mobile
  libs/ui/src/components/NeoTable/NeoTable.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9113 #9112
  components/profile/ProfileActivitySummery.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9124 :wrench: alchemy drop
  utils/drop.ts
Labels: small, waiting-for-review

#9122 fix/deprecated transfer
  components/collection/drop/HolderOfGenerative.vue
  components/transfer/Transfer.vue
  composables/transaction/transactionBuy.ts
  package.json
  pnpm-lock.yaml
  utils/support.ts
  utils/transactionExecutor.ts
Labels: S-code-lgtm-✅, large, waiting-for-review

#9127 beta update
  components/collection/drop/HolderOfGenerative.vue
  components/transfer/Transfer.vue
  composables/transaction/transactionBuy.ts
  package.json
  pnpm-lock.yaml
  utils/support.ts
  utils/transactionExecutor.ts
Labels: beta

#9128 release update
  components/collection/drop/HolderOfGenerative.vue
  components/transfer/Transfer.vue
  composables/transaction/transactionBuy.ts
  package.json
  pnpm-lock.yaml
  utils/support.ts
  utils/transactionExecutor.ts
Labels: release, large

#9133 feat: "Add NFTs" in collection dropdown flow improvement
  components/collection/HeroButtonAddNfts.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/massmint/Massmint.vue
  composables/useCollectionDropdown.ts
Labels: S-code-lgtm-✅, paid, small, waiting-for-review

#9134 fix: Small things in the hover card
  components/base/MediaItem.vue
  components/rmrk/Gallery/GalleryCard.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9129 :ambulance: max on XCM results in loss of funds
  components/teleport/Teleport.vue
Labels: small, waiting-for-review

#9002 feat: Signing modal consistency
  components/buy/Buy.vue
  components/collection/HeroButtonDeleteCollection.vue
  components/collection/HeroButtonDeleteNfts.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/shared/WaitingDrop.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/shared/SigningModal/SigningModal.vue
  components/shared/SigningModal/SigningModalBody.vue
  components/shared/SkeletonLoader.vue
  components/shared/modals/ModalBody.vue
  components/teleport/Teleport.vue
  locales/en.json
Labels: S-changes-requested-🤞, large, waiting-for-review

#9140 chore: bump @nuxtjs/sitemap version
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
Labels: S-code-lgtm-✅, large, waiting-for-review

#9141 chore: upgrade to Node.js v20
  .github/actions/pnpm-install/action.yml
  .github/workflows/build.libs-ui.yml
  .github/workflows/playwright.yml
  .github/workflows/reviewdog.yml
  .node-version
  Dockerfile
  content/blog/first-time.md
  netlify.toml
  package.json
Labels: S-code-lgtm-✅, small, waiting-for-review

#9148 🔧 drop collection path
  components/collection/drop/MintSection.vue
  components/collection/unlockable/utils/useUnlockableTag.ts
Labels: S-works-for-me-✅, small, waiting-for-review

#9135 feat: More cards on mobile carousels
  assets/styles/components/_carousel.scss
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
Labels: S-visual-ok-✅, small, waiting-for-review

#9109 Add royalties to collection mint
  components/create/CreateCollection.vue
  composables/transaction/mintCollection/transactionMintCollectionStatemine.ts
  composables/transaction/types.ts
Labels: S-code-lgtm-✅, small, waiting-for-review

#9168 fix: Extend generative strip to 24 items from AHP
  assets/styles/components/_carousel-arrows.scss
  components/carousel/utils/useCarouselEvents.ts
Labels: medium, waiting-for-review

#9156 feat: Estimate in signing modal
  components/shared/SigningModal/SigningModal.vue
  components/shared/SigningModal/SigningModalBody.vue
  components/shared/SkeletonLoader.vue
  components/shared/TransactionLoader.vue
  composables/useBlockTime.ts
  composables/useTransactionEstimatedTime.ts
Labels: S-visual-ok-✅, small, waiting-for-review

#9161 feat: NFT #Number not showing in profiles
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/profile/ProfileDetail.vue
  components/shared/nftCard/NftCard.vue
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/types.ts
Labels: small, waiting-for-review

#9143 🔧 text-overflow to tailwind
  assets/styles/components/_carousel.scss
  assets/styles/components/_collection-card.scss
  assets/styles/components/_search.scss
  assets/styles/global.scss
  components/carousel/CarouselTypeLatestMints.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/create/Confirm/ConfirmMintItem.vue
  components/massmint/OverviewTable.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/search/SearchSuggestion.vue
Labels: medium, waiting-for-review

#9158 fix: Disable buy on rmrk/ksm
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
Labels: paid, small, waiting-for-review

#8967 fix(drop): nft overlap for same user
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/unlockable/utils.ts
  composables/drop/useGenerativeDropMint.ts
Labels: small, waiting-for-review

#9189 🔧 is-block to tailwind
  components/common/autoTeleport/AutoTeleportModal.vue
  components/search/SearchSuggestion.vue
  pages/blog/index.vue
Labels: small, waiting-for-review

#9188 🔧 is-inline-block to tailwind
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/gallery/GalleryItemDescription.vue
  components/profile/activityTab/HistoryRow.vue
  components/shared/format/BasicMoney.vue
  components/shared/format/Money.vue
  components/shared/format/PriceRange.vue
Labels: small, waiting-for-review

#9196 Update ParaSpell SDK 3.1.1->4.0.1
  package.json
  pnpm-lock.yaml
Labels: small, waiting-for-review

#9131 fix: Cart not opening as a menu item
  assets/styles/global.scss
  components/Navbar.vue
  components/navbar/CreateDropdown.vue
  components/navbar/ShoppingCartButton.vue
Labels: paid, S-works-for-me-✅, small, waiting-for-review

#9166 Faster Loading wheel
  libs/ui/tailwind.config.js
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅, small, waiting-for-review

#9160 feat: Loading modal copy variations
  components/shared/SkeletonLoader.vue
  components/shared/modals/ModalBody.vue
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅, small, waiting-for-review

#9184 fix: parentnode
  components/shared/OnRampModal.vue
  package.json
  pnpm-lock.yaml
  tests/e2e/navigation.spec.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, large

#9187 🔧 is-relative to tailwind
  components/collection/CollectionDetail.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/explore/FilterMenuButton.vue
  components/gallery/GalleryItem.vue
  components/landing/HeroBanner.vue
  components/landing/SignupBanner.vue
  components/massmint/OnBoarding.vue
  components/migrate/landing/content/Ready.vue
  components/migrate/landing/content/Waiting.vue
  components/migrate/landing/header/Index.vue
  components/navbar/ShoppingCartButton.vue
  components/shared/modals/ModalBody.vue
  components/shared/nftCard/NftCard.vue
  components/teleport/Teleport.vue
  components/transfer/Transfer.vue
Labels: S-works-for-me-✅, small

#9205 replace `is-flex-*` with tailwind equivalent
  components/collection/activity/Activity.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/HolderOfCollection.vue
  components/gallery/GalleryItemHolderOf.vue
  components/landing/HeroBanner.vue
  components/migrate/steps/SignLoader3.vue
  components/profile/CollectionFilter.vue
  components/teleport/EDWarningModal.vue
  components/teleport/FundsAtRiskWarning.vue
Labels: small, waiting-for-review

#9204 fix: Modal title changing according to loading text
  components/shared/modals/ModalBody.vue
Labels: S-code-lgtm-✅, small, waiting-for-review

#9180 🔧 delist title modal signing
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  locales/en.json
Labels: S-works-for-me-✅, small, waiting-for-review

#9170 Replace the implementation of royalty tooltip with tippy
  assets/styles/components/_tippy.scss
  components/collection/CollectionInfo.vue
  plugins/vueTippy.ts
Labels: paid, S-works-for-me-✅, S-visual-ok-✅, medium, waiting-for-review

#9209 replace has-text- helpers with tailwind equivalent
  components/carousel/CarouselTypeLatestMints.vue
  components/collection/CollectionInfo.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/activity/events/eventRow/EventRowTablet.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfCollection.vue
  components/collection/drop/MintSection.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/collection/voteDrop/DropContainer.vue
  components/collectionDetailsPopover/CollectionDetailsPopoverContent.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/autoTeleport/AutoTeleportPopover.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  components/drops/DropCard.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/UnlockableTag.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/landing/topCollections/TopCollectionsItem.vue
  components/massmint/OnBoarding.vue
  components/profile/CollectionFilter.vue
  components/profile/activityTab/HistoryRow.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/search/SearchCollection.vue
  components/series/SeriesTable.vue
  components/shared/Loader.vue
  components/shared/OnRampModal.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/filters/modules/AdvancedFilter.vue
  components/shared/form/BasicNumberInput.vue
  components/shared/gallery/Properties.vue
  components/teleport/FundsAtRiskWarning.vue
  layouts/error.vue
Labels: S-code-lgtm-✅, medium, waiting-for-review

#9212 ci: histoire model-viewer
  libs/ui/package.json
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  libs/ui/src/components/NeoAvatar/NeoAvatar.vue
  libs/ui/src/components/TheImage/TheImage.vue
  pnpm-lock.yaml
Labels: S-code-lgtm-✅, large, waiting-for-review
