Repository kodadot/nft-gallery, pull requests merged in 2024-11, with the labels that each got.

#11176 🔧 action list price is_null
  components/items/ItemsGrid/useNftActions.ts
Labels: S-changes-requested-🤞

#11171 feat: Edit Collection & NFT UI
  components/collection/CollectionCard.vue
  components/collection/CollectionHeader.vue
  components/collection/CollectionInfo.vue
  components/collection/CustomizeModal.vue
  components/collection/EditModal.vue
  components/collection/HeroButtonCustomizeCollection.vue
  components/collection/HeroButtonEditCollection.vue
  components/collection/HeroButtonRefreshMetadata.vue
  components/collection/HeroButtons.vue
  components/collection/edit/Section.vue
  components/collection/utils/useCollectionDetails.ts
  components/common/EditNftModal.vue
  components/common/form/FormLogoField.vue
  components/common/form/FormOverrideFile.vue
  components/gallery/GalleryItemButton/GalleryItemEditNftButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/useGalleryItem.ts
  components/rmrk/Create/CustomAttributeInput.vue
  composables/transaction/mintCollection/constructMeta.ts
  composables/transaction/mintToken/constructDirectoryMeta.ts
  composables/transaction/mintToken/constructMeta.ts
  composables/transaction/transactionSetCollectionMaxSupply.ts
  composables/transaction/transactionSetNftMetadata.ts
  composables/transaction/transactionUpdateCollection.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useSubscriptionGraphql.ts
  composables/useTransaction.ts
  locales/en.json
  package.json
  pnpm-lock.yaml
  queries/fragments/collectionDetails.graphql
  services/nftStorage.ts
  services/oda.ts
  types/index.ts
Labels: S-code-lgtm-✅

#11196 fix: only collection issuer can edit NFT
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  queries/subsquid/ahk/nftById.graphql
  queries/subsquid/general/nftById.graphql
  queries/subsquid/ksm/nftById.graphql
  queries/subsquid/rmrk/nftById.graphql
  types/index.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅
