Repository kodadot/nft-gallery, pull requests merged in 2024-09, with the labels that each got.

#10911 feat: Offers tab in `profile` and `gallery item`
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemActivityTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffers.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemOffersTable.vue
  components/gallery/GalleryItemTabsPanel/GalleryItemTabsPanel.vue
  components/offer/OfferOverviewModal.vue
  components/offer/OwnerButton.vue
  components/profile/ButtonConfig.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/OfferRow.vue
  components/profile/activityTab/Offers.vue
  components/profile/types.ts
  components/shared/ResponsiveTable.vue
  components/shared/TabItem.vue
  composables/collectionActivity/types.ts
  composables/transaction/transactionOffer.ts
  composables/transaction/transactionOfferAccept.ts
  composables/transaction/transactionOfferWithdraw.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useFormatAmount.ts
  composables/useIsOffer.ts
  composables/useLoadingNotfication.ts
  composables/useOffers.ts
  composables/useSubscriptionGraphql.ts
  composables/useTransactionNotification.ts
  composables/useTransactionTracker.ts
  locales/en.json
  queries/subsquid/general/offersList.graphql
  stores/fiat.ts
  tests/e2e/galleryitem.spec.ts
  tests/e2e/profile.spec.ts
  utils/notification.ts
Labels: S-code-lgtm-✅

#10944 feat: Remove Art view from Advanced
  components/shared/filters/modules/AdvancedFilter.vue
Labels: S-code-lgtm-✅

#10936 fix: balance fetching bugs
  components/common/ConnectWallet/WalletAsset.vue
  composables/useBalance.ts
  composables/useMultipleBalance.ts
  composables/useToken.ts
  stores/identity.ts
  stores/wallet.ts
Labels: S-code-lgtm-✅

#10964 fix: Offer expiration dropdown moving on scroll
  components/offer/OfferExpirationSelector.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
Labels: S-works-for-me-✅

#10969 (beta): 36 % of September 2024 Yak 🦬
  components/carousel/CarouselTypeDrops.vue
  components/collection/CollectionInfo.vue
  components/collection/CollectionRelatedDropNotification.vue
  components/collection/HeroButtons.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/Phase.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableSchedule.vue
  components/collection/unlockable/utils/useUnlockableTag.ts
  components/collection/utils/useCollectionDetails.ts
  components/common/ConnectWallet/WalletAsset.vue
  components/drops/BasicDropCard.vue
  components/drops/DropCard.vue
  components/drops/DropItem.vue
  components/drops/Drops.vue
  components/drops/DropsGrid.vue
  components/drops/useDrops.ts
  components/drops/utils.ts
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/useGalleryItem.ts
  components/landing/HeroBanner.vue
  components/offer/OfferExpirationSelector.vue
  components/profile/CuratedDrops.vue
  components/profile/activityTab/OfferRow.vue
  components/profile/activityTab/Offers.vue
  composables/useBalance.ts
  composables/useIdentity.ts
  composables/useMultipleBalance.ts
  composables/useToken.ts
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/README.md
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/ua.json
  pages/[prefix]/drops/index.vue
  params/types.ts
  services/oda.ts
  services/ogi.ts
  stores/drop.ts
  stores/dropsMinted.ts
  stores/identity.ts
  stores/wallet.ts
  tests/e2e/collection.spec.ts
  utils/onchain/evm.ts
  utils/onchain/sub.ts
  utils/onchain/types.ts
Labels: beta

#10970 (prod): 36 % of September 2024 Yak 🦬
  components/carousel/CarouselTypeDrops.vue
  components/collection/CollectionInfo.vue
  components/collection/CollectionRelatedDropNotification.vue
  components/collection/HeroButtons.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/Phase.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/unlockable/UnlockableHeroButtons.vue
  components/collection/unlockable/UnlockableLandingMobileBanner.vue
  components/collection/unlockable/UnlockableLandingTag.vue
  components/collection/unlockable/UnlockableSchedule.vue
  components/collection/unlockable/utils/useUnlockableTag.ts
  components/collection/utils/useCollectionDetails.ts
  components/common/ConnectWallet/WalletAsset.vue
  components/drops/BasicDropCard.vue
  components/drops/DropCard.vue
  components/drops/DropItem.vue
  components/drops/Drops.vue
  components/drops/DropsGrid.vue
  components/drops/useDrops.ts
  components/drops/utils.ts
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTransfer.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/gallery/useGalleryItem.ts
  components/landing/HeroBanner.vue
  components/offer/OfferExpirationSelector.vue
  components/profile/CuratedDrops.vue
  components/profile/activityTab/OfferRow.vue
  components/profile/activityTab/Offers.vue
  composables/useBalance.ts
  composables/useIdentity.ts
  composables/useMultipleBalance.ts
  composables/useToken.ts
  libs/ui/src/components/NeoDropdown/NeoDropdown.vue
  locales/README.md
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/ua.json
  pages/[prefix]/drops/index.vue
  params/types.ts
  services/oda.ts
  services/ogi.ts
  stores/drop.ts
  stores/dropsMinted.ts
  stores/identity.ts
  stores/wallet.ts
  tests/e2e/collection.spec.ts
  utils/onchain/evm.ts
  utils/onchain/sub.ts
  utils/onchain/types.ts
Labels: release

#10967 feat: Mass minting drops on evm
  components/collection/drop/MintStepper.vue
  components/drops/utils.ts
  composables/transaction/evm/utils.ts
  composables/transaction/transactionMintDrop.ts
  composables/transaction/types.ts
  params/types.ts
  services/oda.ts
  stores/drop.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#10997 feat: early success in offer modals
  components/common/Notification.vue
  components/offer/MakeOffer.vue
  components/offer/OfferOverviewModal.vue
  components/shared/SigningModal/SigningModal.vue
  composables/useTransactionNotification.ts
  libs/ui/src/components/NeoMessage/NeoMessage.vue
  locales/en.json
  utils/notification.ts
Labels: S-code-lgtm-✅, S-visual-ok-✅

#11000 fix: Listing popup displayed with listing modal
  components/collection/drop/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  layouts/unlockable-mint-layout.vue
Labels: S-code-lgtm-✅

#11023 conditionally rendering slider
  components/collection/drop/GenerativePreview.vue
Labels: S-works-for-me-✅

#11026 fix: Clicking on incoming offers - weird linking
  components/profile/activityTab/Offers.vue
Labels: S-works-for-me-✅

#11052 fix: Base: Minted NFT - didnot get successfull mint preview
  composables/drop/useGenerativeDropMint.ts
Labels: S-works-for-me-✅

#11025 fix: Weird redirect after removing RMRK
  components/Navbar.vue
  middleware/prefix.global.ts
  middleware/redirects.global.ts
  utils/config/permission.config.ts
Labels: S-works-for-me-✅

#11056 (beta): 100% of September 2024 Apple 🍏
  .github/diagram.svg
  components/Navbar.vue
  components/carousel/module/CarouselAgnostic.vue
  components/collection/drop/GenerativePreview.vue
  components/drops/BasicDropCard.vue
  components/drops/calendar/DropPreviewModal.vue
  components/drops/utils.ts
  components/offer/MakeOffer.vue
  components/profile/activityTab/Offers.vue
  components/shared/AddressChecker.vue
  composables/drop/useGenerativeDropMint.ts
  composables/transaction/transactionOffer.ts
  composables/useUpdateProfile.ts
  middleware/prefix.global.ts
  middleware/redirects.global.ts
  utils/config/permission.config.ts
Labels: beta

#11062 (prod): 100% of September 2024 Apple 🍏
  .github/diagram.svg
  components/Navbar.vue
  components/carousel/module/CarouselAgnostic.vue
  components/collection/drop/GenerativePreview.vue
  components/drops/BasicDropCard.vue
  components/drops/calendar/DropPreviewModal.vue
  components/drops/utils.ts
  components/offer/MakeOffer.vue
  components/profile/activityTab/Offers.vue
  components/shared/AddressChecker.vue
  composables/drop/useGenerativeDropMint.ts
  composables/transaction/transactionOffer.ts
  composables/useUpdateProfile.ts
  middleware/prefix.global.ts
  middleware/redirects.global.ts
  utils/config/permission.config.ts
Labels: release
