Repository kodadot/nft-gallery, pull requests merged in 2024-04, with the labels that each got.

#9944 fix: Disable RMRK/KSM
  components/collection/HeroButtons.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/migrate/steps/Review.vue
  components/migrate/steps/SignLoader1.vue
  composables/useTransaction.ts
  locales/en.json
  utils/prefix.ts
Labels: S-works-for-me-✅

#9946 fix wrong results in activity
  components/gallery/GalleryItemTabsPanel/GalleryItemActivity.vue
Labels: S-works-for-me-✅

#9953 fix: Auto teleport - user should have at least 1.5 DOT
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
Labels: S-works-for-me-✅

#9955 fix: Auto teleport welcome modal appearing while generating NFTs
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
Labels: S-works-for-me-✅

#9960 fix: I invented time warp
  components/common/autoTeleport/AutoTeleportModal.vue
Labels: paid, S-works-for-me-✅

#9964 fix: Ux friendly cookie popup mobile
  components/CookieBanner.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9969 refactor: remove migrate button on collection page
  components/collection/CollectionHeader/CollectionBanner.vue
Labels: S-works-for-me-✅

#9959 feat: View all - top collections
  components/explore/ExploreSort.vue
  components/landing/topCollections/TopCollections.vue
  components/search/Search.vue
  composables/useHasRoute.ts
  composables/useRouteSortByOptions.ts
  locales/en.json
Labels: S-changes-requested-🤞, S-works-for-me-✅, S-expected-in-upcoming-release-🚚

#9990 fix: prioritize nft.metadata rather than nft.meta.id
  components/gallery/GalleryItem.vue
  composables/useNft.ts
Labels: S-works-for-me-✅

#10003 fix: Can't retry cancelled teleport singing
  composables/useTeleport.ts
Labels: S-works-for-me-✅

#9993 fix: Bigger previews in the success modal
  components/base/MediaItem.vue
  components/common/successfulModal/MultiItemMedia.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9983 fix: Minting more than 1 NFT on the drop - gives you all random NFTs?
  composables/drop/massmint/useDropMassMint.ts
Labels: S-works-for-me-✅

#9991 fix: counter on drop card not updating
  components/drops/DropCard.vue
  components/drops/useDrops.ts
  services/fxart.ts
  tests/e2e/drops.spec.ts
Labels: S-works-for-me-✅

#10012 fix: show sn in drops listing
  composables/drop/massmint/useDropMassMintListing.ts
Labels: S-works-for-me-✅

#10023 fix: Mobile SkeletonDropCard doesnt match normal DropCard
  components/drops/DropCardSkeleton.vue
Labels: S-works-for-me-✅

#10046 fix: Calendar still showing wrong timezone
  components/drops/utils.ts
Labels: S-works-for-me-✅

#10037 feat: Share collection - as frame and other options
  components/collection/HeroButtons.vue
  composables/useSocialShare.ts
  locales/en.json
  utils/constants.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#10040 fix: grid item skeleton cards size issue
  components/items/ItemsGrid/ItemsGrid.vue
  components/shared/nftCard/NftCardSkeleton.vue
Labels: S-works-for-me-✅

#10056 show only image in profile activity
  components/profile/activityTab/HistoryRow.vue
Labels: S-works-for-me-✅

#9972 fix: Are auto-teleported funds preferred over funds on ahp?
  components/teleport/Teleport.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/autoTeleport/utils.ts
  libs/static/src/chains.ts
  utils/teleport.ts
Labels: S-works-for-me-✅

#10039 fix: Collections sort by filter breaks when multiple options are selected
  components/collection/CollectionGrid.vue
  components/explore/ExploreSort.vue
  utils/router.ts
Labels: S-works-for-me-✅

#10053 style: fix dropdown overflow issue on drop page
  components/collection/drop/GenerativeLayout.vue
Labels: S-works-for-me-✅

#10051 CodeChecker-check-same-hash-diff-art
  components/codeChecker/CodeChecker.vue
  components/codeChecker/PreviewCard.vue
  components/codeChecker/issueHint/ConsistentArt.vue
  components/codeChecker/issueHint/ValidImage.vue
  components/codeChecker/types.ts
  components/codeChecker/validate.ts
  locales/en.json
Labels: S-works-for-me-✅

#10011 fix: Drop carousel bug on reload
  components/carousel/CarouselTypeDrops.vue
  components/carousel/module/CarouselAgnostic.vue
  composables/useDynamicGrid.ts
Labels: S-changes-requested-🤞

#9998 fix: Listed filter being added after route change
  pages/[prefix]/explore/collectibles.vue
Labels: S-works-for-me-✅

#10052 feat: New to koda? Connect wallet sidebar improvements
  assets/styles/components/_connect-wallet.scss
  components/codeChecker/CodeChecker.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  locales/en.json
  utils/config/wallets.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#10088 Update ParaSpell to v5
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅

#9927 feature: added GalleryItemToolBar Component
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemToolBar.vue
  utils/gallery/media.ts
Labels: waiting-for-review, S-stale

#10130 Top up all packages
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅

#10016 feat: Why Koda artist landing V1
  components/TheFooter.vue
  components/why-koda/CtaSection.vue
  components/why-koda/HeroSection.vue
  components/why-koda/SectionItem.vue
  components/why-koda/Sections.vue
  components/why-koda/types.ts
  locales/en.json
  pages/why-koda.vue
  public/Koda_logo.svg
  public/Koda_logo_dark.svg
  public/why-koda-1.webp
  public/why-koda-2.webp
  public/why-koda-3.webp
  public/why-koda-4.webp
  public/why-koda-5.webp
Labels: S-works-for-me-✅, S-resolve-conversations

#10092 fix: Art shortcuts are not working in fullscreen mode
  components/base/MediaItem.vue
  components/codeChecker/PreviewCard.vue
  composables/useMediaFullscreen.ts
Labels: S-works-for-me-✅, waiting-for-review

#10112 feat: Farcaster frame mint is live - notification on landing page
  components/landing/FarcasterMintNotificationBanner.vue
  components/landing/HeroBanner.vue
  locales/en.json
  script/farcasterLiveMint.json
Labels: S-works-for-me-✅, S-visual-ok-✅, S-resolve-conversations

#10095 feat: skip ipfs parts on drops and update metadata v2
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintStepper.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/massmint/useDropMassMintUploader.ts
  composables/drop/useGenerativeDropMint.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  services/fxart.ts
  utils/drop.ts
Labels: S-works-for-me-✅

#10136 fix: Make fullscreen iframe to fit on code-check page
  components/codeChecker/PreviewCard.vue
  components/codeChecker/SandboxIFrame.vue
  libs/ui/src/components/MediaItem/type/IFrameMedia.vue
Labels: S-works-for-me-✅

#10089 Gallery item video full screen not working as expected
  components/base/MediaItem.vue
  components/gallery/GalleryItem.vue
  libs/ui/src/components/MediaItem/type/VideoMedia.vue
Labels: S-works-for-me-✅

#10138 fix: Small responsivity issue on Why Koda? page
  components/why-koda/HeroSection.vue
  components/why-koda/SectionItem.vue
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅

#10114 Profile-creation
  components/common/successfulModal/ShareSocialsSection.vue
  components/profile/ProfileActivitySummeryV3.vue
  components/profile/ProfileDetailV3.vue
  components/profile/create/Modal.vue
  components/profile/create/SelectImageField.vue
  components/profile/create/stages/Form.vue
  components/profile/create/stages/Introduction.vue
  components/profile/create/stages/Loading.vue
  components/profile/create/stages/Select.vue
  components/profile/create/stages/Success.vue
  components/profile/create/stages/index.ts
  composables/useProfile.ts
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  public/profile/create-profile-dark.svg
  public/profile/create-profile.svg
  services/profile.ts
Labels: S-works-for-me-✅

#10096 feat: Notifications system redesign
  components/bsx/Create/GenerativeMint.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/TokenImportButton.vue
  components/common/IdentityForm.vue
  components/common/Notification.vue
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  components/massmint/Massmint.vue
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Gallery/Holding.vue
  components/rmrk/Gallery/UserGainHistory.vue
  components/shared/OnRampModal.vue
  components/transfer/Transfer.vue
  composables/useCreate.ts
  composables/useGraphql.ts
  composables/useMetaTransaction.ts
  composables/useTeleport.ts
  composables/useTransaction.ts
  libs/ui/index.d.ts
  libs/ui/src/components/NeoMessage/NeoMessage.scss
  libs/ui/src/components/NeoMessage/NeoMessage.story.vue
  libs/ui/src/components/NeoMessage/NeoMessage.vue
  libs/ui/src/index.ts
  libs/ui/src/scss/tailwind.scss
  libs/ui/src/types.ts
  libs/ui/tailwind.config.js
  locales/en.json
  utils/error.ts
  utils/github.ts
  utils/notification.ts
Labels: S-works-for-me-✅

#10152 feat: ✨ Mint button in confirm modal for drops
  assets/styles/abstracts/_animations.scss
  components/collection/drop/modal/newsletter/EmailSignup.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/scss/animation.scss
Labels: S-works-for-me-✅, S-visual-ok-✅

#10156 feat: Why koda footer highlight
  components/TheFooter.vue
Labels: S-works-for-me-✅

#10159 fix: Autoteleport modal closing when clicking outside
  components/common/autoTeleport/AutoTeleportModal.vue
Labels: S-works-for-me-✅

#10132 fix: Top collections on base
  components/collection/CollectionCard.vue
  components/landing/LandingPage.vue
  components/landing/topCollections/TopCollections.vue
  components/landing/topCollections/utils/useTopCollections.ts
  composables/useIsChain.ts
  package.json
  pnpm-lock.yaml
  queries/subsquid/general/topCollections.graphql
  utils/collections.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#10140 Edit-Profile
  components/profile/ProfileDetailV3.vue
  components/profile/create/Modal.vue
  components/profile/create/stages/Form.vue
  services/profile.ts
Labels: S-works-for-me-✅
