Repository kodadot/nft-gallery, pull requests merged in 2024-12, with the labels that each got.

#11199 feat: Collection Edit: Support Name Update and Description Update
  components/collection/EditModal.vue
  components/collection/HeroButtonEditCollection.vue
Labels: S-works-for-me-✅

#11200 feat: Item Edit: Limit Name and Image Update
  components/common/EditNftModal.vue
  components/common/NonRecommendFieldNotification.vue
  locales/en.json
Labels: S-works-for-me-✅

#11207 feat: collection Edit - Limit Name and Image Update
  components/collection/EditModal.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅

#11208 feat: Massburn
  components/collection/HeroButtonDeleteNfts.vue
  components/common/ItemBurnModal.vue
  components/common/ItemTransferModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/userCart/UserCartModal.vue
  components/common/userCart/UserCartModals.vue
  components/common/userCart/UserCartMultipleItems.vue
  components/common/userCart/UserCartSingleItem.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/migrate/steps/SignLoader3.vue
  components/shared/AddressInput.vue
  components/unique/utils.ts
  composables/transaction/transactionBurn.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useCollectionAbi.ts
  composables/useIsChain.ts
  composables/useTransaction.ts
  layouts/explore-layout.vue
  locales/en.json
  pages/[prefix]/u/[id].vue
  stores/preferences.ts
  utils/config/permission.config.ts
  utils/gallery/abstractCalls.ts
Labels: S-code-lgtm-✅

#11163 ✨ swap page landing
  assets/svg/swap/arrow-down.svg
  assets/svg/swap/arrow-up.svg
  assets/svg/swap/arrows.svg
  components/collection/utils/types.ts
  components/common/ChainDropdown.vue
  components/common/listingCart/shared/ListingCartPriceInput.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/useAtomicSwapAction.ts
  components/items/ItemsGrid/useItemsGrid.ts
  components/items/ItemsGrid/useNftActions.ts
  components/profile/CollectionFilter.vue
  components/profile/OrderByDropdown.vue
  components/swap/DestinationProfile.vue
  components/swap/GridList.vue
  components/swap/GridListFilters.vue
  components/swap/Preview.vue
  components/swap/PreviewItem.vue
  components/swap/YourProfile.vue
  components/swap/banner/accounts.vue
  components/swap/banner/title.vue
  components/swap/landing.vue
  components/swap/layout/Selection.vue
  components/swap/layout/index.vue
  components/swap/review.vue
  components/swap/types.ts
  components/trade/TradeExpirationSelector.vue
  components/trade/TradeOwnerButton.vue
  components/trade/overviewModal/TradeOverviewModal.vue
  composables/transaction/transactionCreateSwap.ts
  composables/transaction/transactionOffer.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useAsyncGraphql.ts
  composables/useChainRedirect.ts
  composables/useTransaction.ts
  locales/en.json
  middleware/redirects.global.ts
  middleware/swap.ts
  pages/[prefix]/swap/[id]/index.vue
  pages/[prefix]/swap/[id]/offer.vue
  pages/[prefix]/swap/[id]/review.vue
  pages/[prefix]/swap/index.vue
  queries/subsquid/general/collectionLastList.graphql
  queries/subsquid/general/collectionListWithSearchMinimal.graphql
  queries/subsquid/general/countOfNfts.graphql
  queries/subsquid/general/countOfTokenNftsToList.graphql
  stores/atomicSwaps.ts
  utils/config/permission.config.ts
  utils/nfts.ts
  utils/shoppingActions.ts
  utils/swap.ts
Labels: S-code-lgtm-✅, A-atomic-swap

#11193 fix: Can't change chain from profile page
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/profile/ProfileDetail.vue
  composables/useAddress.ts
  composables/useChainRedirect.ts
Labels: S-code-lgtm-✅

#11244 fix: inconsistent styling in swap page
  components/common/ChainDropdown.vue
  components/profile/CollectionFilter.vue
  components/swap/GridListFilters.vue
Labels: S-works-for-me-✅

#11243 fix: Sidebar is not sticky after navbar
  components/swap/Preview.vue
Labels: S-code-lgtm-✅

#11247 fix: swap successful redirect
  components/common/Notification.vue
  components/swap/review.vue
  utils/notification.ts
Labels: S-works-for-me-✅

#11266 fix: Mass mint overview table styles
  components/massmint/OverviewTable.vue
Labels: S-works-for-me-✅

#11281 fix: switch button on mass mint onboarding
  components/massmint/OnBoarding.vue
Labels: S-works-for-me-✅

#11222 feat: Collection View: Display Incoming and Outgoing Swaps
  components/ExploreLayoutWithSidebar.vue
  components/collection/CollectionSwaps.vue
  components/common/BaseCartItemDetails.vue
  components/common/CartItemDetails.vue
  components/common/ChainDropdown.vue
  components/explore/DesktopControls.vue
  components/explore/FilterMenuButton.vue
  components/explore/MobileControls.vue
  components/explore/tab/TabOnCollection.vue
  components/profile/ProfileDetail.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/GridLayoutControls.vue
  components/shared/filters/Filters.vue
  components/shared/filters/MobileFilter.vue
  components/shared/filters/SidebarFilter.vue
  components/shared/filters/modules/EventTypeFilter.vue
  components/shared/filters/modules/IdentityVerficationFilter.vue
  components/shared/filters/modules/PopularCollections.vue
  components/shared/filters/modules/PriceFilter.vue
  components/shared/filters/modules/SiderbarFilterSection.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/filters/modules/TradeFilter.vue
  components/trade/TradeActivityTable.vue
  components/trade/TradeActivityTableRow.vue
  components/trade/TradeOwnerButton.vue
  components/trade/overviewModal/Details.vue
  components/trade/overviewModal/TradeOverviewModal.vue
  components/trade/overviewModal/TypeSwap.vue
  composables/transaction/transactionOfferAccept.ts
  composables/transaction/types.ts
  composables/useIsTrade.ts
  composables/useTrades.ts
  locales/en.json
  pages/[prefix]/collection/[id]/activity.vue
  pages/[prefix]/collection/[id]/index.vue
  pages/[prefix]/collection/[id]/swaps.vue
  pages/[prefix]/explore/items.vue
  queries/subsquid/general/offersList.graphql
  queries/subsquid/general/swapsList.graphql
Labels: S-code-lgtm-✅, S-works-for-me-✅

#11278 fix: Evm Token Transfer Modal error
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/common/userCart/UserCartModal.vue
  components/shared/SigningModal/SigningModal.vue
  composables/autoTeleport/useAutoTeleportActionButton.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/autoTeleport/utils.ts
  composables/transaction/transactionMintDrop.ts
  composables/transaction/types.ts
  composables/useCollectionAbi.ts
  composables/useTransaction.ts
  utils/transactionExecutor.ts
Labels: S-code-lgtm-✅

#11255 fix: Swap landing not disabling submit button on wrong address
  components/shared/AddressChecker.vue
  components/shared/AddressInput.vue
  components/swap/landing.vue
  components/transfer/Transfer.vue
  locales/en.json
Labels: S-code-lgtm-✅
