Repository kodadot/nft-gallery, pull requests merged in 2024-07, with the labels that each got.

#10595 Image tag overlaying sidebar
  components/base/MediaItem.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
Labels: S-visual-ok-✅

#10599 (beta): NightHawk bugfix
  .github/actions/pnpm-install/action.yml
  .github/diagram.svg
  components/base/MediaItem.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/profile/ProfileDetail.vue
  components/shared/ProfileAvatar.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
Labels: beta

#10587 fix: Clicking on `edit existing profile` opens wrong modal state
  components/profile/create/Modal.vue
  composables/useModalIsOpenTracker.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#10434 feat(profiles): faster profile images and Option to remove img and clear profile
  components/profile/ProfileDetail.vue
  components/profile/create/Modal.vue
  components/profile/create/SelectImageField.vue
  components/profile/create/stages/Form.vue
  locales/en.json
  pnpm-lock.yaml
  services/profile.ts
Labels: S-visual-ok-✅

#10629 fix: remove modal close on random clicks
  components/collection/HeroButtons.vue
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/unlockable/UnlockableLoader.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/successfulModal/SuccessfulModal.vue
  components/drops/CreateCalendarEventModal.vue
  components/shared/TransactionLoader.vue
  libs/ui/src/components/NeoModal/NeoModal.vue
  tests/e2e/share.spec.ts
Labels: S-visual-ok-✅

#10639 (prod): Mid July 2024 Otter 🦦
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/collectionInfoLine.vue
  components/common/successfulModal/ShareSocialsSection.vue
  components/landing/DomainChangeNotificationBanner.vue
  components/landing/HeroBanner.vue
  components/profile/ProfileBannerSkeleton.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileSkeleton.vue
  components/profile/create/Modal.vue
  components/profile/create/SelectImageField.vue
  components/profile/create/stages/Form.vue
  components/search/SearchProfiles.vue
  components/search/SearchSuggestion.vue
  composables/useModalIsOpenTracker.ts
  composables/useSocialShare.ts
  libs/static/package.json
  libs/ui/package.json
  libs/ui/src/components/NeoModal/NeoModal.vue
  locales/en.json
  nuxt.config.ts
  package.json
  pages/drop-checker/[chain]/[collection-id].vue
  pnpm-lock.yaml
  services/profile.ts
  utils/env.ts
Labels: release

#10443 perf: collection/gallery explore page images
  components/base/MediaItem.vue
  components/collection/CollectionCard.vue
  components/collection/CollectionDetail.vue
  components/collection/CollectionGrid.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/profile/create/Modal.vue
  components/profile/create/stages/Form.vue
  components/rmrk/service/scheme.ts
  components/shared/DynamicGrid.vue
  components/shared/ProfileAvatar.vue
  components/shared/nftCard/NftCard.vue
  components/shared/view/BasicImage.vue
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  nuxt.config.ts
  package.json
  plugins/pwa.client.ts
  pnpm-lock.yaml
  providers/cdn-worker.ts
  tests/utils/grid.spec.ts
  utils/cachingStrategy.ts
  utils/config/pwa.ts
  utils/grid.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-resolve-merge-conflicts-🤝

#10672 chore: downgrade sass version
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅
