Repository kodadot/nft-gallery, pull requests merged in 2024-08, with the labels that each got.

#10723 fix: The default avatars of EVM addresses would overlap each other
  components/shared/Avatar.vue
Labels: S-visual-ok-✅

#10653 fix: icon gone - connect wallet sidebar
  components/common/ConnectWallet/MnemonicNotice.vue
Labels: S-visual-ok-✅

#10618 feat: Profile creation - signuature toasts
  components/common/Notification.vue
  components/profile/create/Modal.vue
  components/profile/create/stages/Form.vue
  components/profile/create/stages/Loading.vue
  components/profile/create/stages/Success.vue
  components/profile/create/stages/index.ts
  components/profile/create/utils.ts
  components/shared/DynamicGrid.vue
  composables/useIdMap.ts
  composables/useModalIsOpenTracker.ts
  composables/useUpdateProfile.ts
  composables/useVerifyAccount.ts
  libs/ui/src/components/NeoIcon/NeoIcon.vue
  libs/ui/src/components/NeoMessage/NeoMessage.scss
  libs/ui/src/components/NeoMessage/NeoMessage.vue
  libs/ui/src/index.ts
  libs/ui/src/scss/tailwind.scss
  libs/ui/src/types.ts
  libs/ui/tailwind.config.js
  locales/en.json
  utils/notification.ts
Labels: S-visual-ok-✅, waiting-for-review

#10710 feat: Faster skeleton loading on drops
  components/drops/Drops.vue
  components/drops/DropsGrid.vue
  components/drops/useDrops.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#10762 fix: Make sure that EVM connectors work properly
  composables/useModalIsOpenTracker.ts
  composables/useViem.ts
  composables/useWagmi.ts
  composables/useWallet.ts
  composables/useWeb3Modal.ts
  plugins/wagmi.client.ts
  types/nuxt.d.ts
Labels: S-works-for-me-✅

#10742 feat: Chain connect wallet limitation - styling followup
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletTabs.vue
Labels: S-code-lgtm-✅

#10741 feat: Pricing on drop cards
  components/drops/BasicDropCard.vue
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
  components/drops/calendar/DropsCalendar.vue
  composables/useAmount.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅, S-visual-ok-✅

#10788 fix: Switch wallet modal dark mode
  components/common/ConnectWallet/ReconnectWalletModal.vue
  components/common/ConnectWallet/openReconnectWalletModal.ts
  public/right-arrow_dark.svg
  public/token/base_branded_dark.svg
  public/token/dot_branded_dark.svg
Labels: S-code-lgtm-✅, S-visual-ok-✅

#10795 fix: Drop Calendar section is missing & mobile view a bit off
  components/drops/calendar/DropsCalendar.vue
Labels: S-code-lgtm-✅

#10793 feat: Hero design simplification
  assets/svg/landing-blur.svg
  components/landing/HeroBanner.vue
  locales/en.json
  locales/hi.json
Labels: S-code-lgtm-✅, S-visual-ok-✅

#10799 refactor: proper setup wagmiPlugin
  components/common/ConnectWallet/ConnectEvm.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/transaction/evm/useMetaTransaction.ts
  composables/useBalance.ts
  composables/useFees.ts
  composables/useMultipleBalance.ts
  composables/useVerifyAccount.ts
  composables/useViem.ts
  composables/useWagmi.ts
  composables/useWallet.ts
  composables/useWeb3Modal.ts
  package.json
  plugins/wagmi.client.ts
  pnpm-lock.yaml
  stores/identity.ts
  utils/transactionExecutor.ts
  utils/wagmi.ts
Labels: S-works-for-me-✅

#10612 ✨ drops page shortcuts
  .husky/pre-commit
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintStepper.vue
  components/shared/modals/keyboardShortcutsModal.vue
  layouts/centered-half-layout.vue
  layouts/default.vue
  layouts/full-width-layout.vue
  layouts/full-width-no-footer.vue
  layouts/gallery-item-layout.vue
  layouts/no-footer.vue
  layouts/teleport-layout.vue
  layouts/unlockable-mint-layout.vue
  plugins/keyboardEvents.client.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#10832 (beta/fix): Mid-August 2024 Shark 🦈
  .husky/pre-commit
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/MintStepper.vue
  components/collection/drop/PaidGenerative.vue
  components/common/ConnectWallet/ConnectEvm.vue
  components/drops/useDrops.ts
  components/explore/ExploreSort.vue
  components/shared/Avatar.vue
  components/shared/modals/keyboardShortcutsModal.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/useGenerativeDropMint.ts
  composables/transaction/evm/useMetaTransaction.ts
  composables/useBalance.ts
  composables/useFees.ts
  composables/useMultipleBalance.ts
  composables/useProfile.ts
  composables/useVerifyAccount.ts
  composables/useViem.ts
  composables/useWagmi.ts
  composables/useWallet.ts
  composables/useWeb3Modal.ts
  layouts/centered-half-layout.vue
  layouts/default.vue
  layouts/full-width-layout.vue
  layouts/full-width-no-footer.vue
  layouts/gallery-item-layout.vue
  layouts/no-footer.vue
  layouts/teleport-layout.vue
  layouts/unlockable-mint-layout.vue
  nuxt.config.ts
  package.json
  params/types.ts
  plugins/keyboardEvents.client.ts
  plugins/wagmi.client.ts
  pnpm-lock.yaml
  services/ogi.ts
  stores/drop.ts
  stores/identity.ts
  types/nuxt.d.ts
  utils/drop.ts
  utils/onchain/evm.ts
  utils/onchain/sub.ts
  utils/transactionExecutor.ts
  utils/viem.ts
  utils/wagmi.ts
Labels: beta

#10834 fix: Landing create modal still appearing with a profile
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/landing/LandingPage.vue
  components/profile/ProfileDetail.vue
  components/shared/ProfileAvatar.vue
  composables/useFetchProfile.ts
  composables/useIdentity.ts
  composables/useProfile.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#10837 (prod/fix): Mid-August 2024 Shark 🦈
  .husky/pre-commit
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/MintStepper.vue
  components/collection/drop/PaidGenerative.vue
  components/common/ConnectWallet/ConnectEvm.vue
  components/drops/useDrops.ts
  components/explore/ExploreSort.vue
  components/shared/Avatar.vue
  components/shared/modals/keyboardShortcutsModal.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/useGenerativeDropMint.ts
  composables/transaction/evm/useMetaTransaction.ts
  composables/useBalance.ts
  composables/useFees.ts
  composables/useMultipleBalance.ts
  composables/useProfile.ts
  composables/useVerifyAccount.ts
  composables/useViem.ts
  composables/useWagmi.ts
  composables/useWallet.ts
  composables/useWeb3Modal.ts
  layouts/centered-half-layout.vue
  layouts/default.vue
  layouts/full-width-layout.vue
  layouts/full-width-no-footer.vue
  layouts/gallery-item-layout.vue
  layouts/no-footer.vue
  layouts/teleport-layout.vue
  layouts/unlockable-mint-layout.vue
  nuxt.config.ts
  package.json
  params/types.ts
  plugins/keyboardEvents.client.ts
  plugins/wagmi.client.ts
  pnpm-lock.yaml
  services/ogi.ts
  stores/drop.ts
  stores/identity.ts
  types/nuxt.d.ts
  utils/drop.ts
  utils/onchain/evm.ts
  utils/onchain/sub.ts
  utils/transactionExecutor.ts
  utils/viem.ts
  utils/wagmi.ts
Labels: release

#10839 fix: Drops on Base show AHP drops
  components/drops/Drops.vue
Labels: S-works-for-me-✅

#10840 (beta): Mid-August 2024 Tiger 🐅
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/landing/LandingPage.vue
  components/profile/ProfileDetail.vue
  components/shared/ProfileAvatar.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useFetchProfile.ts
  composables/useIdentity.ts
  composables/useMultipleBalance.ts
  composables/useProfile.ts
  pages/[prefix]/drops/[id].vue
  stores/identity.ts
Labels: beta

#10841 (prod): Mid-August 2024 Tiger 🐅
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/landing/LandingPage.vue
  components/profile/ProfileDetail.vue
  components/shared/ProfileAvatar.vue
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/useFetchProfile.ts
  composables/useIdentity.ts
  composables/useMultipleBalance.ts
  composables/useProfile.ts
  pages/[prefix]/drops/[id].vue
  stores/identity.ts
Labels: release

#10859 (beta/fix): Mid-August 2024 Tiger 🐅
  .github/diagram.svg
  .github/push_release_beta.sh
  .github/push_release_production.sh
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/drops/BasicDropCard.vue
  components/profile/activityTab/History.vue
  locales/en.json
  nuxt.config.ts
Labels: beta

#10872 (prod/fix): Mid-August 2024 Tiger 🐅
  .github/diagram.svg
  .github/push_release_beta.sh
  .github/push_release_production.sh
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/drops/BasicDropCard.vue
  components/profile/activityTab/History.vue
  locales/en.json
  nuxt.config.ts
Labels: release

#10871 fix: Drop card having overflow
  components/drops/BasicDropCard.vue
  components/drops/TimeTag.vue
  components/drops/utils.ts
Labels: S-visual-ok-✅

#10720 fix: display all available chains & check wallet VM when buying / minting nft
  components/carousel/CarouselTypeDrops.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/common/ChainDropdown.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/ReconnectWalletModal.vue
  components/common/ConnectWallet/WalletTabs.vue
  components/common/ConnectWallet/openReconnectWalletModal.ts
  components/common/shoppingCart/ShoppingCartModal.vue
  components/create/CreateCollection.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/navbar/ChainSelectDropdown.vue
  composables/useAvailableChainsOptions.ts
  composables/useTransaction.ts
Labels: S-visual-ok-✅

#10886 (beta): 75% of August 2024 Unicorn 🦄
  components/carousel/CarouselTypeDrops.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/common/ChainDropdown.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/ReconnectWalletModal.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletTabs.vue
  components/common/ConnectWallet/openReconnectWalletModal.ts
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/create/CreateCollection.vue
  components/drops/BasicDropCard.vue
  components/drops/Drops.vue
  components/drops/TimeTag.vue
  components/drops/utils.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/navbar/ChainSelectDropdown.vue
  components/shared/modals/keyboardShortcutsModal.vue
  composables/transaction/evm/useMetaTransaction.ts
  composables/useAmount.ts
  composables/useAvailableChainsOptions.ts
  composables/useSubscriptionGraphql.ts
  composables/useToken.ts
  composables/useTransaction.ts
  middleware/redirects.global.ts
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  stores/drop.ts
  utils/config/permission.config.ts
  utils/format/balance.ts
Labels: beta

#10889 (prod): 75% of August 2024 Unicorn
  components/carousel/CarouselTypeDrops.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/common/ChainDropdown.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/ReconnectWalletModal.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletTabs.vue
  components/common/ConnectWallet/openReconnectWalletModal.ts
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/create/CreateCollection.vue
  components/drops/BasicDropCard.vue
  components/drops/Drops.vue
  components/drops/TimeTag.vue
  components/drops/utils.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/navbar/ChainSelectDropdown.vue
  components/shared/modals/keyboardShortcutsModal.vue
  composables/transaction/evm/useMetaTransaction.ts
  composables/useAmount.ts
  composables/useAvailableChainsOptions.ts
  composables/useSubscriptionGraphql.ts
  composables/useToken.ts
  composables/useTransaction.ts
  middleware/redirects.global.ts
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  stores/drop.ts
  utils/config/permission.config.ts
  utils/format/balance.ts
Labels: release

#10877 fix: Onboarding profile creation modal shown multiple times per session
  components/profile/ProfileDetail.vue
  stores/profileOnboarding.ts
Labels: S-code-lgtm-✅

#10902 fix: Profile picture size crippled
  components/profile/ProfileDetail.vue
Labels: S-visual-ok-✅

#10908 (beta): 83% of August 2024 Vampire 🧛🏽‍♀️
  components/collection/drop/MintButton.vue
  components/common/CartItemDetails.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/common/shoppingCart/utils.ts
  components/drops/useDrops.ts
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/navbar/ConnectedProfile.vue
  components/navbar/ProfileDropdown.vue
  components/offer/MakeOffer.vue
  components/offer/MakingOfferSingleItem.vue
  components/offer/SuccessfulMakingOfferBody.vue
  components/offer/types.ts
  components/profile/ProfileDetail.vue
  components/profile/create/Modal.vue
  composables/autoTeleport/useAutoTeleportActionButton.ts
  composables/transaction/transactionOffer.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useIcon.ts
  composables/useProfile.ts
  composables/useTransaction.ts
  composables/useWallet.ts
  locales/en.json
  params/types.ts
  public/chain/mnt.svg
  public/chain/mnt_dark.svg
  stores/drop.ts
  stores/makeOffer.ts
  stores/preferences.ts
  stores/profileOnboarding.ts
  tests/e2e/drops.spec.ts
  utils/chain.ts
  utils/config/permission.config.ts
  utils/kodahash.ts
  utils/onchain/evm.ts
  utils/onchain/sub.ts
  utils/onchain/types.ts
  utils/shoppingActions.ts
  utils/shortAddress.ts
Labels: beta

#10910 (prod): 83% of August 2024 Vampire 🧛🏽‍♀️
  components/collection/drop/MintButton.vue
  components/common/CartItemDetails.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/multipleItemsCart/ListingCartItem.vue
  components/common/listingCart/singleItemCart/ListingCartSingleItemCart.vue
  components/common/shoppingCart/utils.ts
  components/drops/useDrops.ts
  components/gallery/GalleryItemAction/GalleryItemAction.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemOffer.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/navbar/ConnectedProfile.vue
  components/navbar/ProfileDropdown.vue
  components/offer/MakeOffer.vue
  components/offer/MakingOfferSingleItem.vue
  components/offer/SuccessfulMakingOfferBody.vue
  components/offer/types.ts
  components/profile/ProfileDetail.vue
  components/profile/create/Modal.vue
  composables/autoTeleport/useAutoTeleportActionButton.ts
  composables/transaction/transactionOffer.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  composables/useIcon.ts
  composables/useProfile.ts
  composables/useTransaction.ts
  composables/useWallet.ts
  locales/en.json
  params/types.ts
  public/chain/mnt.svg
  public/chain/mnt_dark.svg
  stores/drop.ts
  stores/makeOffer.ts
  stores/preferences.ts
  stores/profileOnboarding.ts
  tests/e2e/drops.spec.ts
  utils/chain.ts
  utils/config/permission.config.ts
  utils/kodahash.ts
  utils/onchain/evm.ts
  utils/onchain/sub.ts
  utils/onchain/types.ts
  utils/shoppingActions.ts
  utils/shortAddress.ts
Labels: release
