Repository kodadot/nft-gallery, pull requests merged in 2024-05, with the labels that each got.

#10172 Update ParaSpell to v5.2.1
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅

#10171 fix: 0 nfts in congrats modal
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/utils.ts
  composables/useAsyncRetry.ts
Labels: S-works-for-me-✅

#10168 fix: Autoteleport after rfc - lowering deposits and fees
  libs/static/src/chains.ts
Labels: S-works-for-me-✅

#10153 Profile-fix-visuals
  components/profile/create/stages/Form.vue
  components/profile/create/stages/Introduction.vue
  components/profile/create/stages/Select.vue
  components/profile/create/stages/Success.vue
  public/profile/create-profile-dark.png
  public/profile/create-profile.png
Labels: S-works-for-me-✅

#10169 fix: New Profile creation/editing better field validation/error handling
  components/profile/ProfileDetailV3.vue
  components/profile/create/stages/Form.vue
  utils/url.ts
Labels: S-works-for-me-✅

#10176 roll out Profile-V3
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileActivitySummeryV3.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileDetailV3.vue
  components/profile/create/stages/Form.vue
  pages/[prefix]/u/[id].vue
  queries/types/fragments/event.ts
  queries/types/fragments/nftSubsquid.ts
  queries/types/subsquid/general/profileStatsByIdRefined.ts
  tests/e2e/custom.ts
  tests/e2e/profile.spec.ts
Labels: S-works-for-me-✅

#10192 fix: Rounding USD to two decimals
  components/collection/drop/MintButton.vue
Labels: S-works-for-me-✅

#10173 chore: fix typos
  STYLE_GUIDE.md
  pages/sustainability.vue
  tests/TESTSUITE.md
Labels: S-works-for-me-✅

#10228 fix: Button size in create new profile
  components/profile/ProfileDetail.vue
  components/profile/create/stages/Select.vue
  locales/en.json
Labels: S-visual-ok-✅

#10208 fix: Modal Not looking right
  components/profile/create/stages/Introduction.vue
  components/shared/modals/ModalBody.vue
Labels: S-works-for-me-✅

#10068 fix: Default images on success dialog even before signing it generated previews well
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/drop/types.ts
  components/common/listingCart/SuccessfulListingBody.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/shoppingCart/utils.ts
  components/common/successfulModal/MultiItemMedia.vue
  components/common/successfulModal/SuccessfulItemsMedia.vue
  composables/drop/massmint/useDropMassMintListing.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/useGenerativeDropMint.ts
  composables/useListingCartModal.ts
  stores/listingCart.ts
Labels: S-works-for-me-✅

#10232 fix: Loaders and skeletons for new profile
  components/profile/follow/Tab.vue
  components/profile/follow/UserRowSkeleton.vue
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue
Labels: S-works-for-me-✅

#10186 chore: update optimizeDeps for development
  nuxt.config.ts
Labels: waiting-for-review

#10219 fix: animated button hover state
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: S-visual-ok-✅

#10239 fix: Align center in profile activity
  components/profile/activityTab/Activity.vue
Labels: S-works-for-me-✅

#10201 fix: Wrong share text on farcaster
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/drop/types.ts
  components/common/successfulModal/ShareSocialsSection.vue
  components/common/successfulModal/SuccessfulModalBody.vue
  components/profile/ProfileDetail.vue
  composables/drop/useGenerativeDropMint.ts
  composables/useSocialShare.ts
  locales/en.json
Labels: S-works-for-me-✅

#10263 beta update
  STYLE_GUIDE.md
  components/CookieBanner.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/drop/types.ts
  components/common/autoTeleport/AutoTeleportPopover.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/listingCart/SuccessfulListingBody.vue
  components/common/listingCart/shared/ListingCartItemDetails.vue
  components/common/shoppingCart/utils.ts
  components/common/successfulModal/MultiItemMedia.vue
  components/common/successfulModal/ShareSocialsSection.vue
  components/common/successfulModal/SuccessfulItemsMedia.vue
  components/common/successfulModal/SuccessfulModalBody.vue
  components/profile/ProfileActivitySummery.vue
  components/profile/ProfileActivitySummeryV3.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileDetailV3.vue
  components/profile/activityTab/Activity.vue
  components/profile/create/Modal.vue
  components/profile/create/stages/Form.vue
  components/profile/create/stages/Introduction.vue
  components/profile/create/stages/Select.vue
  components/profile/create/stages/index.ts
  components/profile/follow/Tab.vue
  components/profile/follow/UserRow.vue
  components/profile/follow/UserRowSkeleton.vue
  components/shared/modals/ModalBody.vue
  composables/drop/massmint/useDropMassMintListing.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/useGenerativeDropMint.ts
  composables/useListingCartModal.ts
  composables/useSocialShare.ts
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoPagination/NeoPagination.vue
  libs/ui/src/components/NeoSkeleton/NeoSkeleton.vue
  libs/ui/tailwind.config.js
  locales/en.json
  nuxt.config.ts
  package.json
  pages/[prefix]/u/[id].vue
  pages/sustainability.vue
  plugins/vue-gtag.client.ts
  pnpm-lock.yaml
  queries/types/fragments/event.ts
  queries/types/fragments/nftSubsquid.ts
  queries/types/subsquid/general/profileStatsByIdRefined.ts
  services/farcaster.ts
  services/fxart.ts
  services/profile.ts
  stores/listingCart.ts
  tests/TESTSUITE.md
  tests/e2e/custom.ts
  tests/e2e/profile.spec.ts
  utils/drop.ts
  utils/randomize.ts
  utils/url.ts
Labels: beta

#10266 close before unmount
  components/profile/follow/Modal.vue
Labels: S-works-for-me-✅

#10265 fix disabled submit profile button
  components/profile/create/Modal.vue
  components/profile/create/stages/Form.vue
  services/profile.ts
Labels: S-works-for-me-✅

#10255 fix:Truncation in followers/following tab
  components/profile/follow/UserRow.vue
Labels: S-works-for-me-✅

#10257 feat: Replace icons with uploaded profile picture
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/identity/IdentityItem.vue
  components/navbar/ProfileDropdown.vue
  components/shared/ProfileAvatar.vue
  composables/useFetchProfile.ts
Labels: S-works-for-me-✅

#10238 🔧 cookie banner btn design
  components/CookieBanner.vue
  locales/en.json
Labels: S-works-for-me-✅

#10275 fix: New warpcast mint landing notif
  components/landing/FarcasterMintNotificationBanner.vue
  script/farcasterLiveMint.json
Labels: S-works-for-me-✅

#10285 Expand web gl check to all js files
  components/codeChecker/CodeChecker.vue
  components/codeChecker/codechecker.config.js
  components/codeChecker/types.ts
  components/codeChecker/utils.ts
  components/codeChecker/validate.ts
Labels: S-works-for-me-✅

#10250 fix: Clicking followed by should open followers tab
  components/profile/ProfileDetail.vue
Labels: paid, S-works-for-me-✅

#10295 beta update
  components/CookieBanner.vue
  components/codeChecker/CodeChecker.vue
  components/codeChecker/codechecker.config.js
  components/codeChecker/types.ts
  components/codeChecker/utils.ts
  components/codeChecker/validate.ts
  components/collection/drop/modal/PaidMint.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/identity/IdentityItem.vue
  components/landing/FarcasterMintNotificationBanner.vue
  components/navbar/ProfileDropdown.vue
  components/profile/ProfileDetail.vue
  components/profile/create/Modal.vue
  components/profile/create/stages/Form.vue
  components/profile/follow/Modal.vue
  components/profile/follow/UserRow.vue
  components/shared/ProfileAvatar.vue
  composables/autoTeleport/useAutoTeleport.ts
  composables/autoTeleport/useAutoTeleportTransactionActions.ts
  composables/useFetchProfile.ts
  composables/useTeleport.ts
  libs/static/package.json
  libs/ui/package.json
  locales/en.json
  package.json
  pnpm-lock.yaml
  script/farcasterLiveMint.json
  services/profile.ts
Labels: beta

#10264 fix: New wallets: Autoteleport: Got stuck on checking funds
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
Labels: S-works-for-me-✅

#10256 Followers-exclude
  components/profile/ProfileDetail.vue
  components/profile/follow/Tab.vue
  components/profile/follow/UserRow.vue
  services/profile.ts
Labels: S-works-for-me-✅, S-resolve-merge-conflicts-🤝

#10319 feat: Confirm connection - information notif
  components/profile/create/Modal.vue
  locales/en.json
  utils/notification.ts
Labels: S-works-for-me-✅

#10258 fix: Paid mint modal auto-teleport flow
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  composables/autoTeleport/useAutoTeleportModal.ts
  composables/useFetchProfile.ts
Labels: S-works-for-me-✅

#10325 fix: Mass mint wrong pricing
  composables/massmint/massMintHelpers.ts
Labels: S-works-for-me-✅

#10293 feat: Display success message after transaction is in block
  components/buy/Buy.vue
  components/buy/SuccessfulBuyModal.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/listingCart/SuccessfulListingBody.vue
  components/common/successfulModal/SuccessfulModal.vue
  components/common/successfulModal/SuccessfulModalBody.vue
  components/common/successfulModal/TransactionSection.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/CreateCollection.vue
  components/create/modals/CollectionSuccessModal.vue
  components/shared/SigningModal/SigningModal.vue
  composables/useTransaction.ts
  composables/useTransactionSuccessful.ts
  composables/useTransactionTracker.ts
  locales/en.json
Labels: S-works-for-me-✅

#10328 fix: Profile navigates to substrate generic address instead of chain …
  components/profile/follow/UserRow.vue
Labels: S-works-for-me-✅

#10326 fix: Profile Creation modal appears for already created profiles
  components/profile/create/Modal.vue
  composables/useProfile.ts
Labels: S-works-for-me-✅

#10299 Remove giant squid from the code
  components/collection/activity/events/Events.vue
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/IdentityForm.vue
  components/common/identity/IdentityConfirmModal.vue
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/identity/module/IdentitySocial.vue
  components/shared/ProfileAvatar.vue
  composables/useFetchProfile.ts
  composables/useIdentity.ts
  composables/useProfile.ts
  package.json
  pages/identity.vue
  plugins/vueQuery.ts
  pnpm-lock.yaml
  queries/subsquid/general/identities.graphql
  queries/subsquid/general/identityById.graphql
  services/profile.ts
  tests/e2e/collection.spec.ts
  tests/e2e/share.spec.ts
  utils/constants.ts
Labels: S-works-for-me-✅

#10345 Perf: avoid invalid requests when loading drop page
  components/collection/activity/events/Events.vue
  components/collection/utils/useCollectionDetails.ts
  components/drops/useDrops.ts
  composables/collectionActivity/useCollectionActivity.ts
  composables/drop/useGenerativeDropMint.ts
  composables/useFetchProfile.ts
  composables/useUnlockable.ts
Labels: S-works-for-me-✅

#10336 refactor: cleanup free drops component
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/newsletter/ConfirmEmail.vue
  components/collection/drop/modal/newsletter/EmailSignup.vue
  components/collection/drop/utils.ts
  components/collection/unlockable/utils.ts
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/useGenerativeDropNewsletter.ts
  pages/[prefix]/drops/[id].vue
  services/fxart.ts
  tests/e2e/drops.spec.ts
  utils/newsletter.ts
Labels: S-works-for-me-✅

#10358 fix: Profile image/button state is lost when network changes
  components/profile/CollectionFilter.vue
  composables/useProfile.ts
Labels: S-works-for-me-✅

#10363 feat: PFP in confirm modal
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/identity/IdentityItem.vue
Labels: S-works-for-me-✅

#10366 fix: Top Collection buttons got reduced
  components/landing/topCollections/TopCollections.vue
Labels: S-works-for-me-✅

#10349 fix: ignore metadata endpoint for fxart
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemToolBar.vue
  components/gallery/useGalleryItem.ts
  composables/useNft.ts
Labels: S-works-for-me-✅, waiting-for-review
