Repository kodadot/nft-gallery, pull requests merged in 2024-03, with the labels that each got.

#9606 fix: Fix dynamic grid on landing page
  components/carousel/CarouselTypeDrops.vue
  components/carousel/module/CarouselAgnostic.vue
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/shared/DynamicGrid.vue
  composables/useDynamicGrid.ts
  utils/drop.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#9630 fix: Collection name truncation
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/NftMediaInfoStacked.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9609 feat: Footer: hoovertext
  components/TheFooter.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9611 fix: Not eligible button label
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9628 Disable buy on RMRK1/2
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/filters/modules/StatusFilter.vue
  locales/en.json
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9602 fix: Hover over card
  components/carousel/module/CarouselInfo.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9619 fix: Text shifted in collection activity
  components/collection/activity/events/eventRow/EventRowDesktop.vue
Labels: paid, S-works-for-me-✅

#9629 fix: button styling retry
  components/migrate/steps/SignLoader1.vue
  components/migrate/steps/SignLoader2.vue
  components/migrate/steps/SignLoader3.vue
  components/shared/SigningModal/SigningModalBody.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
Labels: S-works-for-me-✅

#9614 code checker resolve issue modals
  components/codeChecker/CodeChecker.vue
  components/codeChecker/TestItem.vue
  components/codeChecker/issueHint/AutomaticResize.vue
  components/codeChecker/issueHint/CodeBlock.vue
  components/codeChecker/issueHint/CorrectHTMLName.vue
  components/codeChecker/issueHint/UsingKodaHash.vue
  components/codeChecker/issueHint/UsingParamHash.vue
  components/codeChecker/issueHint/VariationLoadingTime.vue
  components/codeChecker/testItem.vue
  components/codeChecker/types.ts
  locales/en.json
Labels: S-works-for-me-✅

#9638 close modal on cancel
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
Labels: S-works-for-me-✅

#9639 fix: profile stats
  components/profile/ProfileActivitySummery.vue
  queries/subsquid/general/profileStatsById.graphql
Labels: S-works-for-me-✅

#9637 remove funds warning from overview modal
  components/collection/drop/modal/paid/MintOverview.vue
Labels: S-works-for-me-✅

#9587 different partykit cursor
  components/common/party/CursorParty.vue
  components/common/party/Cusor.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#9655 Fix/multiple-reloads
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
Labels: S-works-for-me-✅

#9657 fix: Retry transaction is not displayed after canceling signing
  components/shared/SigningModal/SigningModal.vue
  composables/autoTeleport/useAutoTeleportTransactionActions.ts
Labels: S-works-for-me-✅

#9643 fix: increase limit drops on landing
  components/carousel/CarouselTypeDrops.vue
Labels: S-works-for-me-✅

#9652 fix: Listing cart modal open on page load
  components/common/listingCart/ListingCartModal.vue
Labels: S-works-for-me-✅

#9650 fix: Multiple listing modals being opened at once
  components/buy/SuccessfulBuyModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/PaidGenerative.vue
  layouts/generative-mint-layout.vue
Labels: S-works-for-me-✅

#9667 beta update
  .github/diagram.svg
  components/TheFooter.vue
  components/buy/SuccessfulBuyModal.vue
  components/carousel/CarouselTypeDrops.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
  components/codeChecker/CodeChecker.vue
  components/codeChecker/TestItem.vue
  components/codeChecker/issueHint/AutomaticResize.vue
  components/codeChecker/issueHint/CodeBlock.vue
  components/codeChecker/issueHint/CorrectHTMLName.vue
  components/codeChecker/issueHint/UsingKodaHash.vue
  components/codeChecker/issueHint/UsingParamHash.vue
  components/codeChecker/issueHint/VariationLoadingTime.vue
  components/codeChecker/testItem.vue
  components/codeChecker/types.ts
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/party/CursorParty.vue
  components/common/party/Cusor.vue
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/migrate/steps/SignLoader1.vue
  components/migrate/steps/SignLoader2.vue
  components/migrate/steps/SignLoader3.vue
  components/profile/ProfileActivitySummery.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/DynamicGrid.vue
  components/shared/SigningModal/SigningModal.vue
  components/shared/SigningModal/SigningModalBody.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/NftMediaInfoStacked.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleportTransactionActions.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/autoTeleport/utils.ts
  composables/useDynamicGrid.ts
  layouts/generative-mint-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
  queries/subsquid/general/profileStatsById.graphql
  tests/e2e/footer.spec.ts
  utils/drop.ts
Labels: beta

#9668 release update
  .github/diagram.svg
  components/TheFooter.vue
  components/buy/SuccessfulBuyModal.vue
  components/carousel/CarouselTypeDrops.vue
  components/carousel/module/CarouselAgnostic.vue
  components/carousel/module/CarouselInfo.vue
  components/codeChecker/CodeChecker.vue
  components/codeChecker/TestItem.vue
  components/codeChecker/issueHint/AutomaticResize.vue
  components/codeChecker/issueHint/CodeBlock.vue
  components/codeChecker/issueHint/CorrectHTMLName.vue
  components/codeChecker/issueHint/UsingKodaHash.vue
  components/codeChecker/issueHint/UsingParamHash.vue
  components/codeChecker/issueHint/VariationLoadingTime.vue
  components/codeChecker/testItem.vue
  components/codeChecker/types.ts
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/listingCart/ListingCartModal.vue
  components/common/party/CursorParty.vue
  components/common/party/Cusor.vue
  components/drops/DropCard.vue
  components/drops/DropCardSkeleton.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/migrate/steps/SignLoader1.vue
  components/migrate/steps/SignLoader2.vue
  components/migrate/steps/SignLoader3.vue
  components/profile/ProfileActivitySummery.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/DynamicGrid.vue
  components/shared/SigningModal/SigningModal.vue
  components/shared/SigningModal/SigningModalBody.vue
  components/shared/TransactionSteps/TransactionStepsItem.vue
  components/shared/filters/modules/StatusFilter.vue
  components/shared/nftCard/NftMediaInfo.vue
  components/shared/nftCard/NftMediaInfoStacked.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleportTransactionActions.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
  composables/autoTeleport/utils.ts
  composables/useDynamicGrid.ts
  layouts/generative-mint-layout.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  locales/en.json
  queries/subsquid/general/profileStatsById.graphql
  tests/e2e/footer.spec.ts
  utils/drop.ts
Labels: release

#9653 fix: Teleport Success modal appearing to soon on drops
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
Labels: S-works-for-me-✅, S-resolve-merge-conflicts-🤝

#9645 allowlist text alignment
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
Labels: S-works-for-me-✅

#9442 style: colums and column classes to tailwind
  assets/styles/pages/create.scss
  components/collection/activity/Activity.vue
  components/collection/activity/events/Events.vue
  components/collection/activity/events/eventRow/EventRowDesktop.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/unlockable/UnlockableItemInfo.vue
  components/create/CreateCollection.vue
  components/create/CreateNft.vue
  components/gallery/GalleryItem.vue
  components/generative/GenerativeMintForm.vue
  components/landing/FeaturedArticles.vue
  components/landing/topCollections/TopCollections.vue
  components/migrate/landing/header/Index.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/History.vue
  components/profile/activityTab/HistoryRow.vue
  components/search/SearchPriceRange.vue
  components/shared/BreadcrumbsFilter.vue
  components/shared/ResponsiveTable.vue
  components/shared/form/RadioSelect.vue
  components/shared/gallery/Properties.vue
  components/shared/view/ImageGrid.vue
  components/spotlight/SpotlightDetail.vue
  components/stats/StatsHeader.vue
  layouts/centered-half-layout.vue
  layouts/generative-mint-layout.vue
  pages/migrate/congrats.vue
  pages/qrCode.vue
  pages/series-insight.vue
Labels: S-works-for-me-✅, waiting-for-review, S-resolve-merge-conflicts-🤝

#9673 add modal to layout
  components/common/listingCart/ListingCartModal.vue
  layouts/generative-mint-layout.vue
  layouts/unlockable-mint-layout.vue
Labels: S-works-for-me-✅

#9675 feat: add sort by sn for drop page
  components/profile/OrderByDropdown.vue
  locales/en.json
Labels: S-works-for-me-✅

#9686 fix: Clicking listing closed modal on drop success modal
  components/common/listingCart/ListingCartModal.vue
  composables/autoTeleport/types.ts
  composables/autoTeleport/useAutoTeleportTransitionDetails.ts
Labels: S-works-for-me-✅, S-resolve-merge-conflicts-🤝

#9688 feat: Landing hero iteration (farcaster notif and heading change)
  components/landing/FarcasterBanner.vue
  components/landing/HeroBanner.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  locales/en.json
  public/farcaster-dark.svg
  public/farcaster-light.svg
Labels: S-changes-requested-🤞, paid

#9689 #9683 drop mobile spacing issue
  components/collection/drop/GenerativeLayout.vue
  components/collection/unlockable/UnlockableCollectionInfo.vue
Labels: S-works-for-me-✅

#9620 Start-refactor-drops
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/Phase.vue
  components/collection/drop/const.ts
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/drop/modal/utils.ts
  components/collection/drop/requirement/PrivateMintRequirements.vue
  components/collection/drop/utils.ts
  components/collection/unlockable/UnlockableCollectionBanner.vue
  components/create/CreateNft.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItemHolderOf.vue
  composables/drop/useGenerativeDropDetails.ts
  composables/drop/useGenerativeDropMint.ts
  composables/party/useCursorDropEvents.ts
  pages/[prefix]/drops/[id].vue
  params/types.ts
  services/fxart.ts
  stores/drop.ts
Labels: refactoring, paid, S-works-for-me-✅

#9687 feat: Missing placeholder on newest list strip
  components/base/MediaItem.vue
  components/rmrk/types.ts
  libs/ui/src/components/MediaItem/type/UnknownMedia.vue
  utils/gallery/media.ts
Labels: S-works-for-me-✅

#9676 feat: Estimate when signing mint
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/PaidMint.vue
  components/shared/SigningModal/SigningModal.vue
  components/shared/SigningModal/SigningModalBody.vue
  composables/useTransactionEstimatedTime.ts
  locales/en.json
Labels: S-resolve-merge-conflicts-🤝

#9704 fix: Limited per address on paid mint toast
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  locales/en.json
  locales/hi.json
Labels: S-works-for-me-✅, waiting-for-review

#9705 feat: Share on Farcaster / Warpcast
  components/common/successfulModal/ShareSocialsSection.vue
  composables/useSocialShare.ts
Labels: S-changes-requested-🤞

#9633 holders tab changes
  components/collection/activity/ownerInsightsTabs/HolderTab.vue
  components/collection/activity/ownerInsightsTabs/NFTSDetailsDropdown/Holder.vue
  composables/collectionActivity/helpers.ts
  locales/en.json
Labels: S-changes-requested-🤞, S-visual-ok-✅

#9715 fix/code checker variation loading time
  components/codeChecker/CodeChecker.vue
  components/codeChecker/PreviewCard.vue
Labels: S-works-for-me-✅

#9709 Holder of composable
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/Phase.vue
  components/collection/drop/requirement/PrivateMintRequirements.vue
  components/collection/drop/types.ts
  components/drops/useDrops.ts
  composables/collectionActivity/useCollectionActivity.ts
  composables/drop/useGenerativeDropMint.ts
  composables/drop/useHolderOfCollection.ts
  pages/[prefix]/drops/[id].vue
  stores/drop.ts
Labels: S-works-for-me-✅, waiting-for-review

#9735 #9647 carousel icon change
  assets/styles/components/_carousel-arrows.scss
  components/carousel/module/CarouselAgnostic.vue
Labels: S-works-for-me-✅, S-visual-ok-✅, waiting-for-review

#9743 #9740 telegram links update
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  HIRING.md
  QA.md
  README.md
  SECURITY.md
Labels: S-works-for-me-✅

#9742 feat: Add more resources to code checker
  components/codeChecker/CodeChecker.vue
  locales/en.json
Labels: S-works-for-me-✅

#9733 feat: Update share on x and farcaster number of mint
  components/collection/drop/Generative.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  composables/drop/useGenerativeDropMint.ts
  locales/en.json
Labels: S-changes-requested-🤞, waiting-for-review

#9711 feat: Mass Minting in drop page
  components/buy/SuccessfulBuyModal.vue
  components/collection/drop/Generative.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/MintStepper.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/modal/shared/SuccessfulDrop.vue
  components/collection/drop/modal/utils.ts
  components/collection/drop/types.ts
  components/collection/unlockable/utils.ts
  components/common/IdentityForm.vue
  components/common/successfulModal/MultiItemMedia.vue
  components/common/successfulModal/SingleItemMedia.vue
  components/common/successfulModal/SuccessfulModalBody.vue
  components/drops/useDrops.ts
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/massmint/useDropMassMintListing.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/massmint/useDropMassMintState.ts
  composables/drop/massmint/useDropMassMintUploader.ts
  composables/drop/useGenerativeDropMint.ts
  composables/drop/useGenerativeIframeData.ts
  composables/transaction/mintToken/constructDirectoryMeta.ts
  composables/useAsyncRetry.ts
  composables/useListingCartModal.ts
  composables/useMetaTransaction.ts
  composables/useMultipleBalance.ts
  composables/useTransaction.ts
  composables/useTransactionTracker.ts
  content/blog/first-time.md
  libs/ui/src/components/NeoStepper/NeoStepper.vue
  libs/ui/src/index.ts
  locales/en.json
  queries/subsquid/general/nftEntitiesByIDs.graphql
  services/fxart.ts
  stores/drop.ts
  utils/generative-preview.ts
  utils/subscription.ts
Labels: S-changes-requested-🤞, waiting-for-review

#9780 fix: Collected by gone
  components/collection/activity/Activity.vue
  components/collection/drop/GenerativeLayout.vue
  composables/collectionActivity/useCollectionActivity.ts
Labels: S-works-for-me-✅

#9778 fix: missing serial number on cart
  components/common/confirmPurchaseModal/ConfirmNftPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
Labels: S-works-for-me-✅

#9772 fix: Buy now and add to cart over latest nft mints
  components/collection/drop/ItemsGrid.vue
  layouts/unlockable-mint-layout.vue
Labels: S-works-for-me-✅

#9775 fix: Limit ability to go minus on mass mint drop
  components/collection/drop/MintButton.vue
  components/collection/drop/MintStepper.vue
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoStepper/NeoStepper.vue
Labels: S-changes-requested-🤞

#9782 beta update
  components/collection/activity/Activity.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/ItemsGrid.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/MintStepper.vue
  components/common/confirmPurchaseModal/ConfirmNftPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/common/successfulModal/ShareSocialsSection.vue
  composables/collectionActivity/useCollectionActivity.ts
  layouts/unlockable-mint-layout.vue
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoStepper/NeoStepper.vue
  utils/drop.ts
Labels: beta

#9783 release update
  components/collection/activity/Activity.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/ItemsGrid.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/MintStepper.vue
  components/common/confirmPurchaseModal/ConfirmNftPurchaseItemRow.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseItemRow.vue
  components/common/shoppingCart/ShoppingCartItemRow.vue
  components/common/successfulModal/ShareSocialsSection.vue
  composables/collectionActivity/useCollectionActivity.ts
  layouts/unlockable-mint-layout.vue
  libs/ui/src/components/NeoInput/NeoInput.scss
  libs/ui/src/components/NeoStepper/NeoStepper.vue
  utils/drop.ts
Labels: release

#9785 fix: Sort spotlight drops strip chronologically by upcoming mint date
  components/drops/useDrops.ts
Labels: paid

#9555 Use dropdown search for tablet size
  assets/styles/components/_search.scss
  components/Navbar.vue
  components/search/SearchSuggestion.vue
  tests/e2e/search.spec.ts
Labels: S-works-for-me-✅

#9677 feat: Calendar specific drop copy
  components/collection/drop/Phase.vue
  components/drops/CreateCalendarEventModal.vue
  components/drops/Drops.vue
  components/drops/useDrops.ts
  params/types.ts
  utils/drop.ts
Labels: waiting-for-review

#9800 fix: preheat on massmint
  composables/drop/massmint/useDropMassMintUploader.ts
  composables/transaction/mintToken/constructDirectoryMeta.ts
Labels: S-works-for-me-✅

#9808 style: fix text cut in cart sidebar
  components/common/shoppingCart/ShoppingCartItemRow.vue
Labels: S-works-for-me-✅

#9799 chore: upgrade nuxt & fix some warnings
  assets/svg/accent-blur.svg
  assets/svg/congrats-message-header.svg
  assets/svg/infinity.svg
  assets/svg/k-search-enter.svg
  assets/svg/landing-blur.svg
  assets/svg/migrate/arrow.svg
  assets/svg/migrate/congrats-dark.svg
  assets/svg/migrate/congrats.svg
  assets/svg/migrate/state-ready.svg
  assets/svg/migrate/state-waiting.svg
  assets/svg/migrate/title-arrow.svg
  assets/svg/preloader.svg
  assets/svg/search-k-keyboard.svg
  assets/svg/signup-voucher-blur.svg
  assets/svg/unlockable-introduce.svg
  components/MessageNotify.vue
  components/carousel/utils/useCarouselEvents.ts
  components/collection/CollectionHeader/CollectionBanner.vue
  components/collection/unlockable/UnlockableItemInfo.vue
  components/collectionDetailsPopover/CollectionDetailsPopover.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/identity/module/IdentityChain.vue
  components/landing/HeroBanner.vue
  components/landing/SignupBanner.vue
  components/landing/topCollections/TopCollectionsCard.vue
  components/landing/topCollections/utils/useTopCollections.ts
  components/massmint/modals/MintingModal.vue
  components/migrate/landing/content/Ready.vue
  components/migrate/landing/content/Waiting.vue
  components/migrate/landing/header/Index.vue
  components/search/SearchBar.vue
  components/series/SeriesTable.vue
  components/shared/DragDrop.vue
  components/shared/Loader.vue
  components/shared/TransactionLoader.vue
  nuxt.config.ts
  package.json
  pnpm-lock.yaml
  tests/e2e/landing.spec.ts
Labels: paid

#9815 fix: Show serial number in holder tab in activity
  composables/collectionActivity/useCollectionActivity.ts
Labels: S-works-for-me-✅

#9814 feat: System appearance mode
  components/ColorModeSwitch.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  composables/useTheme.ts
  locales/en.json
Labels: S-works-for-me-✅

#9816 fix: dropdown alignment style
  components/Navbar.vue
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
Labels: paid, S-works-for-me-✅

#9820 items holding in profile
  locales/en.json
Labels: S-works-for-me-✅

#9829 fix: Add to Calendar text
  components/drops/Drops.vue
  locales/en.json
Labels: S-works-for-me-✅

#9828 fix: Add NFT SN on cart buy success modal
  components/common/shoppingCart/utils.ts
Labels: S-works-for-me-✅

#9747 #9684 button styling
  components/collection/drop/ItemsGrid.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/profile/FilterButton.vue
  components/profile/OrderByDropdown.vue
  components/profile/ProfileDetail.vue
  components/profile/activityTab/Activity.vue
Labels: S-visual-ok-✅

#9846 fix: Drop cards order on drop page
  components/drops/Drops.vue
  components/drops/useDrops.ts
Labels: S-visual-ok-✅

#9849 #9843 height change cart icon
  components/navbar/ShoppingCartButton.vue
Labels: S-works-for-me-✅

#9852 beta update
  components/collection/CollectionRelatedDropNotification.vue
  components/collection/drop/CollectedBy.vue
  components/collection/drop/CollectedByAvatar.vue
  components/drops/BasicDropCard.vue
  components/drops/DropCard.vue
  components/drops/Drops.vue
  components/drops/TimeTag.vue
  components/drops/calendar/DropsCalendar.vue
  components/drops/useDrops.ts
  components/drops/utils.ts
  components/identity/module/IdentityPopover.vue
  components/navbar/ShoppingCartButton.vue
  composables/collectionActivity/useCollectionActivity.ts
  composables/drop/useGenerativeDropMint.ts
  locales/en.json
  locales/hi.json
  utils/drop.ts
Labels: beta

#9812 add chevrons to menu items
  assets/styles/components/_connect-wallet.scss
  components/Navbar.vue
  components/common/ConnectWallet/useConnectWallet.ts
  components/navbar/NotificationBoxButton.vue
  components/navbar/ShoppingCartButton.vue
Labels: S-works-for-me-✅, waiting-for-review

#9874 Feat #9334 Add USD to drop button
  components/collection/drop/MintButton.vue
Labels: paid, S-works-for-me-✅

#9877 fix: drop calendar small visual things
  components/drops/BasicDropCard.vue
  components/drops/CreateCalendarEventModal.vue
  components/drops/DropsGrid.vue
  components/drops/calendar/DropPreviewModal.vue
  components/drops/calendar/DropsCalendar.vue
  components/drops/utils.ts
  locales/en.json
Labels: S-works-for-me-✅, waiting-for-review

#9882 feat: Partykit mass minting status
  components/collection/drop/CursorParty.vue
  components/collection/drop/Generative.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/common/party/CursorParty.vue
  components/common/party/Cusor.vue
  composables/drop/massmint/useDropMassMintState.ts
  composables/drop/massmint/useDropMassMintUploader.ts
  composables/party/types.ts
  composables/party/useCursorDropEvents.ts
Labels: S-works-for-me-✅, S-visual-ok-✅, waiting-for-review

#9893 change active order
  components/drops/Drops.vue
Labels: S-works-for-me-✅

#9897 fix: Clicking on connect wallet on old drops redirects you to collection
  components/collection/drop/MintButton.vue
Labels: S-works-for-me-✅

#9899 fix: Hung up on slow rendering arts
  components/collection/drop/modal/paid/MintOverview.vue
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/massmint/useDropMassMintState.ts
Labels: S-works-for-me-✅, S-expected-in-upcoming-release-🚚

#9869 update og card
  nuxt.config.ts
  public/k_card.png
Labels: S-changes-requested-🤞, S-expected-in-upcoming-release-🚚

#9809 Feature: Generative art toolbar
  components/gallery/GalleryItem.vue
  locales/bn.json
  locales/cn.json
  locales/cz.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/it.json
  locales/jp.json
  locales/ko.json
  locales/nl.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sk.json
  locales/tu.json
  locales/ua.json
  locales/ur.json
  locales/vt.json
Labels: S-changes-requested-🤞, S-stale

#9924 feat: Change footer in pure text
  components/TheFooter.vue
  tests/e2e/footer.spec.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#9930 fix: Buy now stops working after a few redirects
  components/shared/BreadcrumbsFilter.vue
  pages/[prefix]/explore/items.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9906 Modal width to tailwind
  assets/styles/components/_connect-wallet.scss
  components/collection/drop/AddFundsModal.vue
  components/collection/drop/modal/DropConfirmModal.vue
  components/collection/drop/modal/newsletter/EmailSignup.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/confirmPurchaseModal/ConfirmPurchaseModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/create/Confirm/MintConfirmModal.vue
  components/shared/modals/ModalBody.vue
  libs/ui/src/components/NeoModal/NeoModal.scss
Labels: S-works-for-me-✅

#9916 fix: Mobile menu gone on 640-1024px
  assets/styles/layouts/_main-navigation.scss
  components/Navbar.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅

#9910 fix: Drop page does not respect visibility from backend
  components/carousel/CarouselTypeDrops.vue
  components/drops/Drops.vue
Labels: S-works-for-me-✅

#9934 Drop test small refactor
  tests/e2e/drops.spec.ts
Labels: waiting-for-review

#9931 Feat/profile_v3
  components/identity/IdentityIndex.vue
  components/identity/module/IdentityChain.vue
  components/profile/ProfileActivitySummeryV3.vue
  components/profile/ProfileDetail.vue
  components/profile/ProfileDetailV3.vue
  composables/useProfile.ts
  layouts/full-width-no-footer.vue
  locales/en.json
  pages/[prefix]/u/[id].vue
  queries/subsquid/general/profileStatsByIdRefined.graphql
Labels: waiting-for-review

#9914 fix: free mint stuck on the first step
  components/collection/drop/modal/DropConfirmModal.vue
Labels: S-code-lgtm-✅

#9948 fix: More Space on mobile drop page
  components/collection/unlockable/UnlockableCollectionInfo.vue
Labels: S-visual-ok-✅
