Repository kodadot/nft-gallery, pull requests merged in 2024-06, with the labels that each got.

#10361 fix: close modal reset drops state
  components/collection/drop/PaidGenerative.vue
Labels: S-works-for-me-✅

#10362 fix: Address copied to clipboard
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/identity/module/IdentityLink.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/profile/ProfileDetail.vue
  components/transfer/Transfer.vue
  locales/en.json
Labels: S-works-for-me-✅

#10086 feat: Go to drop page button in calendar sidebar
  components/drops/calendar/DropPreviewModal.vue
  components/drops/calendar/DropsCalendar.vue
  locales/en.json
  services/fxart.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#10377 feat: Cookie options
  components/CookieBanner.vue
  components/Navbar.vue
  components/navbar/CookiesButton.vue
  components/navbar/ProfileDropdown.vue
  components/settings/UserData.vue
  composables/useCookies.ts
  locales/en.json
  nuxt.config.ts
  pages/settings.vue
Labels: S-works-for-me-✅

#10378 fix: Changing counter resizes windows
  components/collection/drop/GenerativePreview.vue
Labels: S-works-for-me-✅

#10372 fix: try to follow someone without having a profile setup
  components/profile/ProfileDetail.vue
  components/profile/create/openProfileModal.ts
  components/profile/follow/UserRow.vue
  libs/ui/src/components/NeoModalExtend/plugin.ts
Labels: S-works-for-me-✅

#10392 fix: Use new logo on our app
  public/Koda.svg
  public/Koda_Beta.svg
  public/Koda_Beta_dark.svg
  public/Koda_dark.svg
Labels: S-works-for-me-✅, S-visual-ok-✅

#10354 feat: Make EVM wallet connector
  .env.example
  components/common/ChainDropdown.vue
  components/common/ConnectWallet/ConnectEvm.vue
  components/common/ConnectWallet/ConnectSubstrate.vue
  components/common/ConnectWallet/ConnectWalletModal.vue
  components/common/ConnectWallet/MnemonicNotice.vue
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetIdentity.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletMenuItem.vue
  components/common/ConnectWallet/WalletTabs.vue
  components/navbar/ChainSelectDropdown.vue
  components/profile/ProfileDetail.vue
  composables/collectionActivity/helpers.ts
  composables/useAvailableChainsOptions.ts
  composables/useChain.ts
  composables/useIdentity.ts
  composables/useIsChain.ts
  composables/usePrefix.ts
  composables/useWagmi.ts
  composables/useWeb3Modal.ts
  libs/static/src/chains.ts
  locales/en.json
  middleware/prefix.global.ts
  nuxt.config.ts
  package.json
  pages/e2e-login.vue
  pnpm-lock.yaml
  services/profile.ts
  stores/identity.ts
  stores/wallet.ts
  utils/chain.ts
  utils/config/chain.config.ts
  utils/extension.ts
  utils/wagmi.ts
Labels: S-changes-requested-🤞

#10344 refactor: cleanup preview items on drops page
  components/collection/drop/HolderOfGenerative.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/collection/drop/modal/paid/MintOverview.vue
  components/collection/drop/types.ts
  composables/drop/massmint/useDropMassMint.ts
  composables/drop/massmint/useDropMassMintPreview.ts
  composables/drop/massmint/useDropMassMintState.ts
  composables/drop/useGenerativeDropMint.ts
  composables/party/useCursorDropEvents.ts
  composables/transaction/transactionMintDrop.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  services/fxart.ts
  stores/drop.ts
  tests/randomize.spec.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#10398 feat: Cookies cleanup and simplification
  components/settings/Interface.vue
  components/settings/KeyboardShortcuts.vue
  components/settings/Metadata.vue
  components/settings/Minting.vue
  components/settings/Settings.vue
  components/settings/UserData.vue
  components/shared/Support.vue
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/id.json
  locales/pt.json
  locales/ru.json
  locales/ua.json
  pages/settings.vue
  stores/preferences.ts
  tests/e2e/footer.spec.ts
  tests/e2e/navigation.spec.ts
Labels: S-works-for-me-✅, S-visual-ok-✅

#10411 feat: Use eth identicons to distinquish evm from polkadot
  components/profile/ProfileDetail.vue
  components/shared/Avatar.vue
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅

#10365 fix: Timezones on Drop again not working?
  components/collection/drop/MintButton.vue
Labels: S-works-for-me-✅

#10438 Update ParaSpell to v5.5.0
  package.json
  pnpm-lock.yaml
Labels: S-works-for-me-✅

#10413 fix(code-checker): Problematic art passing
  components/codeChecker/CodeChecker.vue
  components/codeChecker/issueHint/KodaHashCalledOnce.vue
  components/codeChecker/types.ts
  locales/en.json
Labels: S-works-for-me-✅, waiting-for-review

#10442 fix: Explore card - reorder networks
  components/navbar/NavbarExploreOptions.vue
Labels: S-works-for-me-✅

#10445 feat: Profiles: Show on Drops profile pictures instead of polkadot wallet
  components/collection/drop/CollectedByAvatar.vue
  components/shared/ProfileAvatar.vue
Labels: S-works-for-me-✅

#10456 fix: Create profile when not connected
  components/profile/ProfileDetail.vue
Labels: S-works-for-me-✅

#10460 feat: Fixed aspect ratio to 1:1 for drop cards
  components/drops/BasicDropCard.vue
  components/drops/DropCardSkeleton.vue
Labels: S-visual-ok-✅

#10432 feat: remove featured articles
  components/landing/FeaturedArticles.vue
  components/landing/LandingPage.vue
  libs/ui/src/components/CardArticle/CardArticle.story.vue
  libs/ui/src/components/CardArticle/CardArticle.vue
  libs/ui/src/index.ts
  locales/en.json
  package.json
  script/posts.json
  script/posts.mjs
Labels: S-code-lgtm-✅

#10375 fix: NeoButton states and variants
  components/collection/drop/MintButton.vue
  components/common/autoTeleport/AutoTeleportActionButton.vue
  components/common/autoTeleport/AutoTeleportModal.vue
  components/common/autoTeleport/AutoTeleportWelcomeModal.vue
  components/common/itemTransfer/ItemTransferModal.vue
  components/common/listingCart/ListingCartMini.vue
  components/common/shoppingCart/ShoppingCartModal.vue
  components/common/successfulModal/ActionButtons.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemBuy.vue
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemRelist.vue
  components/massmint/EditPanel.vue
  components/massmint/Massmint.vue
  components/massmint/OnBoarding.vue
  components/massmint/modals/DeleteModal.vue
  components/massmint/modals/MintingModal.vue
  components/massmint/modals/MissingInfoModal.vue
  components/massmint/modals/ReviewModal.vue
  components/migrate/landing/Index.vue
  components/migrate/steps/Index.vue
  components/migrate/steps/Review.vue
  components/migrate/steps/Sign.vue
  components/navbar/ProfileDropdown.vue
  components/profile/ProfileDetail.vue
  components/profile/create/stages/Form.vue
  components/profile/create/stages/Introduction.vue
  components/redirect/RedirectModal.vue
  components/shared/filters/MobileFilter.vue
  components/shared/filters/modules/PriceFilter.vue
  components/teleport/Teleport.vue
  components/transfer/Transfer.vue
  components/transfer/TransferConfirmModal.vue
  components/why-koda/CtaSection.vue
  libs/ui/src/components/NeoButton/NeoButton.scss
  libs/ui/src/components/NeoButton/NeoButton.story.vue
  libs/ui/src/components/NeoButton/NeoButton.vue
  libs/ui/src/components/NeoDropdown/NeoDropdown.scss
  libs/ui/src/types.ts
Labels: S-works-for-me-✅

#10459 fix: inputting zero should default to 1
  components/collection/drop/MintStepper.vue
Labels: S-works-for-me-✅

#10462 feat: create and follow profiles on Base
  components/profile/ProfileDetail.vue
  components/profile/create/stages/Form.vue
  components/profile/follow/Tab.vue
  components/profile/follow/UserRow.vue
  utils/account.ts
Labels: S-works-for-me-✅

#10433 #10425: remove onchain identity
  components/common/ConnectWallet/WalletAsset.vue
  components/common/ConnectWallet/WalletAssetMenu.vue
  components/common/ConnectWallet/WalletAssetSetIdentity.vue
  locales/en.json
Labels: S-changes-requested-🤞

#10469 fix: Prevent user from adding comma on drops
  libs/ui/src/components/NeoStepper/NeoStepper.vue
Labels: S-works-for-me-✅

#10473 feat: code checker open in a new tab button
  components/codeChecker/CodeChecker.vue
  components/codeChecker/PreviewCard.vue
  components/codeChecker/massPreview/Capture.vue
  components/codeChecker/massPreview/CodeCheckerMassPreview.vue
  locales/en.json
  services/playground.ts
Labels: S-works-for-me-✅

#10476 feat: Hover card changes
  components/identity/module/IdentityPopover.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/utils/useIdentityStats.ts
  components/profile/ButtonConfig.vue
  components/profile/FollowButton.vue
  components/profile/ProfileDetail.vue
  locales/en.json
  stores/identityMint.ts
Labels: S-works-for-me-✅, waiting-for-review

#10334 fix: It is still possible to mint two identic images
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/drops/useDrops.ts
  components/profile/create/Modal.vue
  composables/drop/useGenerativeDropMint.ts
  composables/useModalIsOpenTracker.ts
  queries/subsquid/general/unlockableCollectionById.graphql
  stores/drop.ts
Labels: S-works-for-me-✅, S-resolve-merge-conflicts-🤝

#10480 feat: verification for Polkadot address
  components/profile/ProfileDetail.vue
  components/profile/create/Modal.vue
  components/profile/follow/UserRow.vue
  composables/useVerifyAccount.ts
  services/profile.ts
  stores/wallet.ts
Labels: S-works-for-me-✅

#10481 🔧 notification break all word
  components/common/Notification.vue
Labels: S-works-for-me-✅

#10484 feat: Add new check to code-checker
  components/codeChecker/CodeChecker.vue
  components/codeChecker/issueHint/NotUsingExternalResources.vue
  components/codeChecker/massPreview/Capture.vue
  components/codeChecker/massPreview/utils.ts
  components/codeChecker/types.ts
  components/codeChecker/utils.ts
  components/codeChecker/validate.ts
  locales/en.json
Labels: S-works-for-me-✅

#10483 🔧 dev console warnings
  components/why-koda/HeroSection.vue
Labels: S-works-for-me-✅

#10455 feat: Mental shift from gen art tag to normal png tag
  components/base/MediaItem.vue
  components/carousel/module/CarouselMedia.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/rmrk/Gallery/GalleryCard.vue
  components/shared/nftCard/NftCard.vue
Labels: S-works-for-me-✅, waiting-for-review

#10523 fix: Collection Activity on AHP not loading or taking a long time to load
  composables/collectionActivity/useCollectionActivity.ts
Labels: S-works-for-me-✅

#10522 fix: hover card does not load the correct name
  components/collection/drop/CollectedByAvatar.vue
Labels: S-works-for-me-✅

#10521 fix: Limit image size when upload images to profile
  components/profile/create/SelectImageField.vue
  components/profile/create/stages/Form.vue
  locales/en.json
Labels: S-works-for-me-✅

#10528 fix: Profile followed by images small improvements
  components/profile/ProfileDetail.vue
Labels: S-works-for-me-✅

#10535 fix: Click on following/followers tab with a disconnected account
  components/profile/FollowButton.vue
  components/profile/follow/UserRow.vue
  services/profile.ts
Labels: S-works-for-me-✅

#10515 [Beta] June Update
  .node-version
  components/base/MediaItem.vue
  components/carousel/module/CarouselMedia.vue
  components/codeChecker/CodeChecker.vue
  components/codeChecker/PreviewCard.vue
  components/codeChecker/issueHint/NotUsingExternalResources.vue
  components/codeChecker/massPreview/Capture.vue
  components/codeChecker/massPreview/CodeCheckerMassPreview.vue
  components/codeChecker/massPreview/utils.ts
  components/codeChecker/types.ts
  components/codeChecker/utils.ts
  components/codeChecker/validate.ts
  components/collection/drop/CollectedByAvatar.vue
  components/collection/drop/GenerativeLayout.vue
  components/collection/drop/GenerativePreview.vue
  components/collection/drop/MintButton.vue
  components/collection/drop/PaidGenerative.vue
  components/collection/drop/modal/PaidMint.vue
  components/common/ConnectWallet/WalletAssetNfts.vue
  components/common/Notification.vue
  components/drops/useDrops.ts
  components/gallery/GalleryItem.vue
  components/gallery/GalleryItemDescription.vue
  components/identity/module/IdentityPopover.vue
  components/identity/module/IdentityPopoverFooter.vue
  components/identity/module/IdentityPopoverHeader.vue
  components/identity/utils/useIdentityStats.ts
  components/profile/ButtonConfig.vue
  components/profile/FollowButton.vue
  components/profile/ProfileDetail.vue
  components/profile/create/Modal.vue
  components/profile/create/SelectImageField.vue
  components/profile/create/stages/Form.vue
  components/profile/utils.ts
  components/rmrk/Gallery/GalleryCard.vue
  components/shared/Markdown.vue
  components/shared/nftCard/NftCard.vue
  components/why-koda/HeroSection.vue
  composables/collectionActivity/useCollectionActivity.ts
  composables/drop/useGenerativeDropMint.ts
  composables/useModalIsOpenTracker.ts
  libs/static/package.json
  libs/ui/package.json
  libs/ui/src/components/NeoStepper/NeoStepper.vue
  locales/en.json
  package.json
  pages/[prefix]/drops/[id].vue
  pnpm-lock.yaml
  queries/subsquid/general/unlockableCollectionById.graphql
  services/fxart.ts
  services/playground.ts
  services/profile.ts
  stores/drop.ts
  stores/identityMint.ts
  utils/chain.ts
  utils/config/ipfs.ts
  utils/env.ts
Labels: beta

#10551 feat: disable `clarity` on `dev` env
  nuxt.config.ts
Labels: S-works-for-me-✅
