Repository kodadot/nft-gallery, pull requests merged in 2025-01, with the labels that each got.

#11262 fix: Swap page with no items
  components/search/SearchProfiles.vue
  middleware/redirects.global.ts
Labels: S-code-lgtm-✅

#11317 fix: Squashed profile picture
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
Labels: S-visual-ok-✅

#11330 fix: stop user from inputting their own address
  components/shared/AddressInput.vue
  components/swap/landing.vue
Labels: S-works-for-me-✅

#11329 fix: clicking on item in atomic swap should open new tab
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/shared/nftCard/NftCard.vue
  components/swap/GridList.vue
Labels: S-works-for-me-✅, S-visual-ok-✅

#11291 feat: Action Buttons: Implement Counter-swap Functionality
  components/drops/CreateCalendarEventModal.vue
  components/drops/utils.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTrade.vue
  components/trade/TradeActivityTable.vue
  components/trade/TradeActivityTableRow.vue
  components/trade/TradeOwnerButton.vue
  components/trade/overviewModal/TradeOverviewModal.vue
  components/trade/overviewModal/utils.ts
  composables/useIsTrade.ts
  composables/useTrades.ts
  locales/en.json
  queries/subsquid/general/offersList.graphql
  queries/subsquid/general/swapsList.graphql
  stores/atomicSwaps.ts
  utils/swap.ts
  utils/time.ts
Labels: S-visual-ok-✅

#11332 (beta): 9 % of January 2025 Hazelnut 🌰
  .github/renovate.json
  components/base/BaseCollectionForm.vue
  components/collection/CollectionDetail.vue
  components/collection/drop/GenerativeLayout.vue
  components/drops/CreateCalendarEventModal.vue
  components/drops/utils.ts
  components/gallery/GalleryItemAction/GalleryItemActionType/GalleryItemTrade.vue
  components/gallery/useGalleryItem.ts
  components/items/ItemsGrid/ItemsGrid.vue
  components/items/ItemsGrid/ItemsGridImage.vue
  components/items/ItemsGrid/ItemsGridImageTokenEntity.vue
  components/massmint/OverviewTable.vue
  components/massmint/descriptionTabs.ts
  components/migrate/steps/Index.vue
  components/rmrk/Create/CreateCollection.vue
  components/rmrk/Gallery/EmotionModal.vue
  components/rmrk/Gallery/Flipper.vue
  components/rmrk/Gallery/Holder/Holder.vue
  components/rmrk/Gallery/Holder/helper.ts
  components/rmrk/Gallery/Layout.vue
  components/rmrk/service/Consolidator.ts
  components/search/SearchProfiles.vue
  components/shared/AddressInput.vue
  components/shared/nftCard/NftCard.vue
  components/swap/GridList.vue
  components/swap/landing.vue
  components/trade/TradeActivityTable.vue
  components/trade/TradeActivityTableRow.vue
  components/trade/TradeExpirationSelector.vue
  components/trade/TradeOwnerButton.vue
  components/trade/overviewModal/TradeOverviewModal.vue
  components/trade/overviewModal/utils.ts
  composables/massmint/parsers/parseCsv.ts
  composables/transaction/mintCollection/useNewCollectionId.ts
  composables/transaction/utils.ts
  composables/useIsTrade.ts
  composables/useTrades.ts
  libs/ui/src/components/MediaItem/type/ImageMedia.vue
  locales/en.json
  middleware/redirects.global.ts
  netlify.toml
  package.json
  plugins/filters.ts
  plugins/loader.ts
  pnpm-lock.yaml
  public/massmint/template.csv
  queries/subsquid/general/existingCollectionList.graphql
  queries/subsquid/general/offersList.graphql
  queries/subsquid/general/swapsList.graphql
  stores/atomicSwaps.ts
  tests/e2e/chain-redirect.spec.ts
  tests/e2e/custom.ts
  tests/e2e/prefix.spec.ts
  utils/filters.ts
  utils/mappers.ts
  utils/swap.ts
  utils/time.ts
Labels: beta

#11335 feat: rarity of attribute on mass mint
  components/massmint/OverviewTable.vue
Labels: S-visual-ok-✅

#11356 feat: code checker support `loadTable`
  components/codeChecker/massPreview/Canvas.vue
  components/codeChecker/utils/index.ts
  components/codeChecker/utils/processing.ts
  services/cors-proxy.ts
Labels: S-code-lgtm-✅, S-works-for-me-✅

#11217 feat: edit collection permission
  components/collection/EditModal.vue
  components/collection/HeroButtonEditCollection.vue
  components/collection/SearchInput.vue
  components/collection/utils/useCollectionDetails.ts
  components/search/utils/collectionSearch.ts
  composables/transaction/mintCollection/utils.ts
  composables/transaction/transactionUpdateCollection.ts
  composables/transaction/types.ts
  composables/transaction/utils.ts
  locales/en.json
Labels: S-works-for-me-✅, S-visual-ok-✅

#11376 🔧 profile creation remove avatar popover
  components/collection/drop/CreatedBy.vue
  components/profile/create/stages/Form.vue
Labels: S-code-lgtm-✅, S-works-for-me-✅
