Repository kodadot/nft-gallery, pull requests merged in 2025-04, with the labels that each got.

#11518 (beta): April 2025
  libs/ui/src/scss/tailwind.scss
Labels: beta

#11520 (beta): April 2025
  assets/styles/components/_connect-wallet.scss
  assets/styles/components/_nft-card.scss
  assets/styles/global.scss
  components/Navbar.vue
Labels: beta

#11523 (prod): April 2025
  assets/styles/components/_connect-wallet.scss
  assets/styles/components/_nft-card.scss
  assets/styles/global.scss
  components/Navbar.vue
Labels: release

#11510 feat: Create select page into modal
  components/collection/HeroButtonAddNfts.vue
  components/create/CreateLanding.vue
  components/create/EntryModal.vue
  components/navbar/CreateDropdown.vue
  i18n/locales/en.json
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  pages/[prefix]/create/index.vue
  tests/e2e/createnft.spec.ts
  tests/e2e/navigation.spec.ts
  tests/e2e/sidebar.spec.ts
  utils/chain.ts
  utils/prefix.ts
Labels: S-visual-ok-✅

#11526 fix: can create collection/nft on base
  components/navbar/ChainSelectDropdown.vue
Labels: S-works-for-me-✅

#11535 fix: Seperator remove
  components/landing/LandingPage.vue
Labels: S-visual-ok-✅

#11543 (beta): 70% of April 2025: Lemon 🍋
  assets/styles/components/_search.scss
  components/Error.vue
  components/collection/HeroButtonAddNfts.vue
  components/collection/drop/RefreshMetadata.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/Confirm/PriceItem.vue
  components/create/CreateCollection.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/create/EntryModal.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/LandingPage.vue
  components/massmint/Massmint.vue
  components/massmint/types.ts
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/CreateDropdown.vue
  components/profile/ProfileDetail.vue
  components/shared/TabItem.vue
  components/shared/filters/modules/PriceFilter.vue
  components/trade/TradeOwnerButton.vue
  composables/massmint/useZipValidator.ts
  composables/transaction/mintToken/utils.ts
  i18n/locales/en.json
  layouts/gallery-item-layout.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  package.json
  pages/[prefix]/create/index.vue
  pages/drop-checker/[chain]/[collection].vue
  pnpm-lock.yaml
  services/oda.ts
  tests/e2e/createnft.spec.ts
  tests/e2e/navigation.spec.ts
  tests/e2e/sidebar.spec.ts
  utils/chain.ts
  utils/prefix.ts
  utils/swap.ts
Labels: beta

#11544 (prod): 70% of April 2025: Lemon 🍋
  assets/styles/components/_search.scss
  components/Error.vue
  components/collection/HeroButtonAddNfts.vue
  components/collection/drop/RefreshMetadata.vue
  components/create/Confirm/MintConfirmModal.vue
  components/create/Confirm/PriceItem.vue
  components/create/CreateCollection.vue
  components/create/CreateLanding.vue
  components/create/CreateNft.vue
  components/create/EntryModal.vue
  components/gallery/GalleryItemButton/GalleryItemButton.vue
  components/gallery/GalleryItemButton/GalleryItemMoreActionBtn.vue
  components/items/ItemsGrid/useItemsGrid.ts
  components/landing/LandingPage.vue
  components/massmint/Massmint.vue
  components/massmint/types.ts
  components/massmint/uploadCompressedMedia/UploadCompressedMedia.vue
  components/navbar/ChainSelectDropdown.vue
  components/navbar/CreateDropdown.vue
  components/profile/ProfileDetail.vue
  components/shared/TabItem.vue
  components/shared/filters/modules/PriceFilter.vue
  components/trade/TradeOwnerButton.vue
  composables/massmint/useZipValidator.ts
  composables/transaction/mintToken/utils.ts
  i18n/locales/en.json
  layouts/gallery-item-layout.vue
  libs/ui/src/scss/tailwind.scss
  libs/ui/tailwind.config.js
  package.json
  pages/[prefix]/create/index.vue
  pages/drop-checker/[chain]/[collection].vue
  pnpm-lock.yaml
  services/oda.ts
  tests/e2e/createnft.spec.ts
  tests/e2e/navigation.spec.ts
  tests/e2e/sidebar.spec.ts
  utils/chain.ts
  utils/prefix.ts
  utils/swap.ts
Labels: release
